### ISSUE TITLE
[BUG] Italy Invalid SmartThinQ credentials.

### ISSUE THREAD

**Issue by Maurotb** [ollo69/ha-smartthinq-sensors#101]
**Describe the bug**

When i set redirection url i have
Invalid SmartThinQ credentials.

Sometimes when i select IT IT in hacs, i see 
User input malformed

I can't make to work plugin in hass.io
Manually configured in another HA installation (docker) via homeassistant.yaml function correctly

If i put in my hass.io my token in  homeassistant.yaml , when i add integration it ask me fo IT IT and return error " Invalid SmartThinQ credentials."

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):

Hass.io

 - Home Assistant version installed:

0.116.2

 - Component version installed:
0.5.9
 - Last know working version:
 - LG device type and model with issue:
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by ollo69** [comment]
Sorry but your issue explanation is incomprehensible for me. What is homeassistant.yaml? 
Anyway configuration using yaml file is not supported anymore, you must use HA integration page.

**Comment by Maurotb** [comment]
sorry configuration.yaml, in my old setup (homeassistant + docker +  configuration.yaml) i have setup smartthingq and work.
Now i migrate to hass.io, when i click to install integration, it ask me for location, i select italy italy, next, i copy url to my browser,
i make a login and put back the url retrived.
At this point i receive " Invalid SmartThinQ credentials."

**Comment by KTibow** [comment]
Take screenshot for each step by step?

**Comment by ollo69** [comment]
Probably is usual problem related to new "Term of Service" by LG. Try opening phone APP, logout and login again, than come back to HA and repeat configuration. If this doesn't solve, post screenshot as suggested by @KTibow

**Comment by Maurotb** [comment]
Huao works! Thanks @ollo69 !
