### ISSUE TITLE
[Feature Request] Humidifer

### ISSUE THREAD

**Issue by kvtong93** [ollo69/ha-smartthinq-sensors#102]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I would like to ask if you could please adding the support for dehumidifier, it could read the humidity and choose the operation mode.

**Describe alternatives you've considered**

**Additional context**

**Comment by KTibow** [comment]
Cool, you can use the new humidifier integration for this! https://www.home-assistant.io/integrations/humidifier/

**Comment by kvtong93** [comment]
> Cool, you can use the new humidifier integration for this! https://www.home-assistant.io/integrations/humidifier/

sorry, i dont understannd, after i install this lg intergration, there is no entity added. How can i use humidifier intergration?

**Comment by KTibow** [comment]
I was suggesting *if* @ollo69 implemented it, instead of a switch they could make a `humidifier.name`.

**Comment by ollo69** [comment]
I close this old thread, please refer to #148 instead
