### ISSUE TITLE
Not showing in Lovelace integrations

### ISSUE THREAD

**Issue by Tofty85** [ollo69/ha-smartthinq-sensors#104]
SmartThinQ LG Sensors installed through HACS as per instructions, Hassio restarted but integration not showing in lovelace 
im running Hassio 0.116.4

i have tried all the versions available in HACS

any ideas?

**Comment by ollo69** [comment]
Clean browser cache.

**Comment by Tofty85** [comment]
what a legend! nice one, thanks, 
always seems to be the simplest things 
thanks again
