### ISSUE TITLE
[BUG]- Redirection URL time out

### ISSUE THREAD

**Issue by kzoran** [ollo69/ha-smartthinq-sensors#105]
**Describe the bug**
Redirection URL is timing out. When I got to HA > Integration > +Add SmartThinQ LGE Sensors > select United States and en for language, the wizard populates an url that I should paste into browser. 
I open a browser (tried Firefox, Chrome and Safari same result), paste the link and get prompt for user name and password. I never get a "redirection URL" ..it times out.

I confirmed that I can log to lg & smartthinq with this account. I actually created another 2 accounts and I get same behavior. 
**Expected behavior**

per documentation, I should get redirected to new url. 

**Screenshots**
<img width="589" alt="image" src="https://user-images.githubusercontent.com/13992235/97490269-db5d4180-191d-11eb-8475-2f9021063e06.png">

<img width="624" alt="image" src="https://user-images.githubusercontent.com/13992235/97490373-fc259700-191d-11eb-8d86-41260e9e40af.png">

**Environment details:**
 - Environment HASSIO
 - Home Assistant version installed: 0.116
 - Component version installed:
 - Last know working version:
 - LG device type and model with issue:
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**
I am not using social network account for LG account.

**Comment by KTibow** [comment]
Just copy it from the URL bar, and then paste it into the other field and hit submit.

**Comment by kzoran** [comment]
you mean before I log it?

**Comment by KTibow** [comment]
What do you mean?
1. Copy URL from field
2. New tab
3. Paste it in
4. Log in
5. Copy the URL from the toolbar
6. Go back to HA
7. Paste it in the other field
8. Hit submit

**Comment by kzoran** [comment]
thank you & good, we are on the same page. 
I never get to step 5, it times out.

**Comment by KTibow** [comment]
Just because Safari times out doesn't mean it hides the URL bar.

**Comment by kzoran** [comment]
I guess I was overthinking it ... that worked. 

I do have to admit I do feel like a dummy.

**Comment by KTibow** [comment]
It's okay. Everyone eventually feels like that sooner or later. Mind closing?

**Comment by kzoran** [comment]
of course. thanks again for dumbing it down for me.
