### ISSUE TITLE
What Logic Resets the Washer/Dryer Completed Sensor?

### ISSUE THREAD

**Issue by urbancripple** [ollo69/ha-smartthinq-sensors#106]
After a load is run, the "completed" sensor goes from "off" to "on". What's the internal logic for resetting the sensor to off? As a test I tried opening and closing the door to my washer but that didn't seem to do it.

**Comment by KTibow** [comment]
It's basically the opposite of the sensor. If `sensor.wetty` is on (washing), `binary_sensor.wetty_wash_completed` is off, and vice versa.

**Comment by urbancripple** [comment]
Thanks!
