### ISSUE TITLE
Unable to configure

### ISSUE THREAD

**Issue by nzbdilbert** [ollo69/ha-smartthinq-sensors#107]
I have installed the component via HACS. I can see the directory in cutom_components and it looks like the directory list in the guide. I am unable to progress. I have tried adding the integration via Configuration, Integrations, + but nothing is showing (and I have rebooted (several times), uninstalled, reinstalled (and rebooted)). What should I look at next?

**Comment by ollo69** [comment]
This looks like the more recurring problem... please clear the cache of your browser!

**Comment by nzbdilbert** [comment]
Hi

All working!! Amazing how the easy things can trip you up.

**Comment by KTibow** [comment]
Consider closing then?

**Comment by nzbdilbert** [comment]
Done
