### ISSUE TITLE
[BUG] Integration is not found through http://homeassistant:8123/config/integrations

### ISSUE THREAD

**Issue by nikelone** [ollo69/ha-smartthinq-sensors#110]
**Describe the bug**
I can not find the smartthinqs Integration here: http://homeassistant:8123/config/integrations

See Screenshots.

Logfile: custom component seem to be found:
> 2020-11-28 21:16:31 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

**Screenshots**
![integration](https://user-images.githubusercontent.com/42377599/100526505-5fc30e80-31c1-11eb-8745-36734c4866f5.png)
![folder](https://user-images.githubusercontent.com/42377599/100526506-605ba500-31c1-11eb-8bea-461af8e8d66e.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HassOS 4.17
 - Home Assistant version installed: 0.118.4
 - Component version installed: baed4b8 merged on 9 Sep
 - Last know working version: none, first install.
 - LG device type and model with issue: 
 - LG devices connected (list): did not come so far

**Output of HA logs**
Paste the relavant output of the HA log here.
no other logs found
```
2020-11-28 21:16:31 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
```

**Comment by ollo69** [comment]
Just clear browser cache,

**Comment by nikelone** [comment]
thanks. That did it. Sorry for the stupid error. Thanks a lot for the quick help! And thanks a lot for this great integration. Which makes it possible not to use the crappy app.
