### ISSUE TITLE
[BUG] Connection not available. SmartThinQ platform not ready

### ISSUE THREAD

**Issue by insidexino** [ollo69/ha-smartthinq-sensors#112]
I got the following errors in my logs. I assume this is because of washtower.
Is there any workaround when DeviceType is unknown?

```
Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/device.py:236
Integration: SmartThinQ LGE Sensors (documentation)
First occurred: 4:05:30 PM (11 occurrences)
Last logged: 4:12:09 PM

Connection not available. SmartThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 176, in async_setup_entry
    lge_devices = await lge_devices_setup(hass, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 488, in lge_devices_setup
    if device.type == DeviceType.WASHER:
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 236, in type
    return DeviceType(self._get_data_value("deviceType"))
  File "/usr/local/lib/python3.8/enum.py", line 315, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 617, in __new__
    raise ve_exc
ValueError: 221 is not a valid DeviceType
```

**Comment by KTibow** [comment]
What do you mean by washtower?

**Comment by ollo69** [comment]
Don't know what is a washtower :), but for sure this is a bug that I have to fix...

**Comment by ollo69** [comment]
It should be fixed with last release

**Comment by insidexino** [comment]
Washtower is a combined machine with a washing machine and dryer. 
FYI : https://www.lgnewsroom.com/2020/08/lg-washtower-sets-new-expectation-for-performance-and-convenience/

**Comment by ollo69** [comment]
In version v0.5.13 I implemented support for WashTower based on @pmongloid explanation, please report here if everything work properly.

**Comment by insidexino** [comment]
Thank you for fixing this. I have checked v0.5.13, and it works without the error. Thank you so much. 
Another issue is that the dryer and washer devices are not detected yet. I will check this later.

**Comment by ollo69** [comment]
> Another issue is that the dryer and washer devices are not detected yet. I will check this later.

It should be fixed in v0.5.14

**Comment by insidexino** [comment]
With v0.5.14, they are detected and work perfectly. Thank you.

**Comment by KTibow** [comment]
Does that mean this issue can be closed?

**Comment by insidexino** [comment]
Yes. I apologize for forgetting to close it.
