### ISSUE TITLE
[Feature Request] Add attribute/value for end time

### ISSUE THREAD

**Issue by dieneuser** [ollo69/ha-smartthinq-sensors#114]
**Describe the solution you'd like**
Is it possible to add an attribute for the real (calculated) end time of a washing program?
for example: end_time=10:34 `.now() + remain_time`

**Describe alternatives you've considered**
Or how can this be implemented with a sensor template?

**Comment by KTibow** [comment]
I don't know how, but there's an attribute `remain_time` in the format `H:MM` , which you could parse.

**Comment by ollo69** [comment]
Close this issue. Feature is available based on existing sensors.
