### ISSUE TITLE
[Feature Request] Support for LG Styler

### ISSUE THREAD

**Issue by southwestflavorz** [ollo69/ha-smartthinq-sensors#115]
**Is your feature request related to a problem? Please describe.**
The integration currently does not detect my LG Style which is connected to ThinQ

**Describe the solution you'd like**
Incorporate support for LG Styler

**Describe alternatives you've considered**

**Additional context**

**Comment by KTibow** [comment]
Do you get anything in your logs?

**Comment by southwestflavorz** [comment]
How do I check the logs?

**Comment by KTibow** [comment]
Always google any questions you don't know how to answer, possibly with the platform (Home Assistant) appended.

**Comment by AVKosterin** [comment]
> **Is your feature request related to a problem? Please describe.**
> The integration currently does not detect my LG Style which is connected to ThinQ
> 
> **Describe the solution you'd like**
> Incorporate support for LG Styler
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

+1

**Comment by AVKosterin** [comment]
`2021-02-26 23:40:22 DEBUG (SyncWorker_7) [custom_components.smartthinq_sensors.wideq.core_v2] thinq2_get after: {'resultCode': '0000', 'result': {'langPackCommonVer': '95.7', 'langPackCommonUri': 'https://objectcontent.lgthinq.com/95637f4e-55c4-4ebc-9967-bdd2a53af396?hdnts=exp=1677375590~hmac=d6dc0f43478103cfc3673f4e78492f785ee85fa14e680c0ca92a68c7569daa5d', 'item': [{'appType': 'NUTS', 'modelCountryCode': 'WW', 'countryCode': 'RU', 'modelName': 'WBHTGH', 'deviceType': 201, 'deviceCode': 'LA02', 'alias': 'СТИРАЛЬНАЯ МАШИНА', 'deviceId': 'e6bc5a29-1ac7-127d-9989-44cb8b0c1b4f', 'fwVer': '', 'imageFileName': 'home_appliances_img_wmdrum.png', 'imageUrl': 'https://objectstore.lgthinq.com/3120cb69-4c7c-48d5-9d69-d6fad3480955?Expires=1643952700&Signature=NbtjK5oODA2XnMKA3l78j7pVVkbHxuvrM6wY4eslH9gO4ab1oF7VFKH0WmBgOky0Cg9PMtMOlwN1ICDJqTDV4J7eBo0IjtYk220XEbmSzRbZ0cEfGlrP~Pid3gJxqToDgc9kJnFIWGM0QjvXkeGbJqHZT0e95cweNCqAADgjdr4sFFcbLHL-aRU-NhwwY1zZnxCFxkU-3S9y1sKaUC6xCt6zmOiFstsMfZrBwRrOfoP-BS5AT1D0Qb~hHky8ZVtUxeHbaCHeSuElJ4PDiQ3-vipPFqgZxhv~lm3xbL2bJ8wfpEZFsotRM~nkAEmNtJKEwt67~uhDpkSYiPC7OfvA6A__&Key-Pair-Id=APKAI74R6YENXPGRIWLQ', 'smallImageUrl': 'https://objectstore.lgthinq.com/04f965fe-de9b-42cc-884a-40a852782225?Expires=1643952699&Signature=Ofy5lqBjg5DiNYMHzAQBJqlmLqCBslYa1JYnJU6lAud8t0j65TmgB8aH62koFI7Tw7G9TwQ8~aXzYRktSgvHZKIC28qvdXHrIto~fvDKT6~bHpA614N1uIeRmsK~2VobeGhEa6CFSO9zxQBwp7TWWNDSkAc~-1VwJ1FWrjEtf3y1lVw2OunzJHmURhEdHov81Up9wM7tnNfGie55eAOnft1ZArEZHQh6tA1qKVVQ9GVrelpm1CPU0SeWcjUGdC7Vxp4Ktlu2E7mLuAGs2GjrfTQRZKLyidYPwR4xjyuX14vpzqYa69EdktGB4veITxbwNP~R6Ct5AizUxdPNJcuiHg__&Key-Pair-Id=APKAI74R6YENXPGRIWLQ', 'ssid': 'SERVER', 'softapId': '', 'softapPass': '', 'macAddress': '', 'networkType': '02', 'timezoneCode': 'Europe/Moscow', 'timezoneCodeAlias': 'Russia/Moscow', 'utcOffset': 3, 'utcOffsetDisplay': '+03:00', 'dstOffset': 3, 'dstOffsetDisplay': '+03:00', 'curOffset': 3, 'curOffsetDisplay': '+03:00', 'sdsGuide': '{"deviceCode":"LA02"}', 'newRegYn': 'N', 'remoteControlType': '', 'userNo': 'RU2011232593101', 'tftYn': 'N', 'modelJsonVer': 1.1, 'modelJsonUri': 'https://objectstore.lgthinq.com/742e5c7a-d1a9-448b-b10c-296fbf3c7867?Expires=1645299675&Signature=B2pxKPqEXcT5W1YdT3e4xS-ziABiG1MYn7KnSvFMAIgwwcdcLdZugMvmLbNWzQr8X4KdNRhh7NY1VU6U1CxWJ3Ofrm-itl6g2V4Lxl3LeqNiuK-yLrPZMILfluBZm25-FxGdbET82c7oc60fHrNFVpfvgs9e8A3J5tPhifCejYQbA3yM~umdCb5U~xHTYbhpSDM93AYHIqCvb98cDK6lGtWU6Qab~N1FwoSqWHvjjMrw4GufdCVEJ6cTyWbay0Y7N6qhGb8GD0yfxphRXzUT9~MIivZnM2bWVO0yIepM7bwOtfugjTJpqeRhWBH7qiEVD~l1u4ug7XmikIQM7iv4PQ__&Key-Pair-Id=APKAI74R6YENXPGRIWLQ', 'appModuleVer': 202.22, 'appModuleUri': 'https://objectstore.lgthinq.com/20784175-dc2d-401f-bad5-3dab6e5074f5?Expires=1641123603&Signature=D5dNOCLt4ww3vK09a2Oz3ISOA5KF1xKMvEuRNo2NqexMllhgFjWl0j00hpTFD9nVAARQhU1jmWPwchFlhzrL52vwTpJ~jupyekvjvPAFXPywemK13nXQ~HnFrcEZKdBf5Wr7dMTzsACLxkNonUoOcrdqNWNVIyUctHIHrMW-x2CDT~buaf6sbjXNQckMwFquMJzDDRReh1BLllQLtQFBP1bbYIGyDD7xLGtwfLhwES~E~01QV-uAMIA1v03xBwyZdAaWwGfqPGAPti7CQ~fILEWlqYpoXwsK7i2pgFBE9s2xM0Y~sFdJCQskKPJrvME29mp60kBNHXBzsFWzkhl6aA__&Key-Pair-Id=APKAI74R6YENXPGRIWLQ', 'appRestartYn': 'Y', 'appModuleSize': 560673, 'langPackProductTypeVer': 75.5, 'langPackProductTypeUri': 'https://objectcontent.lgthinq.com/ef249e58-8bb5-4846-9e6c-ad89c5143c63?hdnts=exp=1673749228~hmac=cd805c53754bcdcb6961f8e3e75202ee1bd41ab8556b37af89b76e402a65b266', 'langPackModelVer': 1.0, 'langPackModelUri': 'https://objectstore.lgthinq.com/939ade91-e8dc-488b-be67-c52455b70cca?Expires=1645299676&Signature=r5wEQVG4N67C2u0WXD9zIaczFT9PeN2bkq5KowBQgstSUAIoKIHkbmpWLYcTNW~htjkTK9liddOz1O7LRQymdFRa8m2QPyOxoUWb3~3VrP12pG1f40aSt6YRNPJjiYffdyJ1kdMnm8dahOaY9wugEGYgatUWIhB0OI4dQ0Op3Or-sBwu0MB7B6B-JXe1lKQ8SSrBGIKPfLOnN4-~rGd0BdYHfkTqFzpf3--dbY5YU67DPZMB8OIyl-XB9QNkW~e5alVzir~O8NUP73VQ5BmaEuLszstyfu1GEkA8vgjotpjE5m6O8fQ3DUhBZGBoXNqi3AQSqYFo0ajfyW0dPbDbCg__&Key-Pair-Id=APKAI74R6YENXPGRIWLQ', 'deviceState': 'E', 'snapshot': {'washerDryer': {'initialBit': 'INITIAL_BIT_OFF', 'standby': 'STANDBY_OFF', 'initialTimeMinute': 0.0, 'preState': 'COOLDOWN', 'smartCourseFL24inchBaseBigin': 'NOT_SELECTED', 'error': 'ERROR_NO', 'dryLevel': 'NO_DRYLEVEL', 'downloadedCourseFL24inchBaseBigin': 'RINSESPIN', 'creaseCare': 'CREASECARE_OFF', 'remainTimeHour': 0.0, 'preWash': 'PREWASH_OFF', 'steam': 'STEAM_OFF', 'state': 'POWEROFF', 'proofing': 'PROOFING_OFF', 'rinse': 'NO_RINSE', 'loadItemWasher': 'LOADITEM_OFF', 'temp': 'NO_TEMP', 'reserveTimeMinute': 0.0, 'courseFL24inchBaseBigin': 'NOT_SELECTED', 'TCLCount': 26.0, 'waterPlus': 'WATERPLUS_OFF', 'medicRinse': 'MEDICRINSE_OFF', 'turboWash': 'TURBOWASH_OFF', 'ecoHybrid': 'ECOHYBRID_OFF', 'remainTimeMinute': 0.0, 'reserveTimeHour': 0.0, 'steamSoftener': 'STEAMSOFTENER_OFF', 'childLock': 'CHILDLOCK_OFF', 'remoteStart': 'REMOTE_START_OFF', 'spin': 'NOT_SELECTED', 'soilWash': 'NO_SOILWASH', 'initialTimeHour': 0.0}, 'mid': 354575267.0, 'online': True, 'static': {'deviceType': '201', 'countryCode': 'RU'}, 'meta': {'allDeviceInfoUpdate': False, 'messageId': 'KS8giC9CRGuhusgZM9FQag'}, 'timestamp': 1614334716490.0}, 'online': True, 'platformType': 'thinq2', 'area': 294021, 'regDt': 20201123190528.0, 'blackboxYn': 'Y', 'modelProtocol': 'courseFL24inchBaseBigin', 'order': 0, 'drServiceYn': 'N', 'fwInfoList': [{'checksum': '01454292', 'partNumber': 'SAA40340702', 'order': 2.0}, {'checksum': '0000BDE2', 'partNumber': 'SAA40340603', 'order': 1.0}], 'modemInfo': {'modelName': 'WBHTGH', 'appVersion': 'clip_hna_v1.9.078', 'modemType': 'QCOM_QCA4010', 'ruleEngine': 'y'}, 'guideTypeYn': 'Y', 'guideType': 'TYPE2', 'regDtUtc': '20201123160528', 'regIndex': 0, 'groupableYn': 'N', 'controllableYn': 'N', 'combinedProductYn': 'N', 'masterYn': 'Y', 'pccModelYn': 'N', 'autoOrderYn': 'N', 'initDevice': False, 'existsEntryPopup': 'N', 'tclcount': 0}, {'appType': 'NUTS', 'modelCountryCode': 'WW', 'countryCode': 'RU', 'modelName': '2REF11EIIFW__', 'deviceType': 101, 'deviceCode': 'KI0102', 'alias': 'Холодильник', 'deviceId': 'c1f9ee22-480b-19cf-aceb-60ab14b14fa8', 'fwVer': '', 'imageFileName': 'home_appliances_img_fridge.png', 'imageUrl': 'https://objectstore.lgthinq.com/af46bfb8-048b-4cb7-ab15-93ba970803f8?Expires=1643961230&Signature=BiQqRkalmHm5glWOVe3oKsFYiBCZEwaIUgZ6ZPgRKqITTT5fW2Yg9wDQdBA7Shh2JSz1-YWZJWB14HSZZJsKlA~gXbrU9PNLjf9yXMmWZsGrIi3PLTNWfgb968IQ3SrLtxm55yw7EYeUbKe7SYYcWqm49yfgJpvE4QCXk4U~nymd78tL2J1xo~eUMLjFzNKOZjHpS6yrx9MoucXC1XLdnZ6UB96tNMqSUQiH9PTmosPIHCpBjmCIC0tvbd6p1lj9pNaNHjyLHY7a-ozoZg6Y8uGteY-jLCoPwfOtpTKQaqmFG-NMPCNL3r0Kxryw4NQHzFh17WGO636sbp7MznUUsQ__&Key-Pair-Id=APKAI74R6YENXPGRIWLQ', 'smallImageUrl': 'https://objectstore.lgthinq.com/de2f76ea-0b74-4ff9-9846-a9f56d6cf64d?Expires=1643958979&Signature=PkxiHQbGP5ZYP4NFG3~lIgex3uaeXKGETw1bJErRHsTmGPunfZ~R8bXmKuMlXOufdIodMFCrNSSMjqYItGb7nmU02juQh7UAcKbd8FAm9V22Y5BUndZ1cTtKUH6V0iuzg6u5jPcVkucQ6y49gGvpJwrLfomLjiTNcibNewxoTe~212zm79l8JkT~~i0yP6TP7EHDZ7TNp87dRtD9Jd0VswdBWJ0FRLfJoOUBL7PG6GycnH80mGahr0spBjs0v2~DyxKvQcoUMqrw9xjd3XqVvBijXB5yEGF4sMuWyGbe1PRPoWm8WpwKznBChS4-3wrGcoDr4NtzdVah-AKNcxezdA__&Key-Pair-Id=APKAI74R6YENXPGRIWLQ', 'ssid': 'SERVER', 'softapId': '', 'softapPass': '', 'macAddress': '', 'networkType': '02', 'timezoneCode': 'Europe/Moscow', 'timezoneCodeAlias': 'Russia/Moscow', 'utcOffset': 3, 'utcOffsetDisplay': '+03:00', 'dstOffset': 3, 'dstOffsetDisplay': '+03:00', 'curOffset': 3, 'curOffsetDisplay': '+03:00', 'sdsGuide': '{"deviceCode":"KI01"}', 'newRegYn': 'N', 'remoteControlType': '', 'userNo': 'RU2011232593101', 'tftYn': 'N', 'modelJsonVer': 1.0, 'modelJsonUri': 'https://objectstore.lgthinq.com/070e8652-e553-40cf-bbd5-86c7cc124f03?Expires=1649502049&Signature=e7Dz3z1zQ~~SSvHtK-3tAQzdcLVgDomgsl4oC1czYLlt~zuuN9x4kFR9fpVxb5u~xGV0VE~qgE64cF7ABXWb74wukBhUp82aNVrOuNVReuuXLV7-eAzV001U~XFxDMIhPEkwwXtRO-RijusmMXzYrwO6Q5zNMpnUbDscrRhBk4FcD9TkWsoptSKKOdK-edAJdYEwRZft-HAi9xCsaSv0pOm44VdVp2dvkyAzShxnwudyKBvrSP3QE3iyqkR0tTkQx9C7z9Paqk~i7jK895QAtht5t7nWCP2WUnzZiVP8stvauSUnY4Io2i7hdAxPfK7emIPMQZdkovPn0UOTnuzKEg__&Key-Pair-Id=APKAI74R6YENXPGRIWLQ', 'appModuleVer': 222.09, 'appModuleUri': 'https://objectstore.lgthinq.com/75e0414f-1836-44bf-9ed6-604145b93216?Expires=1636095596&Signature=qKayyWOIGSgnNkZpK1NhHqUpaG5TBN-3rYetWqLYbAtxMrozTZLVOolZdjTM7B-bbEFZzQTC0-3yaJqK0ff8ucxKeyzd-DoN88aWwwWyr~QVJfc51KsBgqrlWDrW5y15UR3WxeRCYIzgnt1Zl3U8YfZasfAyzKZP8VvYk40Ooia7TDdh7A1qoC00AiS3rp2leGM-eeorq9yEIs7iRUZPjH~BHrPKRMCfiQSkSlROrluq1ldc8wbVU313VIQgqgIGSD9JuTwHo0jzDmeUmutNFxmHIR25EG78sIuvjwn3ok2elc~VntVM1bI0nlFXPloGvETgw2rCoFzshejHWnn5Sw__&Key-Pair-Id=APKAI74R6YENXPGRIWLQ', 'appRestartYn': 'Y', 'appModuleSize': 1563441, 'langPackProductTypeVer': 43.3, 'langPackProductTypeUri': 'https://objectcontent.lgthinq.com/38578752-a048-4e7b-b2e3-dbd97fd81dc1?hdnts=exp=1675466719~hmac=07d4a92bf99d5c950bff2ee4075b1a0e412b66469dee139f729023147e12665e', 'deviceState': 'E', 'snapshot': {'mid': 23212174.0, 'online': True, 'static': {'deviceType': '101', 'countryCode': 'RU'}, 'meta': {'allDeviceInfoUpdate': False, 'messageId': 'zHU5MqJXS7acjrLpsJBXXg'}, 'refState': {'atLeastOneDoorOpen': 'CLOSE', 'displayLock': 'UNLOCK', 'freezerTemp': 3.0, 'fridgeTemp': 2.0, 'tempUnit': 'CELSIUS', 'expressMode': 'OFF', 'activeSaving': 'OFF', 'freshAirFilter': 'AUTO', 'monStatus': 'NORMAL', 'smartSavingMode': 'SMARTGRID_DD_ON', 'smartSavingRun': 'STOP', 'waterFilter': '3_MONTH'}, 'timestamp': 1614369618616.0}, 'online': True, 'platformType': 'thinq2', 'area': 294021, 'regDt': 20201123155458.0, 'blackboxYn': 'Y', 'modelProtocol': 'STANDARD', 'order': 0, 'drServiceYn': 'N', 'fwInfoList': [{'checksum': '013A05A5', 'partNumber': 'SAA39840901', 'order': 2.0}, {'checksum': '01369AFC', 'partNumber': 'SAA40094701', 'order': 1.0}], 'modemInfo': {'modelName': '2REF11EIIFW__', 'appVersion': 'clip_hna_v1.9.080', 'modemType': 'QCOM_QCA4010', 'ruleEngine': 'y'}, 'guideTypeYn': 'Y', 'guideType': 'TYPE1', 'regDtUtc': '20201123125458', 'regIndex': 0, 'groupableYn': 'N', 'controllableYn': 'N', 'combinedProductYn': 'N', 'masterYn': 'Y', 'pccModelYn': 'N', 'autoOrderYn': 'N', 'initDevice': False, 'existsEntryPopup': 'N', 'tclcount': 0}, {'appType': 'NUTS', 'modelCountryCode': 'RU', 'countryCode': 'RU', 'modelName': 'S5BB_RU_WIFI', 'deviceType': 203, 'deviceCode': 'LA04', 'alias': 'Styler', 'deviceId': 'eabae7cd-861a-1440-9c68-402f86e6cd72', 'fwVer': '', 'imageFileName': 'home_appliances_img_styler.png', 'imageUrl': 'https://objectstore.lgthinq.com/109a71e8-5427-4c02-8d0d-41ea97a2d62a?Expires=1644212973&Signature=gzuabhDKBXvs855Ni4-K7IxgGWo7cgWVZgG9rRSQgrQ9tW-7aP4pnq0ixsjkOYQitALdpqAkvYGSgdES9mITbbJlqqyo663X5RWe3IZig2hv4k~1DOLga4BvRsKEoREOTmTRkQ3WfWTQdTZZP5g6X1f9tFfDVcqdYvvwXYDRVJY5dLhBYPLbVVPomzJHe-vabC5LB1n~yCWBUAydIDlsvDpv4fpZRgAcghch2haVFQmU7mzoTLKIFsDLTx4nClqKRM6NkA3BuR2W6SewojcR5Kunlbzya1ZZzT8A6hI3kAlMO1~7~2w4opVBnjeTbxAYOSvj5u8KyId1kFshSJLcSg__&Key-Pair-Id=APKAI74R6YENXPGRIWLQ', 'smallImageUrl': 'https://objectstore.lgthinq.com/6d9a4368-fde1-4d8b-aaab-ead3dc5b8b0e?Expires=1643958974&Signature=GJYAUyvr4gtPibAyt12rEQcJoXkAOVLy0XFjjKJbfh6lE-MkrpPTlaarXBVC1e5pkmR4pRg66xbgu9KlxH2OhpWm5acwdfu1XM2hm8Mlwue3Zid-5oaC21~G2blGTRV09nphpNpxXDLbG1daITqmiaQAs88WyZBFnNXHqZSvLGIBmzyjkchBP6eEuGKhzupcF~7U2LAGHLqrVN34Hg-hPw05FeGafXtX3tLemEsLMLd6rXejF~0m6~Jdl2yitcvEDkCJK1VPEo-sF3WEoj2plBoCqCOGGoseM9lwajP6~3MQh9zSaN0OGH71fa8tfVKqF4e6ffAVGM6ty1id3eYfLg__&Key-Pair-Id=APKAI74R6YENXPGRIWLQ', 'ssid': 'SERVER', 'softapId': '', 'softapPass': '', 'macAddress': '', 'networkType': '02', 'timezoneCode': 'Europe/Moscow', 'timezoneCodeAlias': 'Russia/Moscow', 'utcOffset': 3, 'utcOffsetDisplay': '+03:00', 'dstOffset': 3, 'dstOffsetDisplay': '+03:00', 'curOffset': 3, 'curOffsetDisplay': '+03:00', 'sdsGuide': '{"deviceCode":"LA04"}', 'newRegYn': 'N', 'remoteControlType': '', 'userNo': 'RU2011232593101', 'tftYn': 'N', 'modelJsonVer': 1.6, 'modelJsonUri': 'https://objectstore.lgthinq.com/0c9b0579-6c6d-4c05-99ce-4cd83a444485?Expires=1638945183&Signature=sQXvjM953usU01GRhvbx3MC2q9sd6-wklHtQNzlXi4GbXac146RAN1uaCqYQbLR2-7sLaN~5XjS4WlAxNrP7YJbC-AkaFjllfRO6Qot8S6~fNGtxRhrYLACAUtcV1HMggITLd9dS5Da3N6PkO3H-jmGEo~kfR8rJQVKv-bMixbqD1fb0boTHfWgnTaA2iH4rwPJOMWLh1aa1C5444MO9StyJSmReklnTt6F7948Uf5qt8oBxO8FP78qFqzBFJD8AYe06O7J5-ek57Gwwf41OYbiz8bSEHTM0q8zG5r~DmoE~ePsVeiPQMMD~SgTur18SYNBO0Qodx5DRo9kkEfpGqQ__&Key-Pair-Id=APKAI74R6YENXPGRIWLQ', 'appModuleVer': 210.74, 'appModuleUri': 'https://objectstore.lgthinq.com/2f7c1909-7dd1-45f5-a845-9fcc7642d13d?Expires=1641812644&Signature=VWXOIefptTNjo9Npa5ZmPaHveS1LDniMAmgwCbVRCtRExWq~iyarNt6wnwu5KCUAfM2Zi5a-lP2JvgPsaaYZ0rzKz--abZfr3V9KUud2wCKBdCFsZxnpfUDC9Ve~PlzOmMUtLaUBitndw6JN0VeXJo8sWVE-MeKe6bDtsgCH0uFA~VnvCTfOU~ay82tI0dAze6Jla2dy3JJFtKXpzcLNHP7G5yWaUhwvGd33zoSVas8YCgWz1GaU4~23BXFX97L8Kd-0aOWWn-r9b6uFkMr4zHF0kPiZQdCewrMJmziXntePkjdBpUpF4EoXXDJJZaqF6xGqPgeRFqTZMX9K0eFoAw__&Key-Pair-Id=APKAI74R6YENXPGRIWLQ', 'appRestartYn': 'Y', 'appModuleSize': 683341, 'langPackProductTypeVer': 46.82, 'langPackProductTypeUri': 'https://objectcontent.lgthinq.com/46f427d4-3cb6-48b4-b9b0-497f106707e2?hdnts=exp=1675583709~hmac=62026bb4d2fb9917bdc7fc73712429373a755b31f4c8f6df105b29173c99b76f', 'deviceState': 'E', 'snapshot': {'mid': 12891.0, 'online': True, 'styler': {'initialBit': 'INITIAL_BIT_OFF', 'reserveTimeMinute': 0.0, 'initialTimeMinute': 0.0, 'preState': 'COMPLETE', 'energyMonitoring': 572.0, 'error': 'ERROR_NO', 'nightDry': 'NIGHTDRY_OFF', 'remainTimeMinute': 1.0, 'reserveTimeHour': 0.0, 'smartCourse': 'NONE', 'childLock': 'CHILDLOCK_OFF', 'remainTimeHour': 0.0, 'remoteStart': 'REMOTE_START_OFF', 'currentDownloadCourse1': 'BABY_CLOTHING_SANITARY', 'course': 'NONE', 'currentDownloadCourse3': 0.0, 'currentDownloadCourse2': 66.0, 'state': 'POWEROFF', 'currentDownloadCourseCount': 1.0, 'initialTimeHour': 0.0}, 'static': {'deviceType': '203', 'countryCode': 'RU'}, 'meta': {'allDeviceInfoUpdate': True, 'messageId': 'qzVU1WiBQxmB_xqfuOB5WA'}, 'timestamp': 1614369624835.0}, 'online': True, 'platformType': 'thinq2', 'area': 294021, 'regDt': 20210226093944.0, 'blackboxYn': 'Y', 'order': 0, 'drServiceYn': 'N', 'fwInfoList': [{'checksum': '0000E50D', 'partNumber': 'SAA37569135', 'order': 2.0}, {'checksum': '000016A6', 'partNumber': 'SAA37569018', 'order': 1.0}], 'modemInfo': {'modelName': 'S5BB_RU_WIFI', 'appVersion': 'clip_hna_v1.9.078', 'modemType': 'QCOM_QCA4010', 'ruleEngine': 'y'}, 'guideTypeYn': 'Y', 'guideType': 'TYPE1', 'regDtUtc': '20210226063944', 'regIndex': 0, 'groupableYn': 'N', 'controllableYn': 'N', 'combinedProductYn': 'N', 'masterYn': 'Y', 'pccModelYn': 'N', 'autoOrderYn': 'N', 'initDevice': False, 'existsEntryPopup': 'N', 'tclcount': 0}], 'group': []}}`

**Comment by KTibow** [comment]
I have a feeling something in there is private, that would allow random people to do weird stuff with your appliance.

**Comment by AVKosterin** [comment]
> I have a feeling something in there is private, that would allow random people to do weird stuff with your appliance.

the code is partially removed, will not work

**Comment by KTibow** [comment]
Good, but you should probably also delete the old versions.

**Comment by AVKosterin** [comment]
> Good, but you should probably also delete the old versions.

Yes thank you!

are these logs enough to add Styler support?

**Comment by KTibow** [comment]
What kind of support do you want?

**Comment by AVKosterin** [comment]
> What kind of support do you want?

state is on or off. If more then which program is selected

**Comment by KTibow** [comment]
Great. @ollo69 what's the next step on this? Are you willing to implement this, or would you rather someone else?

**Comment by ollo69** [comment]
It looks not so complex implement this, and I have all information required. I will come back here when ready.

**Comment by ollo69** [comment]
Styler should be supported with last release. Please perform tests and report here your result.

**Comment by ollo69** [comment]
Close due to inactivity. Styler now should be supported
