### ISSUE TITLE
[BUG] setup workflow missing in instructions

### ISSUE THREAD

**Issue by boelle** [ollo69/ha-smartthinq-sensors#117]
**Describe the bug**
setup workflow is missing in instructions

**Expected behavior**
expected the instructions to be there, but they are not. after installed it asked for a restart so to be sure i restared the raspberry pi completely. But the setup workflow info is missing

**Screenshots**

![image](https://user-images.githubusercontent.com/3832239/104124834-3d411b00-5353-11eb-8582-b0bdc5bef2c4.png)

**Comment by KTibow** [comment]
HACS installation != integration installation.

**Comment by boelle** [comment]
still what is the setup workflow? installing the integration (or addon or whatever you want to call it) in HACS is easy enough, but from there there are no info on how to add devices

remember that not everyone is an expert and might be new

**Comment by KTibow** [comment]
You go to Configuration > Integrations > plus > LG

**Comment by boelle** [comment]
ahh, as new i did not know that, if it has been mentioned as the workflow i would have known

now i just face this error:

Fejl 400: redirect_uri_mismatch
The redirect URI in the request, https://dk.m.lgaccount.com/spx/login/signInGoogle, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/${your_client_id}?project=${your_project_number}

and i guess that is because i logged in with google when i made the account at lg
