### ISSUE TITLE
Lge Washing Machine Sensors Card

### ISSUE THREAD

**Issue by matteo289** [ollo69/ha-smartthinq-sensors#118]
Hi, i have install the lg Thinq Device integrator v0.5.1. in my ha. 
i have add my lge washing machine in my card. 
i have this sensors:
- sensor.lavatrice - binary_sensor.lavatrice_error_state - binary_sensor.lavatrice_wash_completed
but i can add in my card this addond sensors?
a ) model b) remain time c) turbowash mode ..... ???

Your app can add also the air condition and tv wifi ?
Can you send me a istruction to add all my lge product into ha ? (also my product is on app smart Thinq).

Thanks 
![d97bcb57-dd74-4396-b154-38376c411f8c](https://user-images.githubusercontent.com/57131705/105507580-a87fdb00-5ccb-11eb-9aa4-c80d4490110e.jpeg)
![52d4f08b-2bfa-4a6a-bd4d-ee787224e00e](https://user-images.githubusercontent.com/57131705/105507591-ac136200-5ccb-11eb-9afc-3cdd7887dfee.jpeg)

**Comment by KTibow** [comment]
Could you please read the docs thoroughly? I'm going to be nice, though, and help you with this.
> but i can add in my card this addond sensors?
a ) model b) remain time c) turbowash mode ..... ???

Use the more info card by thomasloven. 

> Your app can add also the air condition

I don't think this is supported, use another custom LG integration for that.

> and tv wifi ?

This is supported in HA. https://www.home-assistant.io/integrations/webostv/

**Comment by ollo69** [comment]
Close due to inactivity. Re-open if additional info requested. Anyway AC support now is available in last released beta version.
