### ISSUE TITLE
[Feature Request] Homekit Integration

### ISSUE THREAD

**Issue by jangerbauer** [ollo69/ha-smartthinq-sensors#119]
I am using HA primarily as a bridge / passthrough to Homekit -- my preference is to use Apple's Home App to manage my devices.

I was able to add my LG Washer and Dryer to HA, but was wondering if it would be possible to view these in the Home app as well.

I'm still pretty new to HA -- happy to provide any additional details / visibility on this request.  Thanks for all of the great development on this.

**Comment by Brahmah** [comment]
HomeKit does not have support for these appliances and therefore requires a medium to facilitate communication.

**Comment by KTibow** [comment]
You should probably be able to do this using the bridge integration: https://www.home-assistant.io/integrations/homekit
Does HomeKit have a special "Washer" type that isn't just multiple entities?

**Comment by Simon-Design** [comment]
I integrated my washer as a humidity sensor into HomeKit. So now I can see the progress of my washer in percent.
Its not pretty but for now the only way I think...

**Comment by ollo69** [comment]
Close this issue due to inactivity. Please open new issue if you still need this feature.
