### ISSUE TITLE
Error to apply updade v0.5.15

### ISSUE THREAD

**Issue by grfernandes54** [ollo69/ha-smartthinq-sensors#123]
When I try to update to the version v0.5.15 I receive the error bellow

 Logger: custom_components.hacs
Source: custom_components/hacs/api/hacs_repository_data.py:117
Integration: HACS (documentation, issues)
First occurred: 8:52:08 (8 occurrences)
Last logged: 8:56:38

No content to download

**Comment by ollo69** [comment]
Seems error related to HACS and not to this components.

**Comment by grfernandes54** [comment]
After I clear the browse cache the problem was fixed. Thank you for the prompt reply
