### ISSUE TITLE
[BUG] No devices found

### ISSUE THREAD

**Issue by beped** [ollo69/ha-smartthinq-sensors#127]
Country Code: BR
Language Code: pt
Account Type: LG Account
Any Further Comments:
So, config done, but no devices are showing in the integration. I have a Air Conditioner on my LG account.
![image](https://user-images.githubusercontent.com/11295620/109243726-33b52a80-77bc-11eb-80fe-d4cda9205ba5.png)

Tried unistall and reinstall twice, no effect.

**Comment by KTibow** [comment]
ACs are not supported. Use the integration by the author of WideQ for this.

**Comment by beped** [comment]
Wich WideQ integration? i dont find any of those. I tried the sampsyo/hass-smartthinq but dont work either.

**Comment by beped** [comment]
> Wich WideQ integration? i dont find any of those. I tried the sampsyo/hass-smartthinq but dont work either.

Btw, my AC use the api2.

**Comment by blakito** [comment]
No repository has full AC integration with HA so far. Watch for the issues
topics as some individuals started working deeper on this.

**Comment by KTibow** [comment]
There is a pending PR that allows initial AC support (#124). It will require more code in order to show up in HA; that PR only adds support to communicate with it.

**Comment by trentjw** [comment]
same issue here my window A/C units do not show up and the sampsyo/hass-smartthinq is abandoned garbage

**Comment by KTibow** [comment]
Bumping this won't help in making progress.

**Comment by hmoffatt** [comment]
@trentjw why so rude?

**Comment by trentjw** [comment]
> @trentjw why so rude?

do you feel better now that you injected your 2 cents that has nothing to do with the topic?

**Comment by ollo69** [comment]
I close this issue. Please avoid this kind of discussion.
