### ISSUE TITLE
[BUG] Unable to reinstall

### ISSUE THREAD

**Issue by zraken** [ollo69/ha-smartthinq-sensors#128]
**Describe the bug**
I changed the password on the LG account and then I noticed that I kept getting this message in the logs:
`[homeassistant.config_entries] Config entry for smartthinq_sensors not ready yet.
`
and of course the washer went offline/unavailable
I tried to uninstall and re-install via HACS but now I am not able to find it when I try to add a new integration. Yes I did restart hass. BTW, this integration had been running great for a couple of months now (until this password change).

**Environment details:**
 - Environment Raspbian Buster
 - Home Assistant version installed: Home Assistant 2021.1.5
 - Component version installed: 0.5.16
 - Last know working version: 0.5.16
 - LG device type and model with issue: Washer (note this was working fine until the password change at LG)
 - LG devices connected (list): Washer

**Output of HA logs**

```
homeassistant.config_entries] Config entry for smartthinq_sensors not ready yet.
```

After attempted re-install this is all I am seeing:
```
2021-02-28 17:30:54 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
```

When I go through the steps to re-install the integration I am not prompted for account information.

**Comment by zraken** [comment]
Turns out I needed to refresh the browser to see the integration option for smartthinq.

**Comment by ollo69** [comment]
In would not necessary to reinstall using hass, but just remove and reconfigure integration from HA integration page.
The warning message from HA is normal and can be ignored.
