### ISSUE TITLE
[BUG] Run State and Pre State not update

### ISSUE THREAD

**Issue by grfernandes54** [ollo69/ha-smartthinq-sensors#132]
After install the new version the wascher Pre State and Run state stopped to work, they are keep showing stand by indepentent of the wasker real state

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSION
 - Home Assistant version installed: core-2021.3.4
 - Component version installed: v0.6.1
 - Last know working version: v0.5.16
 - LG device type and model with issue: Washer CV9011WC4A
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by ollo69** [comment]
The attributes name was changed. Please refer to [release note ](https://github.com/ollo69/ha-smartthinq-sensors/releases/tag/v0.6.1)

**Comment by grfernandes54** [comment]
I saw,  I've also activate the new entities but the run state at the device properties and the run state at the new entities that you created still with the stand by status (Em Espera in portuguese). The washer now is Washing but still showing stand by
<img width="241" alt="State withou update" src="https://user-images.githubusercontent.com/70862164/111222335-764b7500-85ba-11eb-8bfd-6760bd8721a2.png">


Look at this screenshot

**Comment by grfernandes54** [comment]
This is my washer model 

![PXL_20210315_204707625](https://user-images.githubusercontent.com/70862164/111222563-c4607880-85ba-11eb-86af-cc0c13eaa7f6.jpg)
![PXL_20210315_204713636](https://user-images.githubusercontent.com/70862164/111222573-c7f3ff80-85ba-11eb-9577-ffc2943e287d.jpg)

**Comment by ollo69** [comment]
Only this 2 states are not updated? They never changed or at least they was updated once?

**Comment by grfernandes54** [comment]
these ones is the ones that I use and can affirm that not changing.

What I noted is, the stated change from undefined to Stand by when I power on the washer but after I start to wash they not update to the real state of the washer

looking for the current status of each new entity that you created, looks like only the state when the machine was porwered on was pulled and after that nothing was update anymore

current course is showing only a dash - , the same thing for dry level, spin speed, water temp, 

<img width="241" alt="State withou update" src="https://user-images.githubusercontent.com/70862164/111223354-cd057e80-85bb-11eb-8ff1-02e81e804fcd.png">

tube clean count is show 25, this is the count when I power of the washer, I will monitor when the washer finish if it change to 26 or only change when I power off and power on again

I'm locate in Brazil is 18:30 for me now. Thi is a washer in my office. I will be back tomorrow at 09:00 my time and can update here.

**Comment by ollo69** [comment]
This is really strange, I have a washer and everything works fine. Please try also installing previous version from HACS to be sure that is a component issue.
I'll wait for your feedback

**Comment by grfernandes54** [comment]
Hi, after I rebook reboot the host everything started to work.

I apply the last update and still working. following the image with all states with information

<img width="239" alt="all states are working" src="https://user-images.githubusercontent.com/70862164/111310416-d33b3f80-863b-11eb-844e-111914d3387f.png">
