### ISSUE TITLE
[BUG] Error retrieving login URL from ThinQ

### ISSUE THREAD

**Issue by lordraiden** [ollo69/ha-smartthinq-sensors#133]
**Describe the bug**
1
![imagen](https://user-images.githubusercontent.com/17175395/111224128-4f9f3580-85de-11eb-884e-f6d8a5aecf2b.png)
2
![imagen](https://user-images.githubusercontent.com/17175395/111224162-575eda00-85de-11eb-9f63-e0266d6fd502.png)

**Expected behavior**
Go to the next step

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Docker
 - Home Assistant version installed: Home Assistant 2021.3.4
 - Component version installed: 0.6.1

**Output of HA logs**
Paste the relavant output of the HA log here.

```
Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:129
Integration: SmartThinQ LGE Sensors (documentation)
First occurred: 10:25:56 PM (4 occurrences)
Last logged: 10:32:29 PM

Error retrieving login URL from ThinQ
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 392, in connect
    self.ssl_context = create_urllib3_context(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 283, in create_urllib3_context
    context.set_ciphers(ciphers or DEFAULT_CIPHERS)
ssl.SSLError: ('No cipher can be selected.',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='route.lgthinq.com', port=46030): Max retries exceeded with url: /v1/service/application/gateway-uri (Caused by SSLError(SSLError('No cipher can be selected.')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 98, in getLoginUrl
    login_url = client.gateway.oauth_url()
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 600, in gateway
    self._gateway = Gateway.discover(self._country, self._language)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 292, in discover
    gw = gateway_info(country, language)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 206, in gateway_info
    return thinq2_get(V2_GATEWAY_URL, country=country, language=language)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 129, in thinq2_get
    res = requests.get(
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='route.lgthinq.com', port=46030): Max retries exceeded with url: /v1/service/application/gateway-uri (Caused by SSLError(SSLError('No cipher can be selected.')))

```

**Additional context**
It was working before but I don't remeber the component version (2 or 3 weeks ago) then some day it stopped working
Then I uninstalled it and installed again to start from scrach now I get this error.

**Comment by ollo69** [comment]
Did you install something in the machine that host HA? There is an SSL error `('No cipher can be selected.')`, looks like the machine is not able to establish the SSL connection with LG server.

**Comment by lordraiden** [comment]
> 
> 
> Did you install something in the machine that host HA? There is an SSL error `('No cipher can be selected.')`, looks like the machine is not able to establish the SSL connection with LG server.

It's the official docker image, so is not like I can install anything on it and I haven't done it anyway. Could you give me more clues of what could interfere with the SSL cipher selection?
I could do some troubleshoting but I have not idea where to start

**Comment by lordraiden** [comment]
I have HACS with this integrations but nothing else
![imagen](https://user-images.githubusercontent.com/17175395/111227639-29c85f80-85e3-11eb-95cf-81286d7eb15b.png)

**Comment by inorhan** [comment]
Hello.

I have the exact same problem, also "Es" account location, and "ssl.SSLError: ('No cipher can be selected.',)". 
Was working before too.

I see more errors like that one lately: https://community.home-assistant.io/t/get-roomba-blid-pw-the-easy-way-using-windows/75107/20

ProxmoxVE integration it's complaining too (same "ssl.SSLError: ('No cipher can be selected.')

Maybe a problem with Python-Hassio?

**Comment by ollo69** [comment]
It could be. But did you update HASSIO recently?

**Comment by inorhan** [comment]
Yes, I have Home Assistant 2021.3.4, HACS updated too.

core-2021.3.4
Sistema operativo del Host | Home Assistant OS 5.12
Canal de actualización | stable
Versión del Supervisor | supervisor-2021.03.6
Versión de Docker | 19.03.13

I don't really know when started to fail...

**Comment by ollo69** [comment]
This is quite complex, I don't really know how to help. I thing that there are some configuration than provide supported cipher, but I don't know exactly where to find this. I'm not using HASSIO. If I have some time I will make some test with it, but I don't know when it will happen.
I suggest you to google your issue, and please post here if you find a solution.

**Comment by stboch** [comment]
@inorhan Try removing lines 115-125 of custom_components/smartthinq_sensors/wideq/core_v2.py #195

**Comment by inorhan** [comment]
> 
> 
> @inorhan Try removing lines 115-125 of custom_components/smartthinq_sensors/wideq/core_v2.py #139

That worked perfectly, no more "ssl.SSLError: ('No cipher can be selected.',)". Thanks!!!

**Comment by ollo69** [comment]
Really good to know, working on final fix

**Comment by ollo69** [comment]
Can we close this issue? It should be fixed with last release.
