### ISSUE TITLE
Ability to update password?

### ISSUE THREAD

**Issue by jjMustang** [ollo69/ha-smartthinq-sensors#134]
I had to reset my LG Thinq password, but I cannot find a way to update it within the integration. I assume I could remove it and re-add it, but I'm worried about losing my automations. How can I update the HACS add-on to use the new password?

**Comment by ollo69** [comment]
This is not possible, because te password is used to generate a token. You must remove and re-configure integration. Your automations should not be affected because are stored separately.

**Comment by BebeMischa** [comment]
I can confirm this, automation's remain working after reinstall. Just done this and tested.

**Comment by jjMustang** [comment]
Agreed. I removed and re-added without incident. Perhaps in your documentation you could add a note about what to do if you reset your password. I had forgotten about the token URL, and I imagine others will do the same.
