### ISSUE TITLE
The door status entity of my fridge no longer works

### ISSUE THREAD

**Issue by sidwin9** [ollo69/ha-smartthinq-sensors#136]
**Describe the bug**
Since the last update 0.6.2, the status entity for my refrigerator door no longer works while the temperature and refrigerator status entities are working.
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/45182426/111516690-78e1d200-8754-11eb-86e9-7025fb36b3f2.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed: 2021.3.4
 - Component version installed:
 - Last know working version: 0.6.1 I believe
 - LG device type and model with issue: Fridge LG GBB92STAXP
 - LG devices connected (list): Fridge LG GBB92STAXP

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by ollo69** [comment]
This is due to entity rename done in with last release. Please follow instruction provided in [release note](https://github.com/ollo69/ha-smartthinq-sensors/releases/tag/v0.6.2).

**Comment by BebeMischa** [comment]
I had this too. Removed the integration and installed it again. Works.
