### ISSUE TITLE
[BUG] wideq changes SSL DEFAULT_CIPHERS which affects other home-assistant components

### ISSUE THREAD

**Issue by stboch** [ollo69/ha-smartthinq-sensors#139]
**Describe the bug**
Rather then setting the ciphers for the calls made by the service the urllib3's default ciphers are changed which interfers with other home-assistant components needing the excluded URL ciphers. This appears it was a fix for older python urllib and request packages but are not needed when new libraries are managed by home-assistant.

**Environment details:**
google_home custom component is an example of this [issue](https://github.com/leikoilja/ha-google-home/issues/95).

**Additional context**
Removal of lines 115-125 in custom_components/smartthinq_sensors/wideq/core_v2.py resolves the offending issue.

**Comment by ollo69** [comment]
This seems a good suggestion and I will be happy to implement, but are you sure that this always valid? Or I should implement a setting option to leave the option to enable this?

**Comment by KapJI** [comment]
@ollo69 I think modifying `DEFAULT_CIPHERS` is a bad practice maybe you can use `SSLContext` instead?
Example: https://github.com/simon-weber/gpsoauth/pull/25

**Comment by ollo69** [comment]
> I think modifying `DEFAULT_CIPHERS` is a bad practice maybe you can use `SSLContext` instead?

That's fine, also good suggestion. But I'm wondering if I still have to change used cypher or it is not needed as suggested by @stboch

**Comment by stboch** [comment]
@ollo69 really not sure, just tried it out on my setup as I was trying to troubleshoot the mysterious error me and a few others had and let back to this code. I would be interested to see if the other user who is having the cipher problem if it goes away if they change it. 
Luckily its not a big refactor to tweak that section since it seems like its only referred to in one place.

**Comment by ollo69** [comment]
Yes, but I just want to avoid to break component for other user that have no issue, may be this is related to LG server region. Anyway I understand that I should avoid to change `DEFAULT_CIPHERS` because I should also break other components, so I will start trying to manage this with `SSLContext`

**Comment by ollo69** [comment]
Can we close this issue? It should be fixed with last release.

**Comment by KapJI** [comment]
Yes, thank you for fixing this!

**Comment by ollo69** [comment]
> Yes, thank you for fixing this!

Thank you to highlight this, and sorry for issues generated!!!!
