### ISSUE TITLE
[BUG] LG Fridge no temperatures 

### ISSUE THREAD

**Issue by aceindy** [ollo69/ha-smartthinq-sensors#141]
Not sure since when, but i noticed the temperatures in HA are no longer showing any values: 
Refrigerator Temp      - C
Freezer Temp.            - C
🤔😕

**Comment by ollo69** [comment]
Can you please provide more info? Refrigerator model and model info url reported in the log during startup.

**Comment by aceindy** [comment]
I'm ashamed now..sorry...it seems someone turned of the WiFi of the fridge, so that is why it did not give any values
