### ISSUE TITLE
[Feature Request] Lovelace Fridge Card ?

### ISSUE THREAD

**Issue by Pascal66** [ollo69/ha-smartthinq-sensors#143]
**Is your feature request related to a problem? Please describe.**
Not confortable with lovelace yaml, etc..

**Describe the solution you'd like**
A simple card like the washer exist in example

**Describe alternatives you've considered**
Using standard card

**Additional context**
Everything worked fine with my fidge

**Comment by KTibow** [comment]
What do you mean? Could you elaborate, and maybe add screenshots to illustrate?

**Comment by Pascal66** [comment]
I've no screenshot as I ask to help to have a fridge card for lovelace working with this plugin
Btw the plugin just give me no more information than what is displayed on the fridge, and not all the app is sending to the mqtt of lg (internal temps, open/close doors count, and maybe many others), I not hurry to use it.
Thank you for you work

**Comment by KTibow** [comment]
You need to check the attributes for some of the properties. You can also create your own card by configuring the cards built into HA.
