### ISSUE TITLE
[BUG] After install from HACS. Nothing shows in the integration

### ISSUE THREAD

**Issue by microfix** [ollo69/ha-smartthinq-sensors#145]
**Describe the bug**
Fresh home assistant install, installed SmartThinQ LGE Sensors from HACS.
After a 5 min wait, I restartede HA.
Now when I + integration can't find the SmartThinQ LGE Sensors.

![image](https://user-images.githubusercontent.com/1528406/114395891-310c6a00-9b9d-11eb-830f-7b6008d344fa.png)

![image](https://user-images.githubusercontent.com/1528406/114395826-22be4e00-9b9d-11eb-8e94-f5b90ec5ed2f.png)

**Comment by ollo69** [comment]
Clear your browser cache.

**Comment by microfix** [comment]
Thanks. 
I feel stupid. But it works. :)

**Comment by ollo69** [comment]
Can we close?

**Comment by microfix** [comment]
Done
