### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by speedster-pta** [ollo69/ha-smartthinq-sensors#155]
**Describe the bug**
I installed via HACS and the expected SmartThinq sensors are not created, nor does Lovelace give an option to configure the device.

**Expected behavior**
Lovelace to request configuration details for the integration

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Home Assistant Supervised on Docker (Debian)
 - Home Assistant version installed: 2021.5.2
 - Component version installed: 0.7.0
 - Last know working version: N/A
 - LG device type and model with issue: N/A - can't even enter the account credentials as yet

**Comment by ollo69** [comment]
Please provide more information and provide a title to the issue.
What are the expected sensors? What devices you own? Do you have some errors in HA Logs?

**Comment by speedster-pta** [comment]
There are no errors in HA logs. The expected sensors would be those in the
washer, but surely these would only be identified once I'm able to connect
to my LG account

**Comment by ollo69** [comment]
Please provide screenshot about your issue, your description is incomprehensible.

**Comment by speedster-pta** [comment]
How do I provide a screenshot of something that isn't there?

I've installed the integration via hacs but am now not able to configure
it. Let me phrase it differently, what is the next step after installing
the integration via HACS?

**Comment by ollo69** [comment]
Configure the integration from the HA integration page

**Comment by speedster-pta** [comment]
How? There is no option to do so

**Comment by ollo69** [comment]
Looks like you don't really know how HA works. Please remember that this is not an help desk, if you don't now how to configure a new integration you should start reading readme and eventually ask for help in HA forum and not open issue.
In any case, there is a "+" button in the bottom-right corner of the integration page, press the button and search for the integration to start configure it.

**Comment by speedster-pta** [comment]
Thank you

**Comment by ollo69** [comment]
Can we close this?

**Comment by speedster-pta** [comment]
Yes

**Comment by dwspautomation** [comment]
I'm having exactly the same problem that @speedster-pta describes.

Were you able to resolve this @speedster-pta ?

**Comment by ollo69** [comment]
Please not add comment to closed issue. Read the thread, if you have question related to HA usage ask help in HA forum. I will lock this conversation.
