### ISSUE TITLE
[BUG] LG Air Conditioner does not turn on

### ISSUE THREAD

**Issue by hros** [ollo69/ha-smartthinq-sensors#156]
LG Air conditioner is detected by integration and displayed by home assistant
The current status of the air conditioner is correctly displayed
I am able to change the set temperature and turn it off from home assistant
However, once the air conditioner is off I cannot turn it back on from home assistant. It does turn on from LG Thinq app

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): home assistant core
 - Home Assistant version installed: 2021.5.3
 - Component version installed: 0.7.1
 - Last know working version:
 - LG device type and model with issue:
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by ollo69** [comment]
Can you provide more details? There are some errors in HA log when you try to turn device on? Can you provide device JSON info to analyze available commands?

**Comment by hros** [comment]
I'd be happy to provide more information 
When the logging level is set to info or warning, I do not see anything relevant in the log
When I set the log level to debug  I am flooded with messages

Please advise how to collect the relevant information

**Comment by ollo69** [comment]
To begin I just need the JSON info file. You can follow [this](https://github.com/ollo69/ha-smartthinq-sensors/issues/37#issuecomment-817316256) instruction to download the file, than attach it to this thread.

**Comment by hros** [comment]
[ac.zip](https://github.com/ollo69/ha-smartthinq-sensors/files/6500307/ac.zip)

**Comment by ollo69** [comment]
Are you able to make a quick change in the code to perform a test?

**Comment by hros** [comment]
sure

**Comment by ollo69** [comment]
OK, just a tentative. 
Modify the file `ac.py`  in folder `wideq`. Go to line `196`, you should have this code:

```
        # This ON operation appears to be supported in newer AC models
        if ACOp.ALL_ON in operations:
            return ACOp.ALL_ON

        # This ON operation appears to be supported in V2 AC models, to check
        if ACOp.ON in operations:
            return ACOp.ON

```

just invert the 2 `if` in this way:

```
        # This ON operation appears to be supported in V2 AC models, to check
        if ACOp.ON in operations:
            return ACOp.ON

        # This ON operation appears to be supported in newer AC models
        if ACOp.ALL_ON in operations:
            return ACOp.ALL_ON

```

so that will be sent to the device `ACOp.ON` and not `ACOp.ALL_ON`.

Reboot HA and report here if this work.

**Comment by hros** [comment]
The code switch indeed switch the situation, but not solve it....
now the a/c can be turned off, but not turned on

**Comment by ollo69** [comment]
Turn off was already working, right? This is what you say at the beginning of this thread, or something is changed?

**Comment by hros** [comment]
yes, to both:
1. turn-off was working initially, and turn-on wasn't
2. something has changed: now turn-on works, but turn-off doesn't

**Comment by hros** [comment]
After additional tinkering, it turns out that I can start the a/c by pressing the appropriate mode icon (the middle snow flake for cooling), and the power button (right below the cool button) turns the a/c off
the power button does not turn it on
![image](https://user-images.githubusercontent.com/2613469/118659367-eb733a80-b7f5-11eb-9c71-a6592c07bf96.png)

**Comment by ollo69** [comment]
Ok, this is expected behavior, HA climate control work in this way. So I think that issue ca be closed.

**Comment by hros** [comment]
if this is indeed the expected behavior, then, yes, this issue can be closed
I still think it is more intuitive for the power button to turn the a/c both on and off, and not only turn it off

thanks for your great work

on a different note, do you an example showing how to create an automation for an a/c? (reading its current state, and performing changes: turning on/off, changing modes and temperature, and special modes: neo-plasma, auto-dry...)

**Comment by ollo69** [comment]
> I still think it is more intuitive for the power button to turn the a/c both on and off

Yes, but this is related to HA climate architecture and Front-end implementation. Power button is associated to HVAC_MODE_OFF.



> on a different note, do you an example showing how to create an automation for an a/c? (reading its current state, and performing changes: turning on/off, changing modes and temperature, and special modes: neo-plasma, auto-dry...)

I don't have example, anyway there are a lot of solution to implement automation. Basically HA expose a set of standard services that can be called to change climate entity status, refer to [here](https://www.home-assistant.io/integrations/climate/) for more details. Special modes are not currently supported and should require implementation of dedicated service to control them, not in my plan for the moment.

I close this issue.
