### ISSUE TITLE
minimum temperature limit issue

### ISSUE THREAD

**Issue by conductorj** [ollo69/ha-smartthinq-sensors#161]
The component installed and is working great but the lowest I can set the temperature to is 64 degrees Fahrenheit.  It should be 60 degrees Fahrenheit.  Is this something I can adjust somewhere?  I tried another component similar to this one and the minimum was correct at 60.

This is a window AC unit and the device info in HA is showing as WIN_056905_WW-WIN (AC) by LG

**Comment by ollo69** [comment]
Why you think that correct min value is 60. I read min value from definition file and I saw that other integration just use an hard coded value. May be I'm not reading the right value, but I would like to understand why you assume that is wrong.

**Comment by conductorj** [comment]
Thanks for checking on this and really appreciate your work on the component.  The AC unit's adjustable range is 60-86.

**Comment by ollo69** [comment]
Can u please download and share here json definition file?

**Comment by conductorj** [comment]
Can you be more specific about what file you are looking for?  Still learning this stuff.  Thanks

**Comment by ollo69** [comment]
Follow [this](https://github.com/ollo69/ha-smartthinq-sensors/issues/37#issuecomment-817316256) instruction.

**Comment by conductorj** [comment]
Thanks.  File attached.  Model is LG LW1019IVSM

[327b4ff8-1cc6-4f50-a6e3-194754d6d47b.zip](https://github.com/ollo69/ha-smartthinq-sensors/files/6522813/327b4ff8-1cc6-4f50-a6e3-194754d6d47b.zip)

**Comment by ollo69** [comment]
As you can see inside the file, I'm using this for limit:

```
		"airState.tempState.target": {
			"data_type": "range",
			"default": 18,
			"value_validation": {
				"min": 18,
				"max": 30
			}
		},
```

I could also use, for instance: 

```
		"airState.tempState.limitMin": {
			"data_type": "range",
			"default": 16,
			"value_validation": {
				"min": 16,
				"max": 30
			}
		},

```

or also:

```
		"airState.tempState.limitMax": {
			"data_type": "range",
			"default": 16,
			"value_validation": {
				"min": 16,
				"max": 30
			}
		},

```

So, the question is, is this really an issue? Do you really need to set temperature below 18 °C?

**Comment by conductorj** [comment]
I guess you could call it a request at this point as it is working as is.  The unit supports 16-30 so I'm not sure why there is the 18-30 limit.  I run my unit off of external thermostat because I find the internal thermistor to be very inaccurate.  For the last year I've been using a controlled IR transmitter for the triggering but much prefer this option.  I like to run it at the lowest temperature when cooling so I know I'm covered no matter what the temperature in the room is.  Again, really appreciate your time and effort on this component.

**Comment by ollo69** [comment]
Using last version minimal temperature should be fixed. I assume that 16 is minimal supported value by default

**Comment by conductorj** [comment]
16 (60F) is the minimum.  The range (60-86F) is now setting properly with the latest update.  Thanks again for all of your work on this.
