### ISSUE TITLE
Can't delete old LGE WASHERS integration

### ISSUE THREAD

**Issue by nortuzar** [ollo69/ha-smartthinq-sensors#17]
Hi, I was able to set up my washer with the new sensor integration, but the last integration remain and I can't delete it using the basket icon on the integration section. I don't have nothing set up on configuration.yaml   Already reboot, try again to delete but nothing, still the notification regarding the old integration. HA 0.108.6 on rasp 3b+ Any clue?

![image](https://user-images.githubusercontent.com/55258023/79700505-29ed9d00-8264-11ea-97c1-63f1f7d92f9f.png)
![image](https://user-images.githubusercontent.com/55258023/79700583-b9934b80-8264-11ea-8285-7a2acfe9f7f0.png)
![image](https://user-images.githubusercontent.com/55258023/79700600-cf087580-8264-11ea-82a0-d344a75261c2.png)

**Comment by ollo69** [comment]
I suppose that you install the new one without deconfiguring the previous, so probably now the old one is not present as integration but configured in the registry.
I suggest you to do the following:
1) remove configuration of new one
2) install previous version from HACS (last 0.2.x)
3) reboot HA
4) you should now see old integration configured, remove configuration again
5) install last version from HACS
6) configure again

**Comment by nortuzar** [comment]
@ollo69 I was typing when you answer! Thanks, I exactly did that, sorry for the rush before doing my own research.
Anyway, is working great!
