### ISSUE TITLE
[BUG] sensor.washer_door_lock always known

### ISSUE THREAD

**Issue by hmoffatt** [ollo69/ha-smartthinq-sensors#171]
**Describe the bug**
The entity sensor.washer_door_lock is always unknown. The sensor.washer door_lock attribute is correct though (on/off).

**Expected behavior**
sensor.washer_door_lock should be on or off.

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): container
 - Home Assistant version installed: 2021.1.5
 - Component version installed: 0.8.8
 - Last know working version:
 - LG device type and model with issue: Thinqv2 washer
 - LG devices connected (list):

**Comment by ollo69** [comment]
But did you enable the sensor? Many sensor are created in disabled state by default and must be enabled.

**Comment by hmoffatt** [comment]
Argh, sorry that was a template sensor of mine referring to the old name of the attribute doorlock_mode.
