### ISSUE TITLE
Remote start\wakeup not work with my models

### ISSUE THREAD

**Issue by sagitt** [ollo69/ha-smartthinq-sensors#172]
**Describe the bug**
not work with:
LG  F4J7VY1W
LG RC90U2AV4Q

Tried to send service form development tools giving as entity the device sensor.

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HassOS
 - Home Assistant version installed: 2021.6.3
 - Component version installed: 0.8.8
 - Last know working version: n/a
 - LG device type and model with issue: LG F4J7VY1W / LG RC90U2AV4Q
 - LG devices connected (list):

**Comment by ollo69** [comment]
This functionality is still work-in-progress, so is better to provide feed-back using the dedicated thread #47.

In any case please provide:

- detailed operation that you perform on the devices before calling the service
- HA log with debug level for the integration

I'm not able to provide any support without this information

**Comment by sagitt** [comment]
thanks

**Comment by sagitt** [comment]
> This functionality is still work-in-progress, so is better to provide feed-back using the dedicated thread #47.
> 
> In any case please provide:
> 
> * detailed operation that you perform on the devices before calling the service
> * HA log with debug level for the integration
> 
> I'm not able to provide any support without this information

I tried again,

my dryer works with wakeup and remote start. i'm using run_state sensor, before used dryer status sensor.

my washer instead, works with remote_start on run_state sensor but not wakeup.

I checked and seem that the washer have no wifi in standby mode, is possible this?

**Comment by ollo69** [comment]
> I checked and seem that the washer have no wifi in standby mode, is possible this?

Looks strange, how you could wake it up? What you can do from mobile phone app?

**Comment by tayanov** [comment]
it's time to delete the sensors from the name))) BRAVO

**Comment by ollo69** [comment]
I close this thread because remote start seems generally working. Open a new one for specific issue.
