### ISSUE TITLE
[BUG] Oven Rempte

### ISSUE THREAD

**Issue by pbix** [ollo69/ha-smartthinq-sensors#173]
**Describe the bug**
This integration does not seem to work with LG Wall oven.  I do not see the expected values.

**Expected behavior**
I know this is a new integration.  Just trying to provide some feedback on how its working with my oven.

In HA sensor.oven_oven_lower_target_temperature shows the value of "Unknown" while I see in the log that 350 is reported.
Also would like to see the current temperature as a sensor.  This is also reported in the log as 'lowerCurrentTemperatureValue': 185.0.

The lower oven has a remote start capability so that would be nice to see as a service.  The upper oven is a combo convection/microwave.  I cannot see a way to start that one from the iOS app so I think that may not be possible.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed: core-2021.6.3
 - Component version installed: 0.8.8
 - Last know working version: None
 - LG device type and model with issue: LSWC307ST
 - LG devices connected (list): 

**Output of HA logs**
Paste the relavant output of the HA log here.
I have debug turned on for this integration and see the following Oven related output that might be of use.

 'deviceState': 'E', 'snapshot': {'ovenState': {'upperControlLock': 'DISABLE', 'cooktop1CooktopState': 'INIT', 'cooktop2CooktopState': 'INIT', 'cooktop5PowerLevel': 0.0, 'lowerEasyCleanEnable': 'DISABLE', 'cooktop1OperationTimeHour': 0.0, 'upperAutoCookName': 'NONE', 'cooktop5CooktopState': 'INIT', 'lowerRemainTimeSecond': 59.0, 'lowerRemoteStartUsing': 'ENABLE', 'cooktop2OperationTimeSecond': 0.0, 'upperEasyCleanEnable': 'DISABLE', 'upperTargetTemperatureUnit': 'FAHRENHEIT', 'cooktop3CooktopState': 'INIT', 'cooktop4OperationTimeSecond': 0.0, 'cooktop2OperationTimeHour': 0.0, 'lowerDoorLock': 'DISABLE', 'cooktop4CooktopState': 'INIT', 'upperTimerSecond': 0.0, 'upperSabbath': 'DISABLE', 'upperState': 'INITIAL', 'upperDoorLock': 'DISABLE', 'lowerMyRecipeCookNumber': 0.0, 'cooktop4PowerLevel': 0.0, 'cooktop3OperationTimeHour': 0.0, 'upperTimerSet': 'ENABLE', 'cooktop5OperationTimeHour': 0.0, 'lowerDoorOpen': 'DISALBE', 'lowerDemoMode': 'DISABLE', 'lowerCurrentTemperatureUnit': 'FAHRENHEIT', 'lowerRemainTimeMinute': 11.0, 'lowerTimerHour': 0.0, 'upperTimerHour': 0.0, 'cooktop1PowerLevel': 0.0, 'lowerEasyCleanCount': 0.0, 'upperRemainTimeMinute': 0.0, 'upperTimerMinute': 0.0, 'cooktop3PowerLevel': 0.0, 'lowerManualCookName': 'LOWER_BAKE', 'lowerSabbath': 'DISABLE', 'lowerTimerSecond': 0.0, 'drawerPowerLevel': 0.0, 'lowerCurrentProveTemperatureF': 0.0, 'upperTargetTemperatureValue': 0.0, 'upperRemoteStart': 'DISABLE', 'upperRemainTimeHour': 0.0, 'upperFotaEnable': 'DISABLE', 'lowerTargetTemperatureUnit': 'FAHRENHEIT', 'upperDoorOpen': 'DISALBE', 'cooktop1OperationTimeSecond': 0.0, 'cooktop3OperationTimeSecond': 0.0, 'lowerRemainTimeHour': 0.0, 'upperCurrentTemperatureValue': 94.0, 'lowerIsError': 'DISABLE', 'lowerTargetProveTemperatureF': 0.0, 'lowerTargetTemperatureValue': 350.0, 'cooktop5OperationTimeSecond': 0.0, 'lowerTimerSet': 'ENABLE', 'upperRemainTimeSecond': 0.0, 'lowerControlLock': 'DISABLE', 'lowerCurrentTemperatureValue': 185.0, 'upperRemoteStartUsing': 'DISABLE', 'upperOptionSet': 'ENABLE', 'cooktop2PowerLevel': 0.0, 'upperMWOPowerLevel': 0.0, 'lowerTimerMinute': 0.0, 'lowerState': 'PREHEATING', 'upperDemoMode': 'DISABLE', 'lowerFotaEnable': 'DISABLE', 'cooktop1OperationTimeMinute': 0.0, 'upperIsError': 'DISABLE', 'upperEasyCleanCount': 0.0, 'upperCurrentTemperatureUnit': 'FAHRENHEIT', 'cooktop2OperationTimeMinute': 0.0, 'cooktop4OperationTimeMinute': 0.0, 'lowerOptionSet': 'DISABLE', 'upperManualCookName': 'NONE', 'cooktop3OperationTimeMinute': 0.0, 'cooktop5OperationTimeMinute': 0.0, 'lowerRemoteStart': 'ENABLE', 'cooktop4OperationTimeHour': 0.0}, 'mid': 75980518.0, 'online': True, 'static': {'deviceType': '301', 'countryCode': 'US'}, 'meta': {'allDeviceInfoUpdate': False, 'messageId': 'AAy8qkEDRu-JmwyZyXT5WA'}, 'timestamp': 1623272689580.0}, 'online': True, 'platformType': 'thinq2', 'area': 334505, 'regDt': 20201202203229.0, 'blackboxYn': 'Y', 'order': 0, 'drServiceYn': 'N', 'fwInfoList': [{'checksum': '0000E145', 'partNumber': 'SAA41423501', 'order': 1.0}], 'modemInfo': {'modelName': 'WLC389PC', 'appVersion': 'clip_hna_v1.9.080', 'modemType': 'QCOM_QCA4010', 'ruleEngine': 'y'}, 'guideTypeYn': 'Y', 'guideType': 'TYPE4', 'regDtUtc': '20201203003229', 'regIndex': 0, 'groupableYn': 'N', 'controllableYn': 'N', 'combinedProductYn': 'N', 'masterYn': 'Y', 'pccModelYn': 'Y', 'autoOrderYn': 'N', 'initDevice': False, 'existsEntryPopup': 'N', 'tclcount': 0}, {'appType': 'NUTS', 'modelCountryCode': 'WW', 'countryCode': 'US', 'modelName': 'F3P2CYUBE__', 'deviceType': 201, 'deviceCode': 'LA02', 'alias': 'Washer', 'deviceId': '035700b2-63e3-1879-a419-402f86f14cb5', 'fwVer': '', 'imageFileName': 'home_appliances_img_wmdrum.png', 'imageUrl': 'https://objectstore.lgthinq.com/3120cb69-4c7c-48d5-9d..............
```

```

**Additional context**

**Comment by ollo69** [comment]
Thanks for the feedback and information, could you also provide JSON device information file?
I will try to fix as soon as I will have some additional free time.

**Comment by pbix** [comment]
When I call the service as shown below I receive and error in the lower left

"Failed to call service ......: Unknown Error"

Then in the log the below appears:

021-06-09 20:23:10 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 368, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 568, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 666, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/sensor.py", line 680, in async_remote_start
    raise NotImplementedError()
NotImplementedError
2021-06-09 20:23:10 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140170557413216] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 525, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1216, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 350, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 368, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 568, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 666, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/sensor.py", line 680, in async_remote_start
    raise NotImplementedError()

![image](https://user-images.githubusercontent.com/289729/121446051-b70c1d80-c960-11eb-91c6-5029d8ddbb3b.png)


It seems no JSON file is present.  

Am I submitting the correct service?

**Comment by ollo69** [comment]
Remote start is only for DRYER and WASHER, not for Oven. You correctly receive "NotImplementedError".

**Comment by pbix** [comment]
Is this what you need?

[98156830.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/6627671/98156830.txt)

**Comment by ollo69** [comment]
No, this is the translation, I need the definition.

**Comment by pbix** [comment]
[OvenJSON.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/6627738/OvenJSON.txt)

**Comment by ollo69** [comment]
Could you check if with last release target and current temperatures are properly detected?

**Comment by pbix** [comment]
I updated and checked the target and current temperatures and the on/off sensors and they all seem to work.  The lower oven current temperature reads zero until the temperature exceeds 130degF.  The upper over current temperature always seems to work.  Its a cool feature to be able to see the current temperatures using this automation as this is not otherwise available on the oven display or the LG App.

Many sensors, not appropriate to this double wall oven, show "unavailable".  For others who read this in the future the below screen shot shows the sensors that work.  At the time of this writing there are no services available to control the wall oven.  A note for future developments is that it is not possible to start the upper over from the LG App so it may not be possible to do it from HA either.
![Screenshot at 2021-06-12 10-16-36](https://user-images.githubusercontent.com/289729/121778950-58fd5700-cb67-11eb-81aa-e7f7428dbc83.png)

Thanks again to #ollo69 for making all this work.

**Comment by ollo69** [comment]
I will review this in the future to not create sensor not appropriate. The reason is this part is implemented to manage both Oven and CookTop, but i think that is possible to determinate what is availble and what not
Probably `binary_sensor` "Oven" should be renamed something like "Oven State".

**Comment by ollo69** [comment]
Seems that is not possible to avoid creation of all sensors because all info are always provides and available in the JSON info file. There is something available in the config section of the JSON Info, but I don't have enough information to base a filter on this.
For the moment with last release I changed some name and icons of the sensors.

**Comment by ollo69** [comment]
Can we close this issue? Additional feature request can be opened in new threads.

**Comment by pbix** [comment]
Yes I think so.  Thanks for sorting this out.  Its not a big deal to have to decide the appropriate sensors for the appliance you have.
Would rather dedicate and resource you have to creating services.

**Comment by ollo69** [comment]
Ok, I close this, pls open a new feature request for Range control so that we can keep track for this.
