### ISSUE TITLE
[BUG] All LG Devices unavailable after update

### ISSUE THREAD

**Issue by jordibsk10** [ollo69/ha-smartthinq-sensors#174]
**Describe the bug**
After updating the integration to the last version (v.0.8.10) all my LG devices have gone unavailable.

**Expected behavior**
No major changes apart from the new services added.

**Screenshots**
![image](https://user-images.githubusercontent.com/62246724/121663594-de6d0280-caa6-11eb-815f-afa1f37497bd.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed: core-2021.6.3
 - Component version installed: v0.8.10
 - Last know working version: v.0.8.8
 - LG device type and model with issue: Fridge, Drier, Washer, Mini-Washer and Dishwasher (5 devices)

**Output of HA logs**
Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/device.py:636
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 11:11:32 (4 occurrences)
Last logged: 11:12:53

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 201, in async_setup_entry
    lge_devices = await lge_devices_setup(hass, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 576, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 349, in init_device
    features = self._state.device_features
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1289, in device_features
    self._update_features()
  File "/config/custom_components/smartthinq_sensors/wideq/washerDryer.py", line 585, in _update_features
    self.standby_state,
  File "/config/custom_components/smartthinq_sensors/wideq/washerDryer.py", line 477, in standby_state
    status = self.lookup_enum(["Standby", "standby"])
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1222, in lookup_enum
    return self._device.model_info.enum_name(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 665, in enum_name
    options = self.value(data)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 636, in value
    assert False, "unsupported value type {}".format(data_type)
AssertionError: unsupported value type Boolean

**Comment by jordibsk10** [comment]
I've just tried going back to v0.8.8 and it went back to working perfectly as always.
But when updating to v0.8.10, all LG devices go to unavailable and I get the above error message.
(For now, I 'm staying in v0.8.8 as is the last one it works for me. I will try with v0.8.9 afterwards just to see if it's coming from version 9 or 10.)

Don't know what I can provide to give you more details and be able to investigate this issue :(

Nevertheless, really appreciate for your time and your great work!

**Comment by ollo69** [comment]
The issue seems to caused by Standby washer / dryer sensors that I added in last release
Could you provide the JSON info of your washer so that I can try to understand the format of this data that is causing the issue?

**Comment by jordibsk10** [comment]
Sure, but unfortunately I'm don't know where to find it... would you mind pointing me out how can I get that specific JSON?
Apologies

**Comment by ollo69** [comment]
In HA log, during startup, you could find information line that contain a `https` address to download the JSON info file. Copying that address in the browser address bar should start the download of the file. After you download it attach it to this thread,

**Comment by jordibsk10** [comment]
I've only been able to find this https address (https://version.home-assistant.io/stable.json). But I don't think that's the one you are looking for, right? 
![image](https://user-images.githubusercontent.com/62246724/121681114-ae2f5f00-caba-11eb-9ba3-f4870b530327.png)

I'm looking for the address here:
![image](https://user-images.githubusercontent.com/62246724/121681241-dc14a380-caba-11eb-9a25-97fdde1f21ea.png)
Is it correct? Should appear somewhere here, right?

If I'm completely wrong, maybe if you can share the https address you get/refering to, I can try to use it in my system... and see if it works?¿

**Comment by ollo69** [comment]
No is wrort 
You should look in the HA Log and not supervisor log. Search for `Loading model info for  ... "Url: https://...`

**Comment by jordibsk10** [comment]
I don't see any Loading model info for ... "Url: https://...
![image](https://user-images.githubusercontent.com/62246724/121683696-09af1c00-cabe-11eb-8625-3a8c2e9c484b.png)
Should be somewhere here, right?
Sorry for the inconveniences.
Apologies :(

**Comment by ollo69** [comment]
I think that is the right file, but is before. This info is provided during HA startup, may be you can reboot ha and check again

**Comment by aslabicki** [comment]
I have the same issue with my washer and dryer after the update to 0.8.10 version.

JSON from my Dryer:
[Dryer_RC90U2_WW.log](https://github.com/ollo69/ha-smartthinq-sensors/files/6641280/Dryer_RC90U2_WW.log)

**Comment by ollo69** [comment]
Could you check if with last release issue is fixed and Standby sensors/attributes is properly detected (standby means that machine is in remote start mode and go in standby)?

**Comment by aslabicki** [comment]
On the newest version (0.8.11) state of dryer and washer looks good.

I turned on the washer and enabled remote start and state was like this:

```
model: F_R8_Y___W.A__QEUK-FL
mac_address: xx:xx:xx:xx:xx:xx
run_completed: 'off'
error_state: 'off'
initial_time: '3:34'
remain_time: '3:34'
reserve_time: '0:00'
current_course: Bawełna
run_state: Gotowość
pre_state: Gotowość
error_message: '-'
spin_speed: '-'
water_temp: '-'
tubclean_count: '57'
standby: 'off'
remote_start: 'on'
door_lock: 'on'
child_lock: 'off'
crease_care: 'off'
steam: 'off'
steam_softener: 'off'
pre_wash: 'off'
turbo_wash: 'off'
medic_rinse: 'off'
friendly_name: Washer
icon: mdi:washing-machine
```

Then I started washing by calling the service
```
service: smartthinq_sensors.remote_start
data:
  entity_id: sensor.washer
```

And the current state is:
```
model: F_R8_Y___W.A__QEUK-FL
mac_address: xx:xx:xx:xx:xx:xx
run_completed: 'off'
error_state: 'off'
initial_time: '1:30'
remain_time: '1:24'
reserve_time: '0:00'
current_course: Bawełna
run_state: Pranie
pre_state: Pranie
error_message: '-'
spin_speed: '1400'
water_temp: 40℃
tubclean_count: '57'
standby: 'off'
remote_start: 'on'
door_lock: 'on'
child_lock: 'off'
crease_care: 'off'
steam: 'off'
steam_softener: 'off'
pre_wash: 'off'
turbo_wash: 'off'
medic_rinse: 'off'
friendly_name: Washer
icon: mdi:washing-machine
```

**Comment by aslabicki** [comment]
Now I can confirm that the standby sensor works also.

```
model: F_R8_Y___W.A__QEUK-FL
mac_address: xx:xx:xx:xx:xx:xx
run_completed: 'off'
error_state: 'off'
initial_time: '1:30'
remain_time: '0:00'
reserve_time: '0:00'
current_course: '-'
run_state: Gotowość
pre_state: Gotowość
error_message: '-'
spin_speed: '-'
water_temp: '-'
tubclean_count: '58'
standby: 'on'
remote_start: 'on'
door_lock: 'off'
child_lock: 'off'
crease_care: 'off'
steam: 'off'
steam_softener: 'off'
pre_wash: 'off'
turbo_wash: 'off'
medic_rinse: 'off'
friendly_name: Washer
icon: mdi:washing-machine
```

**Comment by aslabicki** [comment]
The dryer standby sensor has a different value than on/off. It's a shortcut of the polish word "Włączony" but works also.

```
model: RC90U2_WW-Dryer
mac_address: xx:xx:xx:xx:xx:xx
run_completed: 'off'
error_state: 'off'
initial_time: '0:00'
remain_time: '0:00'
reserve_time: '0:00'
current_course: '-'
run_state: Gotowość
pre_state: '-'
error_message: '-'
dry_level: '-'
standby: WŁ.
remote_start: 'on'
child_lock: 'off'
friendly_name: Dryer
icon: mdi:tumble-dryer
```

**Comment by ollo69** [comment]
> The dryer standby sensor has a different value than on/off. It's a shortcut of the polish word "Włączony" but works also.

This is wrong. It should only be "on" or "off". Could you enable debug for integration and attach here the result for your dryer, I need to understand what is provided in the paylod.

**Comment by ollo69** [comment]
May be I found the issue, related to translation order. Pls wait next release to make a new test.

**Comment by ollo69** [comment]
Can you try with the last release if standby status now contain the right values?

**Comment by aslabicki** [comment]
Unfortunately dryer stopped working after update

![image](https://user-images.githubusercontent.com/15276598/121808599-84606e80-cc59-11eb-8927-3bc564a85585.png)

**Comment by ollo69** [comment]
Typo adding new feature to your dryer (process info) 😒. Will release fix soon...

**Comment by ollo69** [comment]
It should be fixed with new version 0.8.13 just released

**Comment by aslabicki** [comment]
The newest version is working well. Thanks a lot.

```
model: RC90U2_WW-Dryer
mac_address: xx:xx:xx:xx:xx:xx
run_completed: 'off'
error_state: 'off'
initial_time: '0:00'
remain_time: '0:00'
reserve_time: '0:00'
current_course: '-'
run_state: Gotowość
process_state: Badanie wsadu
error_message: '-'
dry_level: '-'
standby: 'on'
remote_start: 'on'
child_lock: 'off'
friendly_name: Dryer
icon: mdi:tumble-dryer
```

**Comment by ollo69** [comment]
Good, can we close this issue?

**Comment by jordibsk10** [comment]
It works perfectly well 👍
Thank you all for your help and specially to @ollo69
