### ISSUE TITLE
[Feature Request] option to turn on jet mode on LG hvac

### ISSUE THREAD

**Issue by koevoet1221** [ollo69/ha-smartthinq-sensors#175]
Hi, in the LG thinq app I can turn my hvac on jet mode. Would it be possible to do this from homeassistant to?

![Screenshot_20210611-235612_LG ThinQ.jpg](https://user-images.githubusercontent.com/76625701/121752537-a00c2d80-cb10-11eb-879f-1c895ed89e66.jpg)

**Comment by scentedshock** [comment]
+1 on this

**Comment by CesarDenis** [comment]
+1 on this

**Comment by ollo69** [comment]
Could someone provide more details on how jet mode behaviors? I mean, for instance, what happen if Jet mode is on and AC is turned on or some features as AC mode is changed?
Is possible to enable JET mode when AC is off? Is possible to enable it only on some specific AC Status?

**Comment by koevoet1221** [comment]
I was wrong, it disables jet after 30 mins not at a target temperature. here is a part from the manual:

Using the Jet Mode Function

Changing Room Temperature Quickly
This function allows you to cool indoor air quickly during the summer or warm it quickly during winter.
• Cooling & Heating model: The Jet Mode function is available with Cooling, Heating, and Dehumidification Mode.
• Cooling Only model: The Jet Mode function is available with Cooling, Dehumidification, Fan, Auto Operation Mode, and Air Purification function.
1 Turn the appliance on.
2 Press MODE button repeatedly to select the desired mode.
3 Press JET MODE button.
•Po is displayed on the display screen.

NOTE

Jet Heating Mode is not available on some models.
In Jet Cooling Mode, strong air blows out for 30 minutes.
After 30 minutes later, setting temperature is maintaining 18 °C
If you want to change the temperature, Press Up Iconor button to set the desired temperature.
In Jet Heating Mode, strong air blows out for 30 minutes.
After 30 minutes later, setting temperature is maintaining 30 °C
If you want to change the temperature, PressUp Icon or button to set the desired temperature.
This function may operate differently from the remote control display.


So it’ll do jet for 30 minutes and then switch to 18C when cooling or 30C when heating

**Comment by ollo69** [comment]
What happen if you manually disable it?
More in detail, how do you think it should be controlled in HA?

**Comment by koevoet1221** [comment]
I think the best way is to add it to both fan speed and temperature, so that you can press lower when it's set to 18 and it'll do jet or when you press higher at 30 and synced with fan speed since either changing temperature or fan speed disables jet mode / Po. But apparently different models support it in different modes according to the part of the manual so maybe a config file where you can turn the option on or off per mode?

**Comment by koevoet1221** [comment]
Do you need anymore information? Is it possible to add this?

**Comment by khal3d** [comment]
It's getting too hot over here, and the Jet mode has become a severe issue 😅

**Comment by MatiasFernandez** [comment]
@ollo69 I would say the most important feature missing to be able to achieve this is to set the fan speed above high. In the jet mode the fan is way more powerful than in high mode, and that makes the most difference. Did you find in the api the way to do that? Could I help to do the reverse engineering?

**Comment by dougiteixeira** [comment]
I did some testing and managed to include a switch to enable jet mode. I created a PR (#369) for evaluation and review.

**Comment by ollo69** [comment]
I close this FR because completed by PR #369
