### ISSUE TITLE
Modbus rtu conflict [BUG]

### ISSUE THREAD

**Issue by pruwait** [ollo69/ha-smartthinq-sensors#176]
**Describe the bug**
Integration works with my WM good, but other light modbus device will be damaged. I have delay 40-120 seconds

Without smartThing integration my  modbus rtu work:
If I switched on in lovelace, lamp is turn on after 0.5 seconds and lovelace switch is turn on after 1 seconds. All is good.
With smartThing integration my modbus rtu is delayed:
If I switched on in lovelace, lamp is stay turn off and lovelace switch is turn on after 1 seconds but retutn in turn off staying cause receive lamp modbus status.
After 40-120 seconds my lamp is switch on. 
**Screenshots**

**Environment details:**
 - Environment HASSIO docker on Intel NUC 8i3 
 - Home Assistant version installed: 2021.6.4
 - Component version installed: 0.8.13
 - Last know working version: in October 2020 hassio + modbus rtu + LG works fine. But it was other version hassio too.
 - LG device type and model with issue:  F4V5VS0W
 - LG devices connected (list): wm only

**Output of HA logs**
No errors in log!

**Comment by ollo69** [comment]
I don't have enough element to analyze this problem. At least you should find a specific version of the integration that work without issue in current HA version, so that I can analyze the difference that could cause this conflict.

**Comment by hmoffatt** [comment]
Could it be related to the call to time.sleep()? I see the standard integrations are using "await asyncio.sleep" instead.

**Comment by pruwait** [comment]
> I don't have enough element to analyze this problem. At least you should find a specific version of the integration that work without issue in current HA version, so that I can analyze the difference that could cause this conflict.

How can I install not last version ha-smartthinq-sensors?

**Comment by pruwait** [comment]
I can't install old version ha-smartthinq-sensors with hassio 2021.6.4
Log Error:
The custom integration 'smartthinq_sensors' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by pruwait** [comment]
copy smartthinq_sensors 0.6.1 to 
    └── custom_components
        └── smartthinq_sensors
reboot hassio
log:
2021-06-14 13:56:49 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

hassio - SmartThinQ LGE Sensors - NO component(

**Comment by ollo69** [comment]
Just replace the file `manifest. json` in integration folder with the one avaliable in last release and reboot. It should work.

**Comment by pruwait** [comment]
![image](https://user-images.githubusercontent.com/24190186/121916349-ba2a5380-cd3c-11eb-8de7-5ea7a01ffcbf.png)
![image](https://user-images.githubusercontent.com/24190186/121916537-e6de6b00-cd3c-11eb-83fa-bd0722c4fa32.png)

My integration does not show up more!

**Comment by ollo69** [comment]
Just try to clean browser cache

**Comment by pruwait** [comment]
Install integration succsessful in local network. Testing different versions.

**Comment by ollo69** [comment]
> Could it be related to the call to time.sleep()? I see the standard integrations are using "await asyncio.sleep" instead.

No, it couldn't. We cannot use `asyncio.sleep` because ThinQ library is not `async` (it use `requests`). But this is not a problem, and also exist many standard integration not based on `async` library.

**Comment by pruwait** [comment]
Its ONVIF bug,  not smartThing. Closed!
