### ISSUE TITLE
[BUG] LG ThinQ mobile app show "In Use"

### ISSUE THREAD

**Issue by demslam** [ollo69/ha-smartthinq-sensors#179]
LG ThinQ mobile app (android) indicate all devices are "In Use". This is for a heat pump system that, this was not a case and appears to have happened in a recent update.

In the past the LG ThinQ mobile app was able to operate along with the Home Assistant integration.

![Screenshot_20210617-101910_LG ThinQ](https://user-images.githubusercontent.com/5873161/122445158-1d430280-cf56-11eb-8d55-6dab6ce749e2.jpg)

Homeassitant installed via Docker w/ HACS via a Debian VM
Current version V0.8.13
Last known working version V0.8.9 (i think)

LG Devices
(5) LMN079HVT
(2) LSN180HSV5

**Comment by ollo69** [comment]
But this happen always or only after you control your devices using integration?

**Comment by demslam** [comment]
It appears to be always. It is now showing the items with out the "In Use", but when I click through the ThinkQ app it say "Another User is Using It". I have disabled and restarted home assistant and that does not seem to fix the problem.

**Comment by ollo69** [comment]
If you disabled the integration and restart home assistant probably the issue is not related to integration. Did try using previous version of integration that was working?

**Comment by demslam** [comment]
Yes dropped back to V0.8.9, which did not fix the problem. After I disable and after about a half hour i am able to use the ThinkQ App. I am not sure if it is something getting locked out with Home Assistant doing checks on API (not really a code guy just thinking about what is happening)
P.S. Thank you for the help

**Comment by ollo69** [comment]
I leave this thread open for the moment, report here if it happen again.

**Comment by ueilat** [comment]
The same to me. It applies to clima only

**Comment by ollo69** [comment]
If you want that I try to fix this issue, please provide more details. When exactly the issue occurs? What action you do before appear locked in the apps? How long remain locked? What was the last version without issue, if any?
I don't have an LG climate and I will not be able to provide any support with a so generic description.

**Comment by parvbarot** [comment]
same with me also. After my integration of SmartThinQ LGE Sensors, it's showing in use "Air conditioner is used by another user"

**Comment by ollo69** [comment]
Seems that nobody here want to provide additional details, I suppose this has not to be considered a real issue. I will wait one more week and than I will close the issue due to missing information to work on.

**Comment by demslam** [comment]
I would be happy to help (but have been busy balancing life and work). If you would be able to help me get an understanding of what you are looking for. I am thinking this is a change that LG has implemened on their end.

**Comment by demslam** [comment]
Playing with this now. So the first 10 minutes after restarting HA I am able to have both HA and LG app control the Heat Pump Units. When i do a change in HA the unit is locked out in the LG App but after 30 seconds i can turn it off in the LG app. But after about 10 minues the LG app shows everything is in use. This is even for units that i did not interact (test) with when i was swapping controls between HA and LG app.

**Comment by ollo69** [comment]
> But after about 10 minues the LG app shows everything is in use

You send some control from HA in this period or just happen doing nothing?

**Comment by demslam** [comment]
> > But after about 10 minues the LG app shows everything is in use
> 
> You send some control from HA in this period or just happen doing nothing?
> Could be related to the command used to get power usage (that run every 5 minutes)?

During that time from 0 - 2 minutes i played with (2) head units. Then stopped after seeing things were working out. 2 - 10 minutes no playing around all (7) head units show in use. 

That power usage thing maybe the culprit, Is that something easy to disable on my end?

**Comment by demslam** [comment]
![image](https://user-images.githubusercontent.com/5873161/123692736-09c45100-d80c-11eb-968e-f5be3d0a0d7d.png)

**Comment by ollo69** [comment]
Call is done in any case. Are you able to comment a row in the code if I provide you exact indication?

**Comment by demslam** [comment]
Should be able to.

**Comment by ollo69** [comment]
You should modify the file `ac.py` in the `custom_components/smartthinq_sensors/wideq` folder.
First of all make a backup of the file (so that you can rollback quickly)

At line 536 you have the following 2 lines:

```
        if not self.is_air_to_water:
            self._current_power = self.get_power()
```

Just remove 2 lines and replace with:

```
        return
```


Reboot and test

**Comment by demslam** [comment]
The updated i did  

    def _get_device_info(self):
        """Call additional method to get device information.

        Called by 'device_poll' method using a lower poll rate
        """
## removed as test to fix LG app integration
###
#        if not self.is_air_to_water:
#            self._current_power = self.get_power()
###
        return

This seems to have fixed it. There is a slight control issue where if i turn it off via HA i need to wait about 30 seconds before it can be controlled in LG app and vice-versa. I am going to guess this always existed but never ran into because i never tried to control it from one or the other in that time frame.
Thank you so much for helping me out!

**Comment by ollo69** [comment]
Yes, make sense. 30 seconds is expected, because permission is removed after one refresh loop to be sure that there are no issue in case of multiple commands. But in this case I never remove permission, so this is causing the issue. I will manage this with next release. 
Thanks for you support.

**Comment by demslam** [comment]
my pleasure. And thank you for the support

**Comment by ollo69** [comment]
It should be fixed with last release, please check and report if ok.

**Comment by scentedshock** [comment]
as of 0.8.16 works for me

**Comment by demslam** [comment]
Agreed, just updated and it appears to working for me too. Thank you

**Comment by ollo69** [comment]
Very good, can we close this issue?

**Comment by demslam** [comment]
Yes, sorry new to this sort of thing
