### ISSUE TITLE
No show TV in HA[BUG]

### ISSUE THREAD

**Issue by pepsonEL** [ollo69/ha-smartthinq-sensors#180]
Hi. I have a TV in app on Android LG ThinQ but in HA by ntegration TV is not show as entiti. WHy ?

**Comment by ollo69** [comment]
This integration do not support LG TV. I don't have a LG TV, so I will not be able to integrate at all, unless someone analyzes the traffic and provides details on how it is possible to communicate with TV using ThinQ protocol.

**Comment by ollo69** [comment]
Close this because invalid and no answer by 1 month
