### ISSUE TITLE
No SmartThinQ devices found. Component setup aborted.

### ISSUE THREAD

**Issue by nckslater** [ollo69/ha-smartthinq-sensors#181]
Aborted
No SmartThinQ devices found. Component setup aborted.

I have removed social media account;  Gmail and created a new LG account associated with a me.com email and the TV is listed in the ThinQ app

I get a redirection URL that starts with kr.m.lgaccount.com/login. I put this into the redirection field but get the same error every time: **No SmartThinQ devices found. Component setup aborted.**

**Environment details:**
 - Environment - HASSIO
 - Home Assistant version installed: 2021.5.0
 - Component version installed: Latest
 - LG device type and model with issue: TV  LG 55NANO806NA

**Comment by ollo69** [comment]
TV is not supported by this integration.

**Comment by nckslater** [comment]
Ok cool that answers that.I've just bought a fridge and hoping its compatible. It's a Lg GBB62SWFFNOn 6 Jul 2021 12:50, ollo69 ***@***.***> wrote:
TV is not supported by this integration.

**Comment by pepsonEL** [comment]
But is any chance to add TV to this integration ?

**Comment by ollo69** [comment]
> Ok cool that answers that.I've just bought a fridge and hoping its compatible. It's a Lg GBB62SWFFN

Refrigerator should be supported.

> But is any chance to add TV to this integration ?

I don't have an LG TV, and implement TV support without a device to perform test is quite impossible. I'm also not so sure that TV control (WebOS) use the same protocol used by other devices. 
Anyway if someone that have a LG TV could capture commands send by LG app using a tool as [MitMProxy](https://mitmproxy.org/) could be a good starting point.

**Comment by ollo69** [comment]
Please close this thread because not an issue
