### ISSUE TITLE
[Feature Request] Sleep Mode Timer Support for AC Units

### ISSUE THREAD

**Issue by OrbitingOcelot** [ollo69/ha-smartthinq-sensors#182]
Offical LG app provides the functionality to set a sleep mode for air condition units, which automatically turns them off after a specific timeframe. I believe sleep mode may even do some other stuff in the background like slowly increasing the temperature, but this is not well documented.

It would be nice if there would be a way to set the sleep timer via home assistant, same as with LG app.

Although it is possible to manually do this via automations in HA, every command sent from HA to the AC unit results in a confirmation beep generated by the AC unit, which is not desirable in the night.

Thank you for considering this.

**Comment by smackywolf** [comment]
This feels a lot like something you'd implement in Home Assistant rather than directly in the integration. I don't use a sleep timer, but i do use a temperature check that runs at specific times to check if my units should turn on, it'd be very trivial to implement a sleep timer switch for your units in HA.

**Comment by ollo69** [comment]
Totally agree with @smackywolf .
In Home assistant you can define automation based on status of all managed sensors.
You should use automation to define timers or other condition to turn on and off your climate. Does not make sense implement Automation provided by LG in the integration.

**Comment by OrbitingOcelot** [comment]
Thanks guys. As you can see in my first post, I am aware that it can be done with an automation, and I have also explained why I am looking for an alternative way (i.e. to set it natively, same as LG app).

Was hoping this might either be somehow possible or a quick win to implement, but probably most people might be happy with the automation way, so I totally understand if thats something you think is not really needed. Appreciate all your work on this integration in any case :)

**Comment by ollo69** [comment]
> Although it is possible to manually do this via automations in HA, every command sent from HA to the AC unit results in a confirmation beep generated by the AC unit, which is not desirable in the night.

There are no way to disable confirmation beep? I understand that this is not desiderabile in the night, but I don't want to implement logic in the integration that should be managed by HA automation. If you prefer use LG automation as is, you are free to use it and HA is not useful anymore.

**Comment by RayDAnt3D** [comment]
Sleep mode on  LG air conditioners isn't just about timer functionality (which, like already said, is clearly better managed directly by HA via automations.) It also puts them (at least the higher end ones) in a special extra low fan noise mode which is otherwise inaccessible to the user. Which is why I would LOVE to see AC sleep mode support in this repo (since its something that I currently have to manually trigger every night.)

**Comment by OrbitingOcelot** [comment]
> There are no way to disable confirmation beep? I understand that this is not desiderabile in the night, but I don't want to implement logic in the integration that should be managed by HA automation. 

No problem, I understand. Unfortunately you cant diable the beep on LG units - already was in touch with some guys in Korea regarding this. Only method is to disassemble the unit and electronically disable the speaker, which is not that easy d/t the location of the PCB.

> If you prefer use LG automation as is, you are free to use it and HA is not useful anymore.

Of course not, I vastly prefer HA and your integration ;)

**Comment by ollo69** [comment]
Close this issue due to inactivity. As discussed HA automation should be used to implement this feature in HA.

**Comment by RainbowCrash** [comment]
I'd like to point out that sleep mode is SIGNIFICANTLY quieter, and this is the primary importance of it. Unfortuantely, LG limits you to 7 hours before turning off the AC completely. I installed Home Assistant and this addon from scratch hoping to automatically keep setting sleep mode back to 7 hours after the AC turns off to keep the AC on and quiet for longer hours without manual intervention, and was saddened to not find an option for sleep mode in the interface.

I wish you could just set sleep mode as a permeant toggle, alas that's simply not how these ACs were programmed.

Is there no hope of this? Is there another way I'm missing to accomplish this?

**Comment by benrafshoon** [comment]
+1 to what RainbowCrash said

Sleep mode is more than just turning off the AC after some number of hours. It puts the AC into a low fan speed mode that is lower than "fan speed low", in addition to turning off the AC after a certain number of hours. As far as I'm aware, sleep mode is the only way to set the fan speed to "extra low".

This issue should be reopened.

**Comment by ridizy** [comment]
Was hoping support for LG’s “Sleep” feature could be added as well. It’s not well documented but [here is some more information](https://www.hunker.com/13407313/sleep-mode-function-in-lg-air-conditioners)  on it. 

Besides turning off the unit after the preset amount of time has passed, it raises the temperature 1 degree Celsius from the current set point after 30 minutes, and then once again after another 30 minutes.

**Comment by vb7445** [comment]
The term “Sleep” that LG is using here does not mean the unit shuts off and this mode can’t  be simulated by this HA Integration. This “Sleep” mode is a special lower power, lower noise mode as previously stated and cannot be implemented by HA given the provided functionality in this integration. It is an additional feature we would like to see added to the integration. It’s definitely worth the coffee I’ve provided and would probably earn some more.

**Comment by MattL0** [comment]
+1 sleep mode is another mode all together than can'T be acessed by any home assitant.
