### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nckslater** [ollo69/ha-smartthinq-sensors#183]
![Screenshot_20210709-201520_Chrome.jpg](https://user-images.githubusercontent.com/66120199/125120286-88659c00-e0f2-11eb-86c9-4014b7f917ff.jpg)

I wanted to donate but can't as the payment part is greyed out and won't scroll down!

**Comment by ollo69** [comment]
Don't know why is not working, may be something related to browser or antivirus setting?
Not really an integration issue, anyway I appreciate the attempt  😉

**Comment by nckslater** [comment]
Worked now 👍
