### ISSUE TITLE
Conditioner LG DC12RH

### ISSUE THREAD

**Issue by DivanX10** [ollo69/ha-smartthinq-sensors#184]
This is a new model of the LG G12LH air conditioner. The 2021 model year. I am wondering if this air conditioner will appear through this integration. Who has this air conditioner? Successfully flew into the home assistant?

https://www.lg.com/ru/air-conditioners-split-systems/lg-dc12rh#

**Comment by ollo69** [comment]
Can you provide the HA log on startup?

**Comment by DivanX10** [comment]
I don't have this air conditioner yet and I'm just asking.

**Comment by ollo69** [comment]
In this case I don't see any reason for which this model should not work. Probably it will be more simple for you to find and answer using forums.
I change the label for this issue to `Question`.

**Comment by ollo69** [comment]
Close this issue due to inactivity.
