### ISSUE TITLE
[BUG] Sensor wash completed not updated

### ISSUE THREAD

**Issue by TheFes** [ollo69/ha-smartthinq-sensors#185]
Related to issue https://github.com/ollo69/ha-smartthinq-sensors/issues/138

**Describe the bug**
When the washing machine completes its program, the binary_sensor.washer_wash_completed does not change it's state. Therefor automations based on it do not work.

**Expected behavior**
The sensor to change its state to on.

**Screenshots**
![image](https://user-images.githubusercontent.com/28803438/125959979-f69fa22e-be3b-4e42-a3bb-91d6cb27798a.png)
![image](https://user-images.githubusercontent.com/28803438/125960054-3c94a745-edb4-48f3-aaf7-4acea2ef74dc.png)

The unavailable status was caused because I added the integration again, and changed the availability of some entities belonging to the integration.

**Environment details:**
 - Environment: HASSIO
 - Home Assistant version installed: 2021.7.3
 - Component version installed: v0.8.16
 - Last know working version: none
 - LG device type and model with issue: F_C__Y___W.A__QEUK-FL (LG F4WV708P1 TurboWash)
 - LG devices connected (list): only this one

**Output of HA logs**
Paste the relavant output of the HA log here.
No entries in log file, even though debug logs are enabled for the integration
```yaml
logger:
  default: debug
  logs:
    custom_component.smartthinq_sensors: debug
```

**Additional context**
It looks like the binary_sensor depends on the attribute `run_completed` which also stays `off` when the program is completed. I created a template sensor for the attribute to check if that changes, but also there no change.
![image](https://user-images.githubusercontent.com/28803438/125960935-0a7d13e9-792c-45a3-a835-ce2e1c116b0b.png)

**Comment by ollo69** [comment]
`Run completed` is calculated based on te status `run state` and `pre state`. Please provide the history of this 2 state to understand why `Run completed` do not change his value

**Comment by TheFes** [comment]
I created two template sensors for run_state en pre_state (to make it easier to record the history).
Currently a program is running, which will take another 2:30h

both `run_state` and `pre_state` show `wassen` (is washing in Dutch) now.

![image](https://user-images.githubusercontent.com/28803438/126060229-089bab21-4052-4680-8ba3-2880a9b93ab0.png)


I will send an update later today. But could it be that it expects the states in English here to calculate the `run_completed` attribute?

**Comment by ollo69** [comment]
Language do not matter, but something is wrong because this 2 states normally are different. Complete the test, that attach here also the JSON info file for your washer so that I can check it.

**Comment by TheFes** [comment]
These are the state changes for pre_state in my database:
![image](https://user-images.githubusercontent.com/28803438/126080903-c0a69bba-cbc4-4d2d-bdfc-8b5f9ba9a73c.png)

And these for run_state
![image](https://user-images.githubusercontent.com/28803438/126080918-937be29c-8cd9-4781-9051-34d425f1de58.png)

The state changes are very similar (there differences of some microseconds).

JSON info can be found here:
https://paste.ubuntu.com/p/D2dKbBD2Dg/

**Comment by ollo69** [comment]
Looks like device update `run_state` and `pre_state` at the same time, could be a device bug?
I will try to implement `pre_state` locally and not based on information provided by device when I will have some available time, this could fix this issue,

**Comment by TheFes** [comment]
Just curious, but what determines if the `binary_sensor.washer_wash_completed` is turned off again?
I understand how turning `on` works by comparing the `run_state` and `pre_state`, but what triggers it to turn `off` again?

**Comment by ollo69** [comment]
`wash_completed` is on when `run_state = END` or when `run_state = POWER_OFF` and `pre_state = END`. Any other condition set `wash_completed` off. What is strange in your monitored state, is that the state END never occur for both `run_state` and `pre_state`. 
You should compare the real status change of your device with what is happening in HA, seems that many status change are missing, for this reason `wash_completed` is never triggered.

**Comment by ollo69** [comment]
This is duplicated of issue #226. I leave the newest open for progress and close this old issue.
