### ISSUE TITLE
[BUG] Error when I try to add ThinQ integration

### ISSUE THREAD

**Issue by jbiribi** [ollo69/ha-smartthinq-sensors#189]
I added the ThinQ through HACS. On "configuration/integrations/add integration" I search for smartthinq, but when I click on it I have the following mesage:

![image](https://user-images.githubusercontent.com/18632077/127605552-cfc05368-cd28-4772-ae0c-47eb7539e62f.png)

**Comment by ollo69** [comment]
Did you restart HA? Provide also more details about your HA installation.

**Comment by jbiribi** [comment]
> Did you restart HA? Provide also more details about your HA installation and provide errors available in HA logs.

Yes, I restarted it many time. My Home Assistant version is core-2021.6.5. The log error is:

![image](https://user-images.githubusercontent.com/18632077/127890047-5e37ee3f-86df-4ab4-88ff-db809c8903bc.png)

**Comment by ollo69** [comment]
I think you have an issue in your HA installation, may be some firewall issue?

**Comment by jbiribi** [comment]
> I think you have an issue in your HA installation, may be some firewall issue?

I disabled it to test but had the same error. All the other integrations works fine.

**Comment by ollo69** [comment]
It could be one of the other integration that is preventing this from loading. Load the config flow is an action performed by HA, and because normally it work it cannot be an integration issue. 
I could suggest:

- try to clean-up your browser cache
- try using a clean HA installation (without other integration installed)

**Comment by ollo69** [comment]
Dis you solve your problem? Can we close this issue?

**Comment by jbiribi** [comment]
Didn't work, but I added my TV directly, without the ThinG, and it worked.

**Comment by ollo69** [comment]
Didn't catch that you would use the integration to control TV. This integration do not support LG TV, so it is correct use native HA WebOS integration for that.
I close this issue, if in the future you need to use it for supported devices and still have problem please open a new one.
