### ISSUE TITLE
New warnings in HA 0.109.0b0

### ISSUE THREAD

**Issue by towerhand** [ollo69/ha-smartthinq-sensors#19]
As the title says, HA is making some changes in 0.109 and so far I have seen these two warnings.
```
2020-04-22 15:40:33 WARNING (MainThread) [homeassistant.helpers.translation] smartthinq_sensors: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
```
```
2020-04-22 15:37:53 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for smartthinq_sensors doing I/O at custom_components/smartthinq_sensors/wideq/device.py, line 234: return requests.get(info_url, timeout=DEFAULT_TIMEOUT).json()
```

**Comment by tayanov** [comment]
offtopic. Its great. my v1 frige and v2 washer work together. do you plan to set the temperature?
Not only sensor? but interaction too ...

**Comment by ollo69** [comment]
> As the title says, HA is making some changes in 0.109 and so far I have seen these two warnings.
> 
> ```
> 2020-04-22 15:40:33 WARNING (MainThread) [homeassistant.helpers.translation] smartthinq_sensors: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
> ```
> 
> ```
This was solved in other custom_component creating a soft link to the .translation directory, not so simple for me because I work with windows. I will think about best solution

> 2020-04-22 15:37:53 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for smartthinq_sensors doing I/O at custom_components/smartthinq_sensors/wideq/device.py, line 234: return requests.get(info_url, timeout=DEFAULT_TIMEOUT).json()
> ```
The only way to remove this warning is to create an external library for the API (wideq). May be in the future, but fortunatly the API seems working fine :)

Thanks for information.

**Comment by ollo69** [comment]
> offtopic. Its great. my v1 frige and v2 washer work together. do you plan to set the temperature?
> Not only sensor? but interaction too ...

Iteration is not possible in ThinQ v2 for the moment, and implementing only for one version may create issue. So for the moment the component is only sensors.

**Comment by towerhand** [comment]
@ollo69 more info here: 
https://rc.home-assistant.io/blog/2020/04/21/release-109/#detection-of-blocking-io-in-the-event-loop

**Comment by towerhand** [comment]
Thanks @ollo69
