### ISSUE TITLE
[Function request] The ability to enable express cool, express freeze and eco friendly on LG HVAC. Refrigerator.

### ISSUE THREAD

**Issue by stylishkrio** [ollo69/ha-smartthinq-sensors#190]
The inclusion of these functions in the LG thinq application is supported.

**Comment by ollo69** [comment]
This functions are already implemented. There are 3 switch associated to the refrigerator devices.

**Comment by stylishkrio** [comment]
> This functions are already implemented. There are 3 switch associated to the refrigerator devices.

Yes, I know that there is. But I can't use them on the thermostat.

**Comment by ollo69** [comment]
Implement this with standard thermostat functionality is not possible. Express cool and express freeze can be set at same time, while eco friendly disable both others. You should use a dedicated UI control instead of the standard one, search on web for this. Of course a refrigerator is not a climate device, you cannot expect that it work in the the same way.

**Comment by stylishkrio** [comment]
> Implement this with standard thermostat functionality is not possible. Express cool and express freeze can be set at same time, while eco friendly disable both others. You should use a dedicated UI control instead of the standard one, search on web for this. Of course a refrigerator is not a climate device, you cannot expect that it work in the the same way.

![Снимок](https://user-images.githubusercontent.com/77132140/127880370-bf56d4a6-385f-474f-bf66-9f4c0633acc4.PNG)
Okay, I got it. Is it possible to modify the type of thermostat so that you can disable this function (screenshot)? Since it is useless for refrigerators.

**Comment by ollo69** [comment]
Unfortunately no! I need to specify at least 1 HVAC Mode for climate entity. But again, using a dedicated thermostat card you can solve this, combining the thermostat and the buttons

**Comment by stylishkrio** [comment]
> Unfortunately no! I need to specify at least 1 HVAC Mode for climate entity. But again, using a dedicated thermostat card you can solve this, combining the thermostat and the buttons

Ок.

**Comment by ollo69** [comment]
Can we close this?

**Comment by stylishkrio** [comment]
> Can we close this?

Yes.
