### ISSUE TITLE
Failed to call service climate/set_hvac_mode

### ISSUE THREAD

**Issue by rark-ha** [ollo69/ha-smartthinq-sensors#191]
**Describe the bug**
Installed the integration today without issue and impressed with how easy it was. But I can't control the HVAC system.

Any action to set the air con (hvac) on/off or change the mode (cool/heat...) or fan speed (high/low...) does not work with the popup error below. It will change the temperature setting though.

Region is AU with language EN but the error message contains some non-EN characters that I can't decipher.

**Screenshots**
![HVAC-Failed-Call](https://user-images.githubusercontent.com/62318984/128133156-b6a4973a-cf7e-457a-9a2c-48803a76e41b.PNG)

**Environment details:**
 - HASSIO
 - core-2021.7.4
 - ha-smartthinq-sensors v0.8.20
 - LG HVAC DUCT_626301_AU-SAC_DUCT (AC) firmware 1.0.0

**Output of HA logs**
`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:229
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:51:18 PM (12 occurrences)
Last logged: 4:30:03 PM

[1607396200] ('0005', '지원하지 않는 서비스입니다.')
[1594248952] ('0005', '지원하지 않는 서비스입니다.')
[1594248952] ('0011', '등록되지 않은 모델입니다.')
[1666330784] ('0005', '지원하지 않는 서비스입니다.')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 811, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 463, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/climate.py", line 271, in set_hvac_mode
    self._device.power(True)
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 442, in power
    self.set(keys[0], keys[1], key=keys[2], value=op_value)
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 523, in set
    super().set(ctrl_key, command, key=key, value=value, data=data)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 987, in set
    self._set_control(ctrl_key, command, key=key, value=value, data=data)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 948, in _set_control
    self._client.session.set_device_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 582, in set_device_controls
    res = self.post("rti/rtiControl", payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 438, in post
    return lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 202, in lgedm2_post
    return manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 229, in manage_lge_result
    raise exc.APIError(code, message)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: ('0005', '지원하지 않는 서비스입니다.')`

**Comment by ollo69** [comment]
Just inserting the string in google translate report that the error is "This service is not supported".
You should attach the JSON info file for your ac unit so that I can try to analyze supported command for your device.

**Comment by rark-ha** [comment]
Downloaded JSON file. Thanks in advance.

[7c57abb0-9564-11e3-a612-78c40e4032d7.zip](https://github.com/ollo69/ha-smartthinq-sensors/files/6934962/7c57abb0-9564-11e3-a612-78c40e4032d7.zip)

**Comment by ollo69** [comment]
What if you just change the HVAC mode or the FAN speed when the AC unit i already on? Do you have the same error?

**Comment by rark-ha** [comment]
I turned the unit on and tried to change the HVAC mode but got the error.

![hvac-op-mode](https://user-images.githubusercontent.com/62318984/128437792-0fb42d0c-f063-48a5-a374-9bc6291b749b.PNG)

If I tried to change the fan speed I also got an error.

![hvac-fan-speed](https://user-images.githubusercontent.com/62318984/128437866-8da710bb-3c62-4073-88ce-fa066081bad8.PNG)

**Comment by ollo69** [comment]
Are you sure that your device is properly registered in the LG phone app? Translation of message with code 0011 is "This is an unregistered model".
Looks like the LG cloud is not accepting message to control this device, not really related to the integration.

**Comment by rark-ha** [comment]
I rechecked the LG App.
- Logged in via my old social media account, confirmed device was deleted, and then deleted the social media account from LG
- Deleted the device from my LG account
- Added it again from the LG account (and can control it from the App)
- Installed the integration again on my test machine and rebooted HA
- Same error code 0005 (when trying to turn it on)
- App reports the device is in use by another user (so can't control it from there)

**Comment by wishie** [comment]
I also get the following message when trying to change anything in relation to the A/C unit..

Error calling additional poll methods. Error ('0011', '등록되지 않은 모델입니다.')

It translates to "This is an unregistered model". What can I do to help add support for this unit? It works fine in the LG app.

**Comment by lisim** [comment]
I am now also getting this error, can control through app not through HA

**Comment by lisim** [comment]
Further testing rebooting the Hass box has seemed to resolve the issue

**Comment by ollo69** [comment]
Is this issue still present or we can close?

**Comment by rark-ha** [comment]
This issue is still present. I will install the latest version and report back with logs.

**Comment by rark-ha** [comment]
> This issue is still present. I will install the latest version and report back with logs.

Reinstalled the latest version and still get the same "failed to call service climate/set_hvac_mode"

**Comment by rark-ha** [comment]
I still have this issue.

When I log into the ThinQ app it tells me my HVAC device is "in use by another user" and I can't control it from there either.

**Comment by ollo69** [comment]
I have no idea on how to help you on this. I can only suggest to try to fully unregister your device from LG app and than register again, and than try again to configure integration.

**Comment by wishie** [comment]
I have not had this issue in a long time. It only happens if I have the LG app open at the same time.

**Comment by vk2him** [comment]
@rark-ha 

I was also getting this exact error -  are you also using the ```smartthinq``` HACS integration from https://github.com/sampsyo/hass-smartthinq 

I was using this in addition to this integration which was causing the problem - you can only have one "device" logged onto the LG account at the same time. The ```smartthinq``` integration is configured in yaml and is loaded first, hence this integration won't work as ```smartthinq``` logged in first.

**Comment by rark-ha** [comment]
@vk2him I may have tried that other custom component at some stage but it isn't installed anymore.

I did a clean install today as I haven't tried it for months and I can get the temperate (current and set a target) but still can't start/stop the HVAC.

**Comment by vk2him** [comment]
Just to be sure, are you sure you don't have smartthinq: in your configuration.yaml?

**Comment by bleughb** [comment]
Just started seeing this also now on a fresh re-install of home-assistant. I'm getting the OP's error.

I see the temperature and the LG thinq app has 'in use'

Happy for you to login to my HA thingy to see what's going on if it helps
