### ISSUE TITLE
[Feature Request] - change language after initial setup

### ISSUE THREAD

**Issue by jonferreira** [ollo69/ha-smartthinq-sensors#199]
Hey all.

Just got myself a fancy LG Dishwasher and immediatly used this to integrate it with HA - brilliant work!

I'm Portuguese so during initial setup I've chose location / language to be portuguese. However all my HA system is in English and I've noticed that now, obviously, the Dishwasher state is returned in portuguese.

As far as I could see there's no wasy way to change language without reinstaling the integration?

Assuming language doesn't really have an impact on how / where the data is retrieved from, would it be possible to add "language" as an changeable option?

**Comment by ollo69** [comment]
Label language depend on your LG account settings (and in any case the language selected during integration setup must respect LG language account). The only way to change language is to register your LG account with different one and setup integration again.

**Comment by ollo69** [comment]
Close this issue because request cannot be implemented.
