### ISSUE TITLE
"Unregister service" when using Apple to sign in

### ISSUE THREAD

**Issue by allen-jd** [ollo69/ha-smartthinq-sensors#203]
Country Code: US
Language Code: en
Account Type: Social - Apple
Any Further Comments: Doesn't work. After signing in with Apple, I received a popup that said "Unregister service"

_Originally posted by @allen-jd in https://github.com/ollo69/ha-smartthinq-sensors/issues/90#issuecomment-921180093_

**Comment by ollo69** [comment]
Social account are not supported as explained in `readme`.
Create and use LG account.

**Comment by ollo69** [comment]
Closing this old issue, as explained solution is to use LG account.
