### ISSUE TITLE
[Feature Request] energy consumption for HVAC

### ISSUE THREAD

**Issue by danny-117** [ollo69/ha-smartthinq-sensors#204]
Hey @ollo69 

thanks so much for this project, it's really nice to be able to control my LG HVAC from HA.
I think this may have already been asked before but just want to also ask if we could get energy consumption into HA? given the new energy page in HA it would be nice to be able to see just how much power the HVAC is using and how much it is costing to run. 

I think the format that HA would want is the total kWh used by the HVAC so HA is able to count up as it's used in the day and work out the cost

**Comment by hmoffatt** [comment]
Use the `integration` integration to sum up the power across the day to make energy.
https://www.home-assistant.io/integrations/integration/

It's not a job for the LG integration.

**Comment by danny-117** [comment]
thanks for your quick reply @hmoffatt 

Having a look in HA SmartThinQ LGE Sensors entities I can see an entity for sensor.air_conditioner_energy_current but it's unavailable. reloading the integration didn't seem to get it to work. any advice on this one?

**Comment by ollo69** [comment]
Sensor is disabled by default. You must enable it from the device page.

**Comment by danny-117** [comment]
Thanks @ollo69 and @hmoffatt 

I just found that and enabled it, also setup integration so I can get it into the HA energy dashboard.

really love the addin, thanks for your work on this one.

**Comment by mathiasaulo** [comment]
Where is it, because I didn't find it
It was working until this last update, can you help me, thank you in advance
