### ISSUE TITLE
LG ThinQ Fan support

### ISSUE THREAD

**Issue by rjuch** [ollo69/ha-smartthinq-sensors#207]
Hi @ollo69 

As discussed on the HA community site, I would be very grateful if you could add support for the new LG ThinQ Fan. JSON api file is attached.

regards

Rich

[857a0a26-c502-4062-b224-af87dd2deb53.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/7202536/857a0a26-c502-4062-b224-af87dd2deb53.txt)

**Comment by ollo69** [comment]
Fan support is now implemented in version `v0.22.0`. Please test it and provide feed-back, if there are some issue attach error log and integration diagnostic file so that I can analyze it.

Thanks.
