### ISSUE TITLE
[BUG]Washser showing only one sensor after update

### ISSUE THREAD

**Issue by B0ndo2** [ollo69/ha-smartthinq-sensors#208]
I updated to the latest version (I removed the old one and add the integration again via HACS). My washer now is available in HA but with only one entity (switch.washer_power_off) when previously I have 8 of them.

**Expected behavior**
See washer state and other sensors

**Environment details:**
 - HASSIO
 - Core: core-2021.8.8, OS: 6.1
 - Component version installed: v0.9.3
 - Last know working version: 0.9.2
 - LG Washer F3L2CNV4W_WIFI-FL
 - LG devices connected (list): F3L2CNV4W_WIFI-FL

**Output of HA logs**

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:181
First occurred: 12:38:27 PM (6 occurrences)
Last logged: 12:43:39 PM

    Error unloading entry LGE Devices for sensor
    Error unloading entry LGE Devices for binary_sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 432, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 96, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

```

```

**Comment by ollo69** [comment]
Last version of integration require HA 2021.9.x as minimum version as reported in [version release notes](https://github.com/ollo69/ha-smartthinq-sensors/releases/tag/v0.9.3)
Upgrade HA to fix the issue.
