### ISSUE TITLE
Missing Sensors for LG WT7800CW Washing Machine

### ISSUE THREAD

**Issue by hoffdad** [ollo69/ha-smartthinq-sensors#211]
I have the new WT7800CW LG washing machine and can see all of the info in the app (cycle, run time, time left, etc) however in HA I only see 1 device/1 entity and it's _Washer Power Off_.  Is this too new of a washer for all of the washing machine related sensors to appear?

**Comment by ollo69** [comment]
Please provide more detail about your HA instance (version, OS, etc).
Also look in HA log if there are some errors or warnings and post it here

**Comment by hoffdad** [comment]
HAC Version:  core-2021.8.8
OS Version:  6.2

I found this in the HA log
`File "/config/custom_components/smartthinq_sensors/sensor.py", line 245, in <module>
    ThinQSensorEntityDescription(
TypeError: __init__() got an unexpected keyword argument 'native_unit_of_measurement'
2021-09-28 14:01:28 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry LGE Devices for binary_sensor`
`File "/config/custom_components/smartthinq_sensors/sensor.py", line 245, in <module>
    ThinQSensorEntityDescription(
TypeError: __init__() got an unexpected keyword argument 'native_unit_of_measurement'`

**Comment by ollo69** [comment]
You must upgrade HA to version 2021.9.x, as clearly stated in [release note](https://github.com/ollo69/ha-smartthinq-sensors/releases/tag/v0.10.0)

**Comment by hoffdad** [comment]
my sincere apologies
