### ISSUE TITLE
Is it possible to have filter status in fridge exposed?

### ISSUE THREAD

**Issue by jsiemek** [ollo69/ha-smartthinq-sensors#212]
Main objectivity of Home Assistant integration with smart fridge is problem detection and notification. Filter Need replacement is one of such situations. Due to poor eyesight I didn't notice information on fridge display. So the only source of information is LG ThinG app, which I use rarely. 

It will be nice to have HA notification when fridge filter needs replacement.

**Comment by GiveMeTheBits** [comment]
Water and Air filter status are available in the attributes of the main sensor. I pull them out in NodeRed for my automations

[{"id":"b5f18dd3.181f3","type":"server-events","z":"b827b0e4.7f596","name":"","server":"e4a3af48.4cae4","version":1,"event_type":"state_changed","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"waitForRunning":true,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"$outputData(\"eventData\").event_type","valueType":"jsonata"},{"property":"event_type","propertyType":"msg","value":"$outputData(\"eventData\").event_type","valueType":"jsonata"}],"x":120,"y":140,"wires":[["10f129f8.3b1556"]]},{"id":"10f129f8.3b1556","type":"switch","z":"b827b0e4.7f596","name":"Butler","property":"payload.event.new_state.attributes","propertyType":"msg","rules":[{"t":"hask","v":"model","vt":"str"},{"t":"hask","v":"refrigerator_temp","vt":"str"},{"t":"hask","v":"freezer_temp","vt":"str"},{"t":"hask","v":"temp_unit","vt":"str"},{"t":"hask","v":"door_open_state","vt":"str"},{"t":"hask","v":"ice_plus_state","vt":"str"},{"t":"hask","v":"smart_saving_mode","vt":"str"},{"t":"hask","v":"fresh_air_filter_state","vt":"str"},{"t":"hask","v":"water_filter_used_month","vt":"str"}],"checkall":"true","repair":false,"outputs":9,"x":90,"y":260,"wires":[["30497dc3.2dcf72"],["30497dc3.2dcf72"],["30497dc3.2dcf72"],["30497dc3.2dcf72"],["30497dc3.2dcf72"],["30497dc3.2dcf72"],["30497dc3.2dcf72"],["30497dc3.2dcf72"],["30497dc3.2dcf72"]]},{"id":"30497dc3.2dcf72","type":"debug","z":"b827b0e4.7f596","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":650,"y":240,"wires":[]},{"id":"e4a3af48.4cae4","type":"server","name":"Yondu HA","version":1,"legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]

**Comment by jsiemek** [comment]
I must have missed it somehow. Thank you for pointing me to it.

Thank you for your valuable work!
