### ISSUE TITLE
[BUG] Replacing ThinQ token means removing and adding integration again

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [ollo69/ha-smartthinq-sensors#215]
**Describe the bug**
LG ThinQ access token expires from time to time- this creates an error:
```
Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/__init__.py:183
Integration: SmartThinQ LGE Sensors (documentation, issues) 
First occurred: 10:16:55 (1 occurrences) 
Last logged: 10:16:55

Invalid ThinQ credential error. Component setup aborted
```

**Expected behavior**
It would be great do offer "re-login" option that will open ConfigFlow window just to re-enter authorization token.
**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HassOS 6.4
 - Home Assistant version installed: 2021.9.7
 - Component version installed: 0.10.0
 - Last know working version: 0.10.0
 - LG devices connected (list): 2x LG HVAC RAC_056905_WW-RAC (AC)

**Output of HA logs**
Paste the relavant output of the HA log here.

```
Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/__init__.py:183
Integration: SmartThinQ LGE Sensors (documentation, issues) 
First occurred: 10:16:55 (1 occurrences) 
Last logged: 10:16:55

Invalid ThinQ credential error. Component setup aborted
```

**Comment by KrzysztofHajdamowicz** [comment]
Just for another users: remember to open LG ThinQ app before You try to sign-in again!

**Comment by ollo69** [comment]
When problem is related to TOS change's, the solution is not re-configure integration but just accept TOS on phone App and rebooting HA everything works properly again.
So the solution here would be raise `ConfigEntryNotReady` in case of `Invalid ThinQ credential` error, in this way integration will try to reconnect automatically and avoid requirement for HA reboot.

**Comment by ollo69** [comment]
Close this old issue. Now integration support retry in case of invalid credential and allow reconfigure in case that the error is really related to credential change,
