### ISSUE TITLE
Integration Setup not working

### ISSUE THREAD

**Issue by skycryer** [ollo69/ha-smartthinq-sensors#216]
**Describe the bug**
I try to setup the integration with the nabu casa url, url is working correct. But using as redirection url does not work. What url is correct? Not seeing any info about redirection url in documentation 

**Expected behavior**
Redirection URL to Home Assistant should work

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Docker
 - Home Assistant version installed: 2021.9.5
 - Component version installed: latest
 - Last know working version:
 - LG device type and model with issue: Washing Machine
 - LG devices connected (list):

**Comment by ollo69** [comment]
Redirection URL is the URL where you are redirected by the browser from LG login page after inserting and confirming your LG credential. I have no idea of what `nabu casa url` is.

**Comment by stefancvetkovic** [comment]
I have also an error while Im doing re-integration to my HA.
```
Logger: homeassistant.setup
Source: setup.py:311
First occurred: 1:10:06 PM (2 occurrences)
Last logged: 1:10:06 PM

Unable to prepare setup for platform smartthinq_sensors.sensor: Platform not found (cannot import name 'DEVICE_CLASS_PM1' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).
Unable to prepare setup for platform smartthinq_sensors.binary_sensor: Platform not found (cannot import name 'DEVICE_CLASS_PM1' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).
```

This is shown in my logs after I complete integration process.
this is my given url after login:
https://kr.m.lgaccount.com/login/iabClose?state=65af30aa243a11ec85592cf05d3953b1&code=3kf2eiZAfuc8OfrrZlY6Safr1k7oSF&user_number=RS2008235725886&oauth2_backend_url=https%3A%2F%2Fgb.lgeapi.com%2F

**Comment by ollo69** [comment]
> I have also an error while Im doing re-integration to my HA.

Looking at the log I suppose that you have an old HA version. This is nothing to do with authentication, upgrade HA to version 2021.9.x as stated in integration release note. 
I edited your comment removing redirect URL because it contain sensible data.

**Comment by skycryer** [comment]
Ok did works now after I got the information what the correct redirection url is. But did not see this in the documentation maybe the setup instruction need an update.
