### ISSUE TITLE
Washing machine timer

### ISSUE THREAD

**Issue by Paulus88** [ollo69/ha-smartthinq-sensors#22]
Hi ollo69,

First of all, this is awsome, you are awsome!

I was just woundering as you are the expert, is it easy to make a countdown timer of % progress bar for a wash that is running?

Like the "initial_time" - "remain_time" = % done or a timer?
Now I only have the binary sensor which is also handy but a timer would be even more awsome.

I have seen a few solutions but I think you would probably have a better solution :)

**Comment by Hyrules** [comment]
If possible indeed it would be interesting to get the ETA of the drying and washing machine. Keep up the good work here your plugins is working really well with my lg dryer and washer. thanks.

**Comment by ollo69** [comment]
ETA is an attribute of the sensor (remain_time).
All additional value can be calculated using the platform "template".
The issue #13 was created to discuss about this and there are already some suggestion.

I'm available to add other attributes or dedicated sensors, but I'd like to see some discussion with the  community to identify what is really useful.

**Comment by Paulus88** [comment]
> ETA is an attribute of the sensor (remain_time).
> All additional value can be calculated using the platform "template".
> The issue #13 was created to discuss about this and there are already some suggestion.
> 
> I'm available to add other attributes or dedicated sensors, but I'd like to see some discussion with the community to identify what is really useful.

Thanks ollo69!
I looked at #13 but found it had no real conclusion before I opened this ticket, but template is perfect, I still have to look at that Jinja code for a more advanced solution but this seems to work fine.

I managed to get something working with:  - platform: template
```
    sensors:
      wash_state:
        friendly_name: "Wash State"
        icon_template: mdi:washing_machine
        value_template: >
          {{state_attr('sensor.washer', 'remain_time')}}
```

It just simply counts down the remaining time which is pritty much all I really needed :)
For the washing machine I can't really think of any other improvements, maybe that you can start a spin cycle like you can do with the ThinQ app.

I will also get Google Assistant soon and start testing it with voice controls :)
