### ISSUE TITLE
Option to choose HeatPump Leading Temperature

### ISSUE THREAD

**Issue by veno77** [ollo69/ha-smartthinq-sensors#224]
**Is your feature request related to a problem? Please describe.**
Currently the climate.heatpump is showing the water out tempearture but some heatpumps like mine could work based on the indoor temperature set, not the water out set. Here is my case:

![image](https://user-images.githubusercontent.com/4173325/136655439-1be7ef75-b971-48a8-9dce-929eaa2c3264.png)

**Describe the solution you'd like**
I need possibility to choose the climate.heatpump entity put in thermostat card to show the "Room Temperature" instead of "Out water temperature"

API JSON entities are:

        "airState.tempState.outWaterCurrent": 42.0,
        "airState.tempState.current": 21.5,

**Describe alternatives you've considered**

**Additional context**

**Comment by Zap82** [comment]
Please, note that the heat pump does not display the boiler temperature. (DHW)
