### ISSUE TITLE
binary_sensor.washer_wash_completed is never goes to on

### ISSUE THREAD

**Issue by stefancvetkovic** [ollo69/ha-smartthinq-sensors#226]
**Describe the bug**
When washing machine is done with doing a laundry, I receive notification from lg app, but in that moment my sensor from integration never goes to on, machine goes to off mode and thats it.

**Expected behavior**
I would like after doing a laundry, machine stays online a little bit longer, in order to send that machine washing process is done.

**Comment by ollo69** [comment]
This problem was already reported on other issues, but I'm not able to investigate without additional details.
The logic to turn on the sensor `wash_completed` is based on entity `run_state` and `pre_state` provided by the LG Api. What are the state for this 2 sensors when wash is completed?

**Comment by ollo69** [comment]
Any news about this issue? Can we close?

**Comment by StanislavBolshakov** [comment]
> Any news about this issue? Can we close?

Hello. The issue still in place. Last state reported by ```run_state``` is ```Spinning```. By ```pre_state``` is disabled by integration.

**Comment by ollo69** [comment]
> `pre_state` is disabled by integration.

You can enable to monitor it.

**Comment by StanislavBolshakov** [comment]
According to the ```pre_state``` after the washing cycle is finished, the washing machine remains in the ```standby``` status

**Comment by ollo69** [comment]
Seems that you are loosing some state transition, probably due to some connection problem with device or ThinQ cloud.
Try using last released version and than report here results and HA logs.

**Comment by DeadlySin2** [comment]
I have the same error today. All versions are leatest
![F4E91DEA-B58E-4EF7-AD7F-DA9303AB8F23](https://user-images.githubusercontent.com/61819118/148592260-53b29d90-5bbb-49d7-8d3a-d5d21b8f5d48.png)
![CA5420CE-F654-4C87-8430-EB6FD574AB48](https://user-images.githubusercontent.com/61819118/148592266-3d151f2e-22de-4216-b70b-fca20825f3e9.png)

**Comment by ollo69** [comment]
With only images I will never be able to investigate this issue. Could somebody provide log files?

**Comment by david-holbrook** [comment]
> According to the `pre_state` after the washing cycle is finished, the washing machine remains in the `standby` status ![image](https://user-images.githubusercontent.com/47710285/145948492-35999a50-3ffb-4382-89c2-9ba30597da9b.png)
> 
> Second cycle last state was `spinning` ![image](https://user-images.githubusercontent.com/47710285/145996976-d5084c57-17c4-4442-a088-70df4ff63f6c.png)

I am seeing the same behavior, it seems to be 50/50 on whether pre_state goes from Spinning to 'Standby' or to '-' when a cycle finishes.

**Comment by TheFes** [comment]
Hi Ollo, you closed my issue as this was supposed to be a duplicate. (https://github.com/ollo69/ha-smartthinq-sensors/issues/185)
But i think my problem is different, I always have the same `pre_state` as `run_state`
![image](https://user-images.githubusercontent.com/28803438/148735246-c8e26d7f-2f23-44e2-b870-6df4556c1bc8.png)

**Comment by DeadlySin2** [comment]
Can you give me needed parameters for log file? I tried to make a log file but it is very big to post here…

**Comment by ollo69** [comment]
> But i think my problem is different, I always have the same `pre_state` as `run_state`

The title of the issue confused me, but in any case the issue is the same, what is different is the cause.
Provide me log (possible debug) with your washer machine running so that I can investigate returned payload.

**Comment by ollo69** [comment]
> Can you give me needed parameters for log file? I tried to make a log file but it is very big to post here…

If your log file is too big just delete (or rename) it and reboot HA, a new one will be generated.
To enable debug add this lines in `configuration.yaml` log section:

```
logger:
  default: info
  logs:
    custom_components.smartthinq_sensors: debug
```

**Comment by DeadlySin2** [comment]
Logs are attached. 
[home-assistant.log](https://github.com/ollo69/ha-smartthinq-sensors/files/7844195/home-assistant.log)

**Comment by ollo69** [comment]
@DeadlySin2,

looking at payload in your log:

1) state and prestate are always equal
2) state `END` is never trigger by your device

Due to this, the current logic used to determinate `Run Completed` cannot work at all. I don't know exactly which alternative logic I could implement, I'll think about this. In any case this is not an integration issue but a different behavior that have to be managed.

**Comment by nchieffo** [comment]
@ollo69 
A potential solution may be to use the sensor sensor.xxx_remaining_time
when the sensor changes from 01:00 minute to 00:00, if xxx_run_state is set to '-', the program is ended.

**Comment by ollo69** [comment]
Ok, I re-open this, but is unclear why `Run-state` and `Pre-state` are always the same. 
Just trigger the sensor based on your suggestion is not really correct: a power failure could generate the same condition but should not be considered wash completed.
Attach your device diagnostic immediately before and immediately after that the wash cycle end, I will check if there is a way to determinate wash-complete for this conditions.

**Comment by nchieffo** [comment]
Hey @ollo69
here's the logfile I was able to collect, please tell me if I obfuscated too much data.
Unfortunately it seems the debugger captured 3 messages and all of them seems to refer to the machine still running, even though I hit the disable recording button only once the washing machine state changed to off. Not sure what happened.
I prepared a second log file with a response of the machine at rest, but I'm not sure if it's useful or not. please tell me if I need to do provide a second recording (this time I will wait a couple of minutes after the machine turns off)

[home-assistant_smartthinq_sensors_2023-09-27T19-09-36.595Z.obfuscated.log.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/12742604/home-assistant_smartthinq_sensors_2023-09-27T19-09-36.595Z.obfuscated.log.txt)


[2023-09-27 212851.507 DEBUG (MainTh.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/12742668/2023-09-27.212851.507.DEBUG.MainTh.txt)

Thanks for your time

**Comment by nchieffo** [comment]
OK I got a new file with 1 message before the cycle ends, and 1 message after.
[last before and first after cycle ends.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/12752648/last.before.and.first.after.cycle.ends.txt)

I also took a quick look at the diff, which is not so much promising
![www diffchecker com_text-compare_](https://github.com/ollo69/ha-smartthinq-sensors/assets/632266/841302e0-b360-4b81-b4ad-fceb27245af7)

**Comment by nchieffo** [comment]
Still an issue

**Comment by nchieffo** [comment]
Worth reopening

**Comment by Trilis29** [comment]
any update?

**Comment by ollo69** [comment]
I reopen this issue because I made some changes to support `run_completed` for these devices that do not provide `end` state. Can you please test is last release fix the problem?

**Comment by ollo69** [comment]
@Trilis29 ,

thanks for you feed-back, but please test last release ([v0.38.3](https://github.com/ollo69/ha-smartthinq-sensors/releases/tag/v0.38.3) because I review a little bit the code from previous one and I just want to be sure that still work properly.

Thanks  👍

**Comment by Trilis29** [comment]
HACS does not show me v0.38.3 yet :) will test and write feedback

**Comment by Trilis29** [comment]
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/51697921/6d4e0f73-9a9c-4306-a0bd-cf1ba239d241)
Seems working.
