### ISSUE TITLE
Sensors inaccurate WM3600HWA

### ISSUE THREAD

**Issue by vulcanjedi** [ollo69/ha-smartthinq-sensors#229]
1. Integration v 10.1
2. HA v 2021.10.0
3. LG Washer WM3600HWA (brand new about 4 days)

- I get 18 sensors thru the integration. Sensor.washer has a bunch of attributes I think some of the sensors are supposed to key off but some don't match and/or inaccurate.
- The door closed sensor isn't working says Open all the time. (was super excited to have Nodered send alert when wife repeatedly forgets to leave the door open to dry it and prevent mildew/smell but sensors aren't working) Current the value in the sensor.washer attribute says OFF but the binary says OPEN but these don't seem to change. The load is going right now
- The wash complete wont clear after load is done 
- Not sure if the power off switch should work? But it doesn't. We've had a couple instances where water backed up and a load was going so backflowed from the washer drain, was hoping to integrate w/ a leak sensor to detect a leak and stop the washer if possible if this functionality is supposed to work or in the roadmap.
- Not sure what the polling interval is but its really low. 
- Should the sensors work 

w/ the washer off, if Open/Close the door the integration doesn't seem to change.

Super excited by this integration, thanks for efforts.

**Comment by ollo69** [comment]
This issue do not address any specific problem. Please open new issue filling the information requested by the template if there are some specific problem.
