### ISSUE TITLE
0.109 beta translation alert

### ISSUE THREAD

**Issue by sagitt** [ollo69/ha-smartthinq-sensors#23]
![Schermata 2020-04-25 alle 21 08 44](https://user-images.githubusercontent.com/169086/80288604-35940480-8739-11ea-8f85-b90e0e5607dd.png)

**Comment by ollo69** [comment]
Will fix on next release.
Thanks

**Comment by petersoniq** [comment]
Can we help you translation to other language?

**Comment by sagitt** [comment]
I can help for italian

**Comment by ollo69** [comment]
Yes, of course, but at this moment this only apply to config flow.
The best way to do this is using Pull Request:

- fork project on your GitHub accounts
- create the translation files for new language in "translation" directory  copyng the en.json and translate the content 
- create a Pull Request with your new translation file

**Comment by KrzysiekLegnica** [comment]
Polish translation - tested

https://github.com/KrzysiekLegnica/ha-smartthinq-sensors

**Comment by ollo69** [comment]
> Polish translation - tested
> 
> https://github.com/KrzysiekLegnica/ha-smartthinq-sensors

Can you please create a PR?

**Comment by KrzysiekLegnica** [comment]
I don't know how to do it.

**Comment by ollo69** [comment]
> I don't know how to do it.

Ok, I'll do it for you, thanks

**Comment by ollo69** [comment]
I close this issue, new PR with tranclation are welcome
