### ISSUE TITLE
webOS integration

### ISSUE THREAD

**Issue by ayed3** [ollo69/ha-smartthinq-sensors#230]
just wanted to have LG smart TVs running WebOS to be considered in this integration so we can control
TVs

**Comment by ollo69** [comment]
As I know WebOS is totally different from others LG integration. In any case integrate a TV is very complex work and would require a device to perform test, and I don't have an LG TV, so it will be very difficult (probably impossible) that this feature will be added.

**Comment by david-holbrook** [comment]
FYI @ayed3, there is already a native home assistant LG webOS Smart TV integration that does this.

https://www.home-assistant.io/integrations/webostv/
