### ISSUE TITLE
Please add new properties for my dryer

### ISSUE THREAD

**Issue by gtivr4** [ollo69/ha-smartthinq-sensors#233]
Hello from spain, sorry for my english.

Please add this properties for my dryer RC90V9_WW-Dryer (DRYER).

    FEAT_DAMPDRYBEEP,
    FEAT_RESERVATION,
    FEAT_HANDIRON,
    FEAT_SELFCLEAN,
    FEAT_ANTICREASE,
    FEAT_ECOHYBRID,

    @property
    def dampdrybeep_state(self):
        status = self.lookup_bit(
            "dampDryBeep" if self.is_info_v2 else "DampDryBeep"
        )
        return self._update_feature(
            FEAT_DAMPDRYBEEP, status, False
        )

    @property
    def reservation_state(self):
        status = self.lookup_bit(
            "reservation" if self.is_info_v2 else "Reservation"
        )
        return self._update_feature(
            FEAT_RESERVATION, status, False
        )

    @property
    def handiron_state(self):
        status = self.lookup_bit(
            "handIron" if self.is_info_v2 else "HandIron"
        )
        return self._update_feature(
            FEAT_HANDIRON, status, False
        )

    @property
    def selfclean_state(self):
        status = self.lookup_bit(
            "selfClean" if self.is_info_v2 else "SelfClean"
        )
        return self._update_feature(
            FEAT_SELFCLEAN, status, False
        )

    @property
    def anticrease_state(self):
        status = self.lookup_bit(
            "antiCrease" if self.is_info_v2 else "AntiCrease"
        )
        return self._update_feature(
            FEAT_ANTICREASE, status, False
        )

    @property
    def eco_hybrid_option_state(self):
        if not self.key_exist(["EcoHybrid", "ecoHybrid"]):
            return None
        eco_hybrid = self.lookup_enum(["EcoHybrid", "ecoHybrid"])
        if not eco_hybrid:
            eco_hybrid = STATE_OPTIONITEM_NONE
        return self._update_feature(
            FEAT_ECOHYBRID, eco_hybrid
        )

**Comment by ollo69** [comment]
Close this issue, completed with PR #236
