### ISSUE TITLE
Remote start control LG washer [Feature Request]

### ISSUE THREAD

**Issue by vannetta** [ollo69/ha-smartthinq-sensors#234]
**Describe the solution you'd like**
I'd like to remote start my washer, in order to make an automation that the washer starts when the photovoltaic panels are producing at least 1000 W.
Is it that possible with your integration? I only see the sensor but I cannot send any command to the washer. I'd need a switch to turn on it.
The model is: F4WV408S0E

**Additional context**
Screenshot of the sensors
![image](https://user-images.githubusercontent.com/58345243/138484744-95846f9e-ff28-4fa1-aa8d-c6465d90cf7f.png)

**Comment by vannetta** [comment]
> Those are services (commands) not sensors. Check out the services page in the developer tools, and search for smartthinq_sensors. You should find both the wake_up and remote_start commands.

Thank you very much for your suggestions, it works! I only have to understand how to write the automation in order to define the trigger (whether I put clothes in the washer or not). 
And thank you @ollo69 for all your efforts, I really appreciate it

**Comment by wishie** [comment]
I think its so frustrating that you need to enable "Remote Start" on the front panel of the dryer every time.. why cant it default to on, or at least be configurable?

Silly LG..

**Comment by hmoffatt** [comment]
Well you actually have to load it with stuff to dry so I don't think it's a big deal.

**Comment by hmoffatt** [comment]
From the sensors you can work out if the unit is enabled for remote start. Then when the time is right (like there's enough solar power) you can execute the remote start.

**Comment by PremiumUsername** [comment]
> Yes it's all possible right now. Use the smartthinq_sensors.remote_start service to issue the remote start command.

I wasn't able to find the API. Is it possible to choose the washing-program used when you use remote start?

**Comment by newlund** [comment]
service: smartthinq_sensors.remote_start
data: {}

What data is needed/possible for remote start? I can't find it documented anywhere. :)

**Comment by vannetta** [comment]
> service: smartthinq_sensors.remote_start data: {}
> 
> What data is needed/possible for remote start? I can't find it documented anywhere. :)

service: smartthinq_sensors.remote_start
target:
  entity_id: sensor.lavatrice
data: {}
