### ISSUE TITLE
[BUG] Fridge door open

### ISSUE THREAD

**Issue by Pascal66** [ollo69/ha-smartthinq-sensors#237]
**Describe the bug**
Refrigerator door open never work
Everything else work fine

**Expected behavior**
alert when door open as it work in  lg app

**Comment by ollo69** [comment]
I need your refrigerator JSON information file to analyze this issue. You can find the url to download it in HA log during startup.

**Comment by Pascal66** [comment]
Cant get it, but as everything work, i dont want to reinstall.
I maybe have a python script for that but cant retrieve it for now
A goo feature can be a debug button to get the json info

**Comment by ollo69** [comment]
You don't need to reinstall nothing, just open HA log file and search for the url to download it.

**Comment by Pascal66** [comment]
I've 36 Billion of lines. Cant got that

**Comment by ollo69** [comment]
Without this info I cannot help you. If for you is ok as is, please close this issue.👍

**Comment by Pascal66** [comment]
Its an issue, as I cannt give you what you ask

**Comment by hmoffatt** [comment]
grep?

**Comment by ollo69** [comment]
@Pascal66,

info is in the log, and to have support you need to provide info in the log. This is one of the main rules to play this games, clearly stated in HACS installation:

![image](https://user-images.githubusercontent.com/60491700/141171764-72c2b1be-85b7-4755-b692-338fde77168e.png)

If your log file is too big to be managed, rename it with command :

`sudo mv homeassistant.log homeassistant.log.old` (adjust it if log file name is different)

and reboot HA, a new file will be created, so that you will be able to access it and keep information.

**Comment by Pascal66** [comment]
Sorry to bother, but I've only one line related to smarthing in my log.

`2021-11-11 09:27:02 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
`
Everything is working : 
![image](https://user-images.githubusercontent.com/3041616/141265676-db3a1109-1a13-4ea1-bee1-0924078bedf0.png)

**Comment by faibe24** [comment]
[refrigerator_json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/7705945/refrigerator_json.txt)

Same problem here... the door sensor works intermittently

**Comment by ollo69** [comment]
> Sorry to bother, but I've only one line related to smarthing in my log.
> 
> `2021-11-11 09:27:02 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

This is a standard warning that HA logs for every custom integration installed, not an issue if integration works

**Comment by ollo69** [comment]
> Same problem here... the door sensor works intermittently

Please provide more details. When it works and when not?

**Comment by Pascal66** [comment]
There's an tons of values sended to Korea 'external temp, internal temp, time of open, time of close, ... and so on'
This permit to know,  when users use it, and why.
Unfortunatly this is a hard way to have that in aws amazon

**Comment by hugommsilva1** [comment]
Hello,

In the fridge it is possible to have an update time like 5 or 10 seconds, because when the door is opened only 20 or 30 seconds later it appears in the HA.

It's not a bad situation, and I really like the integration if it's possible for me to change it good, if not don't worry.

Thanks!

**Comment by joggs** [comment]
Is your solution using Event Subscription or do you just poll info at a certain interval? It looks like some parts of LG Thinqs api's support event subscriptions which would be an advantage, but I'm sure you looked into that already. My freezer sends a notification in the native app first after 60 seconds, so is that the delay you also get in the api? If so, one will never get a door open notification the first minute the door is open.
