### ISSUE TITLE
Connection not available. ThinQ platform not ready

### ISSUE THREAD

**Issue by insidexino** [ollo69/ha-smartthinq-sensors#238]
I cannot connect and I got an error like this.

![image](https://user-images.githubusercontent.com/11733424/140598689-b822e714-9dd5-44e2-9506-887ebc82a0af.png)

Can you help me?

**Comment by ollo69** [comment]
This should be fixed with last version released (v0.10.5)

**Comment by insidexino** [comment]
It works fine now. Thank you!

**Comment by grfernandes54** [comment]
I'm having the same issue.
