### ISSUE TITLE
[Feature Request] Add Energy meter for Washer F4WV9010P2W

### ISSUE THREAD

**Issue by joaopequeno-git** [ollo69/ha-smartthinq-sensors#239]
**Describe the bug**
I have a washer ref. F4WV9010P2W ,and the energy vlaues dont appear.

**Expected behavior**
How can i get this sensor to be showed.

**Screenshots**
![imagem](https://user-images.githubusercontent.com/56827914/140729527-15b4c935-6f36-4407-82fe-535d758193be.png)

**Comment by ollo69** [comment]
There are no energy meter sensors for washer device, so this is not a bug.
If you think that your device is able to provide this information, please open a `feature request` and provide information to implement the feature:

- JSON file with your device information
- HomeAssistant log file with debug enabled for the integration to show the received payload.

Thanks. 👍

**Comment by joaopequeno-git** [comment]
Hello @ollo69 

The newest machines have energy meter, since the app show the power use on each cycle:
![imagem](https://user-images.githubusercontent.com/56827914/140743655-b162b225-2bb2-486e-92ed-eaf9d6bce55c.png)

What information can i provide for this be fixed/implemented?

**Comment by ollo69** [comment]
In HA log at startup you will find a `url` that you can use to download the JSON info. Download it and attach to the Feature Request that you will open.
Than enable debug log for integration, run for a while the device and again attach the log file to the Feature Request.

Please don't continue use this bug issue that is closed.

**Comment by joaopequeno-git** [comment]
> 
> 
> In HA log at startup you will find a `url` that you can use to download the JSON info. Download it and attach to the Feature Request that you will open. Than enable debug log for integration, run for a while the device and again attach the log file to the Feature Request.
> 
> I re-open this thread marking it as feature request.

Do you have a tutorial on how to do this?
Thanks

**Comment by joaopequeno-git** [comment]
Hello @ollo69 

The newest machines have energy meter, since the app show the power use on each cycle:
![imagem](https://user-images.githubusercontent.com/56827914/140743655-b162b225-2bb2-486e-92ed-eaf9d6bce55c.png)

What information can i provide for this be fixed/implemented?

**Comment by ollo69** [comment]
I don't have tutorial. But as I say the first step is very simple: open HA log and search for a message that start with `Loading model info for...`. Use the `url` in message to download with your browser the JSON info file and attach it to this thread or, if you prefer, just copy here the `url`, I will download the file by myself.

**Comment by joaopequeno-git** [comment]
> 
> 
> I don't have tutorial. But as I say the first step is very simple: open HA log and search for a message that start with `Loading model info for...`. Use the `url` in message to download with your browser the JSON info file and attach it to this thread or, if you prefer, just copy here the `url`, I will download the file by myself.

My Log is clean without entries.
How can i do it?
Thanks

**Comment by ollo69** [comment]
Probably your log is set to warning level. You must change log section settings in `configuration.yaml` with something like this:

```
logger:
  default: info
```

To enable debug for integration use this:

```
logger:
  default: info
  logs:
    custom_components.smartthinq_sensors: debug
```

**Comment by joaopequeno-git** [comment]
> 
> 
> Probably your log is set to warning level. You must change log section settings in `configuration.yaml` with something like this:
> 
> ```
> logger:
>   default: info
> ```
> 
> To enable debug for integration use this:
> 
> ```
> logger:
>   default: info
>   logs:
>     custom_components.smartthinq_sensors: debug
> ```

File attached.

[90683f07-fc16-4ac1-a454-dbb6e6ecf148.zip](https://github.com/ollo69/ha-smartthinq-sensors/files/7509399/90683f07-fc16-4ac1-a454-dbb6e6ecf148.zip)

**Comment by blue-hound** [comment]
Hi,
This integration is awesome! Thanks for the work on it!

Just wanted to help out with this as well. My WM4500 reports energy usage in the app as well. I've added the JSON file from my washer to see if it helps you out. There is a power table, I was hoping to be able to help you decipher the data a bit, I only have 9 cycles on the washer but I can seem to correlate the data. I'm about to do another cycle so I'll see how the file changes between cycles.

[LG Dump JSON.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/7515425/LG.Dump.JSON.txt)

**Comment by kalatos86** [comment]
Same question here. I'd like to add my washer and dryer into the individual devices consumption in HA energy. Models are following: 
Washer: F_W7_Y___W.B_2QEUK-FL (WASHER) by LG
Dryer: RC90V9_WW-Dryer (DRYER) by LG  

Do you want from me LG Dump also or everything has been told already and you are working on future update?

Thanks,
Lukasz

**Comment by majdzik84** [comment]
Hello. Is there any progress in this matter ??

**Comment by ollo69** [comment]
The information related to energy consumptions for Washer are not in the payload. I think that LG app just calculate some statistics based on program and time used, but this do not represent real power consumption. An integration in HA cannot calculate this kind of statistics, this should be done directly by HA based on real time information coming from the the integrations. You can easily implement this for the Washer based on the information already available.
