### ISSUE TITLE
Washing Machine missing other State

### ISSUE THREAD

**Issue by Pistak** [ollo69/ha-smartthinq-sensors#24]
Hi ollo69,
First of all, this is awsome, you are awsome!
I have recovered the json of my LG washer dryer (F4J8FH2W) and I realized that the DEMO status also exists.
Both in State and in Prestate.
This is the string: "16":"@WM_STATE_DEMO_W"

Also missing some WASHING SPIN SPEED:
"3":"@WM_TITAN2_OPTION_SPIN_600_W",
"4":"@WM_TITAN2_OPTION_SPIN_700_W",
"8":"@WM_TITAN2_OPTION_SPIN_1100_W",
"11":"@WM_TITAN2_OPTION_SPIN_1600_W",
"255":"@WM_TITAN2_OPTION_SPIN_MAX_W".

Also missing WASHING TEMP:
"5":"@WM_TITAN2_OPTION_TEMP_50_W".

I also add Dry State:
"DryLevel":{
            "type":"Enum",
            "default":"0",
            "label":"@WM_TITAN2_OPTION_DRY_W",
            "option":{
                "0":"-",
                "1":"-",
                "2":"@WM_TITAN2_OPTION_DRY_NORMAL_W",
                "3":"@WM_TITAN2_OPTION_DRY_30_W",
                "4":"@WM_TITAN2_OPTION_DRY_60_W",
                "5":"@WM_TITAN2_OPTION_DRY_90_W",
                "6":"@WM_TITAN2_OPTION_DRY_120_W",
                "7":"@WM_TITAN2_OPTION_DRY_150_W",
                "8":"@WM_TITAN2_OPTION_DRY_ECO_W",
                "9":"@WM_TITAN2_OPTION_DRY_VERY_W",
                "10":"@WM_TITAN2_OPTION_DRY_IRON_W",
                "11":"@WM_TITAN2_OPTION_DRY_LOW_W",
                "12":"@WM_TITAN2_OPTION_DRY_ENERGY_W",
                "13":"@WM_TITAN2_OPTION_DRY_SPEED_W",
                "14":"@WM_TITAN2_OPTION_DRY_COOLING_W"
            }

I'd like to know if it would be possible to set up custom programs with the API.

I hope I was helpful

**Comment by ollo69** [comment]
Thanks,

I added the states (not demo, I think is used only in the store) and add the dryer option to the washer device.
The API for the moment are integrated in the component, but you can use as you want. In the future maybe I will create a separate library or merge with original wideq project.

**Comment by Pistak** [comment]
Hi Ollo69,
i think that OPTION DRY 30 60 90 120 150 it's time of dry not temperature.
i have see that in dryer_states.py in your last commit you entered the degrees centigrade not the time in minutes.

I hope I was helpful

**Comment by ollo69** [comment]
Fine, I will fix
