### ISSUE TITLE
Unable to find integration

### ISSUE THREAD

**Issue by fredrikscode** [ollo69/ha-smartthinq-sensors#240]
I'm unable to locate the integration for this awesome project. 

> Home Assistant OS 6.6
> supervisor-2021.10.8
> core-2021.11.2

Am I being a dumdum? It's not available through their site either. [Home Assistant Integrations](https://www.home-assistant.io/integrations/#search/SmartThinQ%20LGE%20Sensors)

**Comment by ollo69** [comment]
Did you install HACS?

**Comment by fredrikscode** [comment]
> Did you install HACS?

Apologies. I thought HACS was short for Home Assistant Core Server or something alike. Thank you for such a fast response

**Comment by lukaszzyla** [comment]
this is not funny.
I can't find my integrations too, but for real.
I did install through HACS but there is no new integration available in UI.
Logs don't say anything about it.

**Comment by ollo69** [comment]
Refresh browser cache

**Comment by fredrikscode** [comment]
Since this has been resolved and @lukaszzyla has a different issue I'll close this thread. Thanks for the input
