### ISSUE TITLE
Integration - configuration interface can't be loaded[BUG]

### ISSUE THREAD

**Issue by robertpe01** [ollo69/ha-smartthinq-sensors#242]
Hi,
I would like to use your integratin, but configuration interface can't be loaded.
Just after adding the integretion I have received tha info that:

Configuration intercace can't be loaded.

**Comment by gabrieledaltoe** [comment]
Me also!  
Error retrieving login URL from ThinQ.....

**Comment by gabrieledaltoe** [comment]
LG Servers Maintenance... now is OK

**Comment by kannan-balasubramanian** [comment]
Am also facing a similar issue.
Installed the latest version via HACS.
Then tried the integration via Configuration->Integrations->Add Integrations->SmartThinQ LGE Sensors and when I click on it, nothing happens.

Do note that I had a previous installation of the integration which I removed, uninstalled and restarted the server.

**Comment by yang3535** [comment]
I installed HACS and the integration, but I cannot find anywhere to configure it.  Clicking on the integration only opens the document from Github.  The document says to "follow the setup workflow", but there is no reference to its location and I cannot find it. 

Am I missing something?

**Comment by nickdos** [comment]
> I installed HACS and the integration, but I cannot find anywhere to configure it. Clicking on the integration only opens the document from Github. The document says to "follow the setup workflow", but there is no reference to its location and I cannot find it.
> 
> Am I missing something?

This tripped me up the first time too. Once you've installed it via HACS, you then have to go into the main "Devices & services" section under "Configuration". You'll see the list of integrations you've already got installed in HA. 

Click the blue button "Install integration" and search for smartthinq (from memory). Install as the instructions indicate.

**Comment by kzagatti** [comment]
The integration was not showing up here too. It seems weird, but after forcing a refresh on the integrations page I was able to find it. Might help somebody too.

**Comment by rashmipatel829** [comment]
I still can't find this in the integrations page.  I tried to reinstall in HACS.  Any ideas?

**Comment by ollo69** [comment]
If you don't see the integration, problem is in installation or in HomeAssistant. 

- what is your HA environment?
- do you see other custom integration or you can only use the standard?

The part related to initial configuration is standard, if the issue were related to integration, no one would be able to configure it.

If you don't find a solution the only suggestion that I can give you is to reinstall HomeAssistant because probably your installation have some issue.

**Comment by rashmipatel829** [comment]
> If you don't see the integration, problem is in installation or in HomeAssistant.
> 
> * what is your HA environment?
> * do you see other custom integration or you can only use the standard?
> 
> The part related to initial configuration is standard, if the issue were related to integration, no one would be able to configure it.
> 
> If you don't find a solution the only suggestion that I can give you is to reinstall HomeAssistant because probably your installation have some issue.

Hu, I was able to fix the issue. I had to restart my Home Assistant VM manually.

Thanks

**Comment by ollo69** [comment]
Ok, I close this issue because collect multiple issues, some fixed, some unrelated and others not clear. If still someone have some issue configuring integration, please open a new one and provide details.
