### ISSUE TITLE
[BUG] Unable to prepare setup for platform

### ISSUE THREAD

**Issue by klasenby** [ollo69/ha-smartthinq-sensors#243]
**Describe the bug**
After installing LGE integration, configuring my account and restarting, errors are logged and integration does not load.

**Expected behavior**
Integration to load and not error.

**Screenshots**
![Screenshot_20211119-181636](https://user-images.githubusercontent.com/4096799/142702973-f23c5769-c9d0-4a52-9df9-cf826a133b11.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Docker image on Synology NAS
 - Home Assistant version installed: 2021.6.4
 - Component version installed: V0.10.6
 - Last know working version: None, .5 had same issue
 - LG device type and model with issue: NA
 - LG devices connected (list): Washer and Dryer

**Output of HA logs**
Logger: homeassistant.setup
Source: setup.py:310
First occurred: 6:01:14 PM (4 occurrences)
Last logged: 6:01:14 PM

Unable to prepare setup for platform smartthinq_sensors.sensor: Platform not found (cannot import name 'DEVICE_CLASS_PM1' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).
Unable to prepare setup for platform smartthinq_sensors.binary_sensor: Platform not found (cannot import name 'BinarySensorEntityDescription' from 'homeassistant.components.binary_sensor' (/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py)).
Unable to prepare setup for platform smartthinq_sensors.switch: Platform not found (cannot import name 'SwitchEntityDescription' from 'homeassistant.components.switch' (/usr/src/homeassistant/homeassistant/components/switch/__init__.py)).
Unable to prepare setup for platform smartthinq_sensors.climate: Platform not found (cannot import name 'ClimateEntityDescription' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)).

**Comment by ollo69** [comment]
Upgrade HA. Please refer to issue #222 👍
