### ISSUE TITLE
Integration not showing up

### ISSUE THREAD

**Issue by Scalabanana** [ollo69/ha-smartthinq-sensors#245]
I installed the custom component via HACS and restarted the server. Anyway the integration doesn't show up in the list. I've tried to reinstall and restart several times but cannot figure out what's wrong.

Other custom components work fine.

**Comment by KTibow** [comment]
Is it in the custom_components folder? Also try clearing your cache.

**Comment by Scalabanana** [comment]
Clearing the cache was it, i think. Event though I had to do a few times before it appeared.

**Comment by KTibow** [comment]
If that fixed it, close the issue. Thanks!
