### ISSUE TITLE
Retrying Setup: None

### ISSUE THREAD

**Issue by bb12489** [ollo69/ha-smartthinq-sensors#246]
I noticed recently that the integration has stopped working. I thought this was due to any recent updates, but I've rolled back and noticed the same issue. I'm able to go through the config flow and setup my language, country, and get the redirect url; but when I finish that process the integration simply says "Retrying setup: None" on the integrations page in HA. 

I've tried removing the integration, and uninstalling the repo from HACS. Nothing seems to work.

**Comment by tom-lloyd-veea** [comment]
Same issue here

**Comment by ollo69** [comment]
Please provide logs

**Comment by bb12489** [comment]
This error originated from a custom integration.

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:879
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 3:20:10 PM (4 occurrences)
Last logged: 3:21:13 PM

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 219, in async_setup_entry
    lge_devices = await lge_devices_setup(hass, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 586, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 347, in init_device
    result = await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1055, in init_device_info
    self._model_data = self._client.model_url_info(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 906, in model_url_info
    self._model_url_info[url] = self._load_json_info(url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 879, in _load_json_info
    return json.loads(enc_resp)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ollo69** [comment]
It fail while is trying to load the JSON device information file. You should enable debug to try to manual download it and understand where is the issue

**Comment by beped** [comment]
I have the same problem here. Any solution?

**Comment by tom-lloyd-veea** [comment]
You have to complete the setup on the mobile app first. I ended up using google.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bb12489** [comment]
> You have to complete the setup on the mobile app first. I ended up using google. Get Outlook for Android<https://aka.ms/AAb9ysg>
> […](#)
This doesn't make sense to me. I completed the setup through the app a long time ago. I've been using this integration for most of 2021. I've tried to revert back to older versions of the integration, but I get the same issue. I'm not using a Google account for authentication to LG. Just a standard LG account. Do I have to delete my LG account and start over from scratch then?

**Comment by ollo69** [comment]
My comment is unchanged: `It fail while is trying to load the JSON device information file. You should enable debug to try to manual download it and understand where is the issue.`
If you want delete and recreate your account, you can try, but I don't think this will solve your issue.

**Comment by bb12489** [comment]
> I have the same problem here. Any solution?

So I've just noticed that my window air conditioner that I added earlier in the year seemed to have become disconnected from my LG app dashboard. It would still appear as a registered device, but every time I tried selecting it, it would come back with a server error. I removed the AC device from the LG app, then re-added it. Now it shows connected in the LG app, but also for some reason the LG  HA integration is now working after I did all of this. I'm guessing some configuration error on the LG side of things was screwing up the setup of the integration. 

So I would check to make sure that you don't have some device that's having connection problems with the LG app.

**Comment by ollo69** [comment]
That's fine👍. Can we close this issue?

**Comment by bb12489** [comment]
> That's fine👍. Can we close this issue?

It's solved for me

**Comment by john-sib** [comment]
I have just had the same problem, I solved it by opening LG app on phone accepting new terms and conditions then reloaded the Intergration in home assistant and all went back to normal.
