### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by trex2000** [ollo69/ha-smartthinq-sensors#247]
I've installed manually the custom component in a debian server operating  system.
I was using this before, but after an update, it was necessary to remove and re-add the component, however it won't work any more.
I've been digging into the logs, and the issue that might be related is this :

 File "/home/homeassistant/.homeassistant/custom_components/smartthinq_sensors/config_flow.py", line 4, in <module>
    from pycountry import countries as py_countries, languages as py_languages
  File "/home/homeassistant/.homeassistant/deps/lib/python3.9/site-packages/pycountry/__init__.py", line 30, in <module>
    class ExistingCountries(pycountry.db.Database):
AttributeError: partially initialized module 'pycountry' has no attribute 'db' (most likely due to a circular import)

Any idea how to fix this ?

**Comment by ollo69** [comment]
Looks like pycountry is not properly installed. Did you use a venv or a docker?

**Comment by trex2000** [comment]
Native installation

**Comment by ollo69** [comment]
I think that pycountry have some conflict with other packages installed with your linux installation. I suggest you at least to install HA in venv.

**Comment by trex2000** [comment]
Thanks,
I will figure it out

**Comment by ollo69** [comment]
I close this issue, there are no feed-back from 2 months.

**Comment by pablopoo** [comment]
Had same issue after update. To resolve this:
1.-Remove this integration
2.-Install the pycountry module: pip3 install pycountry
3.-Reinstall this integration.

If you install pycountry without removing and reinstalling this module you will get error:
AttributeError: partially initialized module 'pycountry' has no attribute 'db' (most likely due to a circular import)

**Comment by marcux01** [comment]
> Had same issue after update. To resolve this: 1.-Remove this integration 2.-Install the pycountry module: pip3 install pycountry 3.-Reinstall this integration.
> 
> If you install pycountry without removing and reinstalling this module you will get this error: AttributeError: partially initialized module 'pycountry' has no attribute 'db' (most likely due to a circular import)

Hi Pablopoo - I went straight to installing without first removing integration (ie. step 1).  Don't see anything in logs that call out the error you called out can occur (then again not sure where to look for it).  But am still having the "config flow could not be loaded".  Running 2021.10.5.  Any tips on what to try next?
