### ISSUE TITLE
[Feature Request] AC Unit Action to Set Temperature

### ISSUE THREAD

**Issue by Hime0698** [ollo69/ha-smartthinq-sensors#248]
At the moment when writing automations the only action for my window AC unit appears to be setting the mode. 

Can you add one for setting the temperature. 

I want to set up when to do something like "When I leave the house, set the AC to 75 Degrees"

I can't figure out how to write custom YAML for this, but I have no experience in doing that, so I figured I'd add a feature request. I can see and set the temperature from the Lovelace UI panel. Just not in automations.

**Comment by ollo69** [comment]
If you need information on how configure automation, you should use documentation or ask help in HA forums. If I well understand temperature is available in Lovelace, this means that integration is providing all the elements to create automation using HA services.
