### ISSUE TITLE
[Feature Request] KIMCHI_REFRIGERATOR (modelName': '3REK1G04AR200S_2')

### ISSUE THREAD

**Issue by nukusinji** [ollo69/ha-smartthinq-sensors#249]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

It is similar refrigerator.

It's model json is 'https://objectcontent.lgthinq.com/ea720caf-1376-41d0-86bf-2236e1abc639?hdnts=exp=1700199428~hmac=50a9d81ed0274c8c532d21b241dd1bd2cd661266c683f34082c32c4e7b5c14a9'

[KIMCHI_REFRIGERATOR.zip](https://github.com/ollo69/ha-smartthinq-sensors/files/7685435/KIMCHI_REFRIGERATOR.zip)

**Comment by jweston2112** [comment]
Not sure how he found the files in the Zip ... it contains the Korean Language ... obviously I would prefer english.

**Comment by nukusinji** [comment]
> Not sure how he found the files in the Zip ... it contains the Korean Language ... obviously I would prefer english.

I don't know how to get the EN language pack.
