### ISSUE TITLE
[BUG] Gmail login doesn't work

### ISSUE THREAD

**Issue by Merwenus** [ollo69/ha-smartthinq-sensors#250]
**Describe the bug**
While trying to log in with Gmail I get error 400
Error (400): redirect_uri_mismatch
You cannot sign in to this application because it does not comply with Google's OAuth 2.0 policy.
If you are the developer of the application, please register the redirect URI in the Google Cloud Console.

**Expected behavior**
No idea, first time user, I guess it should log in without error

**Environment details:**
Home Assistant 2021.11.5 core
Firefox 91

**Screenshot**
https://imgur.com/a/39wE3et

**Comment by ollo69** [comment]
You should use a LG account instead of social (Google) account. Create the new LG user in LG mobile app, associate your device in the app and then configure application with that account.

**Comment by Merwenus** [comment]
Thanks, missed that part, my bad!
