### ISSUE TITLE
Duration time attributes format

### ISSUE THREAD

**Issue by lcavalli** [ollo69/ha-smartthinq-sensors#257]
Is it possible to format duration time attributes by adding the seconds at the end of the timetag as ":00"? This will make this integration compatible with timer bar card used to display a progress bar with remaining times. See https://github.com/rianadon/timer-bar-card/issues/15

As a workaround currently it is required to define custom template sensors by manually adding the seconds.

Thanks.

**Comment by ollo69** [comment]
This would be a breaking change because all automations and cards are based on current format, so I prefer to avoid this. Platform template is the right solution to format time values as you need.

**Comment by lcavalli** [comment]
I'm not a big fan of sensor duplication with template platform, but I can understand your opinion regarding the regression. In any case, reading this page https://www.home-assistant.io/integrations/timer/ , I think that the default way to express a duration in HA is with 00:00:00 format.

**Comment by KTibow** [comment]
I can update the card if needed.

**Comment by ollo69** [comment]
Ok, I will think a little bit more about this. Using standard format is better, I'm just worried about the coming issue due to the breaking change.

**Comment by KTibow** [comment]
You've done breaking changes in the past. It should be okay.

**Comment by ollo69** [comment]
Just committed this change in `master` branch.

@KTibow,

can you please create a PR to update the card so that I will create a new release with both changes?

Thanks.

**Comment by KTibow** [comment]
Actually, just from glancing at the card's code, it should work fine. Can someone else test the card (my integration is broken ATM)?

**Comment by lcavalli** [comment]
Installed the card with the updated integration and it seems to work out of the box.

**Comment by lcavalli** [comment]
Yesterday with the updated integration and card active the dryer suddenly stopped the program. I don't think it is related, but better testing.

**Comment by BebeMischa** [comment]
Before I update, what exactly is breaking in this update? The changelog says, there are breaking changes...

**Comment by ollo69** [comment]
The format of attributes / sensors `Initial time`, `Remain time` and `Reserve time` are changed, now they provide also the seconds (e.g it change from `0:00` to `0:00:00`).
The card available in readme still work and do not need update. If you have some sensor template that manipulate those sensor, you need ti be sure that still work and fix that template if required.

**Comment by BebeMischa** [comment]
ok, thank you. that should not affect my setup, i think... we will see. going to give it a shot now ;-)

**Comment by ollo69** [comment]
I close this FR, feature now is implemented and released. If there are some problem with feature please open a new issue describing details.
