### ISSUE TITLE
Gui Titles missing

### ISSUE THREAD

**Issue by molelightn** [ollo69/ha-smartthinq-sensors#26]
Hi there Ollo69,

First of all thanks to your work! 3x coffees for you :)

Got i working with the previous version today, setup through HA Gui was quiet simple. Upgraded to todays latest release 0.3.6 and something messed it up.
Reinstalled it via HACS, and now if i want to add the integration the popup do not show Titles anymore.

![image](https://user-images.githubusercontent.com/62118239/80312546-06879c80-87e6-11ea-96c7-c1329764f9e0.png)

Not sure what i am doing wrong :( 

br 
mole

**Comment by ollo69** [comment]
My mistake, please use last released version (0.3.7)

**Comment by molelightn** [comment]
working again, thank you
