### ISSUE TITLE
[BUG] Washer + dryer

### ISSUE THREAD

**Issue by virusczz** [ollo69/ha-smartthinq-sensors#262]
Hello, i have a washer LG F610V10RW2W and dryer LG RC91V9AV2QR. This machines in LQThingq they have also Power usage. In the Home Assintant i don't see this entities. 
![image](https://user-images.githubusercontent.com/36480973/148676612-38ceb40c-1e19-46de-8877-2f60b2282ee3.png)
![image](https://user-images.githubusercontent.com/36480973/148676619-b3b8e2fd-456a-47a9-9501-8988f9fe6757.png)

All my HA and this integration are up to date. 

thank you

**Comment by ollo69** [comment]
I close this because duplicated of #239 and is not a `Bug` but a `Feature Request`.
