### ISSUE TITLE
redirection url

### ISSUE THREAD

**Issue by sanakgol** [ollo69/ha-smartthinq-sensors#263]
**Status information**

#Provide details about the unknown states showed in the HA log

**Device information**

# Get the from the log the device model URL
# This is provided in the HA log in a row that start with: "Loading model info for ...." 

Device type:
Device Model:
Device model url:

**Comment by ollo69** [comment]
I do not understand what you are asking for.

**Comment by ollo69** [comment]
Close this issue because I do not understand what you are asking for
