### ISSUE TITLE
[BUG] 2022.2.0.dev20220109

### ISSUE THREAD

**Issue by Wibias** [ollo69/ha-smartthinq-sensors#266]
On the newest devs of HA the integration isnt't loading anymore. The same happened to the node-red integration. Also it cant be found anymore in the store of Hacs when searching for it.

**Comment by ollo69** [comment]
This is a HACS issue, see #261. Please close this issue if updating HACS fix the issue.

**Comment by Wibias** [comment]
Yup that did it. Sorry about that!
