### ISSUE TITLE
The integration shows no devices even though I'm not using a social email account

### ISSUE THREAD

**Issue by livlif2dfullest** [ollo69/ha-smartthinq-sensors#269]
**Describe the bug**
I add the integration, it prompts me for the login information and I enter:
User Id: myemail@outlook.com
Pwd:      ******************
Country: US
Language: en
no checkboxes checked
returns "No SmartThinQ devices found"

Log shows: 2022-01-13 15:20:18 ERROR (MainThread) [custom_components.smartthinq_sensors.config_flow] No SmartThinQ devices found. Component setup aborted.

I modified conf_flow.py to log output and it's returning no devices for line 206:
```
        if not client.hasdevices:
            return None, RESULT_NO_DEV
```

When I log in via the LG ThinQ app on my phone using the same credentials (verified it said US/English at top of app) it shows me 1 TV which I would expect the integration to find as well.

**Expected behavior**
For the integration to find my TV.

**Screenshots**
N/A

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Home Assistant on Raspberry Pi
 - Home Assistant version installed: Home Assistant OS 7.1
 - Component version installed: 0.12.2
 - Last know working version: N/A
 - LG device type and model with issue: TV OLED65E7P-U
 - LG devices connected (list): 0

**Output of HA logs**
```
2022-01-13 15:20:18 ERROR (MainThread) [custom_components.smartthinq_sensors.config_flow] No SmartThinQ devices found. Component setup aborted.
```

**Additional context**
N/A

**Comment by ollo69** [comment]
LG TV is not supported by this integration, there is a native integration in HA for WebOS.
I close this issue because there is nothing to fix,
