### ISSUE TITLE
[Feature Request] Use custom brand icons

### ISSUE THREAD

**Issue by rchiileea** [ollo69/ha-smartthinq-sensors#271]
only if you wish, but I created some thinq icons for LG items over at custom brand icons https://github.com/elax46/custom-brand-icons#lg

you can link to this repo if you wish for icons for devices

welcome to link to the LG items and to discuss us adding more

**Comment by ollo69** [comment]
I do not understand how I should use this icons inside the integration. Could you better explain?

**Comment by rchiileea** [comment]
you can pull the icons from the git, but credit the git custom brand icons if you dont mind
