### ISSUE TITLE
"Add Integration" not showing SmartThinQ integrations in docker install of Home Assistant 2021.12.10 

### ISSUE THREAD

**Issue by enygren** [ollo69/ha-smartthinq-sensors#274]
**Describe the bug**

The SmartThinQ integration is now showing up as selectable in the docket install of Home Assistant 2021.12.10 

If another step is needed, it would be great to list it in the Wiki.

**Expected behavior**

With latest version from git installed in /etc/home-assistant/custom_components/smartthinq_sensors
the SmartThinQ should show up as an Integration option when "Add Integration" is selected.

**Environment details:**
 - Environment: Docker on Ubuntu 20.04
 - Home Assistant version installed: Home Assistant 2021.12.10 
 - Component version installed:  0.12.5
 - Last know working version:  N/A

**Output of HA logs**
Even with logging set to debug, the only entry for smartthinq_sensors is:

> 2022-01-23 09:44:36 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

Note that putting a "smartthinq_sensors" stanza (with an invalid token but just to see if this helps) in configuration.yaml does get the deprecation warnings and some log entries about it being loaded, but there is *still* no entry for it on the Integrations page.

```

```

**Additional context**

**Comment by ollo69** [comment]
If you are sure that you properly installed integration in `custom_components` folder and you reboot HA, try cleaning your browser cache.

**Comment by enygren** [comment]
I think just waiting did it --- it may be that the browser had cached an old version of the integrations list.  Thanks!
