### ISSUE TITLE
HVAC State or Status needed

### ISSUE THREAD

**Issue by josephny** [ollo69/ha-smartthinq-sensors#276]
I just installed the ThinQ integration and it's great.

It would sure be nice to have an attribute available that shows the current state, such as HEATING, COOLING, FAN, IDLE, etc.

Thank you!

**Comment by ollo69** [comment]
This points was already discussed in the past [here](#209). Because HVAC_ACTION can only be identical to HVAC_STATE, there is no need to implement this property.
Please close this issue if you don't have requests.

**Comment by josephny** [comment]
Thank you for pointing me to that thread.

I really don't understand.

The HVAC_MODE does not change if the unit is running (producing heat or cold).  The state changes.  

I apologize if I'm not using the correct terminology.  Let me explain with an example.  If the mode is HEAT and the setpoint is 70 degrees F, when the system detects that the room temperature is (for example) 75 degrees, the system will stop making heat.  But the mode will still be HEAT.  The state, however, will be IDLE.

It would be extremely useful to know the STATE of the device.

Thank you.

**Comment by ollo69** [comment]
You properly explain what `HVAC_ACTION` should be, but information to update this value are not available, so the only possibility  should be mirror `HVAC_STATE` and this does not provide any value add.

**Comment by josephny** [comment]
I understand now.

Can you help with ENERGY_CURRENT being available for only 1 of the 4 thermostats?

Thank you.

**Comment by ollo69** [comment]
I will answer to other thread. I close this issue.
