### ISSUE TITLE
Implements device_state_attributes

### ISSUE THREAD

**Issue by tenkaibr** [ollo69/ha-smartthinq-sensors#277]
I ve a washer machine and im getting this msg when I restart HA:

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 09:49:16 (1 occurrences)
Last logged: 09:49:16

Entity sensor.lavadora (<class 'custom_components.smartthinq_sensors.sensor.LGEWashDeviceSensor'>) implements device_state_attributes. Please report it to the custom component author.

******

Home Assistant 2021.12.10
Versão do Frontend: 20211229.1 - latest
Version	core-2021.12.10
Installation Type	Home Assistant OS
Development	false
Supervisor	true
Docker	true
User	root
Virtual Environment	false
Python Version	3.9.7
Operating System Family	Linux
Operating System Version	5.10.63-v7
CPU Architecture	armv7l
Timezone	America/Sao_Paulo
Home Assistant Cloud
Logged In	false
Reach Certificate Server	ok
Reach Authentication Server	ok
Reach Home Assistant Cloud	timeout
Home Assistant Supervisor
Host Operating System	Home Assistant OS 7.2
Update Channel	stable
Supervisor Version	supervisor-2021.12.2
Docker Version	20.10.9

**Comment by ollo69** [comment]
Just update integration to last version.
