### ISSUE TITLE
Can not combine with Home Asisstant

### ISSUE THREAD

**Issue by Umarkhabiliy** [ollo69/ha-smartthinq-sensors#287]
I can't integrate Lg Thinq. I get this message when i  try enter the profile 
![lgggggggggggggggg](https://user-images.githubusercontent.com/79736830/152678327-cd79045a-8f9c-4c06-9ef1-f140a5a8bd6a.png)

Please help me how to integrate Lg Thinq with step by step, i'm new in this sphere.

**Comment by Umarkhabiliy** [comment]
> Same problem happen to me

Can you solve this problem? Have you any ideas brother?

**Comment by ollo69** [comment]
Looking at the image seems that the error occur on LG login page, this is not an integration error and  cannot do nothing. Did you try to login directly from integration config flow instead using URL redirect method?

**Comment by mousawm** [comment]
login directly from integration config flow works. :)

**Comment by ollo69** [comment]
@Umarkhabiliy,

did suggestion provided solve issue also for you? Can we close this?

**Comment by Umarkhabiliy** [comment]
> Looking at the image seems that the error occur on LG login page, this is not an integration error and  cannot do nothing. Did you try to login directly from integration config flow instead using URL redirect method?

Mr I dont understund how to it? Can you share screen step by step?

**Comment by Umarkhabiliy** [comment]
> login directly from integration config flow worked for me. :)

How you did brother?

**Comment by mousawm** [comment]
> > login directly from integration config flow worked for me. :)
> 
> How you did brother?

enter your user and password in the integration without ticking use alternative url method, then submit.

**Comment by Umarkhabiliy** [comment]
Thanks it worked
