### ISSUE TITLE
Refrigerator- Other Sensors

### ISSUE THREAD

**Issue by wonkydog** [ollo69/ha-smartthinq-sensors#29]
Hi Ollo,

First of all, thanks for all of your time and effort on this! Got it working in no time and don’t have to use the app anymore! Brilliant!

Just wondering if you were planning to add any additional sensors to this? In particular my refrigerator has the following available:

![9B8CCE18-D213-4BE5-9EB9-BAE2A565F669](https://user-images.githubusercontent.com/59798254/80480077-eff95680-8947-11ea-9a62-745ba8f594ed.png)

It would be great if I could see filter status and hygiene fresh status of the fridge?

Let me know if your interested or need any more data and I’ll get it to you.

Thanks again for building this - I’ve been looking for years! 😂

**Comment by LongDono** [comment]
I am happy with it as is but here's another example from my Canada model:

![image](https://user-images.githubusercontent.com/5301311/80506717-5aac9100-894c-11ea-912a-1f06cb8be830.png)

**Comment by ollo69** [comment]
I added new information with last release

**Comment by wonkydog** [comment]
Interesting to see the options you have! 

Still just downloaded the latest and its working perfectly! I couldn't ask for more!

Thank you so much!

WD
