### ISSUE TITLE
How to access TARGET_TEMPERATURE for HVAC

### ISSUE THREAD

**Issue by josephny** [ollo69/ha-smartthinq-sensors#291]
My system has the CLIMATE entity, with related entities of ENERGY_CURRENT, ROOM_TEMPERATURE, and HUMIDITY.

But, I would like to use the target (or set-point) temperature.

When I use CLIMATE in a thermostat card, set-point is identified, but I'd like to use it in a difference card and can't find it.

Is it available?

Thank you!

**Comment by josephny** [comment]
I was able to access the target (or set point) temperature from within the CLIMATE entity by adding this to configuration.yaml.

Seems "temperature" is the target and "current_temperature" is the room temperature.

`      255_3rd_floor_target_temperature:
        friendly_name: "255_3rd_floor_target_temperature"
        unit_of_measurement: ""
        value_template: "{{ state_attr('climate.3rd_floor', 'temperature') }}"`

**Comment by ollo69** [comment]
This is not an issue and not the right place to ask information on how Home Assistant works. Right place is HA forum.
