### ISSUE TITLE
Unsuccessful Integration 

### ISSUE THREAD

**Issue by haozgit** [ollo69/ha-smartthinq-sensors#293]
1. Done installation from HACS
2. Rebooted HA
3. SmartThinq not showing up in Integration list
4. SmartThinq not showing as installed integration in HACS.
5. Look into HA logs. Logs indicating all custom components are successfully loaded but not for SmartThinq
![image](https://user-images.githubusercontent.com/74980013/155352583-7d8a33c8-e034-4374-9136-c09f620dd3cf.png)
![image](https://user-images.githubusercontent.com/74980013/155352686-dd21c90f-4394-46bd-9d1e-4de375eeaed3.png)

Need help on this. Thanks.

**Comment by ollo69** [comment]
Go to integration page and setup new integration. If not available refresh your browser cache.

**Comment by haozgit** [comment]
thanks for your prompt response.
The component is not showing as installed integration in HACS even after multiple installation attempts made.
and to note, i did refresh/clear my browser cache. integration still not showing up

**Comment by haozgit** [comment]
found this error
This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:597
Integration: HACS (documentation, issues)
First occurred: 11:51:54 PM (4 occurrences)
Last logged: 11:51:54 PM

A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/ollo69/ha-smartthinq-sensors/v0.12.10/custom_components/smartthinq_sensors/const.py, check the network on the host running Home Assistant
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/ollo69/ha-smartthinq-sensors/v0.12.10/custom_components/smartthinq_sensors/device_helpers.py, check the network on the host running Home Assistant
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/ollo69/ha-smartthinq-sensors/v0.12.10/custom_components/smartthinq_sensors/manifest.json, check the network on the host running Home Assistant
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/ollo69/ha-smartthinq-sensors/v0.12.10/custom_components/smartthinq_sensors/diagnostics.py, check the network on the host running Home Assistant

**Comment by haozgit** [comment]
fixed by doing manual git clone. thanks for the awesome work.
