### ISSUE TITLE
error update device status & reconnect frequently

### ISSUE THREAD

**Issue by cjh0817** [ollo69/ha-smartthinq-sensors#298]
**Describe the bug**
In HA log, updating device status error and reconnect repeatedly.

**Expected behavior**
Normal operation without updating errors

**Screenshots**
![image](https://user-images.githubusercontent.com/46054385/157864122-baf3a7e9-46e2-4b2a-9434-6574950e54dd.png)
![image](https://user-images.githubusercontent.com/46054385/157864202-11ff9846-76be-43d5-9290-a66bd03ad88a.png)
![image](https://user-images.githubusercontent.com/46054385/157864247-a638116c-851d-4b82-958e-36e416eb0cf9.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HA OS on Synology VMM
 - Home Assistant version installed: 2022.3.0
 - Component version installed:  0.12.10 (same issue on 0.12.8, not tested other version)
 - Last know working version: -
 - LG device type and model with issue:  ac / refrigerator / washer / dryer / styler
 - LG devices connected (list): ac / refrigerator / washer / dryer / styler

**Output of HA logs**
Paste the relavant output of the HA log here.

```
이 오류는 사용자 통합 구성요소에서 발생했습니다.

Logger: custom_components.smartthinq_sensors.wideq.device
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:221
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 20:01:15 (21 occurrences)
Last logged: 21:11:26

Unexpected error while updating device status
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 221, in refresh
    if not self._restart_monitor():
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 300, in _restart_monitor
    self.start()
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 308, in start
    self._work_id = self._client.session.monitor_start(self._device_id)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 777, in monitor_start
    res = self.post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 709, in post
    return lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 221, in lgedm2_post
    out = res.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <lgedmRoot><returnCd>9999</returnCd><returnMsg>기타오류</returnMsg></lgedmRoot>: 0
```

```
이 오류는 사용자 통합 구성요소에서 발생했습니다.

Logger: custom_components.smartthinq_sensors.wideq.device
Source: custom_components/smartthinq_sensors/wideq/device.py:203
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 20:01:16 (21 occurrences)
Last logged: 21:11:45

ThinQ client successfully reconnected
```

**Additional context**
I attached the related log file and all diagnostic information.
[halog_220310.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8231770/halog_220310.txt)

[ac_smartthinq_sensors-4d74505453f4a2df3d862bbd7cc63a21-aircon-55ad8c027eb2fc445acba60e5a3ba20f.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8231776/ac_smartthinq_sensors-4d74505453f4a2df3d862bbd7cc63a21-aircon-55ad8c027eb2fc445acba60e5a3ba20f.json.txt)
[DRYER_smartthinq_sensors-4d74505453f4a2df3d862bbd7cc63a21-의류건조기-b3f90380b5eddb85ce82ae6736015e0f.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8231777/DRYER_smartthinq_sensors-4d74505453f4a2df3d862bbd7cc63a21-.-b3f90380b5eddb85ce82ae6736015e0f.json.txt)
[REFRIGERATOR_smartthinq_sensors-4d74505453f4a2df3d862bbd7cc63a21-냉장고-29c5cee43ef2477a7875a09a21679a2c.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8231778/REFRIGERATOR_smartthinq_sensors-4d74505453f4a2df3d862bbd7cc63a21-.-29c5cee43ef2477a7875a09a21679a2c.json.txt)
[STYLER_smartthinq_sensors-4d74505453f4a2df3d862bbd7cc63a21-스타일러-9a28a44e3c07328786c08cfc9496c43c.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8231779/STYLER_smartthinq_sensors-4d74505453f4a2df3d862bbd7cc63a21-.-9a28a44e3c07328786c08cfc9496c43c.json.txt)
[WASHER_smartthinq_sensors-4d74505453f4a2df3d862bbd7cc63a21-세탁기-46ff7af95d6fa8a66f3e544c642e478e.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8231780/WASHER_smartthinq_sensors-4d74505453f4a2df3d862bbd7cc63a21-.-46ff7af95d6fa8a66f3e544c642e478e.json.txt)

**Comment by ollo69** [comment]
This is new, response coming in XML format instead of JSON!
If I well understand, problem is related to the WASHER device. Does the issue occurs also if washer is turned on?

**Comment by cjh0817** [comment]
Thank you for your reply.
same issue after washer is on.

**Comment by cjh0817** [comment]
I attatch the full log file again. (smartthinq_sensors debug)
[log_smartthinq_sensors_debug_220312.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8236965/log_smartthinq_sensors_debug_220312.txt)
 
and another problem here.
wash complate sensor never go to 'off' after 'on'
![image](https://user-images.githubusercontent.com/46054385/158002267-0bb1b5fe-8ed2-47b9-b86f-a53060a4ddb4.png)

**Comment by ollo69** [comment]
Wash complete sensor go to `off` when you start a new cycle, this is not an issue.

I just released a new version to try to handle this XML error, try it and let me know if fix the issue.

**Comment by cjh0817** [comment]
I deleted my integration, reinstalled new version.(via redirect url auth)

 But same error occurred.
```
이 오류는 사용자 통합 구성요소에서 발생했습니다.

Logger: custom_components.smartthinq_sensors.wideq.device
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:117
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 12:13:39 (12 occurrences)
Last logged: 12:49:40

Unexpected error while updating device status (device: d27dfde0-7149-11d3-80be-7440be2c47ed (AC))
Unexpected error while updating device status (device: 701b6da0-3782-11ec-b452-0051ed794b04 (WASHER))
Unexpected error while updating device status (device: be690140-7c24-11e9-b214-0051ed43543e (REFRIGERATOR))
Unexpected error while updating device status (device: 8b89a0e0-7c24-11e9-b406-0051ed6c76d5 (STYLER))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 229, in refresh
    state = self.poll(query_device)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 325, in poll
    return self._poll_v1()
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 337, in _poll_v1
    return self._client.session.monitor_poll(self._device_id, self._work_id)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 818, in monitor_poll
    res = self.post("rti/rtiResult", {"workList": work_list})["workList"]
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 727, in post
    return lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 239, in lgedm2_post
    out = _get_json_resp(res)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 117, in _get_json_resp
    return response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <lgedmRoot><returnCd>9999</returnCd><returnMsg>기타오류</returnMsg></lgedmRoot>: 0
```
```
이 오류는 사용자 통합 구성요소에서 발생했습니다.

Logger: custom_components.smartthinq_sensors.wideq.device
Source: custom_components/smartthinq_sensors/wideq/device.py:206
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 12:14:08 (12 occurrences)
Last logged: 12:50:08

ThinQ client successfully reconnected
```

ha log is here:
[log_smartthinq_sensors_debug_220313.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8238943/log_smartthinq_sensors_debug_220313.txt)

**Comment by ollo69** [comment]
I realize just now that you have installed the module `simplejson` that break the exception handling as reported in some threads that you can simply find on internet. I suppose that this was installed by some others custom integrations, could you try to remove these and check what happen?

**Comment by ollo69** [comment]
Anyway I just released a new version that should catch also the exception generated by module `simplejson`. Please try it and let me know if this fix the issue.

**Comment by cjh0817** [comment]
Thank you ollo69,

In 0.12.11.
As you said, I deactivated some custom integration&components, but the error occurred the same.
I don't know how to find it comfortably, I can't find using 'simplejson' custom components folder.
(all .py and .json file, search 'simplejson' with notepad++)
I'm just using the following integrations except for the ones that are default provided:
(I don't know if it will help you.)

[via HACS]
https://github.com/hacs/integration
https://github.com/staiji/citywaste_korea
https://github.com/GuGu927/damda_awair
https://github.com/ollo69/ha-smartthinq-sensors 

[via integrations]
https://www.home-assistant.io/integrations/broadlink
(https://github.com/home-assistant/core/tree/dev/homeassistant/components/broadlink)
https://www.home-assistant.io/integrations/smartthings
(https://github.com/home-assistant/core/tree/dev/homeassistant/components/smartthings)
https://www.home-assistant.io/integrations/withings
(https://github.com/home-assistant/core/tree/dev/homeassistant/components/withings)
https://www.home-assistant.io/integrations/xiaomi_aqara
(https://github.com/home-assistant/core/tree/dev/homeassistant/components/xiaomi_aqara)
https://www.home-assistant.io/integrations/xiaomi_miio
(https://github.com/home-assistant/core/tree/dev/homeassistant/components/xiaomi_miio)
https://www.home-assistant.io/integrations/mobile_app
(https://github.com/home-assistant/core/tree/dev/homeassistant/components/mobile_app)

[in custom_components folder manually]
https://github.com/fison67/HA-Edge-Connector


So, I just updated version 0.12.12.
No more error in "Logs" now.
In the full log, 'error decoding json response' still appears. But 'reconnected' log disappeared.
I will have to wait and see if there is any problem with actual use.
Do I  have to something?

[log_smartthinq_sensors_debug_220313_0.12.12.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8239483/log_smartthinq_sensors_debug_220313_0.12.12.txt)

**Comment by ollo69** [comment]
Well, now this is just a debug message that is managed, so you can just disable debug log and you will not see it anymore. What is important is that everything works properly and status are correctly updated for all devices. So let's wait some time for testing, if everything will be fine we can close the issue, otherwise report here any new problems. 

About disabling other integrations, does not make any difference now because module `simplejson` is installed (in the folder `/usr/local/lib/python3.9/site-packages/simplejson/` as reported in your log) and so is used by `requests`. You could try to uninstall it using `pip`  at command prompt, but I suggest to avoid this, at the end this is a module supported by requests itself so is should work well as default `json` python library. The only problem was to manage related exception, but with last release this seems be solved.

**Comment by cjh0817** [comment]
Thank you for your support.
I wait and see about 2~3 days.

**Comment by cjh0817** [comment]
everything works fine. thank you.
