### ISSUE TITLE
Not seeing SmartThinQ in Integrations

### ISSUE THREAD

**Issue by xinud190** [ollo69/ha-smartthinq-sensors#300]
Hi

Not sure what I'm doing wrong but I installed custom integration using HACS and rebooted:

![image](https://user-images.githubusercontent.com/54327371/158741830-98d3a6d7-2b6b-4838-be86-b6288a9641bf.png)

Unfortunately when I go to add Integration I'm not seeing it:

![image](https://user-images.githubusercontent.com/54327371/158741932-fc77e50e-df55-4c22-b306-0ad329cf40ea.png)

How do I get the integration working / visible?  All other integrations from HACS are working.

Thansk!

**Comment by joelnewswanger** [comment]
Same. Instructions for configuration are unhelpful.

**Comment by Gh61** [comment]
Try doing Ctrl + F5 on the integrations web page. (Deleting Browser cache.)
It helped in my case.

**Comment by ollo69** [comment]
I close this issue, not an integration problem.
