### ISSUE TITLE
Power usage

### ISSUE THREAD

**Issue by tacopiek** [ollo69/ha-smartthinq-sensors#301]
**Is your feature request related to a problem? Please describe.**
No, not a problem

**Describe the solution you'd like**
The LG Thinq app shows you the power usage for the washer and dryer per month, it would be nice that this information is available in this plugin.

**Describe alternatives you've considered**
Use a seperate power socket for each device and connect this to home assistant

**Additional context**
/

**Comment by realbuz** [comment]
Same here but for my portable AC

**Comment by KTibow** [comment]
@ollo69 given that we have the energy dashboard in HA now, would you be interested in implementing this, or would this not be interesting enough to spend your time on?

**Comment by ollo69** [comment]
Did you check in the payload (from diagnostics) if this power usage is available?
IMHO what you see in LG app are not real power usage but only a value based on the programs that you run in the months

**Comment by tacopiek** [comment]
Its good to know if its based on what it thinks or real power usage. Either way both types of information would be interesting to have available in HA. 
With the estimates you can still see the same graph in the app in your HA dashboard.

**Comment by ollo69** [comment]
But if this is a calculated value, it should be calculated in the same way inside HA based on template sensor and do not require any modification on integration!

**Comment by KTibow** [comment]
This might be relevant?
```json
            "EnergyMonitoring": {
              "valueMapping": [
                "soilWash",
                "temp",
                "spin"
              ],
              "powertable": {
                "1": 1,
                "2": 2,
                "3": 3,
                "4": 4,
                "5": 5,
                "6": 6
              }
            },
```
But I can't find anything with an actual power value.

**Comment by ollo69** [comment]
Attach here your diagnostic file, I will take a look when I will have some available time.

**Comment by KTibow** [comment]
@ollo69
[smartthinq_sensors-cb1cd37be597738d2bef24a02a049347-Top Load Washer-76d6605022d06c6224373b41e2d526cc.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8935911/smartthinq_sensors-cb1cd37be597738d2bef24a02a049347-Top.Load.Washer-76d6605022d06c6224373b41e2d526cc.json.txt)

**Comment by tacopiek** [comment]
any updates on this @KTibow @ollo69  ?
