### ISSUE TITLE
It's not possible to connect with Social Media account using the URL Method

### ISSUE THREAD

**Issue by MrHollowPS** [ollo69/ha-smartthinq-sensors#304]
**Describe the bug**
It seems that the redirect URL has changed when trying to access the Google Account from this URL: https://ro.m.lgaccount.com/spx/login/signIn?country=RO&language=ro-RO&client_id=LGAO221A02&svc_list=SVC202&svc_integrated=Y&show_thirdparty_login=LGE%2CMYLG%2CGGL%2CAMZ%2CFBK%2CAPPL&division=ha%3AT20&oauth2State=HIDDEN&show_select_country=N

When i press the Google Account button it redirects me to: https://ro.m.lgaccount.com/spx/login/signIn?returnCode=910&returnDescription=confirm_ggl and when i login with my account it says that i'm using my account in Romania and i'm trying to LOGIN to a GB server.

This account was already used to subscribe to Romania.
To use services of United Kingdom, please subscribe with a new account.

Both my account Google and LG account are registered to Romania.

Any ideas?

**Comment by MrHollowPS** [comment]
As a temporary work around, i've created a secondary account and shared my devices... however this is a stupid way to fix it.

**Comment by ollo69** [comment]
Social network account are not supported as explained in read me. I close this issue because there are no solution.
