### ISSUE TITLE
Smartthinq not found as integration

### ISSUE THREAD

**Issue by TheRealPorfavor** [ollo69/ha-smartthinq-sensors#308]
followed all the steps however the integration does not show up. 
Tried cache clearing and remove/download again.

what else could be done?

**Comment by gitdewino** [comment]
Was having the same problem and this [solution ](https://github.com/ollo69/ha-smartthinq-sensors/issues/300#issuecomment-1079269096)worked for me.

**Comment by BestGear-tech** [comment]
OP: - Did you get this fixed?

**Comment by TheRealPorfavor** [comment]
> OP: - Did you get this fixed?

Not a real solid fix found but after trying a different browser that I had never used before and the CTRL + F5 it showed up

**Comment by ollo69** [comment]
This issue is normally related to bad installation or browser cache issue, not to integration itself. I close this because there is nothing to fix.
