### ISSUE TITLE
('0110', 'error') 

### ISSUE THREAD

**Issue by tayanov** [ollo69/ha-smartthinq-sensors#31]
All was working with frige apiv1 and washer apiv2.
Today I recive error
('0110', 'error')
if need i show DEBUG log ....

**Comment by ollo69** [comment]
Yes please, provide debug log

**Comment by tayanov** [comment]
Oh. All ok. Russian LG change Privacy Policy.
When i remove and add integration on URL respond need be APPLY new Privacy Policy.
Then i see blank page. Take respond URL and all now work.

Close pls issue
