### ISSUE TITLE
Can't Configure Integration from Web GUI

### ISSUE THREAD

**Issue by BestGear-tech** [ollo69/ha-smartthinq-sensors#313]
Hi Guys

I have installed the SmartThinQ LGE Sensors integration on the HA instance below:

Version core-2022.4.7
Version supervisor-2022.04.0
Operating System Home Assistant OS 7.6

HACS details:
Integration Version 1.24.5
Frontend version: | 20220401183545

SmartThinQ LGE Sensors version v0.12.11

**Expected behavior**
When the integration is installed under HACS there is no config "wizard" or popup to enter the LG credentials etc - even after reboot post installation.

I can only *assume" that "Update information" is used to config the module - but when I click on it - it does nothing - and no errors are visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/74876478/166517237-b5c3e142-45f7-4d2d-9bda-d20c1a7d8dcc.png)

**Output of HA logs**
Paste the relavant output of the HA log here.

Not sure if these are relevant:

2022-05-03 11:12:59 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-03 19:19:27 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /core/info - System is not ready with state: setup
2022-05-03 19:19:27 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /supervisor/info - System is not ready with state: setup

Many thanks in advance for any help!

**Comment by ollo69** [comment]
In HACS tab you cannot configure integration, is just to install and upgrade.
To configure integration you must select `Configuration`->`Device and Service` and that press `+` button on botton right to configure new integration.

**Comment by BestGear-tech** [comment]
> In HACS tab you cannot configure integration, is just to install and upgrade. To configure integration you must select `Configuration`->`Device and Service` and that press `+` button on botton right to configure new integration.

THANK YOU!

I will go setup now. I could not find that missing nugget anywhere.

Much appreciated.

**Comment by ollo69** [comment]
I close this issue.
