### ISSUE TITLE
[Feature Request] Dehumidifier support

### ISSUE THREAD

**Issue by rurufio** [ollo69/ha-smartthinq-sensors#318]
**Is your feature request related to a problem? Please describe.**
LG Dehumidifier isnt supported

**Describe the solution you'd like**
Include LG Dehumidifier support

**Comment by mountain0320** [comment]
Please

**Comment by kksligh** [comment]
Pretty please

**Comment by llin95** [comment]
yeah, please add this feature.

**Comment by ollo69** [comment]
All, please generate diagnostic from integration and attach diagnostic file here, so that I can analyze the Dehumidifier JSON detail.

**Comment by llin95** [comment]
> All, please generate diagnostic from integration and attach diagnostic file here, so that I can analyze the Dehumidifier JSON detail.

attached.
[config_entry-smartthinq_sensors-e9721a40eeae2fa1d832e7ae19b36971.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8749606/config_entry-smartthinq_sensors-e9721a40eeae2fa1d832e7ae19b36971.json.txt)

**Comment by ollo69** [comment]
Dehumidifier support is now available with last release. Please provide yours feed-back.

**Comment by llin95** [comment]
> Dehumidifier support is now available with last release. Please provide yours feed-back.

It's working, thanks!
But the energy monitor info is not able to get through HA.

**Comment by ollo69** [comment]
I don't see energy information in the payload that I have, so I cannot provide this data.

**Comment by JvdMaat** [comment]
Dehumidifier is working well, and I can set the target level and see the current humidity level. However the current level does not update unless I open the ThinQ app on phone, and then it updates the info on the phone, and within a minute also updates in HA.
Is there a way to force the dehumidifier to give an update to ThinQ (and thus get it in HA)?
I'm assuming by opening the ThinQ app on the phone, the app is sending a request to the dehumidifier to update the humidity sensor to ThinQ. 

Secondly, and this may be a reach. By going to Smart Diagnostic in the ThinQ app, it is supposedly checking on a few things (Temperature Senser (sic), Voltage, Fan Motor, etc.). It just marks them with a checkmark (No idea if any of those sensors are actually installed). But could those be exposed somewhere?

**Comment by JvdMaat** [comment]
I just read through that, and found out you need iOS to do it. Which won't work for me, I only have access to Android phones.
So we'll need someone that has a humidifier/dehumidifier and an iPhone (and ability to run mitmproxy to grab commands)

**Comment by ollo69** [comment]
> Only display humidity, no any control panel in HA

Download and attach integration diagnostics

**Comment by ToddTsao** [comment]
FYI
attached.
[config_entry-smartthinq_sensors-e9721a40eeae2fa1d832e7ae19b36971.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8778857/config_entry-smartthinq_sensors-e9721a40eeae2fa1d832e7ae19b36971.json.txt)

**Comment by ollo69** [comment]
@ToddTsao,

you need to upgrade integration to v0.21.0, as I see in Diagnostic you are still using v0.20.2.
Upgrade integration, if still have problem attach here diagnostic extracted using last version.

**Comment by ToddTsao** [comment]
I have update the version. But, the result is the same as before.
      "version": "0.21.0",
      "requirements": [
        "pycountry>=20.7.3",
        "xmltodict>=0.12.0",
        "chardet>=4.0.0

[config_entry-smartthinq_sensors-d4d50679c3a4be4551f5dc35448a3bdb.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8779110/config_entry-smartthinq_sensors-d4d50679c3a4be4551f5dc35448a3bdb.json.txt)
"

**Comment by ollo69** [comment]
@ToddTsao,

please try with last release and let me know if now it works for you.

**Comment by llin95** [comment]
> I don't see energy information in the payload that I have, so I cannot provide this data.
Also attached the lastest config file, I saw the energy related setting is there.
[config_entry-smartthinq_sensors-e9721a40eeae2fa1d832e7ae19b36971.json (1).txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8782507/config_entry-smartthinq_sensors-e9721a40eeae2fa1d832e7ae19b36971.json.1.txt)

**Comment by ollo69** [comment]
> But, HA show some error message after turn on or off.

Please try again with `v0.21.2`

**Comment by ToddTsao** [comment]
Dehumidifier is working well.

**Comment by ollo69** [comment]
> Also attached the lastest config file, I saw the energy related setting is there.

@llin95 

I don't see any energy information in snapshot / status in attached diagnostic file.

**Comment by ollo69** [comment]
I close this FR. Is there are new problem o request related to this type of device, open a new issue.
