### ISSUE TITLE
[Feature Request]  Add support for water boiler LG WH20S F5

### ISSUE THREAD

**Issue by Emile86** [ollo69/ha-smartthinq-sensors#328]
Can you please add support for LG WH20S F5 water boiler?

**Comment by ollo69** [comment]
Attach diagnostic file from integration

**Comment by Emile86** [comment]
You was faster than i was able to upload :)
[config_entry-smartthinq_sensors-edb05f91053a13d91e47eaea28880547.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8757633/config_entry-smartthinq_sensors-edb05f91053a13d91e47eaea28880547.json.txt)

Thank you!

**Comment by ollo69** [comment]
Do not expect same speed in implementation 😉

**Comment by Emile86** [comment]
Of course not. Take your time
Bought you some coffee ;)

**Comment by Dutchy-79** [comment]
Just noticed this one, yesterday I requested support for his bigger brother the LG WH27S.

If I need to get you some information to add them to the list let me know.

**Comment by Emile86** [comment]
It's in fact the same hardware beside water capacity. 
@ollo69 is there any news about adding this boilers?

**Comment by ollo69** [comment]
Add support for new devices always require time, that at this moment I don't have. Please be patient, this integration have many feature requests, and this is not my main jobs 👍

**Comment by Dutchy-79** [comment]
I fully understand, just noticed the log and after scrolled down there is a "unsupported device" that contains the data from the boiler.

Don't know if you need it

I did setup a vacation date because I'm working on the bathroom so we don't use the boiler. Maybe also helpful for implementing. 

`
    "unsupported_devices": {
      "WATER_HEATER": [
        {
          "appType": "NUTS",
          "modelCountryCode": "WW",
          "countryCode": "NL",
          "modelName": "WHT_056905_WW",
          "deviceType": 406,
          "deviceCode": "AI07",
          "alias": "Boiler",
          "deviceId": "626d543b-75bd-1ac7-ba1f-4cbce90a62a2",
          "fwVer": "",
          "imageFileName": "",
          "ssid": "**REDACTED**",
          "softapId": "",
          "softapPass": "",
          "macAddress": "",
          "networkType": "02",
          "timezoneCode": "Europe/Amsterdam",
          "timezoneCodeAlias": "Europe/Amsterdam",
          "utcOffset": 1,
          "utcOffsetDisplay": "+01:00",
          "dstOffset": 2,
          "dstOffsetDisplay": "+02:00",
          "curOffset": 2,
          "curOffsetDisplay": "+02:00",
          "sdsGuide": "{\"deviceCode\":\"AI07\"}",
          "newRegYn": "N",
          "remoteControlType": "",
          "userNo": "**REDACTED**",
          "tftYn": "N",
          "modelJsonVer": 2.01,
          "modelJsonUri": "https://objectcontent.lgthinq.com/fb8be8af-3152-436d-9b3d-a15a68c48712?hdnts=exp=1721390098~hmac=d113f89febb8db9a550541197c27396905ac4f605951a3a1e5ea1aa950a30bcc",
          "appModuleVer": 1.03,
          "appModuleUri": "https://objectcontent.lgthinq.com/375b941d-43fa-4d3e-babf-42e259975fc2?hdnts=exp=1665034455~hmac=bb0184bdeddccfdde2826eabf335c990b544b7663769dff55ad9fe02390009f3",
          "appRestartYn": "Y",
          "appModuleSize": 5511058,
          "langPackProductTypeVer": 6.5,
          "langPackProductTypeUri": "https://objectcontent.lgthinq.com/7528f0a0-228c-44e7-aa35-596a8f391985?hdnts=exp=1714106738~hmac=aa0922f381558592df8e5473dae290df25a866401cef3ac834ff0ca9c39a4d2f",
          "deviceState": "E",
          "snapshot": {
            "airState.reservation.vacationStopDate": 20220805.0,
            "static": {
              "deviceType": "406",
              "countryCode": "NL"
            },
            "airState.tempState.hotWaterCurrent": 30.0,
            "airState.tempState.unit": 0.0,
            "airState.diagCode": 0.0,
            "airState.miscFuncState.extraOp": 0.0,
            "airState.tempState.hotWaterTarget": 50.0,
            "mid": 995201299.0,
            "airState.energy.accumulated": 0.0,
            "airState.energy.onCurrent": 50.0,
            "airState.quality.sensorMon": 0.0,
            "airState.energy.accumulatedTime": 300.0,
            "airState.reservation.vacationStartDate": 20220730.0,
            "airState.operation": 1.0,
            "meta": {
              "allDeviceInfoUpdate": false,
              "messageId": "JA2OFMjzQXSB0225u8SV_Q"
            },
            "online": true,
            "airState.opMode": 28.0,
            "airState.filterMngStates.maxTime": 4320.0,
            "airState.filterMngStates.useTime": 4041.0,
            "airState.preHeat.schedule": 0.0,
            "timestamp": 1659324931718.0
          },
          "online": true,
          "platformType": "thinq2",
          "area": 251608,
          "regDt": 20220720135438.0,
          "blackboxYn": "Y",
          "modelProtocol": "STANDARD",
          "order": 0,
          "drServiceYn": "N",
          "fwInfoList": [
            {
              "checksum": "00000702",
              "order": 2.0,
              "partNumber": "SAA41330702"
            },
            {
              "checksum": "00000F3B",
              "order": 1.0,
              "partNumber": "SAA37643267"
            }
          ],
          "modemInfo": {
            "appVersion": "clip_hna_v1.9.099",
            "modelName": "WHT_056905_WW",
            "modemType": "RTK_RTL8711am",
            "ruleEngine": "y"
          },
          "guideTypeYn": "Y",
          "guideType": "WHT_TYPE1",
          "regDtUtc": "20220720115438",
          "regIndex": 0,
          "groupableYn": "N",
          "controllableYn": "N",
          "combinedProductYn": "N",
          "masterYn": "Y",
          "pccModelYn": "N",
          "sdsPid": {
            "sds4": "",
            "sds3": "",
            "sds2": "",
            "sds1": ""
          },
          "autoOrderYn": "N",
          "initDevice": false,
          "existsEntryPopup": "N",
          "tclcount": 0
`

**Comment by Dutchy-79** [comment]
> > I fully understand, just noticed the log and after scrolled down there is a "unsupported device" that contains the data from the boiler.
> 
> Always useful. Please if possible attach the diagnostic file instead of copying the text👍

Can't add it here, I will add it to the topic I created.

**Comment by Emile86** [comment]
@ollo69 is integration abounded or do you have no time for it now?

**Comment by ollo69** [comment]
All, I'm very busy on this period, but I will work on this as soon as possible.

**Comment by ollo69** [comment]
Water Heater device should now be supported by last release. I close this thread because is the same of #332, please move there and provide feed-back.
