### ISSUE TITLE
Support Hot Water control for Air to Water Heat Pump

### ISSUE THREAD

**Issue by dukicn** [ollo69/ha-smartthinq-sensors#332]
**Is your feature request related to a problem? Please describe.**
I use this add on to control my LG Air To Water Heat Pump HM161M U33. Even though it doesn't specify it as a supported device, add-on is fully functional for heating and cooling. I can turn on and off the heat pump, adjust the temperature and the mode to Heat / Cool / Auto. However, heat pump is also used for hot water, but this plugin doesn't provide any option to control hot water (neither turn on / off or temperature control). Sensor does show the hot water temperature, but doesn't allow any way to control it.

**Describe the solution you'd like**
I would like this plugin to support turning on and off hot water as well as adjusting temperature for the hot water. Ideally, it would create two climate devices, one for heating / cooling and another one for hot water. 

**Describe alternatives you've considered**
No alternatives that I couldn't find to control the hot water except using native LG ThinQ application. However, that doesn't allow any control outside of app.

**Additional context**
Seems that there is an existing PR for this support but it hasn't been merged with main: https://github.com/ollo69/ha-smartthinq-sensors/pull/268

**Comment by kepath** [comment]
+1 for this to enable me to control the hot water temperature on my LG Therma V

**Comment by dukicn** [comment]
When can we expect to merge https://github.com/ollo69/ha-smartthinq-sensors/pull/268 with the main branch? This PR seems to contain the changes requests in this open issue.

Thanks

**Comment by ollo69** [comment]
That PR #268 is very old, need rebase and also some improvement. There are several request about this feature, but not really clear how heat-pump should work. What can you currently do with integration? A basic support should be already in place, Can you please attach integration diagnostic so that I can take a look to device payload and model info?

**Comment by FAB1150** [comment]
I come from #386, where another person attached the integration diagnostics, at the time I don't have HA up and running as the server it was on decided to k-ll itself, but when it was on I don't remember being able to do anything with the water heater (Therma V WH20S).

About the heater, the WH20S and WH27S are the same thing, only thing that differs is the water tank size. From a hypothetical integration you should be able to set water temperature, and mode of the heater (heatpump only / turbo / Auto / holiday). It should be able to receive the water temperature reading and power consumption as sensors, and

**Comment by ollo69** [comment]
Because I also need to check model info to see available options, I need complete diagnostic file and not only the payload. The problem with LG is that they have multiple model with different features, and I remember that in the past some basic ctrl for awhp was already in place. I would not break what is already running.

**Comment by Xnyle** [comment]
ThinQ connected and providing data, yet no devices appear.

This is what I get from the logs. I redacted all tokens / ids.

Hope with this info, integration / mapping should be pretty straightforward.

    "unsupported_devices": {
      "WATER_HEATER": [
        {
          "appType": "NUTS",
          "modelCountryCode": "WW",
          "countryCode": "DE",
          "modelName": "WHT_056905_WW",
          "deviceType": 406,
          "deviceCode": "AI07",
          "alias": "XXXXXXXX",
          "deviceId": "XXXXXXXX",
          "fwVer": "",
          "imageFileName": "",
          "ssid": "XXXXXXXX",
          "softapId": "",
          "softapPass": "",
          "macAddress": "",
          "networkType": "02",
          "timezoneCode": "Europe/Berlin",
          "timezoneCodeAlias": "Europe/Berlin",
          "utcOffset": 1,
          "utcOffsetDisplay": "+01:00",
          "dstOffset": 2,
          "dstOffsetDisplay": "+02:00",
          "curOffset": 2,
          "curOffsetDisplay": "+02:00",
          "sdsGuide": "{\"deviceCode\":\"AI07\"}",
          "newRegYn": "N",
          "remoteControlType": "",
          "userNo": "**REDACTED**",
          "tftYn": "N",
          "modelJsonVer": 2.01,
          "modelJsonUri": "XXXXXXXX",
          "appModuleVer": 1.03,
          "appModuleUri": "XXXXXXXX",
          "appRestartYn": "Y",
          "appModuleSize": 5511058,
          "langPackProductTypeVer": 6.5,
          "langPackProductTypeUri": "XXXXXXXX",
          "deviceState": "E",
          "snapshot": {
            "fwUpgradeInfo": {
              "upgSched": {
                "upgUtc": "0",
                "cmd": "none"
              }
            },
            "static": {
              "deviceType": "406",
              "countryCode": "DE"
            },
            "airState.tempState.hotWaterCurrent": 50.0,
            "airState.tempState.unit": 0.0,
            "airState.diagCode": 0.0,
            "airState.miscFuncState.extraOp": 0.0,
            "airState.tempState.hotWaterTarget": 55.0,
            "mid": 64831710.0,
            "airState.energy.accumulated": 26.0,
            "airState.energy.onCurrent": 50.0,
            "airState.quality.sensorMon": 0.0,
            "airState.energy.accumulatedTime": 344.0,
            "airState.operation": 1.0,
            "meta": {
              "allDeviceInfoUpdate": false,
              "messageId": "XXXXXXXX"
            },
            "online": true,
            "airState.opMode": 26.0,
            "airState.filterMngStates.maxTime": 4320.0,
            "airState.filterMngStates.useTime": 4278.0,
            "airState.preHeat.schedule": 0.0,
            "timestamp": 1664788881211.0
          },
          "online": true,
          "platformType": "thinq2",
          "area": 167921,
          "regDt": 20221002172222.0,
          "blackboxYn": "Y",
          "modelProtocol": "STANDARD",
          "order": 0,
          "drServiceYn": "N", 
          "guideTypeYn": "Y",
          "guideType": "WHT_TYPE1",
          "regDtUtc": "20221002152222",
          "regIndex": 0,
          "groupableYn": "N",
          "controllableYn": "N",
          "combinedProductYn": "N",
          "masterYn": "Y",
          "pccModelYn": "N",
          "sdsPid": {
            "sds4": "",
            "sds3": "",
            "sds2": "",
            "sds1": ""
          },
          "autoOrderYn": "N",
          "initDevice": false,
          "existsEntryPopup": "N",
          "tclcount": 0
        }
      ]

**Comment by Xnyle** [comment]
I have no idea how to get that, a bit of context would be nice...

**Comment by ollo69** [comment]
Just go to integration page and select "download diagnostic"

![image](https://user-images.githubusercontent.com/60491700/205588591-771b13c0-08cf-406d-9907-40d5aadf21dd.png)

**Comment by Xnyle** [comment]
See above that's exactly what I posted minus personalized data / tokens that were still in there.

**Comment by ollo69** [comment]
> See above that's exactly what I posted minus personalized data / tokens that were still in there.

That's not. In diagnostic there is the model info, not in what you posted (this is just the payload). Sensible data in diagnostic is redacted!

**Comment by Xnyle** [comment]
No it isn't, there are tokens linked to my account. If you tell me what json path you think is missing I can provide that part as well but not the whole file and not with tokens.

**Comment by ollo69** [comment]
Can you please tell me which tokens are inside the file? If this are sensible information I will redact that. What I need is the `model info`, a very long JSON that describe the device

**Comment by ollo69** [comment]
You can also download the specific file opening in a browser the URL in the field `modelJsonUri` (that you redacted).

**Comment by Xnyle** [comment]
Internet of s**t at it's best, with korean characters and everything... But ok, I guess no personal data in there.

[modelinfo.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10152431/modelinfo.json.txt)

**Comment by ollo69** [comment]
As I understand there are 2 different situation:

- device identified as AC (type 401) with also heat-pump functions (this is probably what PR #268 was trying to address), but I think should use HA Water Heater Entity for second part so need to be reviewed
- device identified as AWHP (type 406). This need to be managed as new device, PR #268 will not help

@dukicn,

I suppose that you are in first case, can you please also attach the payload extracted from diagnostic as @Xnyle did (clean up sensible data before if any)

**Comment by dukicn** [comment]
> As I understand there are 2 different situation:
> 
> * device identified as AC (type 401) with also heat-pump functions (this is probably what PR [AWHP improvements #268](https://github.com/ollo69/ha-smartthinq-sensors/pull/268) was trying to address), but I think should use HA Water Heater Entity for second part so need to be reviewed
> * device identified as AWHP (type 406). This need to be managed as new device, PR [AWHP improvements #268](https://github.com/ollo69/ha-smartthinq-sensors/pull/268) will not help
> 
> @dukicn,
> 
> I suppose that you are in first case, can you please also attach the payload extracted from diagnostic as @Xnyle did (clean up sensible data before if any)

@ollo69, I attached the whole model_info json path from diagnostics in the previous post. Do you need additional path?

Thanks

**Comment by ollo69** [comment]
Model info is ok, but do not contain payload. I also need that to compare available feature (model info) and exposed data (payload). Payload is what @Xnyle put [here](https://github.com/ollo69/ha-smartthinq-sensors/issues/332#issuecomment-1336827240) and is also inside diagnostics.

**Comment by dukicn** [comment]
@ollo69 , here is the device info payload. Please let me know in case you need anything else.

Thanks

[device_info.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10153231/device_info.json.txt)

**Comment by ollo69** [comment]
@dukicn,

could you please provide some more details on how your device works? Looking at file provided, I see an information that seems related to working mode (`awhpTempSwitch`). This could be AIR or WATER. Does this means that you have to switch from one mode to another? Are 2 alternative modes that can be run not at the same time? There are also others specific options that could be set (I assume from LG app)

**Comment by Xnyle** [comment]
Not sure it that helps, but the air to water device (W270S) basically has target temp, current temp and working mode where you can switch between vacation, heatpump, auto and turbo (each decreasing efficiency while increasing recovery time) and then there is some other settings like timers which i never used. Additionally at the device panel itself you can en- or disable anti legionella mode which you can't change in the app.

**Comment by ollo69** [comment]
Thanks @Xnyle, but I think (at least suppose looking at the files) that @dukicn device is different because it can probably work both as AC and AWHP. I would understand how this 2 modes can coexist. Integration should not send control command not supported in specific modes.
May be a user manual (if is not 500 pages to read) could help.

**Comment by dukicn** [comment]
@ollo69 , the system is air-to-water heat pump. It takes air from the outside and uses it to heat or cool the water. Heat pump has two independent circuits. One is used for heating or cooling (dependent on the mode - cool or heat - it either heats or cools the water). Other circle is just for hot water and is used to heat the water for the household. Control for the heat pump (both in the app or on the unit itself) enable separate control for both circuits. On the Heat/Cool screen, you can turn the unit on or off, select hot or cool mode, see the current temperature and define the target setpoint. On the Hot water screen, you can turn it on or off, see the temperature and select the target setpoint. There are some other things like scheduling, holiday mode, quick heat mode, etc. but they are not important. Modes for heating / cooling and hot water are independent (meaning, you can turn on hot water without Heat / Cool and vice versa, you can turn on Heat or Cool without Hot Water). Let me know in case you have any additional question.

You can take a look at basic and short instructions [here](https://www.manualslib.com/manual/1511067/Lg-Therma-V-Series.html#manual).

**Comment by ollo69** [comment]
So, just to understand, what is missing in your case is just the part related to the hot-water for household, correct?

**Comment by dukicn** [comment]
Yes, that is correct. I can fully control the heat / cool part, but have no control for the hot water part.

**Comment by Svrbinek** [comment]
Hi, I have a LG WP WH27s heat pump for water heating, so if possible I can help with testing. I am not so much concerned with the control as with the data from the water temperature, because the application on the phone does not have a graph, so I do not know how quickly it cools, how quickly it heats from how many degrees to how many, etc. I will be very happy if the integration is successful. Good luck!

**Comment by ollo69** [comment]
Water Heater device should now be supported by last release. Please provide feed-back and possible issue.

**Comment by dukicn** [comment]
I did a quick check and it works. Tried the basic functionality (turn on/off and adjust the temperature) and it worked without any issues. I will play with automation and let you know if I discover any issues. Entity is shown as water_heater. I noticed only one strange thing. Allowed modes for water heater is Off and Heat Pump. It would make more sense to just have Off and On (or Heat).

Thanks a lot for adding this, this is exactly what I need.

**Comment by Dutchy-79** [comment]
Ty very much for adding this.

I do notice that the energy sensor aren't there yet?
![Screenshot_20221209_132233_Docs Viewer](https://user-images.githubusercontent.com/22749572/206702143-4f17754c-2aec-425f-94e1-10a1a4df36ee.png)
![Screenshot_20221209_132556_Home Assistant](https://user-images.githubusercontent.com/22749572/206702191-309d502f-8cdf-44e1-a695-17294e5e51b5.png)

**Comment by ollo69** [comment]
> Allowed modes for water heater is Off and Heat Pump. It would make more sense to just have Off and On (or Heat).

As per HA documentation, the allowed operation modes are the states specified in the base component and implementations of the `water_heater` component cannot differ. You can find more details [here](https://developers.home-assistant.io/docs/core/entity/water-heater)

**Comment by ollo69** [comment]
> I do notice that the energy sensor aren't there yet?

Energy sensor in LG device is complex story, not always energy data is updated in the payload. I can add the sensor, but the risk is that it will always provide the same value. Please make some test, turning your boiler on and checking in diagnostic if `airState.energy.onCurrent` changes. If yes means that this value is updated and add the related HA sensor make sense.

**Comment by Dutchy-79** [comment]
Diagnostics probably update slow, I use HA to change setpoint from 52 to 60 which made the boiler startup though when downloading diagnostic it still says 52

![Screenshot_20221209_141624_Docs Viewer](https://user-images.githubusercontent.com/22749572/206711360-31da3de5-5235-47c4-bb81-b270c12f8b2a.png)
![Screenshot_20221209_141818_Home Assistant](https://user-images.githubusercontent.com/22749572/206711375-5d1cfcfa-cbc7-4510-91de-a94fab20dbd2.png)

**Comment by Xnyle** [comment]
> > I do notice that the energy sensor aren't there yet?
> 
> Energy sensor in LG device is complex story, not always energy data is updated in the payload. I can add the sensor, but the risk is that it will always provide the same value. Please make some test, turning your boiler on and checking in diagnostic if `airState.energy.onCurrent` changes. If yes means that this value is updated and add the related HA sensor make sense.

It's internet of shit anyways, this thing even has an esp controller inside, we could probably flash esphome on it and make it a lot more useful, send it's data directly to mqtt server of own choice and not phone home. But I'm not at that  frustration-level yet, risking to brick a 3k €/$ device.

**Comment by Xnyle** [comment]
Feedback:
Off/Away Mode doesn't work as expected for WH27S

If I change to other modes than Off, They also change at the device and Away mode automatically disables
If I change Mode from any other mode to Off, nothing happens.
If I enable Away Mode, It changes to Vacation at the device and the App and I also get Off Mode.

So this whole OFF/Away mode is kind of crooked atm, you can get all modes you want though.

**Comment by ollo69** [comment]
> Diagnostics probably update slow, I use HA to change setpoint from 52 to 60 which made the boiler startup though when downloading diagnostic it still says 52

Diagnostic should just capture data when you extract. Just download diagnostic every 5 minutes when you know that your boiler is working and check the value. If it is always = 50, that means that the value is not updated. For AC I use a special command to update that value, I could try to enable it also for these devices but I'm not sure that will work in the same way. In case that your tests fail  I can release a beta version with this feature enabled.

**Comment by ollo69** [comment]
> Off/Away Mode doesn't work as expected for WH27S

Because HA [water_heater](https://developers.home-assistant.io/docs/core/entity/water-heater) entity have some logic that must be respected, I mapped LG `Vacation Mode` to HA `Away Mode`.
So your reported behavior was exactly what I was expecting, but if you have some other suggestion that respect HA rules I can take it in consideration.

**Comment by Dutchy-79** [comment]
> > Diagnostics probably update slow, I use HA to change setpoint from 52 to 60 which made the boiler startup though when downloading diagnostic it still says 52
> 
> Diagnostic should just capture data when you extract. Just download diagnostic every 5 minutes when you know that your boiler is working and check the value. If it is always = 50, that means that the value is not updated. For AC I use a special command to update that value, I could try to enable it also for these devices but I'm not sure that will work in the same way. In case that your tests fail I can release a beta version with this feature enabled.

Stays on 50 for a while now so probably not working atm.

**Comment by Dutchy-79** [comment]
Temperature graph does not update while state does.
![Screenshot_20221210_074011_Home Assistant](https://user-images.githubusercontent.com/22749572/206835983-edb60d97-cb2a-4916-986e-e4b48c010710.png)
![Screenshot_20221210_074048_Home Assistant](https://user-images.githubusercontent.com/22749572/206835987-f3a48284-ab99-4743-b9c7-44367c1b916c.png)

**Comment by ollo69** [comment]
> Temperature graph does not update while state does.

Can you better explain what you mean? Do you have some error in the logs? In case can you post here together with diagnostics?
Thanks.

**Comment by Dutchy-79** [comment]
No error, I mean that the graph stays stuck on a certain temperature (46.5 now) while the attribute does update correctly.

![Screenshot_20221210_142113_Home Assistant](https://user-images.githubusercontent.com/22749572/206857667-d26d1ccf-8cb2-4d72-b383-a81bbb64708c.png)
![Screenshot_20221210_142144_Home Assistant](https://user-images.githubusercontent.com/22749572/206857670-6a05a5a7-0f09-4669-bfa9-789ececc7fb1.png)
![Screenshot_20221210_142409_Home Assistant](https://user-images.githubusercontent.com/22749572/206857671-27bfb4df-177f-4ecc-a793-c11159ebd1ed.png)

**Comment by Dutchy-79** [comment]
https://files.fm/u/5y3xgm767

**Comment by ollo69** [comment]
I'm really convinced that I'm doing something wrong here. I download water heater manual, if I well understand there is no way to totally turn off the device from console or mobile app, just exist a vacation mode for this. Because I'm sending a command to the device to turn it off/on, probably this command is wrong and unnecessary.  Could someone confirm that there are not on/off option in water heater device but only 4 possible operation modes?

**Comment by Dutchy-79** [comment]
![Screenshot_20221210_153317_LG ThinQ](https://user-images.githubusercontent.com/22749572/206860520-d3215e61-5ca9-474d-be97-a19b6cd1722b.png)

Heat pump
Auto
Turbo
Vacation

Those are the options from the app

**Comment by Svrbinek** [comment]
How did you manage to add the WH27S boiler to the LG smartthing? I still can't see anything. Either I'm doing something wrong or I don't know.

**Comment by Dutchy-79** [comment]
> How did you manage to add the WH27S boiler to the LG smartthing? I still can't see anything. Either I'm doing something wrong or I don't know.

Did you update to version 0.25?

**Comment by Dutchy-79** [comment]
Energy seems to work well. I have a S0 meter reading with a ESP01 and now the one you created. The S0 is a bit lower but the one from the app is more like yours so I'm happy with that.

The S0 meter is a cheap Chinese one.
![Screenshot_20221211_105353_Home Assistant](https://user-images.githubusercontent.com/22749572/206897150-f8793827-c6f0-4f3c-892f-fbff93fc75bd.png)

**Comment by ollo69** [comment]
I close this FR because support for Water-Heater should be completed. If there are new requests or issues, please open a new thread.

**Comment by HaD3sZ** [comment]
Hi

I have a LG Therma V (AWHP_019101_WW-SAC_AWHP (AC)  Fw: 2.6.0_RTOS_3K) heat pump. The device works well, but the water heater (boiler) not visible (unsupported_devices). I attached the diagnose file. 
[smartthinq_sensors-700654ba51e9ab1d0cf4014e8ab3f5cd-Levegő-víz hőszivattyú-0a2c882661454b401994bc16dba3c9eb.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/11743600/smartthinq_sensors-700654ba51e9ab1d0cf4014e8ab3f5cd-Levego-viz.hoszivattyu-0a2c882661454b401994bc16dba3c9eb.json.txt)
Have you any idea, what I have to do?
