### ISSUE TITLE
 Connection to ThinQ failed. ThinQ API error

### ISSUE THREAD

**Issue by taylormia** [ollo69/ha-smartthinq-sensors#335]
**Describe the bug**
Several disconnect/reconnect warning messages in the log. 

**Environment details:**
 - HA 2022.5.5 on Docker
 - Component version 0.22.0
 - WM5000HVA - Washer
 - DLEX5000V - Dryer

**Output of HA logs**
`today at 8:55:05 PM 2022-06-02 20:55:05 WARNING (MainThread) [custom_components.smartthinq_sensors.wideq.device] Connection to ThinQ failed. ThinQ API error (device: 065e19d0-a3ee-19a3-b5ad-80a589c275ad (WASHER))
today at 8:55:35 PM 2022-06-02 20:55:35 WARNING (MainThread) [custom_components.smartthinq_sensors.wideq.device] ThinQ client successfully reconnected
today at 8:55:37 PM 2022-06-02 20:55:37 WARNING (MainThread) [custom_components.smartthinq_sensors.wideq.device] Connection to ThinQ failed. ThinQ API error (device: 7c129db0-f9ad-195f-b031-74c63b1a7031 (DRYER))
today at 8:56:07 PM 2022-06-02 20:56:07 WARNING (MainThread) [custom_components.smartthinq_sensors.wideq.device] ThinQ client successfully reconnected`

**Additional context**
The washer and dryer are turned off. Seems to happen when the LG ThinQ app on my Android phone has been closed for a while. When I open the app the warning messages stop.

**Comment by mountain0320** [comment]
自行安裝整合產生錯誤。

Logger: custom_components.smartthinq_sensors.wideq.device
Source: custom_components/smartthinq_sensors/wideq/device.py:98
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 22:07:58 (2 occurrences)
Last logged: 22:56:36

Device 0e9e2c9a-2972-1d52-b83b-24e853c17ba8 (DEHUMIDIFIER): Connection to ThinQ failed. Network connection error
Device d27c2920-7149-11d3-80b2-7440be7486a0 (AIR_PURIFIER): Connection to ThinQ failed. Timeout error

**Comment by ollo69** [comment]
This is quite old issue, but I suppose was just related to ThinQ cloud issue, Can we close this?

**Comment by taylormia** [comment]
I still get these errors now and then but not constantly like earlier. Will close for now. Thanks.
