### ISSUE TITLE
Washer/Dryer time now has "seconds place" in time, but appliances don't measure that granularly

### ISSUE THREAD

**Issue by mattgahs** [ollo69/ha-smartthinq-sensors#337]
Hi, 

Some versions ago (I'm not sure when), this integration added an additional place in the Washer/Dryer times, so instead of being HH:MM, it's now HH:MM:SS - for instance, a 70-minute cycle used to be 1:10, now it's 1:10:00. The seconds never change, and don't really have a purpose. 

This seems to be coded in the attributes of the integration, see screenshot. Any way to change this back?

<img width="404" alt="Screen Shot 2022-06-05 at 8 41 39 AM" src="https://user-images.githubusercontent.com/46468864/172051076-b9387c39-2f35-4a84-9b7f-8413dc18a97c.png">

**Comment by ollo69** [comment]
This change was made to have the timer format compatible with HA format as discussed in Issue #257.
There is no reason to change this back, but you can use platform template to change this value and show it without seconds in UI.
Please remember to close this issue if there are not additional comment on this,

**Comment by mattgahs** [comment]
Thank you for the quick reply! I see the justification in #257 and will pursue a platform template. Thanks again, closing issue.
