### ISSUE TITLE
Rinse+ Status

### ISSUE THREAD

**Issue by caribo** [ollo69/ha-smartthinq-sensors#339]
**Is your feature request related to a problem? Please describe.**
Not a problem, but I would like an indication of whether the Rinse+ option has been selected on my washer dryer in the same way that pre-wash and steam functions are exposed as attributes.

**Describe the solution you'd like**
I would like Rinse plus option to be expressed as an attribute of my washer dryer. I'm not 100% sure but I think this could be expressed as an enumerated list rinse, rinse+ etc or alternatively as a boolean switch on / off like the steam option is

**Describe alternatives you've considered**
I'm not aware of any other way of obtaining the status of Rinse+ other than through an amended integration

**Additional context**
I've attached JSON from my washer dryer. (LG-F4J8FH2S)

[LG.Dump.JSON.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8845598/LG.Dump.JSON.txt)

Rinse+ Symbol
![Screenshot from 2022-06-06 10-43-01](https://user-images.githubusercontent.com/664999/172198336-a3ebac60-c0a1-4c94-93af-f647bf9caa83.png)

**Comment by caribo** [comment]
I managed to fudge the code to do this (don't know whether my changes are 100% correct) .. but I would struggle to create a PR..

![image](https://user-images.githubusercontent.com/664999/173030187-17e6c4e4-04fd-490d-ac0f-446699017ba5.png)

**Comment by pepsonEL** [comment]
How you create this ? Please write manual step by step....

pt., 10 cze 2022 o 11:00 caribo ***@***.***> napisał(a):

**Comment by caribo** [comment]
Sorry @pepsonEL  , the post that I deleted was related to a [https://github.com/phrz/lg-washer-dryer-card](https://github.com/phrz/lg-washer-dryer-card). The card itself needs a rinse+ attribute / sensor to toggle the rinse+ icon on/off which is the part that relates to this repo.

I don't want to discuss the washer card on this request.. but will leave the attached file which may help you... 
[washer.zip](https://github.com/ollo69/ha-smartthinq-sensors/files/8880832/washer.zip)

**Comment by caribo** [comment]
@ollo69 any chance you can evaluate this feature request?

**Comment by ollo69** [comment]
Making some clean-up on stale issue, then I will focus on remaining. It's ok your comment to remove stale label.

**Comment by ollo69** [comment]
Not clear if rinse+ is already available as attribute / sensors or not. Please attach diagnostic with your washer turned on so that I can check the device payload.

**Comment by caribo** [comment]
The diagnostics are contained in the initial post, but added again here...

[LG.Dump.JSON.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10307038/LG.Dump.JSON.txt)

The rinse options look to be available here ?

```
     "rinse": {
      "dataType": "enum",
      "label": "@WM_TITAN27_BIG_OPTION_EXTRA_RINSE_W",
      "valueMapping": {
        "RINSE_NORMAL": {
          "index": 14,
          "label": "@WM_TITAN27_BIG_OPTION_EXTRA_RINSE_0_W"
        },
        "RINSE_PLUS": {
          "index": 15,
          "label": "@WM_TITAN27_BIG_OPTION_EXTRA_RINSE_1_W"
        },
        "RINSE_PLUS2": {
          "index": 16,
          "label": "@WM_TITAN27_BIG_OPTION_EXTRA_RINSE_2_W"
        },
        "RINSE_PLUS3": {
          "index": 17,
          "label": "@WM_TITAN27_BIG_OPTION_EXTRA_RINSE_3_W"
        }
      }
    }

```

**Comment by ollo69** [comment]
This feature should be available with last release, please test it and let know.

**Comment by caribo** [comment]
I have tested this today and confirm that it works as expected.  Many thanks!

The **sensor.washer_rinse_mode** sensor toggles between Normal and Rinse+ when I press the Rinse+ button on the machine.

**Comment by ollo69** [comment]
Very well, I close this thread as completed.
