### ISSUE TITLE
Washer current state

### ISSUE THREAD

**Issue by pablopoo** [ollo69/ha-smartthinq-sensors#34]
Hi,
If I'm right, in a washer, the run state is what the washer is doing now and pre state is the previous state?

Right now I see on on run state "detecting" and on pre state "drying" (it's a washer/dryer), but the washer is drying. Seems that they are in the wrong order.

![image](https://user-images.githubusercontent.com/13492043/80820706-6777f180-8ba5-11ea-8b5a-c837aec8295f.png)

Thanks
Pablo

**Comment by ollo69** [comment]
Are you sure?
It's first time that I hear this issue and the code is ok, so seems very strange.
Did you check other cases?

**Comment by pablopoo** [comment]
The ThinQ app on iOS show the same state, so seems that is a bug on the lg servers :/

**Comment by ollo69** [comment]
Fine, I close this issue.
