### ISSUE TITLE
Energy usage in enegy dashboard

### ISSUE THREAD

**Issue by martin-92** [ollo69/ha-smartthinq-sensors#341]
Hello,

I have been using this integration for my 2 air conditioners for some time now and it is working great. I can view the consumption and I would like to add it in the energy dashboard. Is it possible to make this available?
I don't see it listed among the available devices.

**Comment by ollo69** [comment]
Integration provide Power Usage (W), you need to convert Power to Energy to have the value available in energy dashboard. HA provide the platform `integration` for this.
Take a look to issue #169 for more details.

**Comment by ChefkeGremmen** [comment]
> Integration provide Power Usage (W), you need to convert Power to Energy to have the value available in energy dashboard. HA provide the platform `integration` for this. Take a look to issue #169 for more details.

Just adding a direct link to the interesting part of the HA website with the config example: https://www.home-assistant.io/integrations/integration/#energy
