### ISSUE TITLE
A/C - zone control not showing up in HASS (when it is showing up in LG app)

### ISSUE THREAD

**Issue by keiranharris** [ollo69/ha-smartthinq-sensors#342]
**Describe the bug**
Hey @ollo69  - as we spoke of over on the other closed issue my zone control is not showing up in HASS (when it is showing up in LG app)

**Expected behavior**
As I understand (from others that have it working) zones SHOULD show up as simple switch.xxxxxxx entities in HASS.  But they are not there for me.  

**Screenshots**
Can provide if needed but I think you get the idea.

**Environment details:**
 - Home Assistant build: docker container
 - Home Assistant version installed: Home Assistant Core 2022.6.2
 - Component version installed: latest
 - Last know working version: never - I just had zone controller installed
 - LG device type and model with issue: ducted aircon. I think I have v1 of the API

**Output of HA logs**
Attached diagnostic logs.

[smartthinq_sensors-6fe94fa844e5cfceb25da086d32669be-LG Air-ed45d2bc1585ad53400f877b683486c6.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8908674/smartthinq_sensors-6fe94fa844e5cfceb25da086d32669be-LG.Air-ed45d2bc1585ad53400f877b683486c6.json.txt)

thanks Ollo69!

**Comment by ollo69** [comment]
Please can you check if with last release this issue is fixed?

**Comment by keiranharris** [comment]
Oh my bad, i cant believe i didnt have your latest - sorry about that. I got confused with integrations screen vs hacs- i see now i was many versions behind …..

…BUT ive just upgraded your code and _still_ cant see the switch.xxxxx entities inside the device. I assume they should show up here? Have rebooted. Do i need to delete and re-add the integration? 
![6BE20FCF-0F3A-4B79-B840-B941820CBAD7](https://user-images.githubusercontent.com/22670742/175887616-5676d71c-788c-4fbd-adea-96dc7eedc0e3.jpeg)
![DCB06174-3361-41C2-AD93-3DCCD8661EE7](https://user-images.githubusercontent.com/22670742/175887643-8b6c5a41-7f85-43ed-aa73-3144923c45d1.jpeg)

**Comment by sokrates209** [comment]
I've just updated to latest and have exactly the same error as above:

Logger: custom_components.smartthinq_sensors.wideq.ac
Source: custom_components/smartthinq_sensors/wideq/core_async.py:325
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 11:58:51 (15 occurrences)
Last logged: 13:12:34

Duct zone control failed
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 705, in poll
    await self.update_duct_zones()
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 354, in update_duct_zones
    states = await self._get_duct_zones()
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 417, in _get_duct_zones
    zones = await self._get_config(DUCT_ZONE_V1)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1099, in _get_config
    data = await self._client.session.get_device_config(self._device_info.id, key)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1009, in get_device_config
    res = await self.post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 822, in post
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 298, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 325, in _manage_lge_result
    raise exc.APIError(code, message)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 제품 응답 지연

**Comment by keiranharris** [comment]
Sorry for the bother ive created @ollo69 and others. I can also be on high alert to help you debug when you have some time to try again. Let me know how i can help.

**Comment by keiranharris** [comment]
Sure. Give me 10mins.

**Comment by keiranharris** [comment]
ok attached. 

I have only 3 actual zones. But i believe its a 8 zone (capable) controller. 

here is with zone 1 open:
[zone1open_smartthinq_sensors-6fe94fa844e5cfceb25da086d32669be-LG Air-ed45d2bc1585ad53400f877b683486c6.json-2.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8995832/zone1open_smartthinq_sensors-6fe94fa844e5cfceb25da086d32669be-LG.Air-ed45d2bc1585ad53400f877b683486c6.json-2.txt)
 
and here is with all 3 zones open: 
[zone1,2,3open_smartthinq_sensors-6fe94fa844e5cfceb25da086d32669be-LG Air-ed45d2bc1585ad53400f877b683486c6.json-2.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/8995837/zone1.2.3open_smartthinq_sensors-6fe94fa844e5cfceb25da086d32669be-LG.Air-ed45d2bc1585ad53400f877b683486c6.json-2.txt)

I've just diff'd them to save you the hassle: 
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/22670742/176042969-c458bc7b-76b8-48af-99dd-fd09e7fe54f5.png">

**Comment by keiranharris** [comment]
OMG - you legend. Thanks for crazy turn-around time on the fix - this will make our house so much happier :)  

Ill buy you a coffee.  
<img width="788" alt="image" src="https://user-images.githubusercontent.com/22670742/176065847-9ad55e7f-8e82-4b44-aaa3-3525232610e5.png">

**Comment by robertklep** [comment]
Looks like 0.23.2 fixes the error messages I was getting, too 🥳

**Comment by ollo69** [comment]
Fine, I close this issue.👍

**Comment by keiranharris** [comment]
Hi @ollo69 - loving zone control! 

But wondering if this is expected behaviour? When the A/C is off, the zones show up as unavailable. 
![E67EACD8-66B6-4465-ACF3-0D1339BFBF6D](https://user-images.githubusercontent.com/22670742/178134038-7adfc683-6caa-4ebd-a42a-98bcff19d478.jpeg)

Turn it back on again (in any mode, fan, heat, cool etc) and they show up again. 
![CFD76732-4B6D-4E0D-944E-2C25FE866772](https://user-images.githubusercontent.com/22670742/178134048-5ec0919c-8176-4066-80c4-3cad0ba43211.jpeg)

Is this expected?
