### ISSUE TITLE
Separate swing modes (horizontal and vertical) for AC devices

### ISSUE THREAD

**Issue by Chaos02** [ollo69/ha-smartthinq-sensors#343]
Problem:
For my AC device `RAC_056905_WW-RAC` you can set the swing modes as one of 16. In the selection are both, `vertical` and  `horizontal` modes.
At the moment you can set them after one another but this makes it unclear which modes you set or which modes it is in.

As a solution to this problem I'd like this to be split up in two seperate swing modes:
`HorizontalSwing` and `VerticalSwing`. 
This makes it possible for automations to set both at the same time, as well as controlling them separately and being sure, which two modes it is in.

**Comment by ollo69** [comment]
Not clear what are you asking for. The climate entity in HA do not provide support for 2 separate swing modes, so there are no way to split them. 
Automations should just call the `set_swing_mode` 2 times, once with the horizontal mode and once with the vertical, so you can set both mode at any time,

**Comment by Chaos02** [comment]
Ohh okay, I thought, this might have been an issue with the integration, not HA. Will raise an issue on HA then.
Thank you!
