### ISSUE TITLE
Fails to load after update

### ISSUE THREAD

**Issue by dogmatic69** [ollo69/ha-smartthinq-sensors#348]
**Describe the bug**
Updated the module from two versions back and now it fails to load. 

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - HAOS on HA blue
 - Home Assistant version installed: latest
 - Component version installed: latest
 - Last know working version:  0.23.0
 - LG device type and model with issue: N/A
 - LG devices connected (list): N/A

**Output of HA logs**
Paste the relavant output of the HA log here.

```
Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/__init__.py:197
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 14:47:10 (1 occurrences)
Last logged: 14:47:10

Invalid ThinQ credential error, integration setup aborted. Please use the LG App on your mobile device to ensure your credentials are correct, then restart HomeAssistant. If your credential changed, you must reconfigure integration
```

**Additional context**
Was working perfectly fine before updating the component and restarting.

**Comment by ollo69** [comment]
No change in login logic from last 2 version.
Did you check on LG app in mobile device that there are no new Term Of Service and that you login properly as suggested by the error message?

**Comment by dogmatic69** [comment]
The error says nothing about terms of service, it seems to be all about credentials. Perhaps add something about terms of service?

**Comment by ollo69** [comment]
Warning about TOS is highlighted in Readme. Did you check this? Does it solve your problem?

**Comment by vampywiz17** [comment]
+1

**Comment by ollo69** [comment]
Seems SSL issue. But, at least in @varakirill log, I see usage of python 3.10. Not sure if related, but I don't think this version is supported by HA (probably support will be introduced in 2022.7)

**Comment by varakirill** [comment]
@ollo69 yes, sorry, not mentioned before - I am using 2022.7 beta with python 3.10.

**Comment by ollo69** [comment]
Are you able to try using python 3.9? It could be related to stronger security introduced with new python version.

**Comment by vampywiz17** [comment]
I use stable release, but affect same problem.

**Comment by ollo69** [comment]
> I use stable release, but affect same problem.

Can you provide more detail about your installation? Please generate diagnostic and attach diagnostic file. Also provide log information.

**Comment by sab-automation-oz** [comment]
Seeing similar issues - last 24 hrs sensors were flapping unavailable/available. Updated to latest ThinQ integration ... wont load up now at start up..  Mobile app seems to have some issues as well   (been rock stable for months prior!)

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 189, in async_setup_entry
    client = await lge_auth.create_client_from_token(hass, refresh_token, oauth_url)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 118, in create_client_from_token
    return await ClientAsync.from_token(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1222, in from_token
    gateway = await Gateway.discover(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 600, in discover
    gw_info = await core.gateway_info()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 331, in gateway_info
    return await self.thinq2_get(V2_GATEWAY_URL)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 246, in thinq2_get
    async with self._session.get(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 634, in _request
    break
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

**Comment by ollo69** [comment]
> Seeing similar issues - last 24 hrs sensors were flapping unavailable/available. Updated to latest ThinQ integration ... wont load up now at start up.. Mobile app seems to have some issues as well (been rock stable for months prior!)

This is different, timeout issue. May depend on your internet connection or issue on LG server in your region.

**Comment by sab-automation-oz** [comment]
> 
> This is different, timeout issue. May depend on your internet connection or issue on LG server in your region.
Internet is 100% all other services working fine!

Do u know how to see/check on LG servers?  (we are In Australia)

**Comment by ollo69** [comment]
> Do u know how to see/check on LG servers? (we are In Australia)

No idea. The only information I can give you is the address is trying to connect when you receive the timeout in the log:

`https://route.lgthinq.com:46030/v1/service/application/gateway-uri`

**Comment by sab-automation-oz** [comment]
> > Do u know how to see/check on LG servers? (we are In Australia)
> 
> No idea. The only information I can give you is the address is trying to connect when you receive the timeout in the log:
> 
> `https://route.lgthinq.com:46030/v1/service/application/gateway-uri`

THanks! - and just like that it seems service has restored magically!

Will monitor for ongoing stability...

**Comment by ollo69** [comment]
I close this issue, think is duplicated of issue #351 and should be fixed with last release.
