### ISSUE TITLE
LG Washer entities rarely update

### ISSUE THREAD

**Issue by alexeiw123** [ollo69/ha-smartthinq-sensors#349]
**Describe the bug**

LG washer entities will only appear and update infrequently. Most wash cycles don't show in log or history.
Washing complete automation is therefore unreliable.

Notifications from LG thinq app still come through reliably.

If I open the LG Thinq app while the washer is switched on, then the integration will recognise it.

[download diagnostics json with custom_components removed](https://pastebin.com/v0J748Bf)

**Expected behavior**
HA to detect all state changes reliably.

**Screenshots**
N/A

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Pi 3B+ 64 bit with SD 
 - Home Assistant version installed: 2022.6.7
 - Component version installed: v0.23.2
 - Last know working version: N/A
 - LG device type and model with issue: WTR1132WF (shows as TA4D_F-TL (WASHER) in integration)
 - LG devices connected (list): LG C9 (only in thinq app). This washer.

**Output of HA logs**
N/A

**Additional context**
Not sure how to provide meaningful logs. Happy to do so with some intruction.

**Comment by Scags104** [comment]
having the same issue as described above but my washer is fine, the dryer refuses to update. Seems to update when dryer is started but then never updates remaining time and never completes cycle in HA.
