### ISSUE TITLE
Deprecated async_get_registry

### ISSUE THREAD

**Issue by Szeryff** [ollo69/ha-smartthinq-sensors#352]
Hi,
with the latest core 2022.6.x update, I received this error. Can you update this registry change?
thank you
`Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for smartthinq_sensors using this method at custom_components/smartthinq_sensors/__init__.py, line 475: device_registry = await hass.helpers.device_registry.async_get_registry()`

**Comment by ollo69** [comment]
I suppose that you are not using last integration version, call to `async_get_registry` was removed many version ago.
Please update to last release.

**Comment by Szeryff** [comment]
Hmm I'm using the newest Home Assistant OS: core-2022.7.2 and that's where I'm seeing the error.
Shouldn't this version have newest smartthinq-sensors included?

**Comment by ollo69** [comment]
Custom integrations are not included in Home Assistant and must be updated separately, manually or using HACS.

**Comment by Szeryff** [comment]
Update to newest version fix problem indeed.

**Comment by rksim** [comment]
How in the fuck do I unsubscribe from these emails I have tried to unsubscribe but I keep getting them - can someone please remove me?
