### ISSUE TITLE
Missing parameters from Therma V Monobloc heat-pump

### ISSUE THREAD

**Issue by DohmenICT** [ollo69/ha-smartthinq-sensors#359]
Hi all,

I have a Series 4 Therma V monobloc. I'm not seeing all parameters from the logging .

These are all parameters that I see in the logging:

            "snapshot": {
              "airState.ess.opStatus": 0.0,
              "airState.ess.consumeRate": 0.0,
              "airState.tempState.airTempHeatMin": 16.0,
              "airState.diagCode": 0.0,
              "airState.ess.solarPower": 0.0,
              "airState.tempState.waterTempCoolMin": 10.0,
              "airState.tempState.airTempCoolMin": 16.0,
              "mid": 23368867.0,
              "airState.energy.onCurrent": 0.0,
              "airState.quality.sensorMon": 0.0,
              "airState.ess.batteryStatus": 0.0,
              "airState.miscFuncState.awhpWaterControl": 0.0,
              "airState.tempState.target": 17.0,
              "airState.ess.batteryPower": 0.0,
              "airState.tempState.hotWaterTempMin": 40.0,
              "airState.ess.consumePowerExt": 0.0,
              "airState.operation": 0.0,
              "airState.tempState.waterTempHeatMax": 55.0,
              "airState.tempState.airTempCoolMax": 30.0,
              "timestamp": 1658686697456.0,
              "static": {
                "deviceType": "401",
                "countryCode": "NL"
              },
              "airState.tempState.hotWaterCurrent": 47.5,
              "airState.ess.solarPowerExt": 0.0,
              "airState.tempState.current": 28.5,
              "airState.tempState.hotWaterTempMax": 58.0,
              "airState.miscFuncState.awhpTempSwitch": 1.0,
              "airState.miscFuncState.extraOp": 0.0,
              "airState.tempState.hotWaterTarget": 55.0,
              "airState.ess.gridPower": 0.0,
              "airState.tempState.waterTempHeatMin": 20.0,
              "airState.ess.energyFlow": 0.0,
              "airState.miscFuncState.powerHotWater": 0.0,
              "airState.tempState.airTempHeatMax": 25.0,
              "meta": {
                "allDeviceInfoUpdate": false,
                "messageId": "kLPrSRnpSZ-BzHoQr1V7TQ"
              },
              "airState.ess.batteryRemain": 0.0,
              "airState.tempState.waterTempCoolMax": 24.0,
              "airState.miscFuncState.silentAWHP": 0.0,
              "online": false,
              "airState.ess.batteryPowerExt": 0.0,
              "airState.ess.gridPowerExt": 0.0,
              "airState.miscFuncState.hotWater": 0.0,
              "airState.opMode": 3.0,
              "airState.ess.consumePower": 0.0,
              "airState.ess.energyLevel": 0.0,
              "airState.tempState.outWaterCurrent": 27.0,
              "airState.tempState.inWaterCurrent": 32.5
            },

can these missing ones be added so I can monitor them in Home Assistant?

**Comment by kepath** [comment]
I would also be interested in this.

My parameters in the diagnostic info are

```
            "snapshot": {
              "airState.tempState.airTempHeatMin": 16.0,
              "airState.diagCode": 0.0,
              "airState.tempState.waterTempCoolMin": 18.0,
              "airState.tempState.airTempCoolMin": 16.0,
              "mid": 34779672.0,
              "airState.quality.sensorMon": 0.0,
              "airState.miscFuncState.awhpWaterControl": 0.0,
              "airState.tempState.target": 13.0,
              "airState.tempState.hotWaterTempMin": 40.0,
              "airState.operation": 0.0,
              "airState.tempState.waterTempHeatMax": 65.0,
              "airState.tempState.airTempCoolMax": 30.0,
              "timestamp": 1662137184897.0,
              "static": {
                "deviceType": "401",
                "countryCode": "GB"
              },
              "airState.tempState.hotWaterCurrent": 50.0,
              "airState.tempState.current": 28.5,
              "airState.tempState.hotWaterTempMax": 55.0,
              "airState.miscFuncState.awhpTempSwitch": 1.0,
              "airState.miscFuncState.extraOp": 0.0,
              "airState.tempState.hotWaterTarget": 55.0,
              "airState.tempState.waterTempHeatMin": 20.0,
              "airState.tempState.airTempHeatMax": 30.0,
              "meta": {
                "allDeviceInfoUpdate": false,
                "messageId": "xxxxxxxxxxxx"
              },
              "airState.tempState.waterTempCoolMax": 24.0,
              "online": true,
              "airState.miscFuncState.hotWater": 1.0,
              "airState.opMode": 3.0,
              "airState.tempState.outWaterCurrent": 21.0,
              "airState.tempState.inWaterCurrent": 20.5
            },
```
