### ISSUE TITLE
The values in the dishwasher are not updated. (D1211-DW)

### ISSUE THREAD

**Issue by JUNGKYUSEO** [ollo69/ha-smartthinq-sensors#360]
The values in the dishwasher are not updated.

Thank you.

smartthinq_sensors-식기세척기
kr

![FE524BA8-2920-4E1D-A67D-F2755FB12CD3](https://user-images.githubusercontent.com/47815824/180965435-5384e106-6f3f-4b2e-a8f1-51facd0d91d3.jpeg)

[ThinQ Dishwasher Log.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9181523/ThinQ.Dishwasher.Log.txt)

**Comment by ollo69** [comment]
Please attach diagnostics.

**Comment by JUNGKYUSEO** [comment]
Entities are not updated.
There are no alarms.

[Debug Data.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9388684/Debug.Data.txt)
[smartthinq_sensors-db1f65d34a8f04495f7a542898ddaa06-ìê¸°ì¸ì²ê¸°-6c431cbf92d1b1db67fa0ee8135e0bbf.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9388685/smartthinq_sensors-db1f65d34a8f04495f7a542898ddaa06-i.e.i.i.e.-6c431cbf92d1b1db67fa0ee8135e0bbf.json.txt)

**Comment by ollo69** [comment]
Please try last release, should fix this issue.

**Comment by JUNGKYUSEO** [comment]
It changes very well.
Thank you very much.

**Comment by JUNGKYUSEO** [comment]
sorry.
When I check again, the attribute value of the dishwasher is not updated.
I need dishwasher uptime and remaining time.
![F565EF4E-A762-4E64-A984-2B5649194DD8](https://user-images.githubusercontent.com/47815824/186053056-2937b2fd-fada-448c-9284-743beed47582.jpeg)

**Comment by ollo69** [comment]
Did you try enabling the corresponding sensors? What attributes are not updated? Just the time or also others?

**Comment by JUNGKYUSEO** [comment]
Initial_time, rest_time, and reserved_time attribute values ​​are not updated.
Additionally, the Initial Time, Time Remaining, and Countdown Time sensors are disabled by default and their entities will not be updated when switched to enabled.

Where can I check the remaining time of my dishwasher?


[smartthinq_sensors-db1f65d34a8f04495f7a542898ddaa06-ìê¸°ì¸ì²ê¸°-6c431cbf92d1b1db67fa0ee8135e0bbf.json-3.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9401608/smartthinq_sensors-db1f65d34a8f04495f7a542898ddaa06-i.e.i.i.e.-6c431cbf92d1b1db67fa0ee8135e0bbf.json-3.txt)

<img width="692" alt="스크린샷 2022-08-23 오후 7 10 23" src="https://user-images.githubusercontent.com/47815824/186132976-2102694c-81aa-4296-92f2-caef5826e900.png">
<img width="787" alt="스크린샷 2022-08-23 오후 6 40 43" src="https://user-images.githubusercontent.com/47815824/186130651-b3a5eb39-2e08-479f-9d1b-911a9804760f.png">
<img width="325" alt="스크린샷 2022-08-23 오후 6 39 35" src="https://user-images.githubusercontent.com/47815824/186130700-214157a5-caad-42f5-b2e1-83c2f39acde8.png">

**Comment by ollo69** [comment]
Probably reading o wrong place. I'll check and let you know.
