### ISSUE TITLE
Dehumidifier no longer has Current Humidity Sensor

### ISSUE THREAD

**Issue by 3of9** [ollo69/ha-smartthinq-sensors#361]
When first added, the dehumidifier support had the current humidity sensor value.
In an update a month or two ago, that sensor was removed.

Is it possible to bring back this sensor?

Thank you.

Dehumidifier Model: UD701KOG3
Integration version: 0.23.5
HA version: 2022.7.6

**Comment by mtgpcs** [comment]
I just noticed that the same on mine. It shows last updated 6 hours ago.

DHUM_056905_WW
Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220707.1 - latest
I think I have the latest integration, no update in HACS.

**Comment by mtgpcs** [comment]
I rebooted and it seemed to update. I'll keep an eye on it and report back?

**Comment by 3of9** [comment]
I just Deleted and re-added the Integration. The attribute and sensor simply do not exist.

**Comment by ollo69** [comment]
Please attach diagnostic.

**Comment by 3of9** [comment]
[smartthinq_sensors-f3ddec307180a5a3de3590cba4e33352-Dehumidifier-64743be8e15565164fbabfc4c4858a98.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9225392/smartthinq_sensors-f3ddec307180a5a3de3590cba4e33352-Dehumidifier-64743be8e15565164fbabfc4c4858a98.json.txt)

**Comment by mtgpcs** [comment]
Mine seems to still exist but is not updating. The last update I see for mine is when I last posted after a reboot. Should I open a new ticket?

**Comment by ollo69** [comment]
Please try installing last release, it should fix this issue.

**Comment by 3of9** [comment]
That fixed it! Cheers!
