### ISSUE TITLE
Add new device, LG WH27S and WH20S 

### ISSUE THREAD

**Issue by Dutchy-79** [ollo69/ha-smartthinq-sensors#364]
[config_entry-smartthinq_sensors-19c309a80930672f4d8c304f41728372.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9232978/config_entry-smartthinq_sensors-19c309a80930672f4d8c304f41728372.txt)
I have 3 LG ac's and the integration works great 

I also have a heat pump boiler from LG and I'd like to see that data on Home assistant as well. LG WH27S and his little brother the LG WH20S would probably be the same deal. 

How can I get the data you need to implement this? 

![Screenshot_20220730-063935_LG ThinQ](https://user-images.githubusercontent.com/22749572/181872648-35a32ce5-4081-4d52-a4e2-33404a5638f1.png)
![Screenshot_20220730-063901_LG ThinQ](https://user-images.githubusercontent.com/22749572/181872650-3afee000-7efd-4a69-8be5-9f8899224c35.png)

**Comment by Dutchy-79** [comment]
Added log in txt format, Github does not like json

**Comment by Bas1978** [comment]
i have the same question. does anyone have a solution to implement lg wh27s?

**Comment by Dutchy-79** [comment]
At least 3 requests so far. If there is any thing I can do to help I'd like to know.

**Comment by ollo69** [comment]
This integration have a lot of requests, problem is the time that I can dedicate. Just be patient, it will comes...

**Comment by Dutchy-79** [comment]
> This integration have a lot of requests, problem is the time that I can dedicate. Just be patient, it will comes...

👍

**Comment by svetj** [comment]
Hello.
I'm also interested in this feature. 
Unfortunately, I'm a novice about homessistant, but I know python, if some help is needed.
Thank you for your work

**Comment by Linusten** [comment]
I am interested too!

**Comment by Denny2c** [comment]
Hello. I also would like to get this device integrated

**Comment by lacrau1** [comment]
Hi,
I'm also interested in this feature.
Thanks !!

**Comment by amrij** [comment]
Hi,
I'm also interested in this feature.
Thanks !!

**Comment by bjedelijn** [comment]
+1 also using HASS and would love see integration for LG WH27S incl power consumption en controlling modes, on off.
will some funding help?

**Comment by ollo69** [comment]
I close this FR as duplicated of #332 and Water Heater support now is available.
