### ISSUE TITLE
Add support for cycle time remaining on Dryer and Washer

### ISSUE THREAD

**Issue by mattames** [ollo69/ha-smartthinq-sensors#366]
Can you please add the cycle time remaining on the washer and dryers. I can get this information from the LG app, and it would be very very handy to have in Home Assistant. Thanks!

**Comment by ollo69** [comment]
Remaining time is already available as sensor and extra attribute. Please attach diagnostic file if you don't find this information.

**Comment by ollo69** [comment]
Can we close this?

**Comment by mattames** [comment]
Yep, found it no problem once I had a proper look. Thanks!

**Comment by emog** [comment]
@mattames - How did you added the remaining time attribute. In my case it's disabled "This entity is unavailable."

**Comment by mattames** [comment]
Hi @emog, from memory I simply found the disabled entities and clicked enable, then added them to a card. It was very straightforward with no tricks required.
