### ISSUE TITLE
Current Humidity and Water Tank Full not updating

### ISSUE THREAD

**Issue by mtgpcs** [ollo69/ha-smartthinq-sensors#367]
**Describe the bug**
The sensor for both "Current Humidity" and "Water Tank Full" are not auto updating. They only seem to update if I reload the integration or I reboot HA.

**Expected behavior**
They should update on their own.

[config_entry-smartthinq_sensors-a67aebcdda57b6f78014a543b292b264.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9232718/config_entry-smartthinq_sensors-a67aebcdda57b6f78014a543b292b264.json.txt)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HAOS
Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220707.1 - latest

 - Component version installed:
 - Last know working version: Installed today 8/1/22
 - LG device type and model with issue: DHUM_056905_WW- (DEHUMIDIFIER)
 - LG devices connected (list): Dryer and Dehumidifier

**Comment by ollo69** [comment]
This is really strange, I don't see any reason for this. What happen if you open LG mobile app? Does the sensor value change?

**Comment by mtgpcs** [comment]
Yeah I don't understand it either. It updates fine on the LG app. Sometimes it does seem to update but doesn't seem consistent . It's weird though the dryer updates fine.

**Comment by mtgpcs** [comment]
I haven't got the water tank full to turn on even though the LG app will send notifications. The entities show last update yesterday.

**Comment by mtgpcs** [comment]
Well that was weird opened the app and it went from 50% to 45% just checked HA and it shows it updated a few seconds ago. The water tank is empty though so I can't check that.

**Comment by kss20ismine** [comment]
Same issue here. Water tank status not show full in HA but LG app did.

**Comment by ollo69** [comment]
Water tank sensor was buggy but with last release should be ok. Could someone confirm this?

**Comment by ahtoh1029** [comment]
Water tank sensor in HA shows reversed state, when the tank is empty it goes on, and tank full turns it off

**Comment by ahtoh1029** [comment]
> Same issue here. Water tank status not show full in HA but LG app did.

same here! the sensor doesn't update

**Comment by ollo69** [comment]
If this doesn't work probably is because status is not updated in the payload. But if you only report that it doesn't work and you not attach diagnostic I will never be able to analyze this issue. 
You should attach 2 diagnostic files, one when the light is on and one when the light is off👍

**Comment by kss20ismine** [comment]
How to get diagnostic files?

**Comment by mickyshey** [comment]
Any update for this issue? My Water Tank Full entity is always "On" no matter what status is in the LG app.

**Comment by thematrixdev** [comment]
I have got the same issue.
