### ISSUE TITLE
remain_time and other sensors not available

### ISSUE THREAD

**Issue by Blueforcer** [ollo69/ha-smartthinq-sensors#370]
There are some sensors wich are not available in HA. But they are shown in the diagnose file
("remainTimeMinute": 16.0,)

![image](https://user-images.githubusercontent.com/31169771/183090154-ecf4274a-a6dd-4d7c-b4ef-8bc0cff118a2.png)

diagnose-file:

[smartthinq_sensors-f5a107c3427ae37d92b760c842ec2875-Waschmaschne-2053b633c469e2e815a4da198cad2066.json (1).txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9269193/smartthinq_sensors-f5a107c3427ae37d92b760c842ec2875-Waschmaschne-2053b633c469e2e815a4da198cad2066.json.1.txt)

**Comment by ollo69** [comment]
Those sensors are disabled by default, you just need to enable manually once.

**Comment by Blueforcer** [comment]
nevermind :)
thank you!

**Comment by emog** [comment]
@Blueforcer - How did you get the remaining time sensor enabled?
