### ISSUE TITLE
Automation Support for Aircon Units

### ISSUE THREAD

**Issue by embcla** [ollo69/ha-smartthinq-sensors#371]
**Is your feature request related to a problem? Please describe.**
I'm just trying to create an automation for my aircon units, and when I get to the actions sections, I can't find any AC devices.
Thermostat card does work and control the AC units, but automations can't seem to find anything useful.
I only found a service called Remote Start, but no remote stop.

**Describe the solution you'd like**
I'm expecting to be able to set device states like: fan speed, operating mode, target temperature, etc

**Describe alternatives you've considered**
I'm open to options: are there other ways I can set this up?

**Comment by ollo69** [comment]
I'm not understanding what you are asking for. Automation in HA can be created for any entities, refer to [HA automation guide](https://www.home-assistant.io/docs/automation/) for additional information.
This has nothing to do with integration.

**Comment by embcla** [comment]
So for my LG ac units I have no devices, just entities. And when I try and
create an automation, I can't find neither devices nor services that appear
that I can use.

That's why I'm asking here, the integration is creating entities and
devices right, or did I get it wrong?

**Comment by ollo69** [comment]
If you are using this integration is not possible that you don't have devices. Anyway generate and attach diagnostic file so that I can investigate this.

**Comment by embcla** [comment]
Here are the diagnostics

[config_entry-smartthinq_sensors-acc75eb6b08d0b06e4025bef6a9690da.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9290852/config_entry-smartthinq_sensors-acc75eb6b08d0b06e4025bef6a9690da.json.txt)

**Comment by ollo69** [comment]
In diagnostic I see that you have 2 devices (`Cameretta` and `Sala`) associated to 2 climate entities (`climate.cameretta_2` and `climate.sala_2`)
Climate entities expose all required services to control your devices in Automation (e.g. `climate.set_temperature`, `climate.set_hvac_mode`, etc.).
Looks like it's not clear to you how create automation in HA, I suggest to move to HA forum to ask support or read HA documentation more deeply.
