### ISSUE TITLE
Add AC filter remaining time sensor (+ reset switch?)

### ISSUE THREAD

**Issue by cynicer** [ollo69/ha-smartthinq-sensors#375]
**Is your feature request related to a problem? Please describe.**
AC filter needs regular cleaning. The AC keeps track of the usage time and has a countdown when to clean the filter.

**Describe the solution you'd like**
Offer a sensor to display the remaining filter hours. After a clean the value can be reset through the LG app, ideally this would also be possible e.g. with a switch.

**Describe alternatives you've considered**
Stopping HA and doing it manually via the LG app.

**Additional context**
I already implemented that on the old plugin, but I'm not really familiar with the the proper HA plugin architecture so I'll just link it here for reference: https://github.com/sampsyo/hass-smartthinq/pull/105

**Comment by ollo69** [comment]
Add sensors here is not really complicated and filter status was already implemented for other device as Air Purifier, but is not clear how to fetch this information from the AC devices. Please attach diagnostic file or provide some example on how get this information.

**Comment by cynicer** [comment]
The filter state is already implemented in wideq (https://github.com/sampsyo/wideq/blob/master/wideq/ac.py#L318). The filter period (the maximum time a filter shall be used) and the used time can be obtained like this: https://github.com/sampsyo/hass-smartthinq/blob/master/sensor.py#L272

It would be nice to have a sensor showing the remaining time in order to build a notification for a filter clean. Additionally it might be useful to publish the filter period in some way as well.

**Comment by vk2him** [comment]
+1 for this - I'd love to see it working - I'm currently using https://github.com/sampsyo/hass-smartthinq  which displays teh filter info however I would like to use yours instead

**Comment by ollo69** [comment]
In any case can you please configure (may be only temporary) the integration and attach here the diagnostic file so that I can check the payload. I need to understand the best way to implement this functionality trying to do this for both V1 and V2 ac type, despite what the old wideq library does.

**Comment by vk2him** [comment]
Here's the diagnostic files for my 2 LG Aircon systems

[smartthinq_sensors-006a047ba432abfb83cc60c80699c28f-Lounge-11d831a4925f3f174016c46e4082b818.json (1).txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9390413/smartthinq_sensors-006a047ba432abfb83cc60c80699c28f-Lounge-11d831a4925f3f174016c46e4082b818.json.1.txt)
[smartthinq_sensors-006a047ba432abfb83cc60c80699c28f-Bedroom -a6c90c4b11afc9ff62f46e1ee79ea11e.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9390414/smartthinq_sensors-006a047ba432abfb83cc60c80699c28f-Bedroom.-a6c90c4b11afc9ff62f46e1ee79ea11e.json.txt)

**Comment by cynicer** [comment]
[config_entry-smartthinq_sensors-988ee0e3f5864a5c52c6068ea447f010.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9391537/config_entry-smartthinq_sensors-988ee0e3f5864a5c52c6068ea447f010.json.txt)

**Comment by cynicer** [comment]
🚀

**Comment by SN0WTR00PER** [comment]
I was about to create the exact same request.  I have an LG Dualcool and the air filter need to be cleaned after a certain amount of time... The status can be retreived the same way we can retreive the energy consumption if I'm not mistaken.

Taking a look at the other available integration could be a starting point.

**Comment by ollo69** [comment]
This feature should be available in last release. Wait for yours feedback.

**Comment by gabi1324** [comment]
Just updated and reloaded the integration, but I don't have the filter sensor. Shouldn't it just appear in the list?

**Comment by ollo69** [comment]
> Just updated and reloaded the integration, but I don't have the filter sensor. Shouldn't it just appear in the list?

Please attach diagnostics

**Comment by gabi1324** [comment]
[config_entry-smartthinq_sensors-06a774f58ee56ffb645ea7e4f785c74f.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10300482/config_entry-smartthinq_sensors-06a774f58ee56ffb645ea7e4f785c74f.json.txt)

**Comment by ollo69** [comment]
@gabi1324,

what is the current status reported by LG apps for your devices? In the payload all values are = 0, for this reason sensors are not shown (I assume that when max time = 0 the information is not available). May be I should do a specific call to retrieve these data, but in this case we need to investigate....

**Comment by gabi1324** [comment]
If you are referring to the filter time in the LG app, I have for the living room AC 91% and 649 hours remaining and 71 hours used. I checked the diagnostics also and I don't know why the values are 0.

**Comment by ollo69** [comment]
I was hoping that information in LG app was not available for you😂. This means that this information must be query with a specific command and is not available in the payload. We must investigate on this. Let's wait for some other feed-back on this thread to see if this is equal for all V2 models or there are different situation.

**Comment by ricoroodenburg** [comment]
> Just updated and reloaded the integration, but I don't have the filter sensor. Shouldn't it just appear in the list?

Same issue here (LG S12EW). Current filter status is 69% inside the LG Thinq app.

**Comment by bellini666** [comment]
I have 3 ACs in my house connected to LG Thinq. One of them is a ceiling one, and that one is displaying the filter status in my HA instance. The other two, which are wall mounted, are not, even though all 3 does display filter status in the Thinq app.

**Comment by SN0WTR00PER** [comment]
Filter entity and information are present now after updating.  Thanks 😊

**Comment by ollo69** [comment]
I think that problem here is with device based on ApiV2. They not expose the filter status in pay load and is required a specific command (as for model with ApiV1) but we need to discover the command.
Not having a LG climate, there are 2 options:

- I can try to implement this and release beta version to be tested, if someone is available for testing.
- If someone is available to share his credential (I will provide an e-mail for this), I will perform test by myself to see if I discover right command.

**Comment by gabi1324** [comment]
I am willing to test a beta version if you want to do this.

**Comment by cynicer** [comment]
@ollo69 I can provide you with the credentials to my LG account.
Appreciate the work on it!

**Comment by ollo69** [comment]
@cynicer,

write me an e-mail at a.olivero@gmail.com
I need username, password (if you prefer you can set a temporary one) region and language. I promise that I will not play with your device,😉

**Comment by cynicer** [comment]
@ollo69 Sent you the credentials, you can remove your address again.

**Comment by ollo69** [comment]
Thanks, received👍 I'll work on this later today.

**Comment by CRCinAU** [comment]
Thanks for the work on this... I have a wall mounted split system - and the filter doesn't appear on that either.

The only info I can find is:
```
Device App: 35.94
Modem: clip_hna_v1.9.183_QC
Firmware 1: SAA39723703.00003703.0
```

The inside unit is a WH24SLN-18 - with ~7KW outdoor unit.

It's been great to see the improvement in this integration :)

Thanks to all involved.

**Comment by ollo69** [comment]
@all,

I just released a new version with some fix / test for this feature, please test and let me know.

@cynicer,

for device V1 as yours, filter status now should be available. There was a couple of errors that was preventing status to be displayed. Please note that initial startup could be a little bit longer, because I need to get all available status on first refresh (more device, more time for startup of course). About the reset, I need more time, also because this should be implemented with button platform, still not used in this integration. Let me know if you need to change the account password or if i could still use for future tests.

@gabi1324,

for device V2 I added in this version a new command that should output some logs at info level. Because I don't have a clear idea on how this command should be formatted, let me say that we have 99% of probability that it is not correct and will simply fail. It is inside a controlled exception, so should not create any issue in normal operation. Please install new version, restart HA and share generated log so that I can check result and try again in a new release...

**Comment by CRCinAU** [comment]
Is this what you need?

[smartthinq_sensors-141dc1dcd06d7d3b52c8f7f3919a94e1-Air Conditioner-237af0ef187fc22cfafff71f89709340.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10340967/smartthinq_sensors-141dc1dcd06d7d3b52c8f7f3919a94e1-Air.Conditioner-237af0ef187fc22cfafff71f89709340.json.txt)

**Comment by cynicer** [comment]
Remaining filter life looks good to me after the update. One note though: Is the remaining life in % really the best way to handle this? The total filter life might be different for different devices and could be used in automations if the absolute value was accessible.

Looking forward to the reset button, this is the only use case left I have the ThinQ app installed.

@ollo69 You can continue to use the account, but my ACs are usually disconnected from the power (since they're not active atm). Just let me know via mail when you want to look into something, I'll turn them on.)

**Comment by ollo69** [comment]
> Is this what you need?

Tis is the diagnostics, what I need now is the HomeAssistant log file, possibly the one generated after HomeAssistant reboot (not too big and should contain required info).

**Comment by gabi1324** [comment]
I updated and the only mention of this integration is that it is a custom integration. However, I'm not sure if I downloaded the correct log file.

This is the HA Core log file.

[home-assistant_2023-01-04T11-02-04.490Z.log.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10343500/home-assistant_2023-01-04T11-02-04.490Z.log.txt)

**Comment by ollo69** [comment]
This is because your log is set to `warning` level, you should set to `info` level to have requested output. This can be done changing the `configuration.yaml`. Are you able to do this?

**Comment by CRCinAU** [comment]
Ok, just got home.... let me take a quick looksee.....

**Comment by CRCinAU** [comment]
```
2023-01-04 22:36:19.318 INFO (MainThread) [custom_components.smartthinq_sensors.wideq.devices.ac] GetFilerStatus V2: {'resultCode': '0000', 'result': {'data': {'airState.filterMngStates.useTime': 604.0, 'airState.filterMngStates.maxTime': 720.0, 'airState.filterMngStates.changeDate': 20221025.0}}}
2023-01-04 22:36:19.319 INFO (MainThread) [custom_components.smartthinq_sensors] LGE Device added. Name: Air Conditioner - Type: AC - Model: RAC_056905_WW - ID: f291d836-2889-1da6-a5c9-dc0398c70113
2023-01-04 22:36:19.319 INFO (MainThread) [custom_components.smartthinq_sensors] Founds 1 LGE device(s)
```

**Comment by ollo69** [comment]
Wow, so it work on first try 😎. Ok, I will work to use this values....

**Comment by CRCinAU** [comment]
https://tenor.com/en-AU/view/lego-first-firsttry-batman-legobatman-gif-21703761

:D :D :D

**Comment by gabi1324** [comment]
> This is because your log is set to `warning` level, you should set to `info` level to have requested output. This can be done changing the `configuration.yaml`. Are you able to do this?

I managed to set the logger to info, but someone already posted the log. I have the same logs so I'm not going to send them again.

**Comment by ricoroodenburg** [comment]
Hi @ollo69 ,

Unfortunately I don’t get the filter status after updating to the latest version. I’m using the S12EW split unit.

**Comment by ollo69** [comment]
Just released a new version where fetching data for APIv2 devices is fully implemented, please test and give me your feedback.

@cynicer,

I also added to filter sensors 2 attributes to access absolute values (I would avoid to add 2 more sensors for this). Who need `use_time` and `max_time` can get them from the sensor attributes.

**Comment by CRCinAU** [comment]
Nice!

![image](https://user-images.githubusercontent.com/3992884/210667517-7fb63f74-a01e-4d0b-8db8-f974af45d020.png)

Took me a moment to realise that the '84' is the percentage used - until I went into the developer tools....

The LG App shows me 112hr remaining, 608hr used. That seems to agree with the figures presented...

**Comment by CRCinAU** [comment]
Wait - no - the logic on the friendly name is wrong.... 84% isn't life **remaining** - its life **used**

**Comment by ollo69** [comment]
> Wait - no - the logic on the friendly name is wrong.... 84% isn't life **remaining** - its life **used**

Ops, you are right 😒. Ok, question is, what is better to show as percentage? Remaining life (I will change the logic in the calculation) or Used life? In my opinion the first, because when it come to 0 means that you have to change, when is 100% is full capacity (as a battery). And renaming the sensor will invalidate the existing, not so good...

**Comment by CRCinAU** [comment]
I'd vote for percentage remaining.

**Comment by gabi1324** [comment]
> > Wait - no - the logic on the friendly name is wrong.... 84% isn't life **remaining** - its life **used**
> 
> Ops, you are right 😒. Ok, question is, what is better to show as percentage? Remaining life (I will change the logic in the calculation) or Used life? In my opinion the first, because when it come to 0 means that you have to change, when is 100% is full capacity (as a battery). And renaming the sensor will invalidate the existing, not so good...

I think that the percentage should be remaining life.

**Comment by ollo69** [comment]
Ok, new version (0.28.4) ready with fix.

**Comment by ollo69** [comment]
Also did a little mistake in parenthesis order, that's the second commit,🤐

**Comment by gabi1324** [comment]
It is working fine. Is it possible to add a reset button?

**Comment by ollo69** [comment]
This is more complex, require additional commands and implementation of button platform in integration. Please open new FR for this, I will manage when I will have some more time available. 
I want to close this FR with the part related to the filter sensors implementation.

**Comment by ricoroodenburg** [comment]
> Hi @ollo69 ,
> 
> Unfortunately I don’t get the filter status after updating to the latest version. I’m using the S12EW split unit.

Solved by the latest release :)

**Comment by cynicer** [comment]
Looks good to me, thanks! Will follow up with a FR for the reset button.

**Comment by ollo69** [comment]
I temporary reopen this because I think that still there are some issue with device that return filter status directly in the payload.

@SN0WTR00PER,

please report here your issue reported in #445 and your current diagnostic👍

**Comment by SN0WTR00PER** [comment]
> I temporary reopen this because I think that still there are some issue with device that return filter status directly in the payload.
> 
> @SN0WTR00PER,
> 
> please report here your issue reported in #445 and your current diagnostic👍

Hi Ollo,

You can find my 2 diag files attached to my reply.  One on V0.28.2 and the other on V0.28.4.  On the V0.28.2, everything is normal, on V0.28.3, it no longer work and same thing on V0.28.4.  I downgraded to V0.28.2 and everything works fine again.   Other that that, I don't know whats the culprit...  
[Diag on V0.28.2.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10357072/Diag.on.V0.28.2.txt)
[Diag on V0.28.4.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10357073/Diag.on.V0.28.4.txt)

**Comment by ollo69** [comment]
@SN0WTR00PER,

the issue should be fixed with last release, but remain an open point. In last releases I review the method used to calculate the percentage for remaining filter because it was inverted (see some topic above). You said that the value in integration was the same displayed in mobile app, but are representing the same value? Please make test and give me your feed-back.

**Comment by SN0WTR00PER** [comment]
@ollo69

I'll check that during the weekend.  I'll give you an update.

**Comment by SN0WTR00PER** [comment]
@ollo69 

Hi,

Finally, after updating to V0.29.0, instead of having 81% of remaining life, I have 18% (inverted as you stated in your reply).

**Comment by ollo69** [comment]
And 81% is the correct remaining life?

**Comment by SN0WTR00PER** [comment]
@ollo69 Yes, exactly, 100%=new 0%=filter change or cleaning required

**Comment by SN0WTR00PER** [comment]
I don't know if its the same thing for all LG product that have a filter.

**Comment by ollo69** [comment]
I still do not understand if correct filter life for your filter is 18% or 81%.

**Comment by SN0WTR00PER** [comment]
> I still do not understand if correct filter life for your filter is 18% or 81%.

18 is wrong. The correct value is 80%...  As I write this, its at 80% now.  Check my edited answer with screenshot HA and LG app.

**Comment by SN0WTR00PER** [comment]
@ollo69 Oh, and there is a difference of 1% between the LG app and HA...  Dunno why...

**Comment by ollo69** [comment]
Ok, I hope that last release finally fix this last issue. Please test it and let me know.

**Comment by SN0WTR00PER** [comment]
@ollo69 Uodated since yesterday.  Everything is fine.  Thanks!

**Comment by ollo69** [comment]
Finally😁. Ok, I close this thread, if somebody find new problem please open a new issue.
