### ISSUE TITLE
Energy consumption and current temperature for AC not displayed despite being returned in JSON

### ISSUE THREAD

**Issue by R1DEN** [ollo69/ha-smartthinq-sensors#378]
**Describe the bug**
Energy consumption and current temperature for AC not displayed despite being returned in JSON

**Expected behavior**
I expected the consumption to be displayed. And the temperature to be available as an entity and not just only inside the climate object.

**Screenshots**
![image](https://user-images.githubusercontent.com/22258651/186150442-a26fb9b9-ab47-4ef7-9344-16167cac9f97.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Supervised home assistant
 - Home Assistant version installed: 2022.8.6
 - Component version installed: 0.24.2
 - Last know working version: none 
 - LG device type and model with issue: LG B12TS
 - LG devices connected (list):  LG B12TS (x2), washing machine, fridge

**Output of HA logs**
[config_entry-smartthinq_sensors-cb265dc3eac64e23d0368f0546ee32c6.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9402210/config_entry-smartthinq_sensors-cb265dc3eac64e23d0368f0546ee32c6.json.txt)

**Comment by ollo69** [comment]
This 2 sensors are disabled by default. Click on it and enable.

**Comment by R1DEN** [comment]
@ollo69 oh, thanks. That was a rather easy fix)
