### ISSUE TITLE
Unable to create automation on HVAC status changed

### ISSUE THREAD

**Issue by b0ne** [ollo69/ha-smartthinq-sensors#379]
When you try to create an automation on HVAC Status Changed homme assistant give an error

Message malformed: required key not provided @ data['to']

**Expected behavior**
Should ask witch HVAC mode 
Or Switch opiton to HVAC Off, HVAC Cool, HVAC Heat

![image](https://user-images.githubusercontent.com/971968/186497313-1a8a38da-7edb-45f2-9b30-8a1d7edf091a.png)

**Environment details:**
 - Environment: Hassio
 - Home Assistant version installed: 2022.08.3
 - Component version installed:  0.24.2
 - Last know working version: n/a

**Comment by ollo69** [comment]
You need to ask support to HA community or refer to [HA automation documentation](https://www.home-assistant.io/docs/automation/), and eventually open issue to Home Assistant. This is not an issue related to this integration.
