### ISSUE TITLE
LG Refrigerator is not displaying fridge temperature

### ISSUE THREAD

**Issue by MrHollowPS** [ollo69/ha-smartthinq-sensors#38]
![image](https://user-images.githubusercontent.com/5260147/81785184-a80d2e80-9506-11ea-8de4-3dbb7c519c04.png)

model: 1REB1GLPX1___-BF
mac_address: '#####'
refrigerator_temp: '-'
freezer_temp: '-17'
temp_unit: °C
door_open_state: 'off'
smart_saving_mode: Smart Saving Not Used
smart_saving_state: '-'
eco_friendly_state: 'Off'
ice_plus_state: 'Off'
fresh_air_filter_state: unknown
water_filter_used_month: '255'
friendly_name: Refrigerator
icon: 'mdi:fridge-outline'

The refrigerator_temp is not displayed at all, and i think the smart_saving_state is alos not diplayed properly. I can help test if needed.

**Comment by ollo69** [comment]
In the HA log file you should have an information log like this:

```
2020-04-30 01:46:54 INFO (SyncWorker_0) [custom_components.smartthinq_sensors.wideq.core_v2] Loading model info for LAVATRICE. Model: WTWN3, Url: <the url>
```

Can you please post the url indicated in your log so that I can download json file related to your model and check provided states by your devices?

Thx

**Comment by MrHollowPS** [comment]
https://eic.lgthinq.com:46030/api/webContents/modelJSON?modelName=1REB1GLPX1___&countryCode=WW&contentsId=JS0213025419441577&authKey=thinq

**Comment by MrHollowPS** [comment]
I'll give it a try as soon as i refix my whole setup, i started tinkering with my whole server. I'll update the bug if it's not working.

Thanks a lot for your support :)

**Comment by MrHollowPS** [comment]
All good, can be closed :)
