### ISSUE TITLE
Display Light Toggle not working

### ISSUE THREAD

**Issue by digginsa** [ollo69/ha-smartthinq-sensors#380]
Hello,

First thank you for all the work on this integration amazing work, with the new display light function my aircons make a noise when the toggle is toggled but they do not turn the display light off or on.

**Comment by oksibutch** [comment]
Im have this problem too my model in HA RAC_056905_WW-RAC (AC)
LG
diagnostic data:
[smartthinq_sensors-c57a8c55f0da6be77ce845adac50f79b-Кондиционер Зал-5876ecc9316ce783762b62cfdfdcb902.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9625436/smartthinq_sensors-c57a8c55f0da6be77ce845adac50f79b-.-5876ecc9316ce783762b62cfdfdcb902.json.txt)

**Comment by AlexandreLogist** [comment]
Also having the same issue, but will have a look if I can solve it :)

**Comment by DBuit** [comment]
Have the same issue, and same model as @oksibutch

**Comment by AlexandreLogist** [comment]
I checked the API and I do not think that this action is supported ...

**Comment by oksibutch** [comment]
Yes it’s still not working
