### ISSUE TITLE
cannot set eco mode on card - lg lw1017ersm wifi air conditioner

### ISSUE THREAD

**Issue by james28909** [ollo69/ha-smartthinq-sensors#382]
**Describe the bug**
cannot select eco mode on the card with lg air conditioner

**Expected behavior**
expected to be able to set eco mode on the card itself but as it is right now, i have to click the three dots on the card then sel;ect the eco preset. shouldnt it be on the card itself?

**Screenshots**
![eco1](https://user-images.githubusercontent.com/16311827/188485130-4e58f621-5ced-45be-aef3-05fec0505e05.png)
![eco](https://user-images.githubusercontent.com/16311827/188484463-c95661ec-c64c-496d-89bc-b752f67fdb7c.png)
![eco2](https://user-images.githubusercontent.com/16311827/188485338-0bb6f091-0548-4bbf-b8c3-08768e915e2d.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): home assistant OS 
 - Home Assistant version installed: 2022.8.7
 - Component version installed: 0.24.2
 - Last know working version: N/A
 - LG device type and model with issue: lg lw1017ersm
 - LG devices connected (list): lg lw1017ersm

**Output of HA logs**
there is no log because i am able to select eco mode from the three dots on the card -> preset drop down, but cant select on the card panel itself

**Additional context**
i guess 'eco' should be added as an additional 'operation' rather than a 'preset'

**Comment by james28909** [comment]
here is the json file: 
[config_entry-smartthinq_sensors-0985ecb15298d2351b84841a37aa7a10.zip](https://github.com/ollo69/ha-smartthinq-sensors/files/9555703/config_entry-smartthinq_sensors-0985ecb15298d2351b84841a37aa7a10.zip)

**Comment by james28909** [comment]
has this been addressed yet?

**Comment by james28909** [comment]
i would contribute but i am not sure where i need to edit.

**Comment by ollo69** [comment]
This is not an integration issue, and is not an issue at all.
Eco is a preset and not an operation in HA. The standard HA climate card do not provide preset mode settings. You can use alternative card that you can download from HACS, or, if you want to have this feature in native HA climate card, you should open a feature request to HA frontend.

**Comment by ollo69** [comment]
Closing this because there i nothing to do integration side.
