### ISSUE TITLE
Add Water Heater / Heatpump

### ISSUE THREAD

**Issue by Xnyle** [ollo69/ha-smartthinq-sensors#386]
ThinQ connected and providing data, yet no devices appear.

This is what I get from the logs. I redacted all tokens / ids.

Hope with this info, integration / mapping should be pretty straightforward.

    "unsupported_devices": {
      "WATER_HEATER": [
        {
          "appType": "NUTS",
          "modelCountryCode": "WW",
          "countryCode": "DE",
          "modelName": "WHT_056905_WW",
          "deviceType": 406,
          "deviceCode": "AI07",
          "alias": "XXXXXXXX",
          "deviceId": "XXXXXXXX",
          "fwVer": "",
          "imageFileName": "",
          "ssid": "XXXXXXXX",
          "softapId": "",
          "softapPass": "",
          "macAddress": "",
          "networkType": "02",
          "timezoneCode": "Europe/Berlin",
          "timezoneCodeAlias": "Europe/Berlin",
          "utcOffset": 1,
          "utcOffsetDisplay": "+01:00",
          "dstOffset": 2,
          "dstOffsetDisplay": "+02:00",
          "curOffset": 2,
          "curOffsetDisplay": "+02:00",
          "sdsGuide": "{\"deviceCode\":\"AI07\"}",
          "newRegYn": "N",
          "remoteControlType": "",
          "userNo": "**REDACTED**",
          "tftYn": "N",
          "modelJsonVer": 2.01,
          "modelJsonUri": "XXXXXXXX",
          "appModuleVer": 1.03,
          "appModuleUri": "XXXXXXXX",
          "appRestartYn": "Y",
          "appModuleSize": 5511058,
          "langPackProductTypeVer": 6.5,
          "langPackProductTypeUri": "XXXXXXXX",
          "deviceState": "E",
          "snapshot": {
            "fwUpgradeInfo": {
              "upgSched": {
                "upgUtc": "0",
                "cmd": "none"
              }
            },
            "static": {
              "deviceType": "406",
              "countryCode": "DE"
            },
            "airState.tempState.hotWaterCurrent": 50.0,
            "airState.tempState.unit": 0.0,
            "airState.diagCode": 0.0,
            "airState.miscFuncState.extraOp": 0.0,
            "airState.tempState.hotWaterTarget": 55.0,
            "mid": 64831710.0,
            "airState.energy.accumulated": 26.0,
            "airState.energy.onCurrent": 50.0,
            "airState.quality.sensorMon": 0.0,
            "airState.energy.accumulatedTime": 344.0,
            "airState.operation": 1.0,
            "meta": {
              "allDeviceInfoUpdate": false,
              "messageId": "XXXXXXXX"
            },
            "online": true,
            "airState.opMode": 26.0,
            "airState.filterMngStates.maxTime": 4320.0,
            "airState.filterMngStates.useTime": 4278.0,
            "airState.preHeat.schedule": 0.0,
            "timestamp": 1664788881211.0
          },
          "online": true,
          "platformType": "thinq2",
          "area": 167921,
          "regDt": 20221002172222.0,
          "blackboxYn": "Y",
          "modelProtocol": "STANDARD",
          "order": 0,
          "drServiceYn": "N", 
          "guideTypeYn": "Y",
          "guideType": "WHT_TYPE1",
          "regDtUtc": "20221002152222",
          "regIndex": 0,
          "groupableYn": "N",
          "controllableYn": "N",
          "combinedProductYn": "N",
          "masterYn": "Y",
          "pccModelYn": "N",
          "sdsPid": {
            "sds4": "",
            "sds3": "",
            "sds2": "",
            "sds1": ""
          },
          "autoOrderYn": "N",
          "initDevice": false,
          "existsEntryPopup": "N",
          "tclcount": 0
        }
      ]

**Comment by FAB1150** [comment]
I have a water heater too (Therma V WH20S), so I'm interested too.

**Comment by sjoukebakker** [comment]
Yes please! This would be nice.

**Comment by Hideloop** [comment]
Would need this too.

**Comment by Svrbinek** [comment]
Hi, also please add this component. I can offer help with testing.

**Comment by ollo69** [comment]
This is duplicated of #332, please move to that thread and attach integration diagnostic so that I can collect additional information. I close this to not have multiple thread on same argument.
