### ISSUE TITLE
Login flow not working

### ISSUE THREAD

**Issue by Codendaal1120** [ollo69/ha-smartthinq-sensors#387]
Another login issue. I am not able to authenticate. 

I am trying to connect using a Local LG account (NL,en-NL). I can log into the android app and there are no further TOS I can accept.
I am running v0.24.2

If I follow the "redirect url method"  I can log into the LG site, which redirects me to another login form. If I use that url in HA, it says "Error connecting to SmartThinQ. Try again, and make sure you can access the ThinQ app on your phone". If I try to login again on the second form, it tells me that the account has already been registered for services in NL and if I want to use the UK services I need to register another account. The console shows : 

```
2022-10-04 11:50:35.874 ERROR (MainThread) [custom_components.smartthinq_sensors.config_flow] Error connecting to ThinQ

Traceback (most recent call last):
File "/config/custom_components/smartthinq_sensors/config_flow.py", line 206, in _check_connection
client = await lge_auth.create_client_from_token(
File "/config/custom_components/smartthinq_sensors/__init__.py", line 127, in create_client_from_token
return await ClientAsync.from_token(
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1255, in from_token
await client.refresh()
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1194, in refresh
self._auth = await self.auth.refresh(True)
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 777, in refresh
access_token, token_validity = await self._gateway.core.refresh_auth(
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 585, in refresh_auth
out = await self._auth_request(
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 552, in _auth_request
raise exc.TokenError()
custom_components.smartthinq_sensors.wideq.core_exceptions.TokenError

2022-10-04 11:50:35.875 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session

2022-10-04 11:50:35.876 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector
```

**Comment by RobertoCravallo** [comment]
Same here from Germany (DE). Can't for the life of me get this to work. Per App everything is fine.

**Comment by nhazdun** [comment]
Same from my side Ukraine(UK). Looks like LG has changed auth API.

**Comment by yfands** [comment]
Same here, NL-nl 

Accepted all Term and Services (even the ones I dont want) but still,

Invalid SmartThinQ credentials. Use the LG App on your mobile device to verify if there are Term of Service to accept. Account based on social network are not supported and in most case do not work with this integration.

Its a fiirst time clean install with a LG account no previous Social accounts.
Mobile App. works fine, Integration in HA cant pass Invalid SmartThinQ credentials, didnt try Use URL redirect authentication method or Share Home Assistant HTTP connection (may cause SSL errors).

Regards Frank

**Comment by zebrahosting** [comment]
Same login issues. Tried several accounts / countries / languages (what a mess is the app). Can login on the website and in the app. Set to US-EN.  Login says invalid credentials. Using the redirect URL option, I get an invalid signature.

**Comment by gabriel-peracio** [comment]
Same here, I had used the "redirect url method" initially and everything worked, until the app forced me to change my password, at which point I had to go change it and my integration broke.

Now, no methods work. The normal method just hangs and keeps spinning forever without displaying any errors, while the "redirect url method":
1. I visit the url provided by `ha-smartthinq-sensors`. It looks like `https://br.m.lgaccount.com/spx/login/signIn?country=BR&language=pt-BR&client_id=<ClientId>&svc_list=SVC202&svc_integrated=Y&show_thirdparty_login=<stuff>&division=<stuff>&oauth2State=<stuff>&show_select_country=N`
2. That shows a login page. I enter my credentials in that page
3. I get redirected to another url that looks like `https://br.m.lgaccount.com/spx/login/signIn?access_token=<someHash>&refresh_token=<someHash>&oauth2_backend_url=https://us.lgeapi.com/`
4. I log in to THAT page, and get a popup saying "This account was already used to subscribe to Brazil.
To use services of U.S.A, please subscribe with a new account."

The first time, it did work, now it doesn't

If I simply paste the url I get pointed at in the first redirect, ha-smartthinq-sensors accepts that as valid, but again it hangs forever.

Unlike @yfands, I am already using my LG username as my login, and that did not work.

**Comment by gabriel-peracio** [comment]
on the second form, you can append `&country=BR&client_id=LGAO221A02` (replace the values with the ones `ha-smartthinq-sensors` gave you in the first field

This will let you get past the "This account was already used to subscribe..." message, but you will get redirected to a third login field. If you append the url again and login again, you get a fourth login field. Ad infinitum.

**Comment by amacomber** [comment]
Having this same issue with US-en.
Issue is exactly as described above. I can login to the App and accepted any TOS that I could find. 
symptoms are exactly the same as https://github.com/ollo69/ha-smartthinq-sensors/issues/387#issuecomment-1309211249

**Comment by gabriel-peracio** [comment]
I created another US account, and this time it shows "cannot show page" when logging in in the second login page. Seems to be triggered by a lack of `division: "LGAO221A02"` and `division: "ha:T20"` in the query params.

If you add the query params back in (either through modifying the URL or injecting it in the debugger), it works, but you get back to an infinite redirection flow. You do get the `access_token` and `refresh_token` though, and walking through their awful jquery code and translating the comments, it seems to go through a normal login flow and there's nothing wrong besides the stripped query params. There are no "terms" or special things to accept, if you go by what the code says.

**Comment by gabriel-peracio** [comment]
Sometimes, if you login to the first form and just copy the url you get redirected to after that (do NOT login to the second form, just copy the url), the integration will say "configuration successful".

It still gets stuck in "initializing" though.

**Comment by zebrahosting** [comment]
What login method did you use? I am still having the same troubles with both US and NL accounts

**Comment by zebrahosting** [comment]
Last update worked for me.

**Comment by skinkie** [comment]
Today my integration stopped working. I have already done a password reset, and upgraded the component, but it remains broken.

```2022-12-10 22:32:07.174 ERROR (MainThread) [custom_components.smartthinq_sensors.config_flow] Invalid ThinQ credential error. Please use the LG App on your mobile device to verify if there are Term of Service to accept. Account based on social network are not supported and in most case do not work with this integration.
Traceback (most recent call last):
  File "/home/skinkie/.homeassistant/custom_components/smartthinq_sensors/wideq/core_async.py", line 769, in from_user_login
    token_info = await gateway.core.auth_user_login(
  File "/home/skinkie/.homeassistant/custom_components/smartthinq_sensors/wideq/core_async.py", line 500, in auth_user_login
    raise exc.TokenError()
custom_components.smartthinq_sensors.wideq.core_exceptions.TokenError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/skinkie/.homeassistant/custom_components/smartthinq_sensors/config_flow.py", line 202, in _check_connection
    client = await lge_auth.create_client_from_login(username, password)
  File "/home/skinkie/.homeassistant/custom_components/smartthinq_sensors/__init__.py", line 125, in create_client_from_login
    return await ClientAsync.from_login(
  File "/home/skinkie/.homeassistant/custom_components/smartthinq_sensors/wideq/core_async.py", line 1271, in from_login
    auth = await Auth.from_user_login(gateway, username, password)
  File "/home/skinkie/.homeassistant/custom_components/smartthinq_sensors/wideq/core_async.py", line 778, in from_user_login
    raise exc.AuthenticationError("User login failed") from ex
custom_components.smartthinq_sensors.wideq.core_exceptions.AuthenticationError: User login failed
```

**Comment by skinkie** [comment]
> Did you check for new Term of Service in mobile apps?

I think I broke it by uninstalling / reinstalling the app. Upon login, only a cookie request is done. Nothing like a ToS to accept.

**Comment by skinkie** [comment]
Just tried it with https://github.com/mgwoj/Thinq-MQTT-Proxy which is capable of succesfully loging in via a redirect method.

**Comment by ollo69** [comment]
> Just tried it with https://github.com/mgwoj/Thinq-MQTT-Proxy which is capable of succesfully loging in via a redirect method.

That's an interesting project, may be in the future I will take a look if it can provide any improvement for ThinQ library implemented here. But this have nothing to do with this project and I have no time to analyze that now. If you are able to find the reason for which it works there and not here for you, I will be happy to analyze that details.

**Comment by skinkie** [comment]
@ollo69 when taking the redirect approach I end up with the error below. Is there any way to develop and test this component outside the realm of homeassistant?
```
2022-12-11 00:29:44.803 ERROR (MainThread) [custom_components.smartthinq_sensors.config_flow] Error connecting to ThinQ
Traceback (most recent call last):
  File "/home/skinkie/.homeassistant/custom_components/smartthinq_sensors/config_flow.py", line 204, in _check_connection
    client = await lge_auth.create_client_from_token(
  File "/home/skinkie/.homeassistant/custom_components/smartthinq_sensors/__init__.py", line 137, in create_client_from_token
    return await ClientAsync.from_token(
  File "/home/skinkie/.homeassistant/custom_components/smartthinq_sensors/wideq/core_async.py", line 1311, in from_token
    await client.refresh()
  File "/home/skinkie/.homeassistant/custom_components/smartthinq_sensors/wideq/core_async.py", line 1238, in refresh
    self._auth = await self.auth.refresh(True)
  File "/home/skinkie/.homeassistant/custom_components/smartthinq_sensors/wideq/core_async.py", line 814, in refresh
    access_token, token_validity = await self._gateway.core.refresh_auth(
  File "/home/skinkie/.homeassistant/custom_components/smartthinq_sensors/wideq/core_async.py", line 618, in refresh_auth
    out = await self._auth_request(
  File "/home/skinkie/.homeassistant/custom_components/smartthinq_sensors/wideq/core_async.py", line 585, in _auth_request
    raise exc.TokenError()
custom_components.smartthinq_sensors.wideq.core_exceptions.TokenError
```

Personally I would be _much_ more interested in a project like ["grott"](https://github.com/johanmeijer/grott/), preventing any external access. If it would be as simple as firing up a local MQTT server, and hacking a redirect, then this looks a much more future proof method outside of the walled garden of LG.

**Comment by ollo69** [comment]
> Is there any way to develop and test this component outside the realm of homeassistant

Separate the ThinQ library from the HA integration is one of the task in my queue, but I will do that when I will finish to integrate most of the LG device (a lot by the way). For now it is more simple to maintain everything in the same place, but you can take what is in wideq folder and use it without the integration, this is the way in which this has be designed.

> Personally I would be _much_ more interested in a project like ["grott"](https://github.com/johanmeijer/grott/), preventing any external access. If it would be as simple as firing up a local MQTT server, and hacking a redirect, then this looks a much more future proof method outside of the walled garden of LG.

Have a separate "service" to install is an option to consider, but it will not so simple to manage for everybody. I think that the value add that those LG library provide is the possibility to receive notification, that is much more efficient than polling. But from what I can see the last update on that project was more than 1 year ago and the supported devices are limited. As first step if you can find the reason for your token error and can provide solution, it will be really welcome. Probably this will fix some of authentication error reported by some users.

**Comment by skinkie** [comment]
Just tried to login again. And it now worked.

**Comment by ollo69** [comment]
> What I would like to see happening is a service that substitutes the entire LG cloud.

Because LG is the provider of the service connected with their devices, I think that this will never happen. Most probably LG could choose to change something and totally block access  by "not official" devices. LG cloud is not open source, and they can do what they prefer,

This thread is quite old and I don't see any update from the user who open this. Because in last release I implement some improvement in `url connection` method, I hope that this issue is solved. 

If not please open a new one with the current problems.👍
