### ISSUE TITLE
Example of simple usage in Python

### ISSUE THREAD

**Issue by arthurlapertosa** [ollo69/ha-smartthinq-sensors#388]
Hello! I'd like to use this library to integrate with my program built on top of the original https://github.com/sampsyo/wideq. I have devices from api v2 and that's why I'm trying to migrate to this library.
I saw you don't have an `example.py` like the `wideq` library has, so I tried to create a snippet to make it get information from my AC, but I couldn't make it work.
The snippet is:
```
from wideq.core_async import ClientAsync, CoreAsync, lg_client_session
from wideq.ac import AirConditionerDevice
import asyncio

async def get_login():
    core = CoreAsync(country='BR', language='pt-BR')
    gateway = await core.gateway_info()
    auth = await ClientAsync.oauth_info_from_url('(I pasted the callback url here)')
    user_number = await core.get_user_number(auth['oauth_url'], auth['access_token'])
    auth['user_number'] = user_number
    client = ClientAsync.load({'auth': auth, 'gateway': gateway, 'session': lg_client_session(), 'country': 'BR', 'language': 'pt-BR'})
    await client.refresh_devices()

    device = client.get_device('844e329b-d43b-564a5-bsa5-1c39291e6106')
    ac = AirConditionerDevice(client, device)

    resp = await ac.poll()
    print(resp)

asyncio.run(get_login())
```
When I run this code, it returns a 'Not logged in error' (in the `client.refresh_devices()` call). Could you please help me to get this working, or maybe point me out some python script with a basic usage of the `wideq` library, please?

**Comment by pifou25** [comment]
Hello @arthurlapertosa 
I also tried to build a simple `example.py` like yours but there is no function `from_login` did you use some like the `get_oauth_info_from_login` but seems specific to HAss... what else ? Did you make some fork with a public example ?
