### ISSUE TITLE
Remaining time and other values not displayed

### ISSUE THREAD

**Issue by benjR** [ollo69/ha-smartthinq-sensors#389]
**Describe the bug**

Hi there!
First of all, thanks for the work done on this project, it's really nice !
On my side, I have a Washer/Dryer (combined) and some informations don't seem to be displayed, but are displayed in the LG app and seem to be available in the data being sent, I'm not sure if it's a bug or a lack of implementation.

The most important for me would be the remaining time, but there are lot of fields that seem to be available and used on other models and handled in the integration and doesn't seem to be the case for mine ?

**Expected behavior**
Have more data being used by the integration, most of all remaining time would be nice

**Screenshots**
This is what is available today : (I removed the integration and added it back to make sure there wasn't more being displayed)
<img width="256" alt="image" src="https://user-images.githubusercontent.com/1074675/195840764-5954c2c5-fc20-4aea-b2e0-aa617c535a16.png">

**Environment details:**
 - LG device type and model with issue: Washing/Dryer machine F964V72WRHT
 - LG devices connected (list): Washing/Dryer machine F964V72WRHT

**Output of HA logs**
Paste the relavant output of the HA log here.

[washingdryer.zip](https://github.com/ollo69/ha-smartthinq-sensors/files/9786157/washingdryer.zip)

**Additional context**

**Comment by ollo69** [comment]
Sensor in `gray` are just `disabled by default`. Click on the sensor you need and select `Enabled`. After 30 sec the sensor will be available for your scope

**Comment by benjR** [comment]
many thanks @ollo69 working, perfect, sorry for the noob question!
