### ISSUE TITLE
Is it possible to auto-update the card code, or move it to a Lovelace HACS component?

### ISSUE THREAD

**Issue by igorsantos07** [ollo69/ha-smartthinq-sensors#391]
**Is your feature request related to a problem? Please describe.**
Currently, we have to copy-paste the card code into our HA installation. That's prone to get outdated, since there's no auto-updates following the main component changes.

**Describe the solution you'd like**
- not sure if it's possible to bundle the card together with the component?
- if not so, extract the card into its own component, so we can update it with the rest of our custom cards

**Additional context**
My card was kinda broken, and it took me a while trying to figure out where it came from - the card name (lg-laundry-card) returned sparse results from Google, and I couldn't find it in HACS. I went into the file editor to find its source, and luckily I had left a comment above the code with a link to this repo. Guess what? The card code was severely refactored and I had to re-paste the new code. It was also hard to get a refresh to work, which is usually friendlier when done via HACS.

**Comment by rksim** [comment]
STOP EMAILING ME

**Comment by ollo69** [comment]
@rksim,

Nobody is emailing you. You probably are receiving notifications related to your subscription. You are the only one that can know your subscription and can disable them.

**Comment by rksim** [comment]
![Uploading 4FC8B009-F742-4E07-8A29-A613A3C681B1.jpeg…]()
