### ISSUE TITLE
LG Thinq Range Hood Support

### ISSUE THREAD

**Issue by Jonkieber** [ollo69/ha-smartthinq-sensors#394]
**Is your feature request related to a problem? Please describe.**
Is it possible to support LG Range hoods? Link below.
https://www.lg.com/us/cooking-appliances/lg-hced3015s-range-hood#

**Describe the solution you'd like**
It would be great if I could import my range hood to automate fan/light control

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by matthai5** [comment]
I'd like to request the same. Thanks!

**Comment by ollo69** [comment]
Please attach integration diagnostic

**Comment by ollo69** [comment]
Any update here? Could someone attach diagnostics?

**Comment by Jonkieber** [comment]
Here you go
[smartthinq_oven_diagnostics.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10485635/smartthinq_oven_diagnostics.txt)

**Comment by ollo69** [comment]
@Jonkieber,

in attached diagnostic I just see oven and dishwasher, no Range Hood.

**Comment by Jonkieber** [comment]
Strange, I have it visible in my LG app, I wonder why it wouldn't show up?

I currently have my LG Dishwasher, Front Load Washer, Dryer, Oven and Refrigerator showing up in Homeassistant.

The only thing that doesn't appear is my hood.

**Comment by chaliluc** [comment]
Hi @ollo69 ,
my hood shows under 'unsupported_devices'.
[unsupported_devices.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10864417/unsupported_devices.txt)
Let me know if you need anything else, I'll be glad to help get this integrated (especially the lights)!

**Comment by crdnl** [comment]
Additionally, I also have the hood showing in unsupported devices:
[full diagnostics](https://github.com/ollo69/ha-smartthinq-sensors/files/10924204/config_entry-smartthinq_sensors-b6ae914a14732b6406ce71c74d697e1b.json.txt)

**Comment by pknaz** [comment]
I'm also interested in this feature request, thanks!

Range Hood

**Comment by pknaz** [comment]
"HOOD": [
        {
          "appType": "NUTS",
          "modelAppType": "NUTS",
          "modelCountryCode": "WW",
          "countryCode": "US",
          "modelName": "STUDIO_HOOD",
          "deviceType": 304,
          "deviceCode": "KI09",
          "alias": "Hood",
          "deviceId": "76b907bb-5805-1193-8db5-24e8536cd594",
          "fwVer": "",
          "imageFileName": "home_appliances_img_hood.png",
          "imageUrl": "https://objectcontent.lgthinq.com/43712709-2ec9-439d-84c9-2951db0ae32e?hdnts=exp=1702976416~hmac=b9ff1edb67659a91ed2ab9784748fd02147f89a8dcf9f0c6dc58204fabc6b570",
          "smallImageUrl": "https://objectcontent.lgthinq.com/05dd536f-c9f9-4060-8009-76f1fffd82f4?hdnts=exp=1701655219~hmac=8696f32f6e246d9536b542692f501441eec5e3344a3be101078eaf4f022e1428",
          "ssid": "**REDACTED**",
          "softapId": "",
          "softapPass": "",
          "macAddress": "",
          "networkType": "02",
          "timezoneCode": "America/New_York",
          "timezoneCodeAlias": "USA/New_York",
          "utcOffset": -5,
          "utcOffsetDisplay": "-05:00",
          "dstOffset": -4,
          "dstOffsetDisplay": "-04:00",
          "curOffset": -4,
          "curOffsetDisplay": "-04:00",
          "sdsGuide": "{\"deviceCode\":\"KI09\"}",
          "newRegYn": "N",
          "remoteControlType": "",
          "userNo": "**REDACTED**",
          "tftYn": "N",
          "modelJsonVer": 0.61,
          "modelJsonUri": "https://objectcontent.lgthinq.com/b8d132ea-1ce8-47c8-90a1-127db64f0bb6?hdnts=exp=1696845622~hmac=43be0188e6be218f2990a94bc838eb270d174789c8170a9b4217388a5ea9d469",
          "appModuleVer": 211.22,
          "appModuleUri": "https://objectcontent.lgthinq.com/ed6520ba-814e-461d-9915-8b520ed391e1?hdnts=exp=1697090442~hmac=3b8f67a23c3c4c33278c7d159bfc9b0a08ea978a0f12ce43ab0f4e1b5a518079",
          "appRestartYn": "Y",
          "appModuleSize": 1290039,
          "langPackProductTypeVer": 54.0,
          "langPackProductTypeUri": "https://objectcontent.lgthinq.com/b65c61a3-5bb0-47fb-9c02-141a2b9e97c9?hdnts=exp=1746613954~hmac=a8fd1a060a6d47be47b7f583614a7fc68b5443a5e2c530cfff88092692c85672",
          "deviceState": "E",
          "snapshot": {
            "mid": 1521951.0,
            "online": true,
            "hoodState": {
              "ventMode": "NOT_SET",
              "dummyData": 0.0,
              "error": "DISABLE",
              "ventLevel": 0.0,
              "lampSet": "ENABLE",
              "remainTimeMinute": 0.0,
              "ventSet": "ENABLE",
              "hoodFotaEnable": "ENABLE",
              "remainTimeSecond": 0.0,
              "childLock": "DISABLE",
              "standyMode": "DISABLE",
              "lampLevel": 0.0,
              "hoodState": "INIT"
            },
            "static": {
              "deviceType": "304",
              "countryCode": "US"
            },
            "meta": {
              "allDeviceInfoUpdate": false,
              "messageId": "zdzhfug2Toq_TEv8hRxBbg"
            },
            "timestamp": 1686956222640.0
          },
          "online": true,
          "platformType": "thinq2",
          "area": 334505,
          "regDt": 20220408161746.0,
          "blackboxYn": "Y",
          "modelProtocol": "STANDARD",
          "order": 0,
          "drServiceYn": "N",
          "modemInfo": {
            "appVersion": "clip_hna_v1.9.183",
            "modelName": "STUDIO_HOOD",
            "modemType": "QCOM_QCA4010",
            "ruleEngine": "y"
          },
          "guideTypeYn": "Y",
          "guideType": "TYPE1",
          "regDtUtc": "20220408201746",
          "regIndex": 0,
          "groupableYn": "N",
          "controllableYn": "N",
          "combinedProductYn": "N",
          "masterYn": "Y",
          "pccModelYn": "N",
          "autoOrderYn": "N",
          "initDevice": false,
          "existsEntryPopup": "N",
          "tclcount": 0
        }
      ]

**Comment by pknaz** [comment]
This request still in "requesting feedback" - is there anything else we could provide?

**Comment by ollo69** [comment]
Time for me 😉

**Comment by pknaz** [comment]
> Time for me 😉

You got it! :)

**Comment by ollo69** [comment]
@ALL,

sorry for this but I wait to match time to work on this and the link in the attached files are expired, so I cannot download model info to implement this. 
Please attach a new diagnostic file, I will take this with priority.

**Comment by pknaz** [comment]
[config_entry-smartthinq_sensors-b1727a4bba7498b65639a1ed31f050fe.json (1).txt](https://github.com/ollo69/ha-smartthinq-sensors/files/12907637/config_entry-smartthinq_sensors-b1727a4bba7498b65639a1ed31f050fe.json.1.txt)

**Comment by pknaz** [comment]
[config_entry-smartthinq_sensors.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/12907659/config_entry-smartthinq_sensors.json.txt)

Here ya go, just downloaded this a few minutes ago

**Comment by ollo69** [comment]
Hood support is now available in last release. Honestly I have no idea if controls works, I don't have a Hood to test. Please report here your results.

**Comment by ollo69** [comment]
Any update here?

**Comment by matthai5** [comment]
> Any update here?

Sorry for the long wait, I appreciate all your hard work on this. Since the update the integration shows the Range Hood as a device and lists a fan and light control which can be toggled on and off but unfortunately, it fails to turn on/off the Range Hood fan or light. 

A sensor for the hood is also shown but it remains "OFF" regardless of the range hood status. Let me what info you would need to look into this further.
Cheers!

**Comment by ollo69** [comment]
Does the light and fan controls follow the states of the Hood? It is only a problem related to the controls and reported states are correct?

**Comment by matthai5** [comment]
Home Assistant shows the correct options for the entity, but they do not
control the range hood. The state also does not show the current status of
the hood.

**Comment by chaliluc** [comment]
In my case the states are reported properly but with a slight delay (20-30
seconds).
Controlling the hood doesn't work.
If I turn on the light in home assistant, it shows ON for 20-30 seconds
before the real state of the hood updates the home assistant switch back to
the off position.

Le jeu. 16 nov. 2023, à 07 h 55, matthai5 ***@***.***> a
écrit :

> Home Assistant shows the correct options for the entity, but they do not
> control the range hood. The state also does not show the current status of
> the hood.
>

**Comment by ollo69** [comment]
Delay is normal, this integration poll cloud every 30 seconds.
Related to the control, I just try to use the same logic used in microwave, because model info was very similar, but unfortunately this doesn't work.
I could do another try based on another project, but not sure that will solve. 
The best solution should be that someone with a Hood analyze the traffic as described [here](https://github.com/ollo69/ha-smartthinq-sensors#obtaining-api-information) and provide me right command to control the device. There are someone here that can do this?

**Comment by ollo69** [comment]
Please check if with last release vent and lamp controls works. Thanks 👍

**Comment by chaliluc** [comment]
I just installed the latest version. With the new version, trying to
control the hood causes errors in the log.

The below log entry was added when I attempted to control the light:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:230
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 19:49:57 (2 occurrences)
Last logged: 19:49:58

[547146780608] 9006 - {'data': ''}
Traceback (most recent call last):
  File
"/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py",
line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in
async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in
_execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py",
line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876,
in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948,
in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py",
line 580, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/smartthinq_sensors/light.py", line 186,
in async_turn_on
    await self.entity_description.set_effect_fn(self._api, effect)
  File
"/config/custom_components/smartthinq_sensors/wideq/devices/hood.py", line
107, in set_light_mode
    await self.set(CMD_SET_VENTLAMP, cmd, key=STATE_LAMPLEVEL, value=level)
  File
"/config/custom_components/smartthinq_sensors/wideq/devices/hood.py", line
138, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line
550, in set
    await self._set_control(full_key, ctrl_path=ctrl_path)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line
522, in _set_control
    await self._client.session.device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py",
line 1193, in device_v2_controls
    res = await self.post2(cmd_path, payload)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py",
line 1030, in post2
    return await self._auth.gateway.core.lgedm2_post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py",
line 347, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py",
line 360, in _manage_lge_result
    raise exc.APIError(message, code)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 9006 -
{'data': ''}



Trying to turn on the fan at 100% produces a similar log entry:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:230
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 19:56:05 (1 occurrences)
Last logged: 19:56:05

[547146780608] 9006 - {'data': ''}
Traceback (most recent call last):
  File
"/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py",
line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in
async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in
_execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py",
line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876,
in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948,
in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/fan.py", line 357, in
async_set_percentage
    await self._wrapper.async_turn_on(speed=named_speed)
  File "/config/custom_components/smartthinq_sensors/fan.py", line 253, in
async_turn_on
    await self.async_set_speed(on_speed)
  File "/config/custom_components/smartthinq_sensors/fan.py", line 234, in
async_set_speed
    await self._description.set_fanspeed_fn(self._api, speed)
  File
"/config/custom_components/smartthinq_sensors/wideq/devices/hood.py", line
132, in set_vent_speed
    await self.set(CMD_SET_VENTLAMP, cmd, key=STATE_VENTLEVEL, value=level)
  File
"/config/custom_components/smartthinq_sensors/wideq/devices/hood.py", line
138, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line
550, in set
    await self._set_control(full_key, ctrl_path=ctrl_path)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line
522, in _set_control
    await self._client.session.device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py",
line 1193, in device_v2_controls
    res = await self.post2(cmd_path, payload)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py",
line 1030, in post2
    return await self._auth.gateway.core.lgedm2_post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py",
line 347, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py",
line 360, in _manage_lge_result
    raise exc.APIError(message, code)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 9006 -
{'data': ''}


I hope this gives you something to work with.
I personally prefer failure with error messages over no error and no
results :-)

**Comment by ollo69** [comment]
> I hope this gives you something to work with.

Honestly, no.
Because the previous command do not return any errors, probably was more correct that this one (but I suppose that something was missing)
But there are no change for me to guess the right command, the only possible solution is to capture the command. I hope that someone here will be able to follow the instruction in readme mentioned above and provide me the info.

**Comment by chaliluc** [comment]
I hope someone will be able to capture the information as well.
I really would like to help with that but I don't have the necessary
hardware to follow the August '23 recipe.

**Comment by ollo69** [comment]
Any news here? If someone is available to share his LG account (via private e-mail) I could make some test in my env.

**Comment by kevinbarmstrong1** [comment]
@ollo69 I am happy to share my LG account if that would help.   I too see all of the Range Hood controls but get a 'service call failed' error whenever I click on them.   Let me know best way to get that over to you and thanks again for all the help !!

**Comment by ollo69** [comment]
@kevinbarmstrong1,

thanks for your support.
You should send to me your LG credential (login name, password and country), if you prefer you can temporary change your password.
Send me the information to aolivero@gmail.com, I will keep you informed about the progress in the thread,
Just be ready that I need to turn on light and fan of your Hood to capture commands.

**Comment by ollo69** [comment]
@kevinbarmstrong1,

I successfully captured traffic using your account and LG app.
I understood that your device use ApiV1, so I'm still not be able to fix control for Hood that use APIv2.

I will work on this on next days when I will have some available time. If is not a problem for you, do not change your password account until I do not finish implementation so that I will be able to make some tests using integration.

Thanks again for your support👍

**Comment by ollo69** [comment]
Control for APIv1 is available in last release. I also rewrite control for APIv2 device, but I have no idea if this implementation works. Please test and report here results.

**Comment by kevinbarmstrong1** [comment]
@ollo69 sorry I'm not sure what I should do to test it --- i uninstalled from HACS and then tried reinstalling but I still get the same errors.  Is there something else I should do to get the APIv2 working ?  Thanks !

**Comment by ollo69** [comment]
> Is there something else I should do to get the APIv2 working ?

@kevinbarmstrong1 ,

as I see your device is APIv1 so it should work with last release. Can you eventually share error logs?

**Comment by kevinbarmstrong1** [comment]
it works !!!   I just updates your integration to the most recent version and now it controls the Hood Fan and Light.   Simply awesome @ollo69 - we really appreciate your help here !   Case closed and coffee coming your way :)

**Comment by ollo69** [comment]
> it works !!! I just updates your integration to the most recent version and now it controls the Hood Fan and Light.

Good to know and thanks for coffee🎉.
Still waiting for feed-back from some user that have APIv2 devices...

**Comment by drwicid** [comment]
My LG HCED3015S uses APIv2--I can confirm this update does not work with v2.

I have the detailed diagnostic log, python error log, and mitmproxy flows--I'll send those direct to you.

This is the payload to set hood state with POST method:
```
{
    "command": "Set",
    "ctrlKey": "setCookStart",
    "dataGetList": null,
    "dataKey": null,
    "dataSetList": {
        "hoodState": {
            "contentType": 34,
            "dataLength": 5,
            "lampLevel": 2,
            "lampOnOff": "ENABLE",
            "ventLevel": 3,
            "ventOnOff": "ENABLE",
            "ventTimer": 0              // See note
        }
    },
    "dataValue": null
}
```

This is the partial response payload with relevant hood state for GET method
```
{
    "result": {

        // Other attributes

        "snapshot": {
            "hoodState": {
                "childLock": "DISABLE",
                "dummyData": 0.0,
                "error": "DISABLE",
                "hoodFotaEnable": "ENABLE",
                "hoodState": "INIT",
                "lampLevel": 0.0,
                "lampSet": "ENABLE",
                "remainTimeMinute": 0.0,     // See note
                "remainTimeSecond": 0.0,     // 
                "standyMode": "DISABLE",
                "ventLevel": 3.0,
                "ventMode": "USER_MODE",
                "ventSet": "ENABLE"
            },
        },
    },

    // Other attributes

    "resultCode": "0000"
}
```

Observation on the ventTimer and remainTimeMinutes/Seconds Attributes

- The hood features a 5-minute auto-off timer, which can be activated by holding the power button for 3 seconds.
- The API can also initiate the auto-off timer based on the value of ventTimer, which accepts whole numbers between 1 and 5. However, the LG app sets ventTimer to 0 by default, as this feature is not available in the UI.
- The remainTimeMinutes/Seconds values in the API response are cached, reflecting the last update received from the hood. It seems the hood does not transmit state updates for each countdown tick, causing the minutes/seconds to remain unchanged until a significant state change occurs—either when the timer expires, turning off the fan/light, or if the fan/light settings are manually adjusted on the hood.
- Without an API call specifically designed to force the hood to send a current state update, accurately tracking the countdown is not feasible.

Lastly, I have 3 other LG devices using APIv2 if you need/want other traces:
- Refrigerator - LMXS28626S
- Dishwasher - LDTS5552S
- Double Wall Oven - LWD3063ST

**Comment by drwicid** [comment]
@ollo69 -- changing content type from 22 to 34 made this integration work with APIv2 hood.

https://github.com/ollo69/ha-smartthinq-sensors/blob/a0225317f3419308767272215438995ceae5be5e/custom_components/smartthinq_sensors/wideq/devices/hood.py#L37-L47

**Comment by badali16** [comment]
I have an LG hood which was not working and making the change recommend by ollo69 fixed it for me.  Thank you!
