### ISSUE TITLE
LG refrigerator temp not showing

### ISSUE THREAD

**Issue by kylewilliams321** [ollo69/ha-smartthinq-sensors#397]
The refrigerator and freezer temperature sensors are in HA but they don’t show any value and don’t update.

**Comment by kylewilliams321** [comment]
2REF11EID___2-FD (REFRIGERATOR)
by LG
Firmware: clip_hna_v1.9.175

**Comment by yuvalabou** [comment]
Those are the set temperatures and not actual temperatures unfortunately...
Those are not available in the API
