### ISSUE TITLE
Missing washer door lock attribute/sensor

### ISSUE THREAD

**Issue by luisiam** [ollo69/ha-smartthinq-sensors#400]
**Describe the bug**
Washer door lock attribute is missing

**Expected behavior**
The `door_lock` attribute is not showing up inside `sensor.washer` anymore. Neither is the `binary_sensor.washer_door_lock`.

**Screenshots**
N/A

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Docker
 - Home Assistant version installed: 2022.11.2
 - Component version installed: 0.24.2
 - Last know working version: forgot
 - LG device type and model with issue: WM4200HBA
 - LG devices connected (list): WM4200HBA, DLGX4201B, LRFVS3006S, LSGL6337F

**Output of HA logs**
N/A

**Additional context**
N/A

**Comment by ollo69** [comment]
If it not appear probably is because is not available. Please attach diagnostics so that I can check the payload.

**Comment by luisiam** [comment]
It was there before but I didn't notice from which version it's not there anymore. Diagnostics attached.
[smartthinq_sensors-44674e048fa8f922ab79563cab0fcac1-Washer-54f8387fb652bb4221a98152e61fa839.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10203455/smartthinq_sensors-44674e048fa8f922ab79563cab0fcac1-Washer-54f8387fb652bb4221a98152e61fa839.json.txt)

**Comment by ollo69** [comment]
The point is that `doorLock` is not present in model info and for this reason is not exposed in HA. model info is necessary to "translate" the value in the payload to a comprensive value. Just to better understand, is this value exposed in LG app?

**Comment by luisiam** [comment]
> The point is that `doorLock` is not present in model info and for this reason is not exposed in HA. model info is necessary to "translate" the value in the payload to a comprensive value. Just to better understand, is this value exposed in LG app?

How do I check that? I am able to see it on the app
