### ISSUE TITLE
Dryer run state is wrong

### ISSUE THREAD

**Issue by gabi1324** [ollo69/ha-smartthinq-sensors#402]
Hello! Today I noticed that my dryer has the wrong state when drying. The sensor is saying "washing" when it should be saying "drying". I don't know if this is intentional or not, but it is annoying. I think this needs to be changed.
Thanks!
 
![Screenshot_20221118_184622_Samsung Internet](https://user-images.githubusercontent.com/61083655/202795933-45277e38-31f7-4397-915d-188509aebab2.jpg)

**Comment by ollo69** [comment]
This is what the LG device provide, not something wrote by me.

**Comment by gabi1324** [comment]
Ok, thank you!
