### ISSUE TITLE
Please make this integration available in core home-assistant.

### ISSUE THREAD

**Issue by Particpant** [ollo69/ha-smartthinq-sensors#406]
I'd really like it if this were available either in core home-assistant or via the normal add-ons store.
HACS and/or ssh'ing into home assistant to do git commands is an extra layer of difficulty that I'd prefer to avoid to use this.

Thanks!

**Comment by ollo69** [comment]
This is not so simple and immediate. It require a lot of work (and time, that I do not have now). May be in the future..., Hacs is the best solution, it will manage all integration update that can come also more frequently than HA core.
