### ISSUE TITLE
Problem with upgrade on new version

### ISSUE THREAD

**Issue by HITMIK** [ollo69/ha-smartthinq-sensors#41]
Hi,

I have problem with upgrade from 0.3.8 to 0.4.6. After upgrade, next step is restart HA, after start HA I have version 0.3.8. 

Where is problem? In log not show error with upgrade...

Thanks

**Comment by ollo69** [comment]
Be sure that in HACS you are selecting the last version. If you previously downgrade, HACS remain selected on previous version.

**Comment by HITMIK** [comment]
Yes, I have downgrade because was problem with refrigerator temp in 0.4.2 think. I downgrade to 0.3.8 .

**Comment by HITMIK** [comment]
OK, I upgrade to 0.4.2 and next to 0.4.6 and all is OK.

Thanks :-)

👍 💯
