### ISSUE TITLE
Remaing time sensor disabled

### ISSUE THREAD

**Issue by mathgoy** [ollo69/ha-smartthinq-sensors#415]
**Describe the bug**
In My washing Machine, the remaining time sensor is disabled.

**Expected behavior**
Since I can see the remaining time on the LG app, I was expecting to see it in home assistant as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/82324931/206154622-f974d26b-42f4-4750-9456-94c242fc9c6a.png)

**Environment details:**
 - Environment: Home assistant running on a VM in Unraid
 - Home Assistant version installed: Home Assistant 2022.11.5
 - Component version installed: v0.24.2
 - Last know working version: N.A
 - LG device type and model with issue: Washing Machine f51p12wh
 - LG devices connected (list): f51p12wh

**Comment by ollo69** [comment]
This is not a bug, just enable the sensor that is disabled by default.
