### ISSUE TITLE
remaining time sensor unavailable 

### ISSUE THREAD

**Issue by idorose** [ollo69/ha-smartthinq-sensors#417]
I have a weird issue with my washer\dryer where the remaining time and initial time sensors are unavailable in HA but when I use the custom component it shows the time correctly and the progress bar.

why is that?

**Comment by ollo69** [comment]
This is the same of issue #415 (and not a real issue)
Remaining time sensor is not `unavailable` but `disabled`, if you need that sensor just enable via UI.
The custom card use main sensor attributes and not dedicated sensor, for this reason the progress bar is properly displayed.
I close this.
