### ISSUE TITLE
Washer - no door entitiy.

### ISSUE THREAD

**Issue by TRusselo** [ollo69/ha-smartthinq-sensors#418]
**Describe the bug**

No door entity? not an attribute of washer either.

**Expected behavior**
Should have door / lid entity with open/closed state.

**Screenshots**
![image](https://user-images.githubusercontent.com/1154815/206627717-87c74252-5994-47f8-bfa2-814db7397c8b.png)
![image](https://user-images.githubusercontent.com/1154815/206627740-5b984f8e-a7d6-4686-9237-5aca86767f32.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Hass core - docker unraid
 - Home Assistant version installed: 2022-12-07
 - Component version installed: 24.2
 - Last know working version:
 - LG device type and model with issue: 
T1789EFH_F-TL (WASHER)
by LG
Firmware: clip_hna_v1.9.183
 - LG devices connected (list): only the washer

**Output of HA logs**
``

Plugin Diags
[smartthinq_sensors-53dff427bf687b6f6ef0a436e17a16a0-Washer-7f3629c5f0342a7cb3be41b80ea81b8d.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10191904/smartthinq_sensors-53dff427bf687b6f6ef0a436e17a16a0-Washer-7f3629c5f0342a7cb3be41b80ea81b8d.json.txt)

**Comment by TRusselo** [comment]
door was open during screenshots. open/closed during visible history.

**Comment by ollo69** [comment]
Device do not expose this information (probably do not have a sensor for this). The only available information is if the door is locked, and sensor and attribute for this is already available, as shown in your screenshot

**Comment by TRusselo** [comment]
there is a door switch.. it wont start if open.
but maybe for some reason they arent monitoring it...

**Comment by ollo69** [comment]
You could assume that if door is locked is also closed. But of course you don't know if is closed when machine is not running. I close this, there is nothing to fix.
