### ISSUE TITLE
Keep getting emails 

### ISSUE THREAD

**Issue by rksim** [ollo69/ha-smartthinq-sensors#419]
**Describe the bug**
I have tried unsubscribing from this thread many many times and I keep getting email updates. Can someone please look into this?

**Expected behavior**
I would expect that if I unsubscribe then I would not get notifications

**Screenshots**
![BC25532F-8807-49A8-B854-EE35923586F9](https://user-images.githubusercontent.com/1731994/206628815-9ec8146f-0c94-4b2b-b3cd-488db11a503c.jpeg)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed:
 - Component version installed:
 - Last know working version:
 - LG device type and model with issue:
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by rksim** [comment]
I will try blocking the user Ollo69. Hopefully that helps.

**Comment by ollo69** [comment]
@rksim,

your github e-mail and subscription are not manged by me and this is not an issue related to this repository.
You can find details on how manage and check your subscription [here](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/viewing-your-subscriptions#reviewing-repositories-that-youre-watching). If something not working, please contact github support.

If you want I can block you, but I don't know if this will stop you from receiving notification. But please do not open other issue related to this in this repository.

Thanks.👍
