### ISSUE TITLE
Conditioner turning on the ionizer (AIRCLEAN)

### ISSUE THREAD

**Issue by xleonx90** [ollo69/ha-smartthinq-sensors#422]
Thank you for the excellent integration. Please consider adding an ionizer switch for the air conditioner. Diagnostic files with the ionizer on and off are attached.
[On airclean - smartthinq_sensors-27ed86ef5c9035ebb5d7f9ee0b3c2bac-Детская-2651618780d21378212a8784e0579799.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10196512/On.airclean.-.smartthinq_sensors-27ed86ef5c9035ebb5d7f9ee0b3c2bac-.-2651618780d21378212a8784e0579799.json.txt)
[Off airclean - smartthinq_sensors-27ed86ef5c9035ebb5d7f9ee0b3c2bac-Детская-2651618780d21378212a8784e0579799.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10196515/Off.airclean.-.smartthinq_sensors-27ed86ef5c9035ebb5d7f9ee0b3c2bac-.-2651618780d21378212a8784e0579799.json.txt)

**Comment by ollo69** [comment]
I think that I received this request multiple time, so it could be next feature. But please, explain clearly how does in work. There are some logic to be able to turn on ionizer (e.g. AC must be on, mode must be cool or heat etc.).

**Comment by xleonx90** [comment]
The mode is available only when the air conditioner is turned on (Any mode) (for api v1, api v2 is also available for the air conditioner turned off, but in my opinion this is not correct). I think it will be good if you make a switch, for example, how to turn on the display.

**Comment by ollo69** [comment]
This feature should be available with last release. Please test it and let me know if is OK.

**Comment by xleonx90** [comment]
Everything is fine on api v2, I'm still trying to check on api v1, any entry into the LG application blocks work from HA

**Comment by ollo69** [comment]
Yes, APIv1 has this limitation. You need to close LG application and wait some minutes.

**Comment by xleonx90** [comment]
That's great. Thank you very much. Everything works on api v1 too.

**Comment by skinkie** [comment]
Can I assist with anything to get an "UV" switch as well?

**Comment by ollo69** [comment]
> Can I assist with anything to get an "UV" switch as well? It seems to be present in the JSON as well. "AirUVDisinfection".

@skinkie,

please open a new FR to properly track the changes. Remember to attach integration diagnostic to have all required information.

I close this FR because completed.
