### ISSUE TITLE
Invalid redirection URL error

### ISSUE THREAD

**Issue by NDNELSON** [ollo69/ha-smartthinq-sensors#43]
Hello I`m using you add on, I installed it from Hacs and configure by Integrations because I don't have any tokens. I am following your wiki tuto 

but at the final of the process I get an 
Invalid redirection URL  error I try with almost all, includes my hassio duck dns domain.

Could you please help me ? Thanks and best regards

**Comment by ollo69** [comment]
Can you provide more details about the option you select during the configuration (language, region, etc).
May be you can attach some screenshot of configuration steps...
