### ISSUE TITLE
RFE: Support for pedestal washer attachment monitoring

### ISSUE THREAD

**Issue by sandymac** [ollo69/ha-smartthinq-sensors#433]
**Is your feature request related to a problem? Please describe.**
I have a pedestal washer attached to my washer which is available in the LG ThinQ app but not yet visible to Home Assistant.

**Describe the solution you'd like**
I'd like to be able to monitor my pedestal washer along with my main washer.

**Describe alternatives you've considered**
I am able to check the pedestal washer via the LG ThinQ app on my mobile.

**Additional context**
LGE Devices integration diagnostics download: Search for mini_washer .
[config_entry-smartthinq_sensors-e48f79ce99e7bf33ea365d5094032b87.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10238728/config_entry-smartthinq_sensors-e48f79ce99e7bf33ea365d5094032b87.json.txt)

I'll collect some mini_washer data when it's active next time I'm home.

Screen caps of the LG ThinQ app's washer screens:
![Screenshot_20221215-110517](https://user-images.githubusercontent.com/1621917/207909803-fd7054e4-9efc-46f2-8879-68fa5f5ad976.png)
![Screenshot_20221215-110520](https://user-images.githubusercontent.com/1621917/207909847-fd2f435b-ab21-4bca-a8f0-0dd34018d05d.png)
![Screenshot_20221215-110541](https://user-images.githubusercontent.com/1621917/207909863-5ae89209-6a16-4080-b0bd-d01a2d7629c0.png)

**Comment by ollo69** [comment]
Implement this feature was more complex that I was expecting, but now should be available with last release. Please test it and le me know.

**Comment by sandymac** [comment]
Thank you. I noticed my pedestal washer being available in HA after updating this morning.

![Screenshot_20230108-121316](https://user-images.githubusercontent.com/1621917/211209583-27e5f797-4002-4597-8b10-32dd8c08fc63.png)
