### ISSUE TITLE
Add Update instructions to Readme.md

### ISSUE THREAD

**Issue by Dude4Linux** [ollo69/ha-smartthinq-sensors#434]
The Readme.md does not specify how to apply updates. I'm assuming the proper procedure is to issue a `git pull` against the repo (if you didn't delete it) and then repeat the copy (cp) command. Wondering if there is a way to reload the software without doing a full reboot.

**Comment by ollo69** [comment]
As I know full reboot is always required, but you can try to just reload the integration from integration page (but I don't know if this work).
Procedure described by you to apply updates it's correct, but you can simplify your life installing HACS and than installing all custom integration via HACS, so you will also receive notification when new version is available.
