### ISSUE TITLE
Unknown Washer Status

### ISSUE THREAD

**Issue by brywithawhy** [ollo69/ha-smartthinq-sensors#44]
This isn't breaking my functionality, just shows up in the Developer Log window so thought I'd bring it to your attention. I have the WVC9-1410W washer dryer combo which is relatively new.

```
Log Details (WARNING)
Logger: custom_components.smartthinq_sensors.wideq.device
Source: custom_components/smartthinq_sensors/wideq/device.py:819
Integration: SmartThinQ LGE Sensors (documentation)
First occurred: 7:05:39 PM (1 occurrences)
Last logged: 7:05:39 PM

ThinQ: received unknown WASHER status '@WM_TERM_NO_SELECT_W' of type 'SpinSpeed'
```

**Comment by Golab** [comment]
This comes up when you are using drum cleaning?

**Comment by brywithawhy** [comment]
> This comes up when you are using drum cleaning?

No, because I haven't done a drum clean yet.

The time stamp matches up with to the logbook entry of the Wash Completed sensor turning on, so when a load is finished I guess.

**Comment by ollo69** [comment]
In the HA log file you should have an information log like this:

```
2020-04-30 01:46:54 INFO (SyncWorker_0) [custom_components.smartthinq_sensors.wideq.core_v2] Loading model info for LAVATRICE. Model: WTWN3, Url: <the url>
```

Can you please post the url indicated in your log so that I can download json file related to your model and map all possible state?

Thx

**Comment by brywithawhy** [comment]
Yep here you go. Thanks

https://objectstore.lgthinq.com/ec39a221-531d-4613-adc3-57eb4c1992e6?Expires=1646546085&Signature=aMz7wxrdPkwzZ-2wnGEoOWqTE351gXn9YeNbAp0fbwxty2cENqJU7okUj2f0zsAurmVZk4uF7PXImV-mJ-GBR-hu8fiTaMP6tzwG-1fNGy8iep0UiqKYGXKki7IdcEC20SWsdYgDazhwtSyid414hgqK20R-eyx5YJfgXhv-royApzBUzh7ZQCjrvxHMx5HyHHcJx6~LCIQu0hnWNjTqbsfy8h15Za-lPUaJzb39iexq5OqhsbsbkPmbIrpdRxo7oicGT-e9706tyjJJXEHjKXrKco9KuxWonSI38KYW3L0pMmbCFyFpC2KpNfYgazCTSF-UiNUJ2UtUjuZ2S61uAw__&Key-Pair-Id=APKAI74R6YENXPGRIWLQ

**Comment by brywithawhy** [comment]
Wasn't sure if the URL had my api token in it, so I've downloaded the json and pasted it for you:

https://pastebin.com/Yfh0h52u

**Comment by ollo69** [comment]
With last release I implemented a new method to retrieve status description that should not require anymore manual update.
Please check if everything is ok or report here issue.

**Comment by brywithawhy** [comment]
> With last release I implemented a new method to retrieve status description that should not require anymore manual update.
> Please check if everything is ok or report here issue.

Yep that's fixed it. Thanks!
