### ISSUE TITLE
Airco: disable display

### ISSUE THREAD

**Issue by skinkie** [ollo69/ha-smartthinq-sensors#441]
**Is your feature request related to a problem? Please describe.**
When the airco operates at night, one may want to have the display switched off.

**Describe the solution you'd like**
A toggle to enable or disable the display illumination for the airconditioning unit.

**Describe alternatives you've considered**
Using the remote.

**Comment by ollo69** [comment]
Display control switch should be already implemented. If you don't see the switch is because not supported or there are some issue in the implementation.
Please attach integration diagnostic to check your payload.

**Comment by skinkie** [comment]
Works in the latest version for me! 

![image](https://user-images.githubusercontent.com/502394/209466764-cdfce1b2-d0af-4e99-9e76-f2b5be0b8007.png)

**Comment by gabi1324** [comment]
Hello! I have a problem with the display light on an S09ET unit. The switch is always off and if I toggle it the unit beeps but doesn't do anything. I can control the light from the remote but not from the LG app.
