### ISSUE TITLE
binary_sensor.XXX_run_completed missing

### ISSUE THREAD

**Issue by heffneil** [ollo69/ha-smartthinq-sensors#442]
I've been using this integration for some time.  I have 2 pairs of washer and dryers - different models but all LG.

The upstairs washtower is all working properly but my new basement models don't have (until recently for some reason) the sensor:

binary_sensor.downstairsdryer_run_completed

Im not sure where this is defined but I can't find it in my HA system any longer.  Did something recently change?

Thanks!

**Comment by ollo69** [comment]
Are you sure that the sensor is not just disabled? Could you please attach diagnostic?

**Comment by heffneil** [comment]
I don't know how to provide a diagnostic.  I could have sworn there was an instruction to establish the various sensors when I originally set this up. has that changed?  I have Run completed on the new units vs Dry completed on the older ones?

**Comment by ollo69** [comment]
I do not exactly understand what is the issue here.
`binary sensor` xxx_completed should be available for all washer/dryer devices. Prefix can be `run` or any others like `wash` or `dry` depending if during setup integration was able to determinate type or not (may be in the various release something is changed). In any case you can rename your sensors as you prefer in home assistant. If you wan that I check if your sensors are available i need diagnostic file (you can generate it from HA device page).

**Comment by heffneil** [comment]
where is that completed binary sensor created?   I thought all those sensors or several of them had to be user established with a yaml file?  I think that changed? Can you confirm please?

Having two sets I can compare the two completed binary sensors.  I have discovered they are named differently.

**Comment by ollo69** [comment]
Sensors are created during first integration start after setup, and a `uniqueid` is associated to every sensor. You can than change the sensors name and id using HA User Interface, and it will maintain the name assigned by you. Sensor creation have nothing to do with `yaml` file, and this is never changed. As I said, it could be that name used during first creation has changed in the time, and for this reason if you setup the integration in 2 different moment you could have different names. I do not really remember all releases history changes, but you can check in github repository.

**Comment by heffneil** [comment]
ok thanks

**Comment by ollo69** [comment]
Can we close this?

**Comment by heffneil** [comment]
yes sorry
