### ISSUE TITLE
[ENH] Lookup table for idle current energy of known devices

### ISSUE THREAD

**Issue by flaviomartins** [ollo69/ha-smartthinq-sensors#448]
I wonder if it would be appropriate to setup a list of known devices and their known idle power to lookup here instead of hardcoding 5W.

For instance, my POT_056905_WW-POT (AC) idles at 1W.

https://github.com/ollo69/ha-smartthinq-sensors/blob/45ca5373ee40c2afc7a3b1538fbbb4d07a9e3869/custom_components/smartthinq_sensors/wideq/ac.py#L1068

**Comment by ollo69** [comment]
This look really complex to maintain in the time. It could be an integration option to allow set idle value for every device, also if I would avoid to create options if not really required. You can still create a calculated sensor in HA that will covert the value as you prefer when the device is off.
