### ISSUE TITLE
Energy monitoring sensors for washer and dryer

### ISSUE THREAD

**Issue by M0E-lnx** [ollo69/ha-smartthinq-sensors#452]
**Is your feature request related to a problem? Please describe.**
The LG ThinQ app shows energy measurements for my appliances, but it doesn't look like the homeassistant integration has these sensors.

**Describe the solution you'd like**
Expose the energy consumption readings from the ThinQ app as sensors to homeassistant.

**Describe alternatives you've considered**
Nothing yet.

**Additional context**
N/A

**Comment by ollo69** [comment]
This is same request of #384. Refer to that thread where is explained why implement this sensor does not make sense. I close this.
