### ISSUE TITLE
AC Filter seems to be reversed 

### ISSUE THREAD

**Issue by Dutchy-79** [ollo69/ha-smartthinq-sensors#466]
I just installed latest version and the AC filter remaining time status seems to be reversed, I just reset one and it says remaining 1% which should be 99% or it should be called different and not "remaining"

![Screenshot_20230105_011239_Home Assistant](https://user-images.githubusercontent.com/22749572/210673811-24413954-2e7f-4ad5-8dbc-27a9563f8914.png)

**Comment by ollo69** [comment]
This is already fixed in last release (v0.28.4), please refer to discussion on issue #375.
I close this.
