### ISSUE TITLE
Ability to change HVAC Temperature in Automations

### ISSUE THREAD

**Issue by ON2N** [ollo69/ha-smartthinq-sensors#476]
I was wondering if it'd be possible to implement a feature that allowes users to set the AC temperature in an automation. It's already possible to select HVAC Mode (heat/cool, heat, cool, dry, fan), but it would be nice to be able to change the temperature (and maby even fan speed?) as well. 

For example: Change AC temperature in living room to 16 c when nobody is home.

**Comment by ollo69** [comment]
All climate properties (included temperature and speed) can be changed in automation using Home Assistant available services.

**Comment by ON2N** [comment]
Can you teach me how? I'm fairly new to Home Assistant, and I haven't figured this out yet

**Comment by gabi1324** [comment]
There are a few climate services in HA:
climate.set_aux_heat
climate.set_preset_mode
climate.set_temperature
climate.set_humidity
climate.set_fan_mode
climate.set_hvac_mode
climate.set_swing_mode
climate.turn_on
climate.turn_off
Not all of these are available for every unit. You can check the HA climate platform to see more details.
https://www.home-assistant.io/integrations/climate/

**Comment by ON2N** [comment]
> 

And I've learned something new. Thank you!
