### ISSUE TITLE
Support for total energy value on AC unit

### ISSUE THREAD

**Issue by Ryanmt2** [ollo69/ha-smartthinq-sensors#478]
I see a few questions about accessing this data but none for air conditioning wall units. The integration exposes the current wattage consumption but not the accumulated value thats displayed in the app.

I know I can add a helper in HA to calculate this value but its always incorrect vs the application (Over reading by a kWh or so over the course of a day)

I think it's possibly the `airState.energy.accumulated` that I am after? If exposed it would be easy to then plug into the energy dashboard as a consuming appliance.

**Comment by ollo69** [comment]
I don't think that those information is provided by the device, it is probably calculated "on-the-fly" by application based on data collected (same logic used by HA helper). Did you try to generate diagnostic to see if there are value <> 0 for that information?

**Comment by Xitro01** [comment]
Has been discussed before. Please see my comment here:
https://github.com/ollo69/ha-smartthinq-sensors/issues/302#issuecomment-1386798167

**Comment by ollo69** [comment]
I close this as duplicated of #302
