### ISSUE TITLE
Oven Upper State Unavailable

### ISSUE THREAD

**Issue by wendortb** [ollo69/ha-smartthinq-sensors#479]
Oven Upper State is showing Unavailable and Oven Lower State is also showing Unavailable since the latest update.  It was working before the latest updates of everything.  Do you have any ideas why this would be?

[smartthinq_sensors-86ddbbc39e0c3d1db7c0bba9c200167c-Oven-35e594c6f73b50b0fcd0e619c6aeb00b.json(1).txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10403397/smartthinq_sensors-86ddbbc39e0c3d1db7c0bba9c200167c-Oven-35e594c6f73b50b0fcd0e619c6aeb00b.json.1.txt)

**Comment by ollo69** [comment]
Analyzing this but I do not found any reason for this condition. Do you have some error in the log? Did you try if this is working using previous release?
