### ISSUE TITLE
Feature request: Jet/power mode for AC

### ISSUE THREAD

**Issue by elaborate-username** [ollo69/ha-smartthinq-sensors#495]
**Is your feature request related to a problem? Please describe.**
The LG Thinq app includes a 'jet' mode (shown as Po on the device) which sets the Airco to go at maximum power & temp in the current mode, heating or cooling, for half an hour. This feature does not appear to be available in the home assistant integration.

**Describe the solution you'd like**
Add power mode as toggle in home assistant implementation of LG Air Conditioner control.

**Describe alternatives you've considered**
Using the ThinQ app

**Additional context**
This jet mode is needed in freezing temperatures to _get going_ to a reasonable temperature in winter where I live, it would be great to be able to do it all via home assistant.

**Comment by ollo69** [comment]
Jet mode is already implemented and confirmed to work. If you don't see the switch in HA, probably your device expose in a different way this feature. Please attach integration diagnostic

**Comment by elaborate-username** [comment]
Thank you for the quick reply- I did not look well enough in the HA app and I found the option after some search.
