### ISSUE TITLE
Oven Current and Target Temperatures

### ISSUE THREAD

**Issue by jpkoc** [ollo69/ha-smartthinq-sensors#498]
Good morning,
First thanks a lot for this integration. It is awesome! Great work!
Here is my issue: I am interested in tracking the temperature of my oven with 2 entities:
-	sensor.oven_oven_upper_current_temperature
-	sensor.oven_oven_target_current_temperature
I see an unexpected behavior: 
-	when the oven if off the current temperature shows the room temperature. The target temperature shows ‘unknown’.
-	when I start the oven and set the temperature to 350F, the current temperature shows ‘unknown’ (unexpected) and the target temperature shows 350F
-	when I switch off the oven after reaching the target temperature, the current temperature show 350F and the target temperature goes back to unknown.

Here is my question: when the oven is switched on, is it possible to display the current and target temperature?
I have also a request: I would like to display the temperature in a dual gauge. Unfortunately, ‘unknown’ is too long to be properly displayed (see picture). Is it possible to use ‘?’, ‘unk’,’N/A’ instead or let the user define the value to be displayed (by default ‘unknown’).

Thank you so much!
JPK

<img width="305" alt="gauge" src="https://user-images.githubusercontent.com/13867823/219375702-48d5acd3-7f18-46f2-972a-1ad05b489741.png">

**Comment by ollo69** [comment]
Yes, I agree, this is a strange behavior. Please attach diagnostic file generated when device is in this specific condition,

**Comment by jpkoc** [comment]
I tried multiple times to generate the diagnostic file. Here is what I did:
in integrations, 
- enable debug logging from the LGE Devices card 
- switch the oven on for 10 mins
- switch the oven off
- disable debug logging
and .... nothing happen. I am not prompted to download the diagnostic log, same if choose 'download diagnostics'. 
Any suggestions?
Thanks for your help

**Comment by ollo69** [comment]
When you choose download diagnostic you should be prompted to download a file, debug logging have nothing to do with this.
Are you using last integration version?

**Comment by jpkoc** [comment]
I have updated to the latest version 1H ago.
By the way, I am new to HA that is installed on a Raspberry PI 4. Not sure if this is playing a role.
I just tried again after rebooting HA: started/stopped the oven and choose download diagnostic but nothing happened.
Is there another way to extract the information?

**Comment by ollo69** [comment]
May be some settings in the browser are blocking download. This is the right process and should work.

**Comment by jpkoc** [comment]
Ok, let me do a bit more digging...

**Comment by jpkoc** [comment]
Here you go. I used my PC instead of Mac and it works. I have attached the file. Let me know if you need anything else.
Thanks again!

[config_entry-smartthinq_sensors-c1be7f427b9ae3ed72d905b9a5c05a44.json.txt.zip](https://github.com/ollo69/ha-smartthinq-sensors/files/10779575/config_entry-smartthinq_sensors-c1be7f427b9ae3ed72d905b9a5c05a44.json.txt.zip)
