### ISSUE TITLE
Washing machine not loading on 0.31.4

### ISSUE THREAD

**Issue by FajnB** [ollo69/ha-smartthinq-sensors#506]
**Describe the bug**
The integration connects, as it would fail instantly otherwise, but than is stuck on initialisation. i.e. it won't load the washing machine 

**Expected behaviour**
Being able to connect to LG and pull data of devices (in this case washing machine)

**Screenshots**
Not needed

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASS OS (KVM), Ubuntu server (Ubuntu 22.04.1 LTS x86_64)
 - Home Assistant version installed: 2023.2.3 (HASS), 9.4 (OS)
 - Component version installed: 0.31.4
 - Last know working version: 0.31.3
 - LG device type and model with issue: Fully automatic washing machine, F4DV710H1,  Firmware: clip_hna_v1.9.183 (up-to-date)
 - LG devices connected (list): I only have the one above

**Output of HA logs**
Will add, but now I do not know where to look for them.
```

```

**Additional context**
After accepting updated terms and policy in ThinQ app it didn't re-added the washing machine even after several attempts including trying authentication through redirect URL so I tried to downgrade the integration (0.31.4 → 0.31.3) which solved the issue.

**Comment by jhuang0** [comment]
I've got the same problem. Downgrading to 0.31.3 solved the issue for me as well.

**Comment by johndong** [comment]
Same here... 0.31.3 works reliably for days on end, 0.31.4 and higher is stuck on initialization with a washer and dryer. Sometimes after restarting the integration it works for a minute or two and then quickly fails again.

**Comment by FajnB** [comment]
An update to this issue. Now not even this version receives updates and EULA is approved on my account.

**Comment by ollo69** [comment]
@FajnB,

Can you provide details about your issue? I read that someone solved the issue, do I need more details.

**Comment by FajnB** [comment]
Well I didn't update to latest version as I was afraid that I won't be able to downgrade back, but now that even this version stopped working, I guess I have nothing to loose. I'll try upgrading first and than inform you @ollo69.

**Edit:**
You can close this issue. I just upgraded on the latest version 0.31.8 and it works. Thank you for your awesome support!
