### ISSUE TITLE
dependency cchardet cannot be installed on python 3.11

### ISSUE THREAD

**Issue by pleblancq** [ollo69/ha-smartthinq-sensors#507]
Hi,

since HomeAssistant v2023.3.0, we can install HomeAssistant with python 3.11

Your sensors has a dependency that is not working with python 3.11 (cchardet).

see https://github.com/thewhiteh4t/nexfil/issues/24 stating that cchardet seems to be abandonned.

You could easily migrate to charset_normalizer.

I changed the import cchardet in core_async.py  to

`from charset_normalizer import detect
`

and changed the detect line to:

`encoding = detect(content).get("encoding")
`

and everyhing works fine.

Would be nice if you could add this modification so people migrating to v3.11 will be able to use your sensors.

Thanks

**Comment by kleytonn** [comment]
Thank you @pleblancq 

It has worked well with my LG AC.

Regards,

**Comment by ollo69** [comment]
Thanks for this suggestion. I'm busy with work and far from home on this period, I will implement suggested changes as soon I will be back home.

**Comment by tanuva** [comment]
I'm running HA on Python 3.10.10 and also got an error logged when HA tried to install `cchardet` as a dependency of `smartthinq-sensors`. OP's suggestion (and updating `manifest.json`) got me to the account information screen. \o/
Let's see how the rest works out. :)

**Comment by SergioRius** [comment]
@pleblancq I've tried your solution but still is complaining about cchardet.
I've tried searching for cchardet in the whole config folder but didn't had any matches, but still failing.
Is there anything more to be done?

**Comment by kleytonn** [comment]
Hi,

You need to change manifest.json do not try to install cchardet. Try something like that:

$ cat manifest.json

{
  "domain": "smartthinq_sensors",
  "name": "SmartThinQ LGE Sensors",
  "integration_type": "hub",
  "documentation": "https://github.com/ollo69/ha-smartthinq-sensors",
  "issue_tracker": "https://github.com/ollo69/ha-smartthinq-sensors/issues",
  "dependencies": [],
  "codeowners": ***@***.***"],
  "requirements": ["pycountry>=20.7.3", "xmltodict>=0.12.0", "charset-normalizer>=2.1.1"],
  "config_flow": true,
  "iot_class": "cloud_polling",
  "version": "0.31.4"
}

Regrets,

**Comment by SergioRius** [comment]
> You need to change manifest.json do not try to install cchardet.

Thank you very much Kleytonn.

**Comment by ollo69** [comment]
Change implemented in last release, I close this issue. Please open a new one in case of problems.
