### ISSUE TITLE
Request Washer/Dryer Time Remaining to be availabile

### ISSUE THREAD

**Issue by sfumarolo** [ollo69/ha-smartthinq-sensors#509]
**Is your feature request related to a problem? Please describe.**
I use a Stream Deck to keep track of my Washer/Dryer and would love at a glance to see how long is left in the cycles. I know this is available in the API (see below).

**Describe the solution you'd like**
Have an integer value of estimated minutes remaining available.

**Describe alternatives you've considered**
N/A

**Additional context**
In a JSON dump I've seen elsewhere describing the API, I see these fields, which I'm thinking can be done as remainTimeHour * 60 + remainTimeMinute to yield the estimated number of minutes remaining.

`    "remainTimeHour": {
      "dataType": "range",
      "valueMapping": {
        "min": 0,
        "max": 30
      }
    },
    "remainTimeMinute": {
      "dataType": "range",
      "valueMapping": {
        "min": 0,
        "max": 59
      }
    },`

**Comment by rasssta** [comment]
This is already available as hh:mm:ss. Just use a template if you would like to convert it to an integer containing minutes.

![image](https://user-images.githubusercontent.com/4455235/226115466-09e23629-e2aa-4507-b41b-aeadf17b4d2e.png)

**Comment by sfumarolo** [comment]
Interesting... the sensor was showing as disabled and unavailable. I just tried forcing it to Enabled. I'll give it a shot next time we do a load of laundry.

**Comment by sfumarolo** [comment]
As above, noticed it's there, it was just disabled for some reason in my setup. As soon as I enabled it, things worked great. Sorry for the false report!
