### ISSUE TITLE
[Feature Request] More Languages to Translate

### ISSUE THREAD

**Issue by jordibsk10** [ollo69/ha-smartthinq-sensors#51]
Dear ollo69,

This custom integration is awesome and it may be even greater if we all help in having more languages available.

Therefore, it would be great if you could share how we can translate it and what do you need from us in order to get it working with more languages. 

I'm willing to translate it to Spanish ;)

Thank you!

**Comment by ollo69** [comment]
Thanks, but what exactly do you expect to be translated? Only translation supported at this moment is message of configuration flow.

**Comment by jordibsk10** [comment]
Yes, I was refering to the configuration flow... I should have been more specific 😆

Would you like it to have that bit in more languages or you prefer to keep it simple with Eng (I think you also have a couple more)?

Just wondering as this would make things a little easier for some people it its in their own language...

Thanks

**Comment by ollo69** [comment]
In this case you have to create new file for the languange starting from en.json that is available in "Translation" folder. The best way to do this is using Pull Request, 2 PR was already done by other contributors so you can take a look to closed PR as example. 

Thanks.
