### ISSUE TITLE
VerticalOff twice in list

### ISSUE THREAD

**Issue by Hadatko** [ollo69/ha-smartthinq-sensors#510]
**Describe the bug**
If possible attach the JSON info file for your devices.

Hi. In the image you can see that VerticalOff is there twice. Very first and very last. Other values looks like there are only once. Air condition bought and installed today. HA and HACS on latest version.
![image](https://user-images.githubusercontent.com/13130700/227384669-bd20ea15-fca3-4461-bd04-a01387213427.png)

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

Every option just once.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Raspbian HA supervised
 - Home Assistant version installed: core-2023.3.6
 - Component version installed: 0.31.4
 - Last know working version: -
 - LG device type and model with issue: lg pc12sk
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by Hadatko** [comment]
;)

**Comment by ollo69** [comment]
Please try if last release fix the issue.

**Comment by Hadatko** [comment]
Issue solved. Thank you for fixing such a low prio thing ;)
