### ISSUE TITLE
LG Standard 2 HVAC unit - can't handle display brightness

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [ollo69/ha-smartthinq-sensors#515]
**Describe the bug**
Device has ability to control display brightness (on/off) via remote pilot.  
Switch entity is exposed via this integration in Home Assistant.  
Changing switch state doesn't change display brightness.  

**Expected behavior**
Changing switch state in HA, changes display brightness.

**Screenshots**
![image](https://user-images.githubusercontent.com/24268470/228773251-a9832978-eabc-450b-b4ed-ddd066a7973f.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSOS
 - Home Assistant version installed: 2023.3.6
 - Component version installed: 0.31.4
 - Last know working version: N/A
 - LG device type and model with issue: HVAC unit LG Standard 2, 2,5 and 3,5kW variants
 - LG devices connected (list): 3x LG Standard 2

**Output of HA logs**
Paste the relavant output of the HA log here.

1. ('Display light' is on, while backlight was disabled via remote)
[lg-standard2-display-brightness-disabled-via-remote.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/11109521/lg-standard2-display-brightness-disabled-via-remote.txt)
2. Then enabled display via remote
[lg-standard2-display-brightness-enabled-via-remote.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/11109538/lg-standard2-display-brightness-enabled-via-remote.txt)
('Display light' switch changed it's state to off. Inversion required?)
3. Then disabled display via remote again
[lg-standard2-display-brightness-disabled-via-remote-again.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/11109553/lg-standard2-display-brightness-disabled-via-remote-again.txt)
('Display light' changed its state to 'on'. Definetely inversion is required)
4. Enabled backlight via turning HA switch off
[lg-standard2-display-brightness-enabled-by-ha.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/11109601/lg-standard2-display-brightness-enabled-by-ha.txt)
Device beeped, display remain unlit
5. Repeat step 4.
[lg-standard2-display-brightness-enabled-by-ha-again.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/11109608/lg-standard2-display-brightness-enabled-by-ha-again.txt)
(Device beeped, display is still dark)

**Comment by erkr** [comment]
I have the same issue. We have 3 units. The display light entity is created for all  3 units. On the LG remote the light button works for all 3 units.
The entity display switch in HA only works for the unit of model type AP09RK. But not for the slightly older model PC09ST.
When I toggle the display switch, the units make a beep weggaat should indicate it is a supported command, but nothing happens.
I can provide more info, but please indicate what is needed.
Best  Eric

**Comment by vincentwolsink** [comment]
I also have issues with S09ET and S12ET (RAC_056905_WW-RAC) airco's. The display light button is present for both ACs. When toggling the button the ACs do make a beep sound, but nothing happens.

**Comment by KrzysztofHajdamowicz** [comment]
Bump

**Comment by erkr** [comment]
Still hoping ☺️

**Comment by ollo69** [comment]
This point was discussed on issue #475. Probably API to control the light does not exists, considering that is also not controllable from LG app but only from remote control (that use infrared and not Api).
I close this issue, refer to #475.

**Comment by erkr** [comment]
Fair! Thanks for all the efforts🥳
