### ISSUE TITLE
LG Oven(Range) not working

### ISSUE THREAD

**Issue by limitless00net** [ollo69/ha-smartthinq-sensors#526]
**Describe the bug**
I can see my LG oven as range device type in HA. But all sensors of this oven are not working.
[smartthinq_sensors-oven.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/11239476/smartthinq_sensors-oven.txt)

**Expected behavior**
I want to see oven states and cook mode in HA.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HAOS 
 - Home Assistant version installed: HA 2023.4
 - Component version installed: 0.31.6
 - Last know working version: Never worked
 - LG device type and model with issue: Oven, ML32WW1
 - LG devices connected (list): 

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by fantastxu** [comment]
Me too, I can see there are "LG Oven Cooktop center state", "LG Oven Cooktop right rare state", "LG Oven Cooktop left rare state" etc, but they never work. When I restart the integration, it now stuck at ''Initializing" and all the entities are now unavailable.

**Comment by limitless00net** [comment]
up

**Comment by limitless00net** [comment]
Up

**Comment by limitless00net** [comment]
up
