### ISSUE TITLE
Integration is not loading after upgrade to HAOSS 2023.5.0 core

### ISSUE THREAD

**Issue by michalw2-alt** [ollo69/ha-smartthinq-sensors#533]
**Describe the bug**
After update to HAOSS 2023.5.0 core integration is no longer loading.

**Expected behavior**
Integration should load.

**Output of HA logs**
```
2023-05-03 23:09:40.628 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration smartthinq_sensors: Requirements for smartthinq_sensors not found: ['cchardet>=2.1.7'].
```

**Additional context**
![image](https://user-images.githubusercontent.com/74453829/236058958-ebeff033-e2de-46bf-8b55-2f628baad0a3.jpeg)

**Comment by ollo69** [comment]
Please upgrade to last version, on which `cchardet` requirement has been replaced by `charset_normalizer`.

**Comment by michalw2-alt** [comment]
I have removed and re-downloaded latest version which allowed to fix the issue.
I'm wondering why I did not get updated version using HACS store.
Thank you for your help.
