### ISSUE TITLE
[BUG] Invalid region/language

### ISSUE THREAD

**Issue by jprates** [ollo69/ha-smartthinq-sensors#54]
**Describe the bug**
Right at the first setup screen after deploying files into HASS, we get the request for region and language.
For my case it is Portugal/Português as I can check on the mobile android app.
However when I try to enter this strings the response is "invalid region format".

**Expected behavior**
"Portugal" should be accepted for as region and "Português" should be accepted as language.

**Screenshots**
![image](https://user-images.githubusercontent.com/20585218/85948548-636c1400-b949-11ea-8688-a6c474da3c97.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HA supervised
 - Home Assistant version installed: 0.111.4
 - Component version installed: 0.5.2
 - Last know working version:
 - LG device type and model with issue: washing machine F4J8JS2W
 - LG devices connected (list): just the F4J8JS2W

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by ollo69** [comment]
Region: PT
Language: pt-PT

**Comment by jprates** [comment]
Hi,
Thanks a lot for the swift answer.
May I suggest you include a url for all the possible combinations of region and language so that first timers like me don't have the need to trouble you in the future with small issues like this one?

**Comment by ollo69** [comment]
Ok, I keep in mind your suggestion.
Close this issue.
