### ISSUE TITLE
LG Washer  8 entities not availible

### ISSUE THREAD

**Issue by AlterSu24** [ollo69/ha-smartthinq-sensors#542]
**Describe the bug**
My washer has 8 entities always being unavailible, but other entities works fine. 
**Expected behavior**
Showing like intial time or countdown time and other entities.

**Screenshots**
[https://imgur.com/CRSFitu](url)

**Environment details:**
 - HAOS 10.1
 - Home Assistant version installed: 2023.5.0
 - Component version installed: 0.31.6
 - Last know working version: None
 - LG device type and model with issue: F0K2CHK2T_WIFI-FL (WASHER)
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by ollo69** [comment]
Witch entities? Did you try to enable from UI?

**Comment by AlterSu24** [comment]
I tried and it works now， thanks.

**Comment by ollo69** [comment]
Ok, I close this.
