### ISSUE TITLE
Add Model Number

### ISSUE THREAD

**Issue by cyber-junkie9** [ollo69/ha-smartthinq-sensors#547]
**Describe the bug**
Please add support for this model, currently it's showing as TLVN1CA-TL

**Expected behavior**
THD10SWP

**Screenshots**
![photo_2023-05-17_12-33-03](https://github.com/ollo69/ha-smartthinq-sensors/assets/50986901/a6df5276-bb88-4b46-bbcc-d7f73b8dba63)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed: 2023.5.1
 - Component version installed: v0.31.7
 - Last know working version:
 - LG device type and model with issue: Top Load Washer, THD10SWP
 - LG devices connected (list): 1

**Output of HA logs**
[smartthinq_sensors-b310b1c0cbf4bac6b1f7225567fbdce1-Top Load Washer-48fb5a1e612f7b011d7735cdd2784926.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/11495110/smartthinq_sensors-b310b1c0cbf4bac6b1f7225567fbdce1-Top.Load.Washer-48fb5a1e612f7b011d7735cdd2784926.json.txt)

```

**Comment by ollo69** [comment]
I'm not understanding what is the issue here? Just the model displayed? This is what come from LG, I don't have other information. There are other problem with your model?
