### ISSUE TITLE
The Time Sensors show the seconds

### ISSUE THREAD

**Issue by scannifn** [ollo69/ha-smartthinq-sensors#548]
I have successfully integrated my LG washer/dryer model LSWD100E.
The only "issue" I'm having is that the time sensors also show seconds (they are not necessary, they are always set as 00).
Is there any way to display only hours and minutes? **H:MM**

The README.md specifies that the timers are in the format **H:MM**. Why do I have them in **H:MM:SS** format?

![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/67062892/cf549046-c9e6-4d3a-8b3e-981c4286a0b8)

I know that this issue is not "tragic" but please could you help me to fix it in order to save space in the Lovelace mobile card view?
Thank you

**Screenshots**

![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/67062892/8c5019f9-496d-4bc6-a2bc-8a802563db08)

![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/67062892/4f66526c-9e25-40be-aa2e-f1bd5b830f8f)

**Comment by scannifn** [comment]
First of all thanks for the reply.
Not being very experienced, I didn't find your answer very understandable (for me).
Would you be kind enough to help me figure out if my current card can be changed based on your advice?

```
type: custom:mushroom-template-card
primary: Lavasciuga LG
secondary: >
  {% if is_state("sensor.lavatrice", "on") %}

  Programma: {{ state_attr("sensor.lavatrice", "current_course") }}

  Stato: {{ state_attr("sensor.lavatrice", "run_state") }}

  {{ state_attr("sensor.lavatrice", "initial_time") }} Durata - {{
  state_attr("sensor.lavatrice", "remain_time") }} Tempo rimanente

  {% else %}

  Off

  {% endif %}
icon: mdi:washing-machine
entity: sensor.lavatrice
multiline_secondary: true
icon_color: '{{ "green" if is_state("sensor.lavatrice", "on") else "" }}'
tap_action:
  action: more-info
```

**Comment by ollo69** [comment]
I'm not so expert in UI, I suggest you to move to HA forum for help about this topic. Please close this thread if you don't have other issue directly related to integration.

**Comment by scannifn** [comment]
Many thanks in any case. Sure, I will close it as you requested.
Bye, Nicola
