### ISSUE TITLE
[BUG] Authorization Error

### ISSUE THREAD

**Issue by jprates** [ollo69/ha-smartthinq-sensors#55]
**Describe the bug**
Trying to get the redirection url I am presented with the login options, from where I choose google account login as I always do.

First thing odd is that sync in Chrome is immediately paused, and I'm invited to authenticate on my Google account once again.

Then authorization via Google credentials redirect url fail with "Error 400: redirect_uri_mismatch".

Visiting the Google's suggested url I get the message that I'm not authorized to view the requested page... 

**Screenshots**
![image](https://user-images.githubusercontent.com/20585218/85950227-7be12c00-b953-11ea-88cc-721223e9b589.png)

![image](https://user-images.githubusercontent.com/20585218/85950438-8ea83080-b954-11ea-83e8-0d032cc53984.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):  HA supervised
 - Home Assistant version installed: 0.111.4
 - Component version installed: 0.5.2
 - Last know working version:
 - LG device type and model with issue: washing machine F4J8JS2W
 - LG devices connected (list): just the F4J8JS2W

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by jprates** [comment]
For the record, I've also tried to login with LG credentials, and I got redirected to this korean (!?!?) url which showed a blank page:

https://kr.m.lgaccount.com/login/iabClose?state=e3bdd2ceb94e11eaa7180011325d205b&code=OwzPIOdz70ixIVpsGOeUlJTClvwvfW&user_number=PT2006285075535&oauth2_backend_url=https%3A%2F%2Fgb.lgeapi.com%2F

Even tried to use it as a redirect url in the setup process but got this message back:

![image](https://user-images.githubusercontent.com/20585218/85950955-d7151d80-b957-11ea-9563-11239b695897.png)

**Comment by ollo69** [comment]
Before you must use your your LG credential to login in LG mobile app and register there your devices. 
Using google or other social network account does not work as explained in readme.
Redirection to korean url is correct.

**Comment by jprates** [comment]
I've the app working for over 2 years on my mobile phone with no issues whatsoever.

![image](https://user-images.githubusercontent.com/20585218/85951392-e5186d80-b95a-11ea-9fda-0bc2d77c0f3c.png)

What else could be wrong?

**Comment by jprates** [comment]
wait, don't spend more time on this, let me try something

**Comment by ollo69** [comment]
I suppose that you have registered your device in the mobile app using Google account, you must use LG account also in mobile app.
This is the reason for which devices are not found by the component!

**Comment by jprates** [comment]
Indeed, I had assumed being the same email address and same password the account would be only one, but it seems not.
I logged on in the app with the LG email account and confirmed there was no device registered there (although the email was the same).
I'm waiting for a washing cycle to end and register the washing machine on the LG email account and try again.
Thank you for your patience, I'll keep you posted today still.

**Comment by jprates** [comment]
Hi,

After deleting the device from the google connected account and added to the normal login everything worked at first try.

Thank you so much and sorry for the trouble.

You can close this issue.
