### ISSUE TITLE
ha update 27-5-2023

### ISSUE THREAD

**Issue by Mackstoresdotcom** [ollo69/ha-smartthinq-sensors#553]
Logger: homeassistant.setup
Source: setup.py:206
First occurred: 12:17:25 PM (1 occurrences)
Last logged: 12:17:25 PM

Setup failed for custom integration smartthinq_sensors: Requirements for smartthinq_sensors not found: ['cchardet>=2.1.7'].

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 12:17:21 PM (3 occurrences)
Last logged: 12:17:25 PM

Unable to install package cchardet>=2.1.7: ERROR: Cannot install cchardet>=2.1.7 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1 -> 23.1.2 [notice] To update, run: pip install --upgrade pip

**Comment by dariuszpaluch** [comment]
It looks already fixed by https://github.com/ollo69/ha-smartthinq-sensors/commit/1966bc16ad67ba06b486dd53092bb9c7d0172c2a

So download new changes from master and copy custom_components :) or update by HACS
