### ISSUE TITLE
DOCUMENTATION: List of supported devices

### ISSUE THREAD

**Issue by typxxi** [ollo69/ha-smartthinq-sensors#558]
I can not find a list of supported devices to check if the WH27S or WH20S is supported. 
You mention in the readme.md water heater but I am not sure if you mean these big air 2 water heatpumps with 270 Liter of water or rather water kettle.

I also miss a list of key features (at least from those who have these devices in use) what is supported or not cause there are some essential things missing in these 2 devices, the SG Ready (power) input to use surplus power if you feed into the grid.

Would be nice to have some screenshots from users about the key features they are using like you washing machine card and the Koch or Buntwäsche that was running. Shows a lot and looks really usefull but a few others might be usefull too where I mean that users should simply send such screenshots or feature lists.

Right now I am on the verge of buying a WH20S but would love to know before buying how the device is supported. 
If SG ready would have been implemented it would be a lot easier cause it is quite expensive (over 2000€ + the service guy to replace the old with the LG one).

thanks a lot !

**Comment by NdR91** [comment]
+1

I'm going to use both THERMA V HM091MR.U44 and WH27S.F5

**Comment by Fonske64** [comment]
+2

Pretty much the same question here. Will I be able to control the WH20S target temperature through this integration?
