### ISSUE TITLE
Does this component work with TVs?

### ISSUE THREAD

**Issue by blakito** [ollo69/ha-smartthinq-sensors#56]
**Is your feature request related to a problem? Please describe.**
I couldn't get my TV detected on my LG account

**Describe the solution you'd like**
I would like to have it detected. Its a LG B9

**Describe alternatives you've considered**
Tried reconnecting device, different countries.

**Comment by ollo69** [comment]
LG webOS use different communication protocol that is managed by a dedicated HA component (https://www.home-assistant.io/integrations/webostv/).

**Comment by KTibow** [comment]
@blakito consider closing?

**Comment by blakito** [comment]
Thanks mates. Sorry for the disturb.
