### ISSUE TITLE
washer time remain defaults to 0:01

### ISSUE THREAD

**Issue by mcnutter1** [ollo69/ha-smartthinq-sensors#572]
Using the integration on a brand new LG front load washer, everything works as expected except when there is no load the remain time attribute defaults to 1:00, not sure where this is coming from but it reports this even when the washer is off.

**Comment by catduckgnaf** [comment]
@mcnutter1 is it a WM8900HBA ? I am having the exact same issue. 
Also with the count down timer, it seems to keep going down 1 minute on lovelace.

**Comment by mcnutter1** [comment]
> @mcnutter1 is it a WM8900HBA ? I am having the exact same issue. Also with the count down timer, it seems to keep going down 1 minute on lovelace.

Exactly, same model.

I made some workarounds in the Lovlace UI to make it look nicer by using a condition for that field to show.

Also, for some reason the Power On attribute is always on, even when the Washer is Off.

**Comment by ollo69** [comment]
Please provide integration diagnostic file when device is in this specific state / condition

**Comment by ollo69** [comment]
Close this a s duplicate of #544
