### ISSUE TITLE
[Feature Request] Don't add attributes when not included

### ISSUE THREAD

**Issue by KTibow** [ollo69/ha-smartthinq-sensors#58]
**Is your feature request related to a problem? Please describe.**
Some features (`steam_mode`, `creasecare_mode`) don't apply to the washer, but they still show up as attributes.

**Describe the solution you'd like**
An irrelevant attribute shouldn't show up at all.

**Describe alternatives you've considered**
Maybe another attribute that lists all of the relevant attributes, or the irrelevant attributes. The value could also be `(not relevant)`.

**Additional context**
![attr list](https://user-images.githubusercontent.com/10727862/86034457-7e915f00-b9ef-11ea-8325-8f8519bc85fb.png)

**Comment by ollo69** [comment]
Real problem is that I'm not able to determinate valid attributes until Washer is turned on.
I'll think about possible solutions...

**Comment by ollo69** [comment]
Close due to inactivity. Anyway this feat-request now should be implemented.
