### ISSUE TITLE
Wash completed not working anymore

### ISSUE THREAD

**Issue by mallebuchsbaum** [ollo69/ha-smartthinq-sensors#580]
**Describe the bug**
Hi, the bool for wash completed is not working anymore. 
I skipped some versions just because I have not checked for updates in HACS. 

**Expected behavior**
When a wash is completed the status should change from off to on

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): hass OS
 - Home Assistant version installed: 10.4 (OS), Homeassistant 2023.8.2
 - Last know working version: not sure, downgraded to oldest available version to check if it works with this
 - LG device type and model with issue: F4WV408S0
 

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**
already did a complete new setup with the LG Account, deleted device in homeassistant

**Comment by Trilis29** [comment]
still not working
