### ISSUE TITLE
Over the Range Microwave Vent Fan does not work 

### ISSUE THREAD

**Issue by trentjw** [ollo69/ha-smartthinq-sensors#588]
**Describe the bug**
If possible attach the JSON info file for your devices.

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen. fan control  should be available 

**Screenshots**
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/12220533/671e1291-3f11-40c0-965a-73a812819490)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): hassio
 - Home Assistant version installed: Home Assistant 2023.8.3
Supervisor 2023.08.1
Operating System 10.4
Frontend 20230802.1 - latest
 - Component version installed: v0.33.0
 - Last know working version: none
 - LG device type and model with issue:  microwave is MHEC1737D 
 - LG devices connected (list): Oven microwave and two window AC units

**Output of HA logs**
Paste the relavant output of the HA log here.

```
HA shows it as unavailable 
```

**Additional context**

**Comment by ollo69** [comment]
Please attach integration diagnostic

**Comment by trentjw** [comment]
[config_entry-smartthinq_sensors-9274ed859fa860b738c90ed5e4807e1b.json (2).txt](https://github.com/ollo69/ha-smartthinq-sensors/files/12389199/config_entry-smartthinq_sensors-9274ed859fa860b738c90ed5e4807e1b.json.2.txt)

**Comment by ollo69** [comment]
Please try last release and let me know if it fix this issue.

**Comment by ollo69** [comment]
@trentjw,

Any news?

**Comment by trentjw** [comment]
Seems to be working as it should

**Comment by ollo69** [comment]
Ok, close this issue. Thx
