### ISSUE TITLE
Remaining Time (entity) on my Washer is not working fine

### ISSUE THREAD

**Issue by gabbo583** [ollo69/ha-smartthinq-sensors#594]
On Washer, the sensor of remaining time is not working. It said that this entity is not available, but in my LG Thinq app I can see the remaining time. 

Screenshots

Environment details:
 - Environment: Raspberry Pi4
 - Home Assistant version installed: The latest of today
 - Component version installed: 0.33.2
 - Last know working version: I don't know :(
 - LG device type and model with issue: Washer F4WV509S1E.ABWQPIS

**Comment by ollo69** [comment]
That sensor is disabled by default. Just enable it in HA.

**Comment by gabbo583** [comment]
How can I enable in HA? I'm sorry that I'm a beginner :((

**Comment by ollo69** [comment]
Ok, but this is not a HA help forum, you should ask for this in the community.
Anyway: go to `Settings -> Device and Service`. Select integration device, select your device and there you can select and enable disabled entities.

I close this issue because not an integration problem.
