### ISSUE TITLE
Unable to trigger automations of HVAC / AC using current temperature

### ISSUE THREAD

**Issue by abilashs1990** [ollo69/ha-smartthinq-sensors#599]
I have tried all sorts of triggers from the available options in entities, but I am unable to trigger an automation using the following

1. *Room Temperature Changes* trigger (under trigger -> devices)
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/42211409/bd9444f3-e449-4006-84fe-bdf49378a4e1)
2. *Room's AC measured temperature Changed* trigger (under trigger -> devices)
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/42211409/6815fe01-9298-4925-8fbb-d2676d4e7414)
3. *Current temperature above 26* trigger (under trigger -> number state -> AC Entity -> Current Temperature) 
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/42211409/4ee65cbd-537a-488d-bc52-884a2727c418)

I have also tried adding conditions, but nothing works as a trigger.

I also see this under sensors

![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/42211409/6b420906-4d45-4de2-8ea3-aebe7547a59c)

But if we see the AC dashboard, we can see the current temperature
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/42211409/d505b8ab-fe5d-4176-a2b3-f1e7ea0872bc)

**Expected behavior**
Trigger based on temperature readings should trigger an action

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HAOS Running on Zima Board
 - Home Assistant version installed: Home Assistant 2023.9.1, Supervisor 2023.08.3, Operating System 10.5, Frontend 20230908.0 
 - Component version installed: RAC_056905_WW-RAC (AC) by LG, Firmware: clip_hna_v1.9.192
 - Last know working version: N/A
 - LG device type and model with issue: LG AC Model: PNSQ13SWZF.AMLG
 - LG devices connected (list): LG AC

**Comment by andreyneto** [comment]
I'm facing the same issue with two units of an LG Dual Inverter Artcool.
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/2815005/b73e3566-d045-49f2-9775-6d06d96aa1f8)

**Comment by ollo69** [comment]
Room temperature is a sensor disabled by default, you should enable it.
Or you enable the sensor or you base the trigger on ac entity current temperature attribute, and I have no idea why this doesn't work. There are some errors in the log?

**Comment by abilashs1990** [comment]
> Room temperature is a sensor disabled by default, you should enable it. Or you enable the sensor or you base the trigger on ac entity current temperature attribute, and I have no idea why this doesn't work. There are some errors in the log?

I have enabled the sensor, and I have posted the screenshot. I don't see any logs related to the same.

I was wondering how you are showing the current temperature on the dashboard and why we can't use the same entity for automation

<img width="504" alt="image" src="https://github.com/ollo69/ha-smartthinq-sensors/assets/42211409/23f2677d-369f-415f-8034-749e1921dfb0">

**Comment by ollo69** [comment]
> I was wondering how you are showing the current temperature on the dashboard and why we can't use the same entity for automation

I'm not showing temperature in the dashboard, Home Assistant is doing it. If the data provided to HA by the integration should be wrong probably nothing would be shown, does it make sense for you? And automation trigger are not managed by integration but by HA platform, so I don't think that this could really be an integration issue.
Also because this integration is used by many people, it is quite improbable that until now nobody create an integration for AC (probably one of the most used automation in HA). Most probably something is wrong in your automation, your HA installation or your network connection.
Not able at this moment to make any test because I'm far from home for work, I will test an automation in my dev environment when I will be back home at the end of the month.

**Comment by abilashs1990** [comment]
> > I was wondering how you are showing the current temperature on the dashboard and why we can't use the same entity for automation
> 
> I'm not showing temperature in the dashboard, Home Assistant is doing it. If the data provided to HA by the integration should be wrong probably nothing would be shown, does it make sense for you? And automation trigger are not managed by integration but by HA platform, so I don't think that this could really be an integration issue. Also because this integration is used by many people, it is quite improbable that until now nobody create an integration for AC (probably one of the most used automation in HA). Most probably something is wrong in your automation, your HA installation or your network connection. Not able at this moment to make any test because I'm far from home for work, I will test an automation in my dev environment when I will be back home at the end of the month.

That would be super helpful! Thank you very much for your effort!

I will test my integration as well
