### ISSUE TITLE
Missing logo brand for hass 0.108 (now beta)

### ISSUE THREAD

**Issue by sagitt** [ollo69/ha-smartthinq-sensors#6]
Missing brands for this integration.

https://rc.home-assistant.io/blog/2020/03/27/release-108/

Integration logos & icons
We have created a new repository on GitHub containing all the brand icons and logos Home Assistant is able to integrate with. These images are, for example, used in our documentation.

In 0.108, we made a start on using the content from this repository in the Home Assistant frontend. The device information page got a layout update and the integrations page as well.

These pages will now show the icons and logos matching the integration.

**Comment by ollo69** [comment]
Interesting option but seems that isn't possible for custom components yet. Please reopen if it becomes available.

**Comment by sagitt** [comment]
see 0.110

![Schermata 2020-05-16 alle 17 37 31](https://user-images.githubusercontent.com/169086/82123924-4bc33c80-979c-11ea-8067-8fc5691f2eed.png)

**Comment by ollo69** [comment]
Thanks @sagitt, I already PR logos for this integration, so probably shortly will be available.

**Comment by sagitt** [comment]
very well!

**Comment by ollo69** [comment]
Logo are now availaible, I close this issue.
