### ISSUE TITLE
[BUG] Failed update counter not being reset and device ends up marked as unavailable

### ISSUE THREAD

**Issue by alexanv1** [ollo69/ha-smartthinq-sensors#60]
**Describe the bug**
The new functionality to mark the device as Unavailable has a bug where the "failure counter" is not being reset.
_not_logged_count does not appear to be getting set back to 0 unless _disconnected is true and it seems that the counter just gets incremented on every failed update. As a result, if a number of updates fail (not in a row), the device gets marked as unavailable.

It's possible that I am reading the code wrong but the state I ended up in was that 2 out of 3 of my LG devices were marked as unavailable and restarting hassio fixed it. Unfortunately I lost the logs when I restarted.

**Expected behavior**
Counter should be getting reset on a successful update.

**Comment by ollo69** [comment]
Yesm you are right.
It should be fixed with last release (v0.5.3)

**Comment by KTibow** [comment]
@alexanv1 fixed? time to close yet?
