### ISSUE TITLE
LGSmartThinq refrigerator door status

### ISSUE THREAD

**Issue by Giltechy** [ollo69/ha-smartthinq-sensors#600]
In the home assistant LGSmartThinq, the refrigerator door status is not updated, the entity "Refrigerator Door open" is not getting real-time information, and cannot run automation based on this.
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/40049841/90a4c9d6-b4f3-4984-922e-8e50dde7f7db)

**Comment by ollo69** [comment]
Integration use polling, polling interval is 30 seconds. There are no way to update status faster than this.

**Comment by RandomUserName22** [comment]
I noticed this stop working too.  It used to work, so did something change with the integration, or with LG?

Because if I change ICEPLUS for example, your integration updates instantly, and the appliance updates immediately.  WOrks immediately in both directions.
