### ISSUE TITLE
Change Temperature Unit

### ISSUE THREAD

**Issue by matheuspel** [ollo69/ha-smartthinq-sensors#601]
**Describe the bug**
After I inserted the LG SmartThinQ LGE Sensor integration, my air conditioning was detected correctly, as were all its functions. However, I am unable to change the temperature unit from Fahrenheit to Celsius. There is no option for this within the entity.

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed: 2023.9.1
 - Component version installed:
 - Last know working version:
 - LG device type and model with issue: AC LG Dual Inverter Wifi 12000BTUs
 - LG devices connected (list): AC LG Dual Inverter Wifi 12000BTUs

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by nufastjo** [comment]
Hello,
You must change the HA system parameters - General parameters - unitary system and not at the plugin.

**Comment by ollo69** [comment]
Not integration issue, I close this.
