### ISSUE TITLE
lg_dryer_remaining_time is unavailable.

### ISSUE THREAD

**Issue by aho206** [ollo69/ha-smartthinq-sensors#603]
**Describe the bug**
My raspberry Pi broken, and reinstall a new HA, also smarththinq-sensors, but notice that , the LG dryer remaining time entity is unavailable. How can fix it?

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**
<img width="1626" alt="image" src="https://github.com/ollo69/ha-smartthinq-sensors/assets/65076364/31ad37c6-82dc-450f-b8cd-4c68721840b6">

**Environment details:**
 - Environment (HASSIO)
 - Home Assistant version installed:
--Home Assistant 2023.9.2
--Supervisor 2023.09.2
--Frontend 20230911.0 - latest
 - Component version installed:
--0.33.3
 - Last know working version:
 - LG device type and model with issue:
--RC90V9_RUS-Dryer (DRYER) by LG
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by ollo69** [comment]
Just click on it and enable, because it is disabled by default. Not integration issue, I close this.
