### ISSUE TITLE
PM10, PM25, etc. sensors

### ISSUE THREAD

**Issue by skinkie** [ollo69/ha-smartthinq-sensors#606]
**Is your feature request related to a problem? Please describe.**
Are the sensor values of PM10, PM25 available through Thinq?

**Describe the solution you'd like**
The ability to log the property similar to temperature.

**Comment by ollo69** [comment]
You must provide more details and attach integration diagnostic!!!!
From which device you expect  pm sensors, your dishwasher?

**Comment by skinkie** [comment]
[smartthinq_sensors-f2602f0d26f4390e50358d85290c71ff-Huiskamer-029ef71f20a8afbf57bf64ab176ed0ce.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/12716639/smartthinq_sensors-f2602f0d26f4390e50358d85290c71ff-Huiskamer-029ef71f20a8afbf57bf64ab176ed0ce.json.txt)

**Comment by skinkie** [comment]
I think airState.quality.* is what I would like to have as properties, and airState.quality.airMon = 1 should be enabled.
