### ISSUE TITLE
Airconditioner without humidity support

### ISSUE THREAD

**Issue by Xitro01** [ollo69/ha-smartthinq-sensors#607]
Hi,

My airconditioning unit does not support humidity.
So the value in "current_humidity" shows as 0. Which is also sent to my HomeKit, which thinks the humidity in that room is 0%.

Is it possible to not show this value? If the humidity value that you get is "0" that it removes current_humidity completely?

For now (workaround) I just removed this part in climate.py:
```
     @property
     def current_humidity(self) -> int | None:
         return self._api.state.device_features.get(AirConditionerFeatures.HUMIDITY)
```

Thanks in advance!

**Comment by ollo69** [comment]
You could just disable the entity from HA UI instead of modify the code.
If you attach integration diagnostics I will check if there is a way to understand if this sensor is available or not.

**Comment by ollo69** [comment]
This issue should be fixed in last release, please check and report here.

**Comment by Xitro01** [comment]
> This issue should be fixed in last release, please check and report here.

Just updated and rebooted, this solves my issue. Thanks alot for your quick fix!
Hopefully this does not affect others that actually do have a humidity sensor in their airconditioners.

**Comment by ollo69** [comment]
> Hopefully this does not affect others that actually do have a humidity sensor in their airconditioners.

I hope so too, the idea is that humidity=0 just do not make sense. In the case of new issue I will compare diagnostics of device with humidity sensors and yours to try to find a different way👍
