### ISSUE TITLE
Not able to add integration

### ISSUE THREAD

**Issue by rt45433** [ollo69/ha-smartthinq-sensors#608]
I'm from the Uk and have had this working in the past, just setup a new raspberry pi with HA and when adding the integration and going through the redirect its not working. 

I have tried (email login UK, English) (Social media login) and tried the redirect method but none are working. I can log into the app on my phone with the same credentials. Can you offer any advise on if i am doing anything wrong?

**Comment by ollo69** [comment]
@rt45433,

please use issue template and provide requested information, as HA and integration version, error log etc.
Generally speaking this integration do not work with social media login as explained in readme. It could work in some cases, but most of time it doesn't.

**Comment by ollo69** [comment]
I close this because no feed-back after 2 weeks, open a new one using issue template if you still need support.
