### ISSUE TITLE
Add Dishwasher steam sensor 

### ISSUE THREAD

**Issue by bzzzggz** [ollo69/ha-smartthinq-sensors#610]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
Add Dishwasher's steam option as a sensor, similar like 'half load', etc. 
![Screenshot_20231013_214009_LG ThinQ](https://github.com/ollo69/ha-smartthinq-sensors/assets/58054872/0f75bdb2-43ac-4c0e-90cc-5ee5d25353be)

**Describe alternatives you've considered**

**Additional context**

**Comment by bmorgan99** [comment]
Also, shouldn't `sensor.dishwasher_process_state `list "Steam" when it is on?  I've only tried it once, but "Washing" was displayed from the start which should be when steam is applied.

**Comment by bzzzggz** [comment]
> Also, shouldn't `sensor.dishwasher_process_state `list "Steam" when it is on? I've only tried it once, but "Washing" was displayed from the start which should be when steam is applied.

Might be different model shows differently? Mines steam is like an option it's not showing under the "process state". Only three states available: washing, rinsing and drying. Am guessing steam is part of drying?

**Comment by sthevenp** [comment]
"Steam" is a separate button like "Extra dry" and "High Temperature" or "Dual Zone" button in the dishwasher buttons before you start the program.

**Comment by ollo69** [comment]
Steam sensor should be available with last release.

**Comment by lezruk** [comment]
That is very nice feature 👍🏻, after upgrade to 0.38 I do not see steam in attributes or in objects list. Is there any particular step to be done? I see steam in ThinQ app for my LDTS5552S dishwasher.

**Comment by ollo69** [comment]
Not all devices expose same sensor. Please attach integration diagnostic so that I can check your device.

**Comment by lezruk** [comment]
> Not all devices expose same sensor. Please attach integration diagnostic so that I can check your device.

PFA

[smartthinq_sensors-acf19b28d8cc69cf15c01ba6a5bc82b1-Посудомойка-2b69c33e02aef29dab4ee318bff6fefb.json](https://github.com/ollo69/ha-smartthinq-sensors/files/14224397/smartthinq_sensors-acf19b28d8cc69cf15c01ba6a5bc82b1-.-2b69c33e02aef29dab4ee318bff6fefb.json)

**Comment by bmorgan99** [comment]
Also not seeing it.

[config_entry-smartthinq_sensors-560a1b67c19e3e733c14772d8c901026.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/14225528/config_entry-smartthinq_sensors-560a1b67c19e3e733c14772d8c901026.json.txt)

**Comment by lezruk** [comment]
It reports though on device status structure

`"device_status": {
            "State": "RUNNING",
            "Process": "RINSING",
            "Error": "ERROR_NO",
            "Initial_Time_H": "2",
            "Initial_Time_M": "59",
            "Course": "1",
            "CourseType": "COURSE",
            "Remain_Time_H": "1",
            "Remain_Time_M": "7",
            "Reserve_Time_H": "0",
            "Reserve_Time_M": "0",
            "ChildLock": "OFF",
            "Door": "CLOSE",
            "RinseRefill": "NOT_SET",
            "SaltRefill": "NOT_SET",
            "SignalLevel": "LEVEL_ON",
            "MCReminderSetting": "ON",
            "CleanLReminder": "ON",
            "NightDry": "ON",
            "DelayStart": "OFF",
            "EnergySaver": "OFF",
            "ExtraDry": "ON",
            "HighTemp": "ON",
            "DualZone": "OFF",
            "HalfLoad": "OFF",
            "AutoDoor": "OFF",
            "PreSteam": "",
            **"Steam": "ON",**
            "RinseLevel": "LEVEL_2",
            "SofteningLevel": "LEVEL_0",
            "SmartCourse": "0",
            "CurrentDownloadCourse": "POTS_PANS",
            "TclCount": "14"
          },`

**Comment by bmorgan99** [comment]
Not sure what that means,  I have an LDPH7972D, if that's of consequence.

**Comment by ollo69** [comment]
Sorry, I forgot to add definition in binary sensor, it will be available with next release.

**Comment by lezruk** [comment]
> Sorry, I forgot to add definition in binary sensor, it will be available with next release.

Thank you for your awesome work.

**Comment by ollo69** [comment]
Ok, now sensor should be available in last release.

**Comment by lezruk** [comment]
> Ok, now sensor should be available in last release.

I confirm - seeing now steam in sensors and attributes on 0.38.1 👍

**Comment by ollo69** [comment]
Good, I close this
