### ISSUE TITLE
Energy monitor for LG ThinQ Washing machine and dryer 

### ISSUE THREAD

**Issue by rikray02** [ollo69/ha-smartthinq-sensors#612]
Hello,

First of all, thank your for the plug-in.  It's work very well.  My brand new LG Washing machine and dryer can show, in app, th energy consumption.  But i'm not sure if this plugging can read this information.  

If yes, could you tell me how can i read and use it?

If no, is it possible to evaluate the possibility to add this featureY

Tanks for you reply!
Richard

**Comment by ollo69** [comment]
Close because duplicated of #555
