### ISSUE TITLE
LG Therma V heat pump-water heater Add sensor

### ISSUE THREAD

**Issue by Asso1960** [ollo69/ha-smartthinq-sensors#615]
HI,
I use your package to monitor the pdc.
I saw that the machine also provides other parameters on the RS485 interface:
- compressor on/off status
- defrost status on/off
- flow of liters per minute
and others that are already provided by integration.
To control the efficiency of the HP it is essential to control these parameters. Is it possible to integrate them? or are they only available on rs485 interface?
   Thank you
Joseph

**Comment by ollo69** [comment]
If you download integration diagnostics you can see available information in `Device Status` section, but I don't think that these parameters are available via LG ThinQ API.

**Comment by Asso1960** [comment]
Thanks for Reply
