### ISSUE TITLE
Jet mode for ACs stopped working

### ISSUE THREAD

**Issue by igorsantos07** [ollo69/ha-smartthinq-sensors#620]
**Describe the bug**
I'm sorry for taking this out of the blue, but there's quite some time the jet mode switches for my two AC units stopped working. They're from similar models, and I _think_ this stopped working after some update, but lots of stuff have been going on in HA and in my installation that I haven't kept up with, so... I don't have a timeline for the issue :(

I have the diagnostics files, though, I hope this helps:
- [Ar quarto-18c7bcbfba932f9f97f0766e4162243f.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/13031857/smartthinq_sensors-298e7b62c878358f070e8ed5557ad1c7-Ar.quarto-18c7bcbfba932f9f97f0766e4162243f.json.txt)
- [Ar cinema-8edc6fbad1f26c66b4c03173d641dd78.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/13031872/smartthinq_sensors-298e7b62c878358f070e8ed5557ad1c7-Ar.cinema-8edc6fbad1f26c66b4c03173d641dd78.json.txt)
- [config_entry-smartthinq_sensors-298e7b62c878358f070e8ed5557ad1c7.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/13031886/config_entry-smartthinq_sensors-298e7b62c878358f070e8ed5557ad1c7.json.txt)

**Expected behavior**
I remember it used to work at some point 😅 

**Screenshots**
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/532299/8c077ef5-42f1-42ba-a502-0820634ae19e)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HA OS 11.0, just updated from 10.5
 - Home Assistant version installed: 2023.10.3
 - Supervisor 2023.10.0
 - Frontend 20231005.0
 - Component version installed: 0.34.0
 - Last know working version: ?
 - LG device type and model with issue: can't find this, I guess diagnostics file is enough?
 - LG devices connected (list): Ar quarto, Ar cinema (both AC units with the fault), Lava-e-seca (unrelated combo washing machine)

**Comment by igorsantos07** [comment]
I saw that on a related issue, turned it on and nothing changed. Tried it again and, indeed, it went on. Not sure why it didn't work before, I wonder if I tried to turn it on Fan mode instead.

I guess there's no way to block a switch in HA without causing it to be unavailable, right?
Would it be viable to just refuse to turn on when not in valid mode, with an accompanying error message/notification? The current way isn't obvious for the user what's going on (given at least two users already reported it); something "unavailable" in HA would mean "something is wrong with your setup" instead of "you're in a mode where this switch won't do anything". Specially, I found that by using [Watchman](https://github.com/dummylabs/thewatchman), which is an add-on to look for outdated/broken stuff in your setup.

**Comment by ollo69** [comment]
> The current way isn't obvious for the user what's going on (given at least two users already reported it); something "unavailable" in HA would mean "something is wrong with your setup" instead of "you're in a mode where this switch won't do anything"

Make sense, but I'm not sure that raise an error when the switch should not be used make difference. Probably most of the people will complain that the switch is not working, exactly in the same way. May be the switch is not the right entity... I will think about this, and suggestion are welcome.

**Comment by igorsantos07** [comment]
The switch makes sense - it's the same on the LG app, for instance, and it's a mode you would turn on and off. It wouldn't make sense, for instance, inside de AC modes dropdown because it's effectively an option for some of those modes.

The error message, if it states the problem clearly, should be enough... unless people don't even read it, but then it's not our business - if they want to understand what's going on, they'll have to read it at some point. It must show as soon as the user tries to do the forbidden operation, this way they'll know their action caused a problem, and will know the reason - instead of staring at a non-functioning switch, guessing what might be going on.

As a web developer but that never touched HA inner stuff, my questions are:
- is it even _possible_ to leave the switch enabled, but have it refuse to turn on - or maybe make it go off again right after you try to turn it on?
- if so, can that be a real alert (like the ones we get on the corner when the system is rebooting), or the only way would be a log entry? If we're only able to emit a log error, that's not exactly helpful since it's quite hidden, and the user should have immediate feedback about the error they produced.

**Comment by ollo69** [comment]
> * is it even _possible_ to leave the switch enabled, but have it refuse to turn on - or maybe make it go off again right after you try to turn it on?

Yes

> * if so, can that be a real alert (like the ones we get on the corner when the system is rebooting), or the only way would be a log entry? If we're only able to emit a log error, that's not exactly helpful since it's quite hidden, and the user should have immediate feedback about the error they produced

Yes, a persistent notification could be created 

I have another question: what is the behavior of  the switch in LG app?

**Comment by selectcarleasing** [comment]
In the app the buttons are not there you only have the option to power on.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ollo69** [comment]
> In the app the buttons are not there you only have the option to power on.

This is not what @igorsantos07 is reporting. I'm confused now...

**Comment by igorsantos07** [comment]
>I have another question: what is the behavior of the switch in LG app?

Good question, indeed!
When the AC is off, the button won't display; it just shows the current state (Off + temperature) and the mode select box, plus a scheduling button.
When it's on Cooling mode, the button is obviously there.
But then, on Fan mode......... the button also shows up! If I toggle it, it changes the AC into Cooling+Jet mode. No clue what it would do if my AC had Heating mode as well (does Jet mode works when Heating? Would it enter into Auto mode instead?)

**Comment by igorsantos07** [comment]
Dang, yet another issue closed because the dev didn't interact and we have to be dilligent with spammy "up" comments...
