### ISSUE TITLE
Washing Machine - Add Pause/Resume command

### ISSUE THREAD

**Issue by mattefox** [ollo69/ha-smartthinq-sensors#627]
"The function available in the LG ThinQ app is not available in the integration. It would be very useful for managing electrical consumption and avoiding power disconnection or optimizing consumption if a photovoltaic system is in place."

**Comment by FilippoS1973** [comment]
I Agree, feature request very usefull. However, I don't know if it's easy to create. In any case, thanks Ollo69!

**Comment by FilippoS1973** [comment]
I'll specify better. Currently the ability to turn off the washing machine from HA is integrated and it works.
However, if we use this switch to manage a load control, we are not able to restart it and, if we do it manually from the washing machine, when it is turned back on, the washing machine has lost the wash information and we have to start again from the beginning.
For these reasons it would be very useful to integrate the possibility of the pause button that is present in the LG app.

**Comment by ollo69** [comment]
Pause button is now available with last release. Please test is and report here results.

**Comment by FilippoS1973** [comment]
test ok. pause command works from ha. well done!
new issue. to resume program from ha I used "remote start" of this release but washing machine started program from scratch.

**Comment by ollo69** [comment]
> new issue. to resume program from ha I used "remote start" of this release but washing machine started program from scratch.

Was it working properly with previous release?
Could someone capture traffic from Mobile app to see the command used to resume? 
Please also attach device diagnostics so that I can take a look to your model info and maybe found additional info.

**Comment by FilippoS1973** [comment]
the pause/resume button from the app works fine. the "remote start" button in HA works the same way in the previous release: it starts the program from scratch.
we need to understand how to replicate the app's resume button.
I attach the diagnostics

[smartthinq_sensors-d45cacc22fb0e37e6c898e3c348f20dd-LAVATRICE-4233ca5e0aac5f40d0a83ffd8f1b959b.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/14157718/smartthinq_sensors-d45cacc22fb0e37e6c898e3c348f20dd-LAVATRICE-4233ca5e0aac5f40d0a83ffd8f1b959b.json.txt)

**Comment by ollo69** [comment]
Unfortunately diagnostics do not provide additional info. I suppose that is just a matter of calling `WMStart` with different parameter but we need to capture traffic from LG App.
I will try to do this my side but I have a APIv1 device and commands are different from APIv2

**Comment by ollo69** [comment]
Maybe I found the reason, could be the `initial_bit` value send with the `start` command. Please try last release and let me know if fix the issue.

**Comment by FilippoS1973** [comment]
Well done, I tested and it works perfectly
thank you

Il giorno lun 5 feb 2024 alle ore 01:55 ollo69 ***@***.***>
ha scritto:

**Comment by ollo69** [comment]
Good, close this.
