### ISSUE TITLE
Washer-Dryer combo is missing sensors or sensors have no values

### ISSUE THREAD

**Issue by lukasmalkmus** [ollo69/ha-smartthinq-sensors#629]
**Describe the bug**

I have a Washer/Dryber Combo which exports a sensor for "Wash Completed" but not for "Dry Completed".

Also I don't see any state changes for "Error state" and "Error message" although the machine reported an error this morning that needed my attention and it was also displayed in the LG ThinQ App.

**Expected behavior**

Since it is a Washer/Dryer Combo I also expect to see a separate sensor for "Dry Completed", maybe even a sensor that reports when a Wash and Dry cycle is completed.

I also expected the error states to change when the machine fired an error.

**Screenshots**

<img width="325" alt="Screenshot 2023-10-28 at 17 53 59" src="https://github.com/ollo69/ha-smartthinq-sensors/assets/9931588/de074429-0985-4878-9cd4-d05df22adf73">

**Environment details:**

Raspberry Pi 4 running:

```
Home Assistant 2023.10.5
Supervisor 2023.10.1
Operating System 11.1
Frontend 20231005.0 - latest
```

The only device I'm using as reported by the Integration is `DB0080E7-FL (WASHER)` otherwise known as the `LG SIGNATURE LSWD100E`.

**Output of HA logs**

Not an error that occurs with the integration inside Home Assistant so no helpful logs (correct me if otherwise).

**Additional context**

None.

**Comment by TorbjornMohn** [comment]
Same problem for me.... 
![Screenshot 2023-11-10 175223](https://github.com/ollo69/ha-smartthinq-sensors/assets/64417279/555cb918-f830-458d-bbc7-9d93c8498213)
Lots of sensors missing! Used to work..

**Comment by florianmueller** [comment]
I want to report the same issue with my washer/dryer combo device. Some sensors are not getting any info, while the info is present in the app. For example these red marked sensors are all in state „unavailable“. Unfortunately also the most usful one for me „Time remaining“. Thank you for your work in this and for having a look into this!
![IMG_6426](https://github.com/ollo69/ha-smartthinq-sensors/assets/7986193/7ce9f6ba-b47e-4d0d-97ed-4c97a14610b9)

**Comment by ollo69** [comment]
Please attach diagnostics.
Related to unavailable sensors, you just need to enable them from UI.

**Comment by lukasmalkmus** [comment]
> Please attach diagnostics.

As described in [this section](https://github.com/ollo69/ha-smartthinq-sensors#obtaining-api-information)?

Will try, although I'm on iOS so this might be slightly more complicated?

> Related to unavailable sensors, you just need to enable them from UI.

I guess you are referring to @florianmueller? The states I described are definitely missing and/or not working, as described in my initial posting.

**Comment by ollo69** [comment]
> As described in [this section](https://github.com/ollo69/ha-smartthinq-sensors#obtaining-api-information)?

No, just download device diagnostics on integration page and attach extracted file to this thread
 
> I guess you are referring to @florianmueller?

Yes, second post and related image.

**Comment by lukasmalkmus** [comment]
Ah, much appreciated. Here you go @ollo69:

[config_entry-smartthinq_sensors-a3a12fb60b267994a0cc37824e323f1c.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/13403522/config_entry-smartthinq_sensors-a3a12fb60b267994a0cc37824e323f1c.json.txt)

**Comment by florianmueller** [comment]
> Please attach diagnostics. Related to unavailable sensors, you just need to enable them from UI.

Hey @ollo69 , Thank you for your reply. I attached the diagnostics file.

Where in the UI can I enable unavailable sensors? Under the Integration settings I did not found it, also not under the device settings. Thanks!

[smartthinq_sensors-1cbb3fe2f2b1c4cb6844a4aa53d8b06b-BigWash-2997a9e111cb72da881864914f825bb2.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/13407176/smartthinq_sensors-1cbb3fe2f2b1c4cb6844a4aa53d8b06b-BigWash-2997a9e111cb72da881864914f825bb2.json.txt)

**Comment by florianmueller** [comment]
> @florianmueller If you visit the affected device there is the `Sensors` card which lists all the enabled sensors. The last row should read something like `+5 other sensors` or something similar. If you expand that section, a couple of greyed-out sensors should appear. Click a sensor, than in the overlay click the cogwheel (settings) button in the top-right corner. From there you need to toggle the `Enabled` switch. Repeat for every sensor you want to enable.

Thank you so much, that solved the issue for me. After enabling all 8 disabled sensors/entities and restarted HA, they all have correct values now from the dryer/washer. Awesome integration, thanks!

**Comment by ollo69** [comment]
Error message now should be properly handled in last release. Related to the binary sensor Wash Completed / Dry completed, I just renamed it Run completed. There are no way to really understand if monitored device is a Washer or a Dryer and generic sensor name make more sense because in any case is related to specific device.

**Comment by lukasmalkmus** [comment]
Nice, gonna test it out as soon as I can and report my findings.

**Comment by ollo69** [comment]
Any news here?

**Comment by ollo69** [comment]
Ok to keep this open, also because I'm doing some additional minor changes, so you can report here if you will find some issue with next releases.
If this will auto-close means that everything is ok.

Thanks.

**Comment by lukasmalkmus** [comment]
Thanks, the latest release(s) fixed everything!

I got an error because my filter was clogged and I also ran out of detergent. Both sensors triggered accordingly 🙌 

Thanks for your great work!

Closing.
