### ISSUE TITLE
Heating pump - Hot water temperature not available

### ISSUE THREAD

**Issue by cahenning2901** [ollo69/ha-smartthinq-sensors#637]
**Describe the bug**
Values for entity "Hot_water_temperature" are not available anymore.

**Expected behavior**
I expect the value for hot_water_temperature again

**Screenshots**
<img width="240" alt="image" src="https://github.com/ollo69/ha-smartthinq-sensors/assets/83812950/984815fb-b2cb-48a6-a3e0-78a063f52a78">

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): See attachment
 - Home Assistant version installed: 2023.11.1
 - Component version installed: See attachment
 - Last know working version:
 - LG device type and model with issue: AWHP_019101_WW-AWHP (AC) von LG
 - LG devices connected (list):

**Output of HA logs**
[smartthinq_sensors-170c16cddd9d96d0af6b3980b33bb5fc-Luft-Wasser-Wärmepumpe-756dca63c60628e4e56513ed74dcdd32.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/13277511/smartthinq_sensors-170c16cddd9d96d0af6b3980b33bb5fc-Luft-Wasser-Warmepumpe-756dca63c60628e4e56513ed74dcdd32.json.txt)

```

```

**Additional context**

**Comment by ricsch** [comment]
Hi,

same her, but i can‘t fetch any data from the heatpump since the update a few days ago.

**Comment by cahenning2901** [comment]
Hi,
value for Hot_water_temperature is available. For me the issue is solved. Thanks.

**Comment by ollo69** [comment]
I changed nothing about this from many version, so I don't think this is an issue related to version update. Maybe something is changed LG side.

**Comment by cahenning2901** [comment]
okay, thanks. Maybe on LG side is something wrong. Sometimes values are shown and sometimes not. I´ll do further investigation.

**Comment by cahenning2901** [comment]
Hi, I´ve a question. How can I check if on LG side all values are available or not?

**Comment by ollo69** [comment]
Check LG app, than download integration diagnostics and verify value in `snapshot` payload.

**Comment by cahenning2901** [comment]
Below is the snapshot payload. It shows "hotWaterCurrent", but not "hotWaterTemperature". Maybe that´s the problem?
            "snapshot": {
              "airState.tempState.airTempHeatMin": 16.0,
              "airState.diagCode": 0.0,
              "airState.tempState.waterTempCoolMin": 5.0,
              "airState.tempState.airTempCoolMin": 16.0,
              "mid": 38949639.0,
              "airState.miscFuncState.awhpWaterControl": 0.0,
              "airState.tempState.target": 17.0,
              "airState.humidity.current": 0.0,
              "airState.tempState.hotWaterTempMin": 30.0,
              "airState.operation": 1.0,
              "airState.reservation.absoluteStopTime": 0.0,
              "airState.tempState.waterTempHeatMax": 65.0,
              "airState.tempState.airTempCoolMax": 30.0,
              "timestamp": 1700831855068.0,
              "airState.quality.PM10": 0.0,
              "static": {
                "deviceType": "603",
                "countryCode": "DE"
              },
              "airState.tempState.hotWaterCurrent": 54.0,
              "airState.tempState.current": 19.0,
              "airState.tempState.hotWaterTempMax": 80.0,
              "airState.miscFuncState.awhpTempSwitch": 1.0,
              "airState.miscFuncState.extraOp": 0.0,
              "airState.tempState.hotWaterTarget": 55.0,
              "airState.reservation.absoluteStartTime": 0.0,
              "airState.tempState.waterTempHeatMin": 15.0,
              "airState.miscFuncState.powerHotWater": 0.0,
              "airState.tempState.airTempHeatMax": 30.0,
              "meta": {
                "allDeviceInfoUpdate": false,
                "messageId": "o79Nw1AxQO2XGDWfBGTBjQ"
              },
              "airState.quality.PM1": 0.0,
              "airState.tempState.waterTempCoolMax": 27.0,
              "airState.miscFuncState.silentAWHP": 0.0,
              "airState.quality.PM2": 0.0,
              "online": true,
              "airState.miscFuncState.hotWater": 1.0,
              "airState.opMode": 3.0,
              "airState.tempState.outWaterCurrent": 45.0,
              "airState.tempState.inWaterCurrent": 43.0

**Comment by ollo69** [comment]
Maybe, I'll check what I'm mapping as soon as I will have some available time (I'm really busy in this period...)

**Comment by ollo69** [comment]
Can you please attach the diagnostic file?

**Comment by cahenning2901** [comment]
Please find the diagnostic file attached.
[home-assistant_smartthinq_sensors_2023-11-26T09-58-53.264Z.log](https://github.com/ollo69/ha-smartthinq-sensors/files/13466435/home-assistant_smartthinq_sensors_2023-11-26T09-58-53.264Z.log)

**Comment by cahenning2901** [comment]
or is it this one?
[config_entry-smartthinq_sensors-170c16cddd9d96d0af6b3980b33bb5fc.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/13466443/config_entry-smartthinq_sensors-170c16cddd9d96d0af6b3980b33bb5fc.json.txt)

**Comment by ollo69** [comment]
> or is it this one? 

Yes, this is what I need, thaks👍

**Comment by ollo69** [comment]
@cahenning2901,

could you better explain what your device exactly is? It is just a water heater or also an heat device. Looks like do not have some of the characteristics I saw before and I'm not sure that it is properly managed.

Thanks.

**Comment by cahenning2901** [comment]
Hi,
the device is an air-water heating pump. It heats my house and heats my water. So it is a heat device and a water heater.
Thanks.

**Comment by ollo69** [comment]
> the device is an air-water heating pump. It heats my house and heats my water. So it is a heat device and a water heater.

Ok, can you give some more details? As example I'd like to know the operation available for the heat pump and for the water heater. You can set heat and cold, just heat, set temperature...(using LG app or directly the device, not HA)???
As I can see I'm not providing any operation mode for "AC" device, but I don't think this is correct!

**Comment by cahenning2901** [comment]
The device name is HM071MR U44. Direkt on the operation panal of the device its possible to operate a lot parameters. In the LG app ou can only operate the "Target Hot Water Temperature" and switch on a "Quick DHW Heating" (see attached picture).
For me the sensors and switches in your HA solution are sufficient if they are available. 

![Screenshot_20231127_090747_LG ThinQ](https://github.com/ollo69/ha-smartthinq-sensors/assets/83812950/34e25688-32b3-478b-8dbd-ffdd983cc3d6)

**Comment by ollo69** [comment]
Ok, I found the reason for which Water Heater was not shown, I will provide a fix as soon as possible, but please be patient because I cannot work on this immediately.

**Comment by cahenning2901** [comment]
Hi, any news on this issue? Did you had the chance to work on this?

**Comment by ollo69** [comment]
I'm traveling for work, I will work on this when I will be back home.

**Comment by cahenning2901** [comment]
Perfect! Thanks for your quick answer.

**Comment by ollo69** [comment]
This now should be fixed with last released version. Please check and let me know.

**Comment by cahenning2901** [comment]
Perfect! Looks good. Thanks a lot!
I wish you a Merry Christmas and a happy New Year.
