### ISSUE TITLE
Craft Ice Maker

### ISSUE THREAD

**Issue by Hdkquest** [ollo69/ha-smartthinq-sensors#638]
Hello, is there any way to add the Craft Ice maker ?
![Screenshot 2023-11-10 095611](https://github.com/ollo69/ha-smartthinq-sensors/assets/108177738/71480a5f-ee0f-4a6d-b0fb-a690b51990a0)

LG : GSXV90MCDE 
Core
2023.11.1
Supervisor
2023.11.0
Frontend
20231030.1

**Comment by yoda98mnt** [comment]
I have also ask for that feature:
https://github.com/ollo69/ha-smartthinq-sensors/issues/501
but nothing :-(

**Comment by utzy79** [comment]
+1 for this feature request
