### ISSUE TITLE
Freezer Climate: Setting Temperature to 0 fails

### ISSUE THREAD

**Issue by skylyn** [ollo69/ha-smartthinq-sensors#639]
**Describe the bug**
Setting temperature to 0 does nothing. Temperature returns to previously set temperature. All other numbers work.

**Expected behavior**
When setting temperature to 0, temperature is successfully set to 0.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed: 2023.10.5, but has been a problem with all previous releases
 - Component version installed: 0.35.2
 - Last know working version: None
 - LG device type and model with issue: Refrigerator/freezer
 - LG devices connected (list):

**Output of HA logs**
I haven't seen any relevant logs.

**Additional context**
N/A

**Comment by ollo69** [comment]
Fixed by #640
