### ISSUE TITLE
LG Heat Pump-thermostat card shows wrong temperature

### ISSUE THREAD

**Issue by gvala** [ollo69/ha-smartthinq-sensors#643]
The thermostat card shows as current temperature the out_water temperature instead of the room_temperature.

I've made a correction in smartthinq_sensors/climate.py file and now it shows the correct temperature

@property
    def current_temperature(self) -> float:
        """Return the current temperature."""
        curr_temp = None
        if self._device.is_air_to_water:
            curr_temp = self._api.state.device_features.get(
                AirConditionerFeatures.ROOM_TEMP
            )
        if curr_temp is None:
            curr_temp = self._api.state.device_features.get(
                AirConditionerFeatures.ROOM_TEMP
            )
        return curr_temp

**Comment by ollo69** [comment]
I don't have a Heat Pump device so I don't really know what current temperature means, but I'm quite sure that this check was implemented for a specific reason defined when this device was introduced. So I will not implement this change until the real meaning of current temp is clarified.

By the way if you always want ROOM_TEMP, you should remove everything except the last 2 line.

**Comment by ollo69** [comment]
@gvala 

please take a look to issue #157.
This was talking about exposed temperature and for this reason now integration is using water temperature. May be your device is different, but I need to understand the right way to manage both. 
Please provide more details about your device and attach integration diagnostic so that I can analyze it.

**Comment by gvala** [comment]
Thanks for coming back!
I believe that I have the same LG model as referred to #157.
I attach the diagnostics.
[smartthinq_sensors-654b8b066e00da8febec874e4d8b95db-Αντλία θερμότητας-5cabac28bc2b2aa59e1772d6d45d92b0.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/13485215/smartthinq_sensors-654b8b066e00da8febec874e4d8b95db-.-5cabac28bc2b2aa59e1772d6d45d92b0.json.txt)

All screenshots in #157 are not valid anymore, so I cannot understand what was the object

**Comment by ollo69** [comment]
Please check if  with last release current temperature and related target range now are correct.

**Comment by gvala** [comment]
Yes, now it seems right. Thank you!
