### ISSUE TITLE
LG Range target temperature entities not working

### ISSUE THREAD

**Issue by Waank1** [ollo69/ha-smartthinq-sensors#647]
LG Stove model #LTE4815ST
Integration lists 12 entities:

OVEN
sensor.oven
SmartThinQ LGE Sensors
Kitchen
—
OVEN Cooktop center state
sensor.oven_cooktop_center_state
SmartThinQ LGE Sensors
Kitchen
—
OVEN Cooktop left front state
sensor.oven_cooktop_left_front_state
SmartThinQ LGE Sensors
Kitchen
—
OVEN Cooktop left rear state
sensor.oven_cooktop_left_rear_state
SmartThinQ LGE Sensors
Kitchen
—
OVEN Cooktop right front state
sensor.oven_cooktop_right_front_state
SmartThinQ LGE Sensors
Kitchen
—
OVEN Cooktop right rear state
sensor.oven_cooktop_right_rear_state
SmartThinQ LGE Sensors
Kitchen
—
OVEN Cooktop state
binary_sensor.oven_cooktop_state
SmartThinQ LGE Sensors
Kitchen
—
OVEN Oven lower state
sensor.oven_oven_lower_state
SmartThinQ LGE Sensors
Kitchen
—
OVEN Oven lower target temperature
sensor.oven_oven_lower_target_temperature
SmartThinQ LGE Sensors
Kitchen
—
OVEN Oven state
binary_sensor.oven_oven_state
SmartThinQ LGE Sensors
Kitchen
—
OVEN Oven upper state
sensor.oven_oven_upper_state
SmartThinQ LGE Sensors
Kitchen
—
OVEN Oven upper target temperature
sensor.oven_oven_upper_target_temperature
SmartThinQ LGE Sensors
Kitchen
—
If possible attach the JSON info file for your devices: UNK
All but 2 entities report as expected.  Non working are:
Oven upper target temperature
Oven lower target temperature
They both show: unknown all the time

**Expected behavior**
Once oven is on and a temperature is set, I would expect entities to have some value:

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):  HASSIO
 - Home Assistant version installed:  
Core: 2023.12.3
Supervisor: 2023.11.6
Operating System: 11.2
Frontend: 20231208.2
 - Component version installed:
 - Last know working version: As far as I know they have never worked
 - LG device type and model with issue: LG Stove model #LTE4815ST 
 - LG devices connected (list): LG Stove model #LTE4815ST and Refrigerator LMXS30796*

**Output of HA logs**
Paste the **relevent (SP)** output of the HA log here.
N/A
```

Software version
Device App: 35.58
Modem: QC Modem 1.2.80
Firmware: SAA39155802.00003483.0

**Additional context**
Add any other context about the problem here.
I Like the integration, not a deal breaker that they don't work, just would be nice.

**Comment by Waank1** [comment]
Software version
Device App: 35.58
Modem: QC Modem 1.2.80
Firmware:  SAA39155802.00003483.0

**Comment by thomaskistler** [comment]
FWIW, my target temperature does work:
<img width="826" alt="Screen Shot 2023-12-23 at 10 13 13 AM" src="https://github.com/ollo69/ha-smartthinq-sensors/assets/542423/e3c589f3-2d6a-4b4d-b7a2-eabb5d7b218b">

**Comment by Waank1** [comment]
Thanks, thomaskistler, Mine is a dual oven and the only 2 entities that don't work are the target temps.

**Comment by ollo69** [comment]
Please attach integration diagnostics (while device is on and target temperature set) so that I can analyze your payload.

**Comment by Waank1** [comment]
Here is the diagnostics data:
[smartthinq_sensors-0905bfbc33cf9234eee00179e1229d90-OVEN-115a7fff3f813e0c023b0f72ee854fc2.json](https://github.com/ollo69/ha-smartthinq-sensors/files/14350622/smartthinq_sensors-0905bfbc33cf9234eee00179e1229d90-OVEN-115a7fff3f813e0c023b0f72ee854fc2.json)

**Comment by ollo69** [comment]
@Waank1 ,

please try is last release fix the issue.

**Comment by Waank1** [comment]
I tried it and it is working perfectly now.  Thank you!

**Comment by ollo69** [comment]
Good, I close this.

**Comment by Waank1** [comment]
I spoke too soon.  Now the current temperature is not working....... But the target temperature is.

**Comment by ollo69** [comment]
I need more information. Please attach new diagnostic with the device turned on so that I can analyze returned data. If possible also collect some logs with debug level.

**Comment by Waank1** [comment]
Here are the logs.  The oven temperature is displayed correctly until I set a target temperature.  Then the target appears and the oven temp changes to unknown.
[config_entry-hacs-074eca2c5c9ab65cf3238250466a3339.json](https://github.com/ollo69/ha-smartthinq-sensors/files/14398144/config_entry-hacs-074eca2c5c9ab65cf3238250466a3339.json)
[config_entry-smartthinq_sensors-0905bfbc33cf9234eee00179e1229d90.json](https://github.com/ollo69/ha-smartthinq-sensors/files/14398145/config_entry-smartthinq_sensors-0905bfbc33cf9234eee00179e1229d90.json)

**Comment by ollo69** [comment]
I need diagnostics generated when target temperature is set, I think that the issue is related to unit of measure, but I need to see the values returned to understand where is the error.

**Comment by Waank1** [comment]
Here is when target temp is set:
[config_entry-hacs-074eca2c5c9ab65cf3238250466a3339 (1).json](https://github.com/ollo69/ha-smartthinq-sensors/files/14398287/config_entry-hacs-074eca2c5c9ab65cf3238250466a3339.1.json)

**Comment by ollo69** [comment]
@Waank1,

you attach hacs diagnostics, I need integration diagnostiscs.

**Comment by ollo69** [comment]
Unfortunately this doesn't seems to be an issue related to the integration but the way the data is provided. When target temperature value is set, the current temperature returned is 0, at least in the payload present in the diagnostics provided, and for this reason is set to `None` (unknown in UI)
My question is: what are the information provided by LG app?

**Comment by Waank1** [comment]
It has been many months since I have looked at the LG app.  I just checked, it only provides the temperature (which is very slow to update) and the status ie.  preheating, baking, broiling etc.

**Comment by ollo69** [comment]
When you say temperature you mean target or current? Could you extract a diagnostic when temperature is shown in LG app and give me detail (may be a picture) of information shown in the app at that moment?

**Comment by Waank1** [comment]
Here is a picture from my iPad and a diagnostic which was taken at the same time.
![IMG_0865 (002)](https://github.com/ollo69/ha-smartthinq-sensors/assets/68567593/c8c1792a-fcd5-4a37-80ec-cf1d16356e7e)
[config_entry-smartthinq_sensors-0905bfbc33cf9234eee00179e1229d90.json](https://github.com/ollo69/ha-smartthinq-sensors/files/14399058/config_entry-smartthinq_sensors-0905bfbc33cf9234eee00179e1229d90.json)

**Comment by ollo69** [comment]
Tis is quite complex situation. Your app is saying 72, but in the payload I just see the target temperature = 200. It is also providing a value of 77 for the Lower Cook temp, just wondering if this value could be inverted.
As first option you could try to collect some information in different condition (up on and low off, up off and low on, both on) and send diagnostic in every situation so that I can try to understand if there is some logics....

**Comment by thomaskistler** [comment]
It generally works for me. However, the resolution is quite poor and there
doesn't seem to be any reports during pre-heating:

[image: Screenshot 2024-02-26 at 7.00.27 AM.png]

**Comment by Waank1** [comment]
I will continue to get you more data in the near future, it seems each oven is now reading correctly the current temp until a target temp is set, then it no longer reports the current temp.  The lower oven when not on and no target set, merely reports the ambient temperature in the room.  Previously (in the integration) the oven temperature would always report accurately.

In the following data, the upper is on and cooking at 375.  The lower is off.

[config_entry-smartthinq_sensors-0905bfbc33cf9234eee00179e1229d90.json](https://github.com/ollo69/ha-smartthinq-sensors/files/14412556/config_entry-smartthinq_sensors-0905bfbc33cf9234eee00179e1229d90.json)

**Comment by Waank1** [comment]
Upper cooking at 385 while lower is preheating to 375.
[config_entry-smartthinq_sensors-0905bfbc33cf9234eee00179e1229d90.json](https://github.com/ollo69/ha-smartthinq-sensors/files/14423628/config_entry-smartthinq_sensors-0905bfbc33cf9234eee00179e1229d90.json)

**Comment by ollo69** [comment]
@Waank1,

the situation is always the same, I see all values that do not match with value you provide, most of them set to 0. 
Please enable debug log and send me log file, the last thing I can do is check the raw data to verify if it is properly converted to status data. I would be surprised if something is wrong because should fail most of devices, but everything is possible...
