### ISSUE TITLE
Support for WashTower devices 

### ISSUE THREAD

**Issue by jonad0521** [ollo69/ha-smartthinq-sensors#649]
**Is your feature request related to a problem? Please describe.**
It looks like the API is detecting my devices, but that it is an unknown device type of 223. It is a combined washer dryer tower that appears in the thinq app as one device
[config_entry-smartthinq_sensors-749924fa0c81aabb63a3f1d5792dee37.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/13757215/config_entry-smartthinq_sensors-749924fa0c81aabb63a3f1d5792dee37.json.txt)

**Comment by jonad0521** [comment]
[256cde1d-dd1e-4fe2-ac10-7ae09faeaff5.json](https://github.com/ollo69/ha-smartthinq-sensors/files/13788923/256cde1d-dd1e-4fe2-ac10-7ae09faeaff5.json)
Here is my model_info .json. The model_info.py is failing to validate the MonitoringValue key even though its present. I'm not sure what the issue is. Even if I force that check true, it still fails to find the MonitoringValue key while polling.

**Comment by ollo69** [comment]
This new device require some adjustment, working on this.

**Comment by jonad0521** [comment]
Great! Let me know if you need anything from me.

**Comment by ollo69** [comment]
Support for this device is available with last release, please test and report here result. Please do not expect control to work: I take a look to the device info and remote start command are totally different from previous device. To implement this should be necessary capture some logs from LG apps.

**Comment by jonad0521** [comment]
Wow! Looks great! At a glance the only missing thing for me would be the door open status on the dryer (its available on the washer). Here's a screenshot from HA:
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/68717785/149bb22b-5e51-422c-940d-3dadfa9649b5)
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/68717785/7ab9c110-4c19-4717-8739-111a9064c184)

I'll work on getting you logs from the LG app tonight.

**Comment by jonad0521** [comment]
OK here's the flow from mitmproxy when I turn the dryer power on. Is this what you're looking for? 
[flows.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/14119716/flows.txt)

**Comment by jonad0521** [comment]
Here's another where I change washer options then start a washer cycle, do the same for a dryer cycle then turn both devices off.
[flows (2).txt](https://github.com/ollo69/ha-smartthinq-sensors/files/14133034/flows.2.txt)

**Comment by jonad0521** [comment]
[flows (3).txt](https://github.com/ollo69/ha-smartthinq-sensors/files/14133054/flows.3.txt)
Here's another where I change lots of options then send it to the dryer, which can't start because remote start on the device was turned off locally.

**Comment by ollo69** [comment]
New controls are implemented with last release. Please test it and report here issue.

**Comment by jonad0521** [comment]
Works great. The control entities go unavailable when they aren't available to be used, either because remote start isn't available or its already running. Power works good too.

The only thing missing for me is accurate door open state. On the washer, it never changes from "open". On the dryer its not included anywhere.

Thanks for all the hard work.

**Comment by ollo69** [comment]
>The only thing missing for me is accurate door open state. On the washer, it never changes from "open". On the dryer its not included anywhere.

The door open is not available in the dryer payload. It's available in the washer payload but probably not supported. Is this information available by ThinQ app? You could try to generate diagnostics with door closed and open, so I can check if this information change inside the payload. Wait at least 1 minutes on status change to be sure that new status is properly polled.

**Comment by jonad0521** [comment]
i don't see it. A shame, since I can get a notification about not taking the clothes out of the dryer/washer so I guess it figures it out somehow.

Otherwise, I thank you wholeheartedly for integrating this, I think this FR can be closed.
