### ISSUE TITLE
[Feature Request] Control laundry

### ISSUE THREAD

**Issue by KTibow** [ollo69/ha-smartthinq-sensors#65]
**Is your feature request related to a problem? Please describe.**
This is a list of things I suggested in #47, but these are all of them, part of the issue. The idea is to control the washer/dryer, not just sense it.

**Describe the solution you'd like**
- Supported items:
  - Washer
  - Dryer
- Remote Start
  - Specify options
- Turn on/off
- Pause/resume
- Download additional cycles

**Describe alternatives you've considered**
A partial implementation is fine.

**Additional context**
Comment on this with questions

**Comment by dragonerix** [comment]
Hi, is any news? I bought new washing machine. I Hope IT Will early working remote start. Thank you

**Comment by KTibow** [comment]
Nobody doesn't want to bother developing it yet. If someone wants to, then they can.

**Comment by ollo69** [comment]
I'm working on this, but very slowly for the moment for different reason:
- lot of work in this period (first I need to eat😒)
- working on another project, near to closing it
- control is more complex than monitoring, must be well architected to avoid uncontrolled call to LG cloud and potential consequent limitation.

Be patient, it will come...

**Comment by pbix** [comment]
Several of the items in this are now working.  The important ones that remain I think are:

-Pause/Resume 
-Remote Start with the ability to specify options.

#olle69 I am available to test these for you when you get a change to work on them.

**Comment by vannetta** [comment]
> Several of the items in this are now working. The important ones that remain I think are:
> 
> -Pause/Resume -Remote Start with the ability to specify options.
> 
> #olle69 I am available to test these for you when you get a change to work on them.

@ollo69 @pbix I made an automation to start the washer, the boiler and the dishwasher in order, when the photovoltaic panels start producing...
At the moment I put the washer as first, in order to avoid the problem that I cannot start it from HA. When the washer finishes, the boiler starts, and then the dishwasher (it's Bosch and the remote start is available)...
It would be beautiful to automate all the process...
I'm available to test it if you need...
Thanks a lot

**Comment by ollo69** [comment]
> It would be beautiful to automate all the process...

Not clear to me exactly what is missing here. This component is for LG device and for sure cannot control Bosh device (you eventually need another integration, if exist).

**Comment by vannetta** [comment]
> > It would be beautiful to automate all the process...
> 
> Not clear to me exactly what is missing here. This component is for LG device and for sure cannot control Bosh device (you eventually need another integration, if exist).

@ollo69 Sorry, maybe I didn't explain:
My problem is about the LG washer (I need the remote start) because I cannot start it form HA. The dishwasher Bosch starts with its own integration. No problem about it.

**Comment by ollo69** [comment]
Ok, now is clear. But in this case is better that you open a new issue detailing information of your washer model and the issue that you have in remote start functionality, because this is already implemented.

**Comment by KTibow** [comment]
Never thought this would happen, and it took a year, but this satisfies me enough. Thanks for the work on this.
