### ISSUE TITLE
SmartThinQ LGE Sensors integration has stopped connecting to the server.

### ISSUE THREAD

**Issue by golds69** [ollo69/ha-smartthinq-sensors#651]
**Describe the bug**
The SmartThinQ LGE Sensors integration has stopped connecting to the server. There were no updates of HA or other components. Everything was working well, but suddenly stopped a few hours ago.

**Expected behavior**
N/A

**Screenshots**
N/A

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Debian GNU/Linux 12 (bookworm) VirtualEnv
 - Home Assistant version installed: 2023.12.3
 - Component version installed: 0.35.6
 - Last know working version: 0.35.6
 - LG device type and model with issue: All
 - LG devices connected (list): Washing Machine, Refrigerator

**Output of HA logs**

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/__init__.py:252
Integration: SmartThinQ LGE Sensors ([documentation](https://github.com/ollo69/ha-smartthinq-sensors), [issues](https://github.com/ollo69/ha-smartthinq-sensors/issues))
First occurred: 18:02:14 (1 occurrences)
Last logged: 18:02:14
Connection not available. ThinQ platform not ready

Traceback (most recent call last):
  File "/home/homeassistant/config/custom_components/smartthinq_sensors/__init__.py", line 252, in async_setup_entry
    client = await lge_auth.create_client_from_token(refresh_token, oauth2_url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/config/custom_components/smartthinq_sensors/__init__.py", line 151, in create_client_from_token
    return await ClientAsync.from_token(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1446, in from_token
    await client.refresh()
  File "/home/homeassistant/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1366, in refresh
    await self._load_devices()
  File "/home/homeassistant/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1283, in _load_devices
    new_devices = await self._session.get_devices()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1065, in get_devices
    self._common_lang_pack_url = dashboard.get("langPackCommonUri")
                                 ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

**Comment by ErikProductions** [comment]
I'm getting the same.

**Comment by LeonidPY** [comment]
Same here.

**Comment by ollo69** [comment]
This is strange. I will add an additional check to this part of code to avoid this error, hoping that there are no other changes in API.

**Comment by vicar82** [comment]
Same problem. Password change in LG ThinQ app doesn't help.

**Comment by ollo69** [comment]
Uhm, wait, dos not make sense. If `dashboard` is type str it doesn't contain all the info related to devices, this would be a problem. There are someone with this problem able to add a line a of log at line 1064 of `core_asyng.py` module to get the content of variable dashboard?

Just a line like this:

```
_LOGGER.info(dashboard)
```

**Comment by LeonidPY** [comment]
I can't login into account via HA.
If i just put mail and pass, getting this
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/66218923/63b5b187-dc90-42b7-ae26-9b65f6fc9ec9)

If i try token - this 
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/66218923/29b2ecdf-9229-4ce8-96da-7d2ce84f137a)

**Comment by LeonidPY** [comment]
Looks like LG fixed something on their side. Successfully logged in by login and password.

**Comment by ErikProductions** [comment]
![IMG_0087](https://github.com/ollo69/ha-smartthinq-sensors/assets/56169484/e5a41351-370f-4fa6-9fff-3ac6e965b461)
I still can't log in.

**Comment by golds69** [comment]
This morning I woke up and was surprised to see that the devices were connected. But I was happy early. After some time, the devices disconnect again and the error repeated.

**Comment by ollo69** [comment]
I think that there are some problem LG server side. Wait some days to see if they fix.
BTW at my side everything working properly till now.

**Comment by LeonidPY** [comment]
Rebooted HA, took error again. Before reboot all worked ok.
```
2023-12-24 20:34:30.406 WARNING (MainThread) [custom_components.smartthinq_sensors] Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 252, in async_setup_entry
    client = await lge_auth.create_client_from_token(refresh_token, oauth2_url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 151, in create_client_from_token
    return await ClientAsync.from_token(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1447, in from_token
    await client.refresh()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1367, in refresh
    await self._load_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1284, in _load_devices
    new_devices = await self._session.get_devices()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1066, in get_devices
    self._common_lang_pack_url = dashboard.get("langPackCommonUri")
                                 ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
2023-12-24 20:34:30.456 ERROR (MainThread) [homeassistant.components.homekit.type_thermostats] climate.dc07rh: Received invalid HVAC mode: unavailable
```

**Comment by diahellfire** [comment]
Did it work for anyone?
Same problem...

**Comment by ollo69** [comment]
Please enable integration debug and provide debug log.

**Comment by LeonidPY** [comment]
> Please enable integration debug and provide debug log.

[home-assistant_smartthinq_sensors_2023-12-25T22-14-08.307Z.log](https://github.com/ollo69/ha-smartthinq-sensors/files/13767385/home-assistant_smartthinq_sensors_2023-12-25T22-14-08.307Z.log)

**Comment by ollo69** [comment]
Looks like the endpoint `https://ruic-service.lgthinq.com:46030/v1/service/application/dashboard` is returning an empty string instead of a `dict` with device information. Also fixing this will not fix the problem because integration will not be able to discover registered device.
I do not understand if there are some changes at API level, but seems that this issue is limited to some region. If the app is still working could someone try to analyze the traffic using instruction provided [here](https://github.com/ollo69/ha-smartthinq-sensors#obtaining-api-information) ?

**Comment by ErikProductions** [comment]
> Looks like the endpoint `https://ruic-service.lgthinq.com:46030/v1/service/application/dashboard` is returning an empty string instead of a `dict` with device information. Also fixing this will not fix the problem because integration will not be able to discover registered device. I do not understand if there are some changes at API level, but seems that this issue is limited to some region. If the app is still working could someone try to analyze the traffic using instruction provided [here](https://github.com/ollo69/ha-smartthinq-sensors#obtaining-api-information) ?

The app is not working for me.

**Comment by ollo69** [comment]
> The app is not working for me.

In this case I think that you could try to contact LG support and ask for clarification.

**Comment by vicar82** [comment]
I don't know how, but integration is working!!!!
I was able to login through integrations. But yesterday it definitely didn’t work as I tried several times.
It seems to me that this is not related to integration and the problem was on LG's side.

**Comment by Druidblack** [comment]
There is a pattern in the failure of integration. According to the +3 time zone, the integration starts working at night and works during the day. The shutdown occurs in the evenings and into the night.

**Comment by Taronaga** [comment]
Hello everyone, this problem also appeared after rebooting the system. The APP works without failures, notifications are received, devices are available.
2023-12-27 18:06:42.138 WARNING (MainThread) [custom_components.smartthinq_sensors] Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 252, in async_setup_entry
    client = await lge_auth.create_client_from_token(refresh_token, oauth2_url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 151, in create_client_from_token
    return await ClientAsync.from_token(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1446, in from_token
    await client.refresh()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1366, in refresh
    await self._load_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1283, in _load_devices
    new_devices = await self._session.get_devices()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1065, in get_devices
    self._common_lang_pack_url = dashboard.get("langPackCommonUri")
                                 ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

**Comment by wantsoftat** [comment]
I confirm, but it started recently

**Comment by freest555** [comment]
> There is a pattern in the failure of integration. According to the +3 time zone, the integration starts working at night and works during the day. The shutdown occurs in the evenings and into the night.

Changing the region in the same situation helped me for this moment.

**Comment by ollo69** [comment]
Today I took some logs from LG app. While in my country integration is still working, seems that application use some different web requests. I suppose that they changed something in the API and they are progressively disabling old API.
I need some times to implement new requests, hoping that this will not break functionality on other countries.

**Comment by ollo69** [comment]
Please try using last release and let me know if it fix this issue.

**Comment by Andreweburg** [comment]
> Please try using last release and let me know if it fix this issue.

Thnx. Logged in, but. I devices found 🙈
![IMG_1954](https://github.com/ollo69/ha-smartthinq-sensors/assets/98278997/976155a0-a33e-4633-9422-0580be10c5f7)

**Comment by e2ret** [comment]
Invalid SmartThinQ credentials. Use the LG App on your mobile device to verify if there are Term of Service to accept. Account based on social network are not supported and in most case do not work with this integration.

**Comment by Andreweburg** [comment]
> Invalid SmartThinQ credentials. Use the LG App on your mobile device to verify if there are Term of Service to accept. Account based on social network are not supported and in most case do not work with this integration.

Everything is ok in mobile app. I used to try 2 accounts. No luck.

**Comment by edwardtich1** [comment]
1. I tried several accounts
2. I have the latest version
3. I tried changing the region and country

mobile app works well
It does not work for me

`Invalid SmartThinQ credentials. Use the LG App on your mobile device to verify if there are Term of Service to accept. Account based on social network are not supported and in most case do not work with this integration.`

**Comment by Stif007** [comment]
after authorization:
"No SmartThinQ devices found. Component setup aborted"

**Comment by Drafteed** [comment]
Got it after update:

```
2024-01-05 10:01:05.719 WARNING (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] LG API return invalid homes information: ''
2024-01-05 10:01:05.719 WARNING (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] Not possible to determinate a valid home_id
```

**Comment by DivanX10** [comment]
SmartThinQ LGE Sensors 0.36.0
Core 2024.1.0
Supervisor 2023.12.0
Operating System 11.3

Region Russia

When adding SmartThinQ integration, LGE Sensors received a message. There are devices in the LG ThinQ mobile app.
```
SmartThinQ LGE Sensors
No SmartThinQ devices found. Component setup aborted.
```

There is a message in the logs
```
Logger: custom_components.smartthinq_sensors.wideq.core_async
Source: custom_components/smartthinq_sensors/wideq/core_async.py:1123
Integration: SmartThinQ LGE Sensors ([documentation](https://github.com/ollo69/ha-smartthinq-sensors), [issues](https://github.com/ollo69/ha-smartthinq-sensors/issues))
First occurred: 12:37:47 (1 occurrences)
Last logged: 12:37:47

Not possible to determinate a valid home_id
```

```
This error occurred in the user integration.

Logger: custom_components.smartthinq_sensors.wideq.core_async
Source: custom_components/smartthinq_sensors/wideq/core_async.py:1079
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 12:37:47 (1 occurrences)
Last logged: 12:37:47

LG API return invalid homes information: ''
```

**Comment by ErikProductions** [comment]
Hi there!

Smarthinq LGE	 Sensors v.0.36.0
Core 2023.12.4
Supervisor 2023.12.0
OS 11.2

Region: Spain

It' s still now working, neither the app nor the integration. I have reinstalled the app, accepted terms and updated password.

![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/56169484/1904f750-76a7-40b8-a7b2-26a86919b57a)

**Comment by ollo69** [comment]
@all,

I see here a lot of different issue reported all here, I think that this is just creating confusion.
The issue we are trying to address here is related to integration that was working past months and now do not work anymore, if this is not the case please open a new issue.

To find a solution for the specific case, that cause error like:

- LG API return invalid homes information: ''
- LG API return invalid devices information: ''

I tried to use different API with last release, but this seems that do not fix the problem.
Because I don't have this error my side, the only way to find a solution is to capture the traffic from LG app based on instruction provided in [readme](https://github.com/ollo69/ha-smartthinq-sensors#obtaining-api-information).

If someone with this issue can do this and share the captured traffic, I will analyze to find the proper call. If nobody can do this, the only alternative solution is that someone share the LG credential (via e-mail of course) and I will try to capture the traffic for you. 

Wait for your feedback
I do not see any other possible option.

**Comment by oksibutch** [comment]
what you email, im send you my account info

**Comment by ollo69** [comment]
> what you email, im send you my account info

Send to aolivero@gmail.com.
I need user, pwd, country and region (I suggest to temporary change pwd for test). 
Not sure if app will require 2 phase authentication, it this case it could require to put the mobile number to have back authentication code.
For now just start with credential.

**Comment by ollo69** [comment]
@oksibutch,

I successfully captured some traffic from LG app using your account. Now (today or tomorrow) I will make some tests with integration. Please do not change your pwd until I finish with my tests.

Thanks for your support👍

**Comment by oksibutch** [comment]
@ollo69  thx for you! you do a great job

**Comment by ollo69** [comment]
Please try last release, problem should be fixed.

**Comment by ErikProductions** [comment]
> Please try last release, problem should be fixed.
![imagen](https://github.com/ollo69/ha-smartthinq-sensors/assets/56169484/c84bd73a-613f-436f-92f0-5550afabc127)
Same for me. I have even tried deleting and installing the integration.

**Comment by Andreweburg** [comment]
> Please try last release, problem should be fixed.

Great thnx. It seems to me that it works with v0.36.1 🎉🎉 
Wow.

**Comment by ollo69** [comment]
@ErikProductions,

this is a different problem (seems you cannot connect to the LG server), please open a new issue.

**Comment by ollo69** [comment]
@oksibutch,

thanks again to  for your support. Now you can change your LG account password if you like and if issue is solved also for you.

**Comment by ErikProductions** [comment]
> Many thanks to the author and helped everyone!

Would you mind telling me what region you are on?
I can't get it to work. (Spain)

**Comment by Andreweburg** [comment]
> > Many thanks to the author and helped everyone!
> 
> Would you mind telling me what region you are on? I can't get it to work. (Spain)

Try new version v0.36.1 🤔

**Comment by edwardtich1** [comment]
> > > > Огромное спасибо автору и всем помог!
> > > 
> > > 
> > > Не подскажете ли вы, в каком вы регионе? Я не могу заставить его работать. (Испания)
> > 
> > 
> > Попробуйте новую версию v0.36.1 🤔
> 
> Я уже пробовал. :(

click download again in HACS
reboot HA
everything should work

**Comment by wantsoftat** [comment]
Thank you, version v0.36.1 fixed everything

**Comment by ollo69** [comment]
I think that this issue now is solved, I close this.
