### ISSUE TITLE
Washer Remote Start - 0005 - ThinQ APIv2 error

### ISSUE THREAD

**Issue by mzakharo** [ollo69/ha-smartthinq-sensors#654]
**Describe the bug**
When pressing 'Remote Start',  APIv2 error is generated

**Expected behavior**
Remote start works.

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Raspbian
 - Home Assistant version installed:  2023.12.3
 - Component version installed: 0.35.6
 - Last know working version: - 
 - LG device type and model with issue:  F3P2CYVAT__-FL (WASHER) by LG. Firmware: clip_hna_v1.9.195
 - LG devices connected (list): Washer

**Output of HA logs**
Paste the relavant output of the HA log here.

```
File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 124, in _async_press_action
    await self.async_press()
  File "/config/custom_components/smartthinq_sensors/button.py", line 137, in async_press
    await self.entity_description.press_action_fn(self._wrap_device)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 269, in remote_start
    await self.set(keys[0], keys[1], key=keys[2])
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 275, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 569, in set
    await self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 530, in _set_control
    await self._client.session.device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1193, in device_v2_controls
    res = await self.post2(cmd_path, payload)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1030, in post2
    return await self._auth.gateway.core.lgedm2_post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 347, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 360, in _manage_lge_result
    raise exc.APIError(message, code)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 0005 - ThinQ APIv2 error
```

**Additional context**
Remote start is working via the Official ThinQ App.

**Comment by mzakharo** [comment]
Not sure if this is useful, but I ran wireshark, and these are commands used for OFF/Remote Start/Pause: 

```POST /v1/service/devices/<UUID>/control-sync```

```json

{"ctrlKey":"vtCtrl","command":"Set","dataKey":null,"dataValue":null,"dataSetList":{"vtData":{"UNDEFINE":[{"cmd":"power","value":"POWER_OFF","type":"ABSOLUTE"}]},"ctrlTarget":["UNDEFINE"],"reqDevType":"APP","productType":"NORMAL"},"dataGetList":null}

{"ctrlKey":"vtCtrl","command":"Set","dataKey":null,"dataValue":null,"dataSetList":{"vtData":{"UNDEFINE":[{"cmd":"wmControl","value":"START","type":"ABSOLUTE"}]},"ctrlTarget":["UNDEFINE"],"reqDevType":"APP","productType":"NORMAL"},"dataGetList":null}

{"ctrlKey":"vtCtrl","command":"Set","dataKey":null,"dataValue":null,"dataSetList":{"vtData":{"UNDEFINE":[{"cmd":"wmControl","value":"PAUSE","type":"ABSOLUTE"}]},"ctrlTarget":["UNDEFINE"],"reqDevType":"APP","productType":"NORMAL"},"dataGetList":null}
```

Is this APIv1 and my washer is incompatible with this integration?

**Comment by Saik0Shinigami** [comment]
You're not alone, I'm getting the same result. Old api had no issues running the start call. This new one throws the exception seen above.

**Comment by iku777** [comment]
Same here. Dryer works fine with remote start but front load washer (model #F3P3CYKL2__-FL) with version 0.37 gives error "Failed to call service button/press. 0005 - ThinQ APIv2 error"

**Comment by ollo69** [comment]
> Not sure if this is useful, but I ran wireshark, and these are commands used for OFF/Remote Start/Pause:

This is absolutely useful. I will work on this new commands on next days 👍

**Comment by iku777** [comment]
@ollo69 Like that?
[config_entry-smartthinq_sensors-6421efd926f8daa714f9a779fc361a51.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/14130913/config_entry-smartthinq_sensors-6421efd926f8daa714f9a779fc361a51.json.txt)

**Comment by ollo69** [comment]
Please try if last release fix device controls.

**Comment by iku777** [comment]
Hi @ollo69.
I have just tested with the new version (0.37.1) and the remote start now doesnt give an error and works with my front laoder washing machine. Thanks for the quick turnaround!

**Comment by ollo69** [comment]
Good, I close this issue.
