### ISSUE TITLE
Error State/Message do not respond to unbalanced washer load?

### ISSUE THREAD

**Issue by kylepyke** [ollo69/ha-smartthinq-sensors#655]
**Describe the bug**
Error state is not triggered by unbalanced washer load.

**Expected behavior**
States should change if there is an issue.

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HA on Proxmox
 - Home Assistant version installed: 12.4
 - Component version installed: 0.35.6
 - Last know working version: --
 - LG device type and model with issue: LG Washer WM4200HWA

**Output of HA logs**
No Log errors

**Additional context**
[smartthinq_sensors-633aa373a16e27433a4f589846d19272-LG Washer-49b6e268c91de4f9b1f45f523d8c4f50.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/13790889/smartthinq_sensors-633aa373a16e27433a4f589846d19272-LG.Washer-49b6e268c91de4f9b1f45f523d8c4f50.json.txt)

**Comment by ollo69** [comment]
Close because duplicated of #629
