### ISSUE TITLE
Some entities intermittently go unavailable

### ISSUE THREAD

**Issue by kylepyke** [ollo69/ha-smartthinq-sensors#656]
**Describe the bug**
Power and remote start frequently go unavailable.

**Expected behavior**
The state should always be reported.

**Screenshots**
<img width="627" alt="Screen Shot 2023-12-28 at 10 14 28 PM" src="https://github.com/ollo69/ha-smartthinq-sensors/assets/107963487/a76b2a42-e2b1-40e7-bb66-8216d4b74882">

<img width="619" alt="Screen Shot 2023-12-28 at 10 14 37 PM" src="https://github.com/ollo69/ha-smartthinq-sensors/assets/107963487/3c826cf3-2fc4-42a1-b471-62ee0f3e3fc0">

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HA on Proxmox
 - Home Assistant version installed: 12.4
 - Component version installed: 0.35.6
 - Last know working version: --
 - LG device type and model with issue: LG Washer WM4200HWA

**Output of HA logs**
No Log errors

**Additional context**
[smartthinq_sensors-633aa373a16e27433a4f589846d19272-LG Washer-49b6e268c91de4f9b1f45f523d8c4f50.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/13790889/smartthinq_sensors-633aa373a16e27433a4f589846d19272-LG.Washer-49b6e268c91de4f9b1f45f523d8c4f50.json.txt)

**Comment by wantsoftat** [comment]
I confirm, but it started recently
