### ISSUE TITLE
non HA use

### ISSUE THREAD

**Issue by zraken** [ollo69/ha-smartthinq-sensors#66]
Hi, I would appreciate it very much if you could  provide any pointers on using this via CLI (i.e. without Home Assistant). Thanks.

**Comment by KTibow** [comment]
@zraken related to [wideq](https://github.com/sampsyo/wideq), not `ha-smartthinq-sensors`.
Consider closing?

**Comment by KTibow** [comment]
@zraken any luck with `wideq`? If you have an issue you can always make one there.
Maybe consider closing this?

**Comment by zraken** [comment]
Yes I tried wideq but it does not work, I was hoping to get some tips on how you got it to work. Closing issue per your request.

**Comment by KTibow** [comment]
@zraken by the way, `ha-smartthinq-sensors` uses a slightly modified version you can find [here](https://github.com/ollo69/ha-smartthinq-sensors/tree/master/custom_components/smartthinq_sensors/wideq) (`custom_components/smartthinq_sensors/wideq`)
