### ISSUE TITLE
Plugin is using deprecated supported features values which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by hartmood** [ollo69/ha-smartthinq-sensors#661]
https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by ollo69** [comment]
This is a new deprecation just introduced in 2024.1. To maintain compatibility with previous HA version, I cannot apply this change now. I will wait a couple of new HA version.

**Comment by hartmood** [comment]
All good, just wanted to let you know. Thanks for making your plugin public.

**Comment by ollo69** [comment]
@hartmood,

sorry but I do not understand if you are just informing about deprecation or you receive a specific alert.
I think that I already removed this constant some times ago but may be I miss someone.

Thanks,

**Comment by hartmood** [comment]
I found the error message in my logfile using log viewer and thought it would be helpful for the developer to know.

**Comment by ollo69** [comment]
Yes, thanks, but my question is if error message was related to this integration and in case if you can provide details, just because I thought that I already updated all reference but maybe I forgot someone.

Thanks.👍

**Comment by hartmood** [comment]
I can confirm that I found the error message in my log file a few minutes before posting. And I can confirm I last saw the message a few days ago.

**Comment by ollo69** [comment]
Ok, can you provide detail about the message?

**Comment by ollo69** [comment]
Ok, could you please provide details about your LG device so I have an idea about what I should search? Thanks.

**Comment by hartmood** [comment]
:-) - I am sorry:
Device Information
2RES1VE61PFWA-SxS (REFRIGERATOR)
from LG
Firmware: QC_Modem_1.2.80

**Comment by ollo69** [comment]
Sorry, but are you running last integration version?

**Comment by ollo69** [comment]
This should be reported in the log during startup, but if you are sure about the version is ok. It is strange because I also have a refrigerator and I don't have any message, anyway I will deeply check.

**Comment by jhemak** [comment]
Is this helpful?

WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.frigidaire.humidifier.FrigidaireDehumidifier'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <HumidifierEntityFeature.MODES: 1>, please create a bug report at https://github.com/bm1549/home-assistant-frigidaire/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by ollo69** [comment]
Ok, I found the issue due to some specific device status where `supported_feature` was returning 0.
Will be fixed on next release.

**Comment by hartmood** [comment]
Wow. Well done. Thank you.
