### ISSUE TITLE
Problems with LG Therma V Heat Pump with Version v0.36.0

### ISSUE THREAD

**Issue by guevara777** [ollo69/ha-smartthinq-sensors#663]
**Describe the bug**
After Updating to v0.36.0 the integration shows to values for all the entities and gives an error in the logs (see below). Downgrading to v0.35.6 fixed the problem.

**Expected behavior**
Access to all entities with version v0.36.0

**Screenshots**
-

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/29648553/4554b823-6272-44cb-ad69-6b043a786eec)
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/29648553/d3991e61-8175-4167-a120-2bf612ecfe56)

 - Home Assistant version installed: 2024.1
 - Component version installed: v0.36.0
 - Last know working version: v0.35.6
 - LG device type and model with issue: LG Therma V - AWHP_019101_WW-AWHP (AC)
 - LG devices connected (list):
    - LG Therma V - AWHP_019101_WW-AWHP (AC)

**Output of HA logs**
Paste the relavant output of the HA log here.

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/__init__.py:294
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 13:11:38 (1 occurrences)
Last logged: 13:11:38

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 294, in async_setup_entry
    lge_devices, unsupported_devices, discovered_devices = await lge_devices_setup(
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 586, in lge_devices_setup
    dev = LGEDevice(lge_dev, hass)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 362, in __init__
    self._firmware = device.device_info.firmware
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/device_info.py", line 174, in firmware
    if fw_ver := self._data["modemInfo"].get("appVersion"):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Additional context**
-

**Comment by ollo69** [comment]
Ok, I'll fix this with next release. Please temporary roll-back to previous release.

**Comment by guevara777** [comment]
Thank you. I did the downgrade and everything is ok againg. I´ll wait till the fix is there.

**Comment by ollo69** [comment]
Please upgrade to last release, problem should be fixed.

**Comment by guevara777** [comment]
Tested with v0.36.1. Works without problems. Thank you.

**Comment by ollo69** [comment]
Good, I close this issue.

**Comment by DivanX10** [comment]
@ollo69 Thank you. In version 0.36.1, everything worked. Devices have appeared
