### ISSUE TITLE
Dryer  - add option to pause/resume

### ISSUE THREAD

**Issue by penfold** [ollo69/ha-smartthinq-sensors#664]
**Is your feature request related to a problem? Please describe.**
I'm able to pause and resume the dyer via the app. It would be great to do this from HA.

**Describe the solution you'd like**
I want to be able to create an automation, so that when my home battery is below X% then I can pause my dryer. And restart it at a later point. 

**Describe alternatives you've considered**
None

**Additional context**
Happy to supply any further details if you let me know what you need and how to provide it.

**Comment by ollo69** [comment]
Pause button is now available with last release. Please test is and report here results.

**Comment by ollo69** [comment]
Feature is implemented. If there are problem please open a dedicated issue.
