### ISSUE TITLE
No SmartThinQ devices found. Component setup aborted

### ISSUE THREAD

**Issue by wantsoftat** [ollo69/ha-smartthinq-sensors#665]
After the update it started displaying a message:
"No SmartThinQ devices found. Component setup aborted", although devices are visible in the mobile application

**Comment by ollo69** [comment]
Please update to last release, this issue should be fixed.

**Comment by arierom70** [comment]
I Have the same problem .

	Line 2305: 2024-01-08 12:44:20.653 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] thinq2_get before: https://route.lgthinq.com:46030/v1/service/application/gateway-uri
	Line 2306: 2024-01-08 12:44:21.052 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] thinq2_get after: {'resultCode': '0000', 'result': {'countryCode': 'GB', 'languageCode': 'en-GB', 'thinq1Uri': 'https://eic.lgthinq.com:46030/api', 'thinq2Uri': 'https://eic-service.lgthinq.com:46030/v1', 'empUri': 'https://gb.m.lgaccount.com', 'empSpxUri': 'https://gb.m.lgaccount.com/spx', 'rtiUri': 'eic.lgthinq.com:47878', 'mediaUri': 'eic-media.lgthinq.com:47800', 'appLatestVer': '5.0.12120', 'appUpdateYn': 'N', 'appLink': 'market://details?id=com.lgeha.nuts', 'nestSupportAppVer': '', 'uuidLoginYn': 'N', 'lineLoginYn': 'N', 'lineChannelId': '', 'cicTel': '0344-847-5454', 'cicUri': '', 'isSupportVideoYn': 'N', 'countryLangDescription': 'UK/English', 'empTermsUri': 'https://gb.emp.lgsmartplatform.com', 'googleAssistantUri': 'https://assistant.google.com/services/invoke/uid/000000d26892b8a3', 'smartWorldUri': '', 'racUri': 'gb.rac.lgeapi.com', 'cssUri': 'https://eic-common.lgthinq.com', 'cssWebUri': 'http://s3-an2-op-t20-css-web-resource.s3-website.ap-northeast-2.amazonaws.com', 'iotssUri': 'https://eic-iotservice.lgthinq.com', 'chatBotUri': '', 'autoOrderSetUri': '', 'autoOrderManageUri': '', 'aiShoppingUri': '', 'onestopCall': '', 'onestopEngineerUri': '', 'hdssUri': '', 'amazonDrsYn': 'N', 'features': {'betaFeedbackCode': 'SpH28i9gRexOvJfnfW6CSw==', 'supportTvIoTServerYn': 'Y', 'nonProductThemes': 'GIF,FOM', 'nonWifiQrSupportYn': 'Y', 'shareAccountYn': 'Y', 'androidAutoYn': 'Y', 'googleAssistantYn': 'Y', 'searchYn': 'Y', 'thinqFaq': 'Y', 'thinqQuickguide': 'N', 'multiProfile': 'Y', 'eventAutoScrollYn': 'Y', 'supportBleYn': 'Y', 'empFrontLoginYn': 'Y', 'checkWhiteListYn': 'N', 'pccPushProd': '101,201,202,204,301,401', 'thinqCss': 'Y', 'tvRcmdContentYn': 'Y', 'deviceSuggestionLevel': '3', 'awhpWidgetFeatureYn': 'Y', 'tvFeatureYn': 'Y', 'SKSIntergrateYn': 'Y', 'thinqNotice': 'Y', 'inAppReviewYn': 'Y', 'pccNoticeAgreement': 'N', 'cicSupport': 'Y', 'qrRegisterYn': 'Y', 'easySetupYn': 'Y', 'tvCastYn' ...


	Line 2307: 2024-01-08 12:44:21.053 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] GatewayV2 info: {'countryCode': 'GB', 'languageCode': 'en-GB', 'thinq1Uri': 'https://eic.lgthinq.com:46030/api', 'thinq2Uri': 'https://eic-service.lgthinq.com:46030/v1', 'empUri': 'https://gb.m.lgaccount.com', 'empSpxUri': 'https://gb.m.lgaccount.com/spx', 'rtiUri': 'eic.lgthinq.com:47878', 'mediaUri': 'eic-media.lgthinq.com:47800', 'appLatestVer': '5.0.12120', 'appUpdateYn': 'N', 'appLink': 'market://details?id=com.lgeha.nuts', 'nestSupportAppVer': '', 'uuidLoginYn': 'N', 'lineLoginYn': 'N', 'lineChannelId': '', 'cicTel': '0344-847-5454', 'cicUri': '', 'isSupportVideoYn': 'N', 'countryLangDescription': 'UK/English', 'empTermsUri': 'https://gb.emp.lgsmartplatform.com', 'googleAssistantUri': 'https://assistant.google.com/services/invoke/uid/000000d26892b8a3', 'smartWorldUri': '', 'racUri': 'gb.rac.lgeapi.com', 'cssUri': 'https://eic-common.lgthinq.com', 'cssWebUri': 'http://s3-an2-op-t20-css-web-resource.s3-website.ap-northeast-2.amazonaws.com', 'iotssUri': 'https://eic-iotservice.lgthinq.com', 'chatBotUri': '', 'autoOrderSetUri': '', 'autoOrderManageUri': '', 'aiShoppingUri': '', 'onestopCall': '', 'onestopEngineerUri': '', 'hdssUri': '', 'amazonDrsYn': 'N', 'features': {'betaFeedbackCode': 'SpH28i9gRexOvJfnfW6CSw==', 'supportTvIoTServerYn': 'Y', 'nonProductThemes': 'GIF,FOM', 'nonWifiQrSupportYn': 'Y', 'shareAccountYn': 'Y', 'androidAutoYn': 'Y', 'googleAssistantYn': 'Y', 'searchYn': 'Y', 'thinqFaq': 'Y', 'thinqQuickguide': 'N', 'multiProfile': 'Y', 'eventAutoScrollYn': 'Y', 'supportBleYn': 'Y', 'empFrontLoginYn': 'Y', 'checkWhiteListYn': 'N', 'pccPushProd': '101,201,202,204,301,401', 'thinqCss': 'Y', 'tvRcmdContentYn': 'Y', 'deviceSuggestionLevel': '3', 'awhpWidgetFeatureYn': 'Y', 'tvFeatureYn': 'Y', 'SKSIntergrateYn': 'Y', 'thinqNotice': 'Y', 'inAppReviewYn': 'Y', 'pccNoticeAgreement': 'N', 'cicSupport': 'Y', 'qrRegisterYn': 'Y', 'easySetupYn': 'Y', 'tvCastYn': 'Y', 'bleConfirmYn': 'Y', 'awhpWi ...


	Line 2308: 2024-01-08 12:44:21.053 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] Request new access token

**Comment by ollo69** [comment]
@arierom70,

your log is truncated and I'm not understanding what is your issue. Did you upgrade to last release?

**Comment by arierom70** [comment]
I have the last upgrade release .
i attached the logs.
[home-assistant_smartthinq_sensors_2024-01-09T11-49-24.894Z_new.log](https://github.com/ollo69/ha-smartthinq-sensors/files/13873309/home-assistant_smartthinq_sensors_2024-01-09T11-49-24.894Z_new.log)

**Comment by SamKirsch10** [comment]
I interestingly also had this issue, and randomly pinned it down today by happenstance... I have a GeoIP Firewall rule block, and noticed HomeAssistant was getting blocked *A LOT*. I guess most of LG's domains resolve outside the US. I plan on adding a rule above allowing port 46030 out even if it is in the GeoIP block
