### ISSUE TITLE
unknown device type with id 603

### ISSUE THREAD

**Issue by thitcher** [ollo69/ha-smartthinq-sensors#667]
**Describe the bug**
After each restart of HA it shows this Message:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.smartthinq_sensors.wideq.device_info
Source: custom_components/smartthinq_sensors/wideq/device_info.py:197
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 16:27:08 (1 occurrences)
Last logged: 16:27:08

Device 915f13b3-f748-10e1-a5e4-5026ef357f80: unknown device type with id 603

**Expected behavior**
no errors at startup

**Screenshots**
n.A.

**Environment details:**
HASSIO

I have enabled the logs and got an URL 
https://objectcontent.lgthinq.com/b5db8a86-a73f-479d-bbe7-d2dc0af353a3?hdnts=exp=1763186250~hmac=60d38a9e9xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Can I send the URL or the file I downloaded it over the URL or is that security-related?

It is a LG ThermaV heatpump

**Comment by ollo69** [comment]
What are your LG devices? Error is because device with ID 603 is unknown.

**Comment by thitcher** [comment]
It is a LG air/water Heatpump "LG Therma V Monobloc S 9kW - HM093MR.U44", connectet over LG cloud gateway.
Values are shown in HA and controllable.


![grafik](https://github.com/ollo69/ha-smartthinq-sensors/assets/430574/cd63fc55-3495-44fe-b1df-ae8a61a0b567)

**Comment by thitcher** [comment]
[smartthinq_sensors-200526a9185260f8b1ba9bd05cdf010a-Ansgar-57984c7f9788f278d494e147831110be.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/13852436/smartthinq_sensors-200526a9185260f8b1ba9bd05cdf010a-Ansgar-57984c7f9788f278d494e147831110be.json.txt)

**Comment by ollo69** [comment]
OK, this is just a warning for unknown device type, anyway I added to the list and released a new version to remove the warning.

**Comment by thitcher** [comment]
Thank you very much

**Comment by thitcher** [comment]
Thank you very much
