### ISSUE TITLE
Integration won't load after latest update

### ISSUE THREAD

**Issue by kevmang** [ollo69/ha-smartthinq-sensors#668]
**Describe the bug**
The integration won't load after updating to the latest version

**Expected behavior**
Integration loads and entities appear in HA

**Screenshots**
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/69849984/e7df12ae-334d-4dde-85b7-e942bda508e1)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO 11.3
 - Home Assistant version installed: 2024.1.2
 - Component version installed: v0.36.2
 - Last know working version:  v0.36.1
 - LG device type and model with issue: N/A
 - LG devices connected (list): LG Fridge GS-VB655PL

**Output of HA logs**
Logger: homeassistant.config_entries
Source: config_entries.py:2087
First occurred: 9:53:06 AM (1 occurrences)
Last logged: 9:53:06 AM

Error occurred loading flow for integration smartthinq_sensors: No module named 'custom_components.smartthinq_sensors.wideq.const'

```

```

**Additional context**
N/A

**Comment by ollo69** [comment]
I think there there is a problem in your installation, seems it is not finding a module. I suggest to full reinstall last release.
From 0,36.1 to 0,36,2 there is a very little change and nothing to do with the log error than you provide.

**Comment by kevmang** [comment]
> I think there there is a problem in your installation, seems it is not finding a module. I suggest to full reinstall last release. From 0,36.1 to 0,36,2 there is a very little change and nothing to do with the log error than you provide.

Do you have a recommended method to re-install? I can't uninstall and reinstall using the standard method as the interface won't load so HACS won't let me remove it.

**Comment by ollo69** [comment]
This really means that integration folder is broken / corrupted. Fully delete the folder `smartthinq_sensor` under `<home assistant configuration folder>/custom_components`, reboot HA and that try to install again with HACS.

**Comment by kevmang** [comment]
> This really means that integration folder is broken / corrupted. Fully delete the folder `smartthinq_sensor` under `<home assistant configuration folder>/custom_components`, reboot HA and that try to install again with HACS.

Thanks for the advice - I deleted the folder, removed the integration and re-installed. All working again now!

**Comment by kevmang** [comment]
> This really means that integration folder is broken / corrupted. Fully delete the folder `smartthinq_sensor` under `<home assistant configuration folder>/custom_components`, reboot HA and that try to install again with HACS.

Thanks for the advice - I deleted the folder, removed the integration and re-installed. All working again now!
