### ISSUE TITLE
Display Light toggle makes mini-split beep but does not change display light state

### ISSUE THREAD

**Issue by Asmor** [ollo69/ha-smartthinq-sensors#669]
**Describe the bug**

In Home Assistant, all of my mini-splits have a Display Light toggle. When I click it, it toggles the state inside Home Assistant, and the mini-split beeps as it does whenever you make any change, but the display light's state is unchanged. If it was off, it remains off. If it was on, it remains on.

Additionally, the state of the display light toggle in Home Assistant has no correlation with the actual state of the display light on the units.

Here's the [JSON for one of my mini-splits](https://pastebin.com/JyGV5ugR) (it's huge so I didn't want to paste it inline)

**Expected behavior**
- The toggle should turn the unit's display light  on or off as appropriate
- Ideally the state of the toggle in Home Assistant should reflect the actual state of the light on the devices

**Screenshots**

![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/2127204/5869ae15-1c1e-4072-8b21-130cf10915a0)

**Environment details:**
 - Environment: VM running on Hyper-V under Windows 11
 - Home Assistant version installed: 
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/2127204/674ffaa4-bf3a-4d2e-8c9b-bfe6d04ce83d)
 - Component version installed: Not sure how to check this, but I downloaded it yesterday (Jan 8th 2024) by cloning the master branch of this repo
 - Last know working version: n/a (I just set up HomeAssistant for the first time and have no historical context)
 - LG device type and model with issue: All of the following mini-splits:
 	- 6 x - LMN079HVT
	- 1 x - LSN090HSV5
	- 1 x - LSN120HSV5
	- 1 x - LSN181HSV5
 - LG devices connected (list): compressors:
	- 2 x - LMU300HHV
    - 1 x - LMU240HHV

**Output of HA logs**
Paste the relavant output of the HA log here.

No relevant entries found in the logs (settings -> system -> logs). Is there somewhere else I should check for logs?

**Additional context**

**Comment by ollo69** [comment]
This has been discussed on many other threads: some device do not support this function also if it is exposed in `model_info` and so is not possible to determinate when switch should not be exposed.
Just disable the control in HA to not show it.
