### ISSUE TITLE
smartthinq_sensors/set_sleep_time. Reservation sleep time is not available

### ISSUE THREAD

**Issue by cybermann22** [ollo69/ha-smartthinq-sensors#671]
**Describe the bug**

Error on set sleeptime:

`type: tile
entity: climate.klimaanlage_studio
tap_action:
  action: call-service
  service: smartthinq_sensors.set_sleep_time
  target:
    device_id: 0109f3206101739371669731d553005d
  data:
    sleep_time: 60`

If possible attach the JSON info file for your devices.
`  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.1.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.1.70-haos",
    "supervisor": "2023.12.0",
    "host_os": "Home Assistant OS 11.3",
    "docker_version": "24.0.7",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "smartthinq_sensors": {
      "version": "0.36.2",
      "requirements": [
        "pycountry>=20.7.3",
        "xmltodict>=0.12.0",
        "charset_normalizer>=2.0.0"`

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:14:05 (1 occurrences)
Last logged: 11:14:05

[140351030309952] Reservation sleep time is not available
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 831, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/climate.py", line 439, in async_set_sleep_time
    await self._device.set_reservation_sleep_time(sleep_time)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 878, in set_reservation_sleep_time
    raise ValueError("Reservation sleep time is not available")
ValueError: Reservation sleep time is not available
`

**Comment by cybermann22** [comment]
`service: smartthinq_sensors.set_sleep_time
data:
  sleep_time: 120
target:
  device_id: 0109f3206101739371669731d553005d`

**Comment by JaccoSmit** [comment]
Same problem here.
Can not use sleep_time any more

**Comment by modem** [comment]
In my case, the sleep timer works when the AC is set to cool, in any other HAVC mode it throws this error. 

After the sleep timer is set in the cool state, it can be changed to any other HVAC mode, and after that the sleep timer service can still be called to change the timer. It seems it just fails the activation in any other HVAC mode.

It would be nice if this sleep function could be used in other states, specially for the heat state.
