### ISSUE TITLE
Add humidity sensor to AC integration

### ISSUE THREAD

**Issue by xilopaint** [ollo69/ha-smartthinq-sensors#676]
Not sure if it's possible, but it would be a good addition. Here's my diagnostics file:

[smartthinq_sensors-d08847ba01c871c340f8c727f1ba7f67-Ar-Condicionado-1c3f01a05aae6fcce376db0de2db2282.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/13931277/smartthinq_sensors-d08847ba01c871c340f8c727f1ba7f67-Ar-Condicionado-1c3f01a05aae6fcce376db0de2db2282.json.txt)

**Comment by ollo69** [comment]
This sensor is already implemented, but your device do not provide this value (at least not in the payload).
Close this.
