### ISSUE TITLE
Minor thing: LG Heatpump AI mode shows weird degrees instead of +/- 5 like the LG app

### ISSUE THREAD

**Issue by daath** [ollo69/ha-smartthinq-sensors#677]
As the title suggests, this is a minor thing; My LG Heatpump is in AI-mode (shown as "Auto" - mode is also shown as a button), but the temperature selector in the card shows 18° C where the app shows +1 - not sure what 18° C is, because the temp that the AI has set is 43° C right now (or 43° C depending on where you look). 
It would be cool if it would match more closely to what you see in the app: 17° C should just read 0, 19° C should read +2 and 15° C should read -2 etc ...

If screenshots or further explanation is needed, I am happy to oblige :)

I'm using the latest HAOS etc and the latest of this integration...

Device info in HA says "AWHP_019101_WW-AWHP (AC) by LG" and firmware reads "Firmware: clip_hna_v1.9.194"
The official name is LG Therma V 7 KW All In One HU071MR - the model number is HN0913T

**Comment by gerhardL70** [comment]
Same issue here.
Furthermore i noticed, that the LG Heatpump does not seem to really care about the target temperature i fixed in the manual mode. If i put 33°C the outgoing heating water is most of the time 35 and sometimes as low as 26. Any ideas how i can bring the  heatpump to the fixed temperature? I am not sure, if this is an HA issue.

**Comment by JediAAK** [comment]
I am having the same issue with the Auto mode. My heat pump is set to 35oC and in Auto, it shows 17oC. If I add +1, it changes to 18 and in ThinQ app it shows +1 in the Auto Mode graph.

Everything is working normally, it's just that this target temp in Auto Mode seems to be getting a wrong reading from something/somewhere.

Model: AWHP_019101_WW-AWHP (AC)
Firmware: clip_hna_v1.9.198.

![msedge_r7hPIucx25](https://github.com/ollo69/ha-smartthinq-sensors/assets/138729770/9bc8fcb9-ef5d-4839-a1fb-4548aeec04d2)
