### ISSUE TITLE
[BUG] The integration is not available after including the files in the custom_components folder

### ISSUE THREAD

**Issue by loac404** [ollo69/ha-smartthinq-sensors#68]
The custom integration is not available in the web UI after copying the files in the custom_components folder and rebooting HA.  In consequence it's not possible to configure it. 

Nothing relevant in the log, just the stantard warning regarding the use of a custom component. 

Since there is no option to configure the integration in configuration.yaml, there is no possible way to use the integration. 

 - Environment (HASSIO, Raspbian, etc): HassOS 4.11
 - Home Assistant version installed: Home Assistant 0.112.4
 - Component version installed: 0.5.5

**Output of HA logs**
Paste the relavant output of the HA log here.

 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

**Comment by KTibow** [comment]
What do you mean? It just doesn’t show up when you go to configure it under “Integrations”?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ollo69** [comment]
Just clear the cache of your browser, close and re-open it

**Comment by loac404** [comment]
> Just clear the cache of your browser, close and re-open it

it worked! Thanks for the quick reply and the support. 

Sorry for the inconvenience, I ´m quite new in this arena. 

All the best!

**Comment by KTibow** [comment]
@loac404 consider closing???
