### ISSUE TITLE
AC Device Snapshots Outdated

### ISSUE THREAD

**Issue by buric** [ollo69/ha-smartthinq-sensors#680]
Hello,
this is not a bug with this repository, but an issue I have while developing my own API. Unfortunately I have not found any API docs, so hoping someone can help me here.
I am doing APIv2 `/service/application/dashboard` calls and I get all my AC devices, but unfortunately the snapshots I get are couple of hours old. But, when I open the `LG Thinq` app on my phone, a new snapshot gets created and sent to the cloud, so next time I do the API call I see the refreshed state with up-to-date temperatures.
How is the app doing that? Is there an API call I could use to tell the AC devices to refresh the state in the cloud?
Thank you

**Comment by ollo69** [comment]
It's strange that snapshot is not updated, I never here about this. Anyway you can try to directly query the device snapshot calling `service/devices/{device_id}`, replacing `{device_id}` with the ID of the device.
I close this because not an integration issue.
