### ISSUE TITLE
LG Smart Washer Dryer Combo not working.

### ISSUE THREAD

**Issue by reinerkap** [ollo69/ha-smartthinq-sensors#681]
I'm trying to use this integration for my LG Smart Washer/Dryer Combo system (LG FH6G1BAPK2_US-FL). However I can't do anything with it as every time it tries to pull the data from the cloud it raises an error. Log enclosed below. I'm using the latest version of Home Assistanct, HACS and ha-smarthinq-sensors.

Reiner

Logger: custom_components.smartthinq_sensors
Source: helpers/update_coordinator.py:300
Integration: SmartThinQ LGE Sensors ([documentation](https://github.com/ollo69/ha-smartthinq-sensors), [issues](https://github.com/ollo69/ha-smartthinq-sensors/issues))
First occurred: January 22, 2024 at 11:13:18 AM (149 occurrences)
Last logged: January 24, 2024 at 10:07:05 AM
Unexpected error fetching smartthinq_sensors-Washer data: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 474, in _async_update
    await self._async_state_update()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 486, in _async_state_update
    state = await self._device.poll()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 312, in poll
    res = await self._device_poll(WM_ROOT_DATA)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 741, in _device_poll
    res = self._model_info.decode_monitor(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/model_info.py", line 402, in decode_monitor
    return self.decode_monitor_json(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/model_info.py", line 393, in decode_monitor_json
    return json.loads(data.decode("utf8"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ollo69** [comment]
Please attach integration diagnostics

**Comment by reinerkap** [comment]
[smartthinq_sensors-ce2650eb34b55d468245456dbb0b9dbc-Washer-47a21d2b5963dbba1cdafd530913545f.json(1).txt](https://github.com/ollo69/ha-smartthinq-sensors/files/14073309/smartthinq_sensors-ce2650eb34b55d468245456dbb0b9dbc-Washer-47a21d2b5963dbba1cdafd530913545f.json.1.txt)

This is the information I've got. If this is not what you've been looking for please let me know how I get what you need as I'm new to HA.

Reiner

**Comment by reinerkap** [comment]
This is what I receive in the Log Window:

Logger: custom_components.smartthinq_sensors.wideq.model_info
Source: custom_components/smartthinq_sensors/wideq/model_info.py:421
Integration: SmartThinQ LGE Sensors ([documentation](https://github.com/ollo69/ha-smartthinq-sensors), [issues](https://github.com/ollo69/ha-smartthinq-sensors/issues))
First occurred: February 5, 2024 at 1:59:56 PM (233 occurrences)
Last logged: 11:31:22 AM

    Received XML data from device: b'<MonRoot><main_washer><currenttime>3,28</currenttime><fwVer>GPLUS_20170324_V155</fwVer><MainCountryCode>4</MainCountryCode><State>7</State><PrevState>6</PrevState><Remain>3</Remain><All>58</All><Reserve>0</Reserve><Course_type>0</Course_type><Course>1</Course><staincare>0</staincare><Error>0</Error><soil>2</soil><spin>8</spin><watertemp>4</watertemp><rinse>1</rinse><dry_level>0</dry_level><Wash>3</Wash><Steam>0</Steam><Steamsoftener>0</Steamsoftener><Dooropen>0</Dooropen><WM_Option1>208</WM_Option1><WM_Option2>216</WM_Option2><AddedDT>0</AddedDT><TotalRinseCnt>1</TotalRinseCnt><StainLevel>0</StainLevel><LoadLevel>2</LoadLevel><EnergyWatt>1</EnergyWatt><EnergyWater>1</EnergyWater><EnergyDetergent>0</EnergyDetergent><EnergySoftener>0</EnergySoftener><DetergentAmount>45</DetergentAmount><SoftenerAmount>30</SoftenerAmount><TubCleanCount>34</TubCleanCount><WifiLevel>3</WifiLevel><Down1>139</Down1><Down2>110</Down2><Down3>149</Down3><Down4>-1</Down4><Down5>151</Down5><Down6>117</Down6><MyPattern><HitCount>81</HitCount><Course>1</Course><staincare>0</staincare><soil>2</soil><spin>8</spin><watertemp>4</watertemp><rinse>1</rinse><dry_level>0</dry_level><Wash>3</Wash><Steam>0</Steam><Steamsoftener>0</Steamsoftener><WM_Option1>16</WM_Option1></MyPattern><MyPattern><HitCount>45</HitCount><Course>1</Course><staincare>0</staincare><soil>2</soil><spin>8</spin><watertemp>3</watertemp><rinse>1</rinse><dry_level>0</dry_level><Wash>3</Wash><Steam>0</Steam><Steamsoftener>0</Steamsoftener><WM_Option1>16</WM_Option1></MyPattern><MyPattern><HitCount>43</HitCount><Course>32</Course><staincare>0</staincare><soil>0</soil><spin>0</spin><watertemp>0</watertemp><rinse>0</rinse><dry_level>3</dry_level><Wash>0</Wash><Steam>0</Steam><Steamsoftener>0</Steamsoftener><WM_Option1>0</WM_Option1></MyPattern></main_washer><mini_washer><State>22</State><PrevState>22</PrevState><Remain>43</Remain><All>43</All><Reserve>0</Reserve><Course>50</Course><Course_type>0</Course_type><Error>0</Error><spin>4</spin><watertemp>2</watertemp><rinse>0</rinse><extraRinse>0</extraRinse><defaultRinse>0</defaultRinse><EnergyWatt>0</EnergyWatt><EnergyWater>0</EnergyWater><MiniCountryCode>0</MiniCountryCode><TubCleanCount>0</TubCleanCount><WM_Option3>0</WM_Option3></mini_washer></MonRoot>'

**Comment by ollo69** [comment]
Please try if last release works with your device. I have to change a lot of things to support this "strange" payload, hope I do not break any other devices. I ask to myself if LG engineering have nothing better to do that create different protocol for their devices 🤐

**Comment by ollo69** [comment]
Any update here?
