### ISSUE TITLE
Incorrect state of the dryer RC81U2AV3W in standby mode - remote start error

### ISSUE THREAD

**Issue by Jirka44** [ollo69/ha-smartthinq-sensors#688]
**Describe the bug**
The dryer RC81U2AV3W displays an incorrect status in stand by mode, remote start not working.
In the standby state, it shows the "power" and the "weighing process".

**Expected behavior**
N/A

**Screenshots**
![Dryer_IMG](https://github.com/ollo69/ha-smartthinq-sensors/assets/150792368/2506cb7a-08db-4b56-a4d7-e9b9bece2764)

**Environment details:**
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.1.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Prague",
    "os_name": "Linux",
    "os_version": "6.1.71-haos",
    "supervisor": "2023.12.1",
    "host_os": "Home Assistant OS 11.4",
    "docker_version": "24.0.7",
    "chassis": "vm",
    "run_as_root": true
 - LG device type and model with issue: 
 - RC81U2AV3W
 - LG devices connected (list): 
 - Dryer RC81U2AV3W (displayed as RC90U2_WW)
 - Washer F94J8VS2W (displayed as WTWS3-FL)

**Output of HA logs**
[smartthinq_sensors-e91b845c3d3d24f84b2d7dead3ee2010-Susicka-f5d4396df59b639317941367a04067f9.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/14178972/smartthinq_sensors-e91b845c3d3d24f84b2d7dead3ee2010-Susicka-f5d4396df59b639317941367a04067f9.json.txt)
[config_entry-smartthinq_sensors-1d77c044972c3e4628a161399a90e993.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/14178973/config_entry-smartthinq_sensors-1d77c044972c3e4628a161399a90e993.json.txt)

```

```

**Additional context**

**Comment by Jirka44** [comment]
OK.
Thank You very much

**Comment by ollo69** [comment]
@Jirka44,

please try if last release fix your issue and report here your feedback.

**Comment by Jirka44** [comment]
Hi ollo69,

you are megamind. :) Update works great! Issue is solved.

Thank You very much.
Your work is awesome!

**Comment by ollo69** [comment]
Good to hear that it works, so I close this.
