### ISSUE TITLE
Log Warning about ClimateEntityFeature.TURN_OFF for AC Device

### ISSUE THREAD

**Issue by roygeraets** [ollo69/ha-smartthinq-sensors#692]
Core version: 2024.02.0
Supervisor: 2023.01.1
OS: 11.5
Frontend: 20240207.0
ha-smartthinq-sensors version: 0.37.2

2 airco's connected. RAC_056905_WW-RAC (AC)

Home assistant Logbook spits out following 3 warning logs. 

```
Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues

Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues

Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) implements HVACMode(s): off, heat, dry, cool, fan_only, heat_cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues
```

**Comment by ollo69** [comment]
Thanks👍

**Comment by yarafie** [comment]
Getting same warnings

Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues

Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues

Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) implements HVACMode(s): off, auto, dry, cool, fan_only and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues

**Comment by ollo69** [comment]
Please do not add comment to this thread. The deprecated warning is expected and will be fixed in next releases .

**Comment by ollo69** [comment]
Close this a s fixed with last release.
