### ISSUE TITLE
Download  gets stuck

### ISSUE THREAD

**Issue by Kaaremi** [ollo69/ha-smartthinq-sensors#697]
**Describe the bug**
When trying to redownload the V0.38.1 the download seems to never end. With the first installation I didn't encounter that.

**Comment by ollo69** [comment]
Redownload using what? What does this have to do with integration?

**Comment by ollo69** [comment]
This is totally incomprehensible. There is an issue template, fill the requested field and provide requested information. I close this issue because unmanageable.

**Comment by Kaaremi** [comment]
Sorry for insufficient clarity.

The HACS integration stopped working with LG Dishwasher and I tried to
remove it and install it back. HACS menu has a "Redownload" option which I
selected. However, the installation didn't succeed, and after waiting for
nearly half an hour I decided to let you know about the issue.

Once again, as a novice with GitHub I probably violated the protocol, but
hope that you will take a look at the issue.



Parhain terveisin / Best Regards / Mit freundlichen Grüßen

Mikko Kaarela ***@***.***)

**Comment by ollo69** [comment]
Download is not managed by integration but by HACS. Because seems that you have problem connecting to LG and downloading from git, the most probable cause is an issue related to your network.

**Comment by Kaaremi** [comment]
Thank you for that clarification. If the problem continues I will try to
get in touch with HACS.

Regarding my network, I have a very reliable 100 Mbps connection and
downloading updates is usually very straightforward.

Thank you for your time, keep doing the gif work.



Parhain terveisin / Best Regards / Mit freundlichen Grüßen

Mikko Kaarela ***@***.***)

**Comment by ollo69** [comment]
Any news here, Can we close this?

**Comment by Kaaremi** [comment]
I guess yes



Parhain terveisin / Best Regards / Mit freundlichen Grüßen

Mikko Kaarela ***@***.***)
