### ISSUE TITLE
LG hood fan control

### ISSUE THREAD

**Issue by renekii** [ollo69/ha-smartthinq-sensors#701]
3 entities appear in HA for my LSHD3080ST

fan.hood_fan - to control the fan
light.hood_light - to control the light
sensor.hood - checks if the others are on

Both the control options do not work, but they do report correctly if either is on when I do so via LG app.  Is this expected and they are meant to only operate as sensors and not a way to control it? Is there a way I can troubleshoot this myself?

Thank you,

**Comment by ollo69** [comment]
@renekii,

support for this device is discussed at FR #394. To support the control, is necessary to capture the traffic from LG app as discussed inside the issue. If you are able to provide this information I will be happy to integrate device control.

I close this issue as duplicated.
