### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by Pammetje** [ollo69/ha-smartthinq-sensors#706]
The integration completly stopped working after the latest updates from yesterday
I run the latest HA and the latest ha-smartthing integration

I have this device

F_V8_Y___W.B_2QEUK-FL (WASHER)
by LG
Firmware: clip_hna_v1.9.198

It is washing at  the moment and I do not recieve any info anymore

**Comment by ollo69** [comment]
You need to provide all requested information in issue template (error log, diagnostics, your configuration, ha version etc) because my chrystal ball is broken. I close this, open a new issue providing all requested information.

Thanks👍

**Comment by Pammetje** [comment]
Ok I am very sorry. thanks you anyway.

**Comment by Pammetje** [comment]
I completly understand I am very sorry. Me not providing all the information is not helping you troubleshoot potential issues. Thank you for all your work. P.s. I also found the issue (it was a network problem) I feel very stupid.
