### ISSUE TITLE
Issues with smartthinq sensors after core update to 24.2.3

### ISSUE THREAD

**Issue by Frank-Leysen** [ollo69/ha-smartthinq-sensors#708]
Hello,

To whom it may concern: 
This morning I updated Home Assistant Core to version 24.2.3, I saw these issues in the logbook:

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Klimaat (documentation, issues)
First occurred: 10:42:28 (12 occurrences)
Last logged: 10:42:28

Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues
Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues
Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) implements HVACMode(s): off, heat, dry, cool, fan_only, heat_cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues

I have no idea what this means and what is wrong, but the airco/heating units seem to be working as they should. 
I hope this information helps you to solve the issues.

Thank you and keep up the good work. 

Frank

**Comment by ollo69** [comment]
This is just a warning for a feature that will be removed in HA 2024.1 and will be addressed in future releases to not break compatibility with previous HA version for now,
Closed as duplicated of #692
