### ISSUE TITLE
ClimateEntityFeature.TURN_OFF implements the turn_off method

### ISSUE THREAD

**Issue by dimitripb** [ollo69/ha-smartthinq-sensors#712]
**Describe the bug**
Since I updated to 0.38.4 an error message appears in HA.

**Expected behavior**
No errors about turn_off/on method

**Screenshots**
N/A

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed: 2024.2.3
 - Component version installed: 0.38.4
 - Last know working version: 0.38.0
 - LG device type and model with issue: RAC_056905_WW-RAC (AC)
 - LG devices connected (list): RAC_056905_WW-RAC (AC)

**Output of HA logs**

```
    Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues
    Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues
    Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) implements HVACMode(s): off, heat, dry, cool, fan_only, heat_cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues

```

**Additional context**
Related to: https://github.com/home-assistant/core/issues/109865

**Comment by ollo69** [comment]
Close as duplicated of #692
