### ISSUE TITLE
Notifications trigger when turned on

### ISSUE THREAD

**Issue by freggel2** [ollo69/ha-smartthinq-sensors#718]
**Describe the bug**

When the washer or dryer is ready I get a notification. But this notification is also sent when the washer or dryer is turned on. This was not the case before.
binary_sensor.dryer_dry_completed
binary_sensor.washer_wash_completed

**Expected behavior**

It is expected to be triggered only when the program is finished and not when the machines are turned on.

**Screenshots**
--
**Environment details:**
 - Environment HomeAssistant Raspberry pi4 SSd
 - Home Assistant version installed: Home Assistant

    Core 2024.2.5
    Supervisor 2024.02.1
    Operating System 12.0
    Frontend 20240207.1
 - Component version installed: 0.38.7
 - Last know working version:
 - LG device type and model with issue:
 - LG devices connected (list):

**Output of HA logs**
none

```

```

**Additional context**

![lg](https://github.com/ollo69/ha-smartthinq-sensors/assets/86834188/861b86af-5469-4fdd-910b-6e0b7d72b153)

**Comment by ollo69** [comment]
Please attach integration diagnostic captured before and after that the sensor change state

**Comment by freggel2** [comment]
I want to do that but in the diagnostics there is some sensitive data like user id, ssid,  etc.. I'm not comfortable with posting it here. The diagnostics has about 631.284 characters.

**Comment by ollo69** [comment]
Just edit the files replacing data that you don't want provide. Normally that data are not really sensitive, data as Mac addr, password, access token etc should be already redacted. Please attach the file and don't paste contents in the thread.

**Comment by freggel2** [comment]
[home-assistant_smartthinq_sensors_2024-03-11T14-51-24.405Z.log](https://github.com/ollo69/ha-smartthinq-sensors/files/14593751/home-assistant_smartthinq_sensors_2024-03-11T14-51-24.405Z.log)

log file is attached

**Comment by ollo69** [comment]
@freggel2 ,

sorry but I was very busy on last months, but I do not forget this issue.
If this is still an issue for you, to analyze this I don't need integration logs but device diagnostic generated before and after the issue occurs. You can generate diagnostic directly from the device page.

Thanks👍
