### ISSUE TITLE
Stuck at "SmartThinQ LGE Sensors - Authentication Page

### ISSUE THREAD

**Issue by sominaik** [ollo69/ha-smartthinq-sensors#72]
Hi,

I am stuck at the page while adding the integration where the form is asking for a Redirection URL.
I am not sure, what needs to be used there .. kindly guide

**Comment by KTibow** [comment]
Can you send a screenshot?

**Comment by sominaik** [comment]
I got it working .. was doing a silly mistake :)
thanks

**Comment by gravyflex** [comment]
What did you do? I am stuck as well. 

I am using https://sso.lg.com/oauth/page/login?authorizeKey=c65a6479-0993-4939-a954-39f2bf38ea36 as the URL and 
The redirection URL for me is: https://www.lg.com/ca_en/mylg. I am sure I am missing something...
