### ISSUE TITLE
Cannot add integration

### ISSUE THREAD

**Issue by stimpy2318** [ollo69/ha-smartthinq-sensors#73]
I installed the custom component via HACS and rebooted my HA system. After waiting a few minutes post bootup, I am still not seeing this component in the Integration list to add the configuration.

I would think based on the configuration information that this component would show up in the integrations list to be able to add the integration and configure it.

I am running HassOS 4.12 on a Pi4.
Supervisor version is 234
HA Core version is 0.114.1

I do see the following message in the logs shortly after bootup which would seem to indicate that the component is actually installed:
WARNING (MainThread) [homeassistant.loader] You are using a custom integration for smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

**Comment by ollo69** [comment]
Just clear your browser cache, close and re-open it.

**Comment by stimpy2318** [comment]
Thank you, that seemed to work. I should have tried clearing the cache.
