### ISSUE TITLE
Not working in 2024.4.1

### ISSUE THREAD

**Issue by Waank1** [ollo69/ha-smartthinq-sensors#733]
**Describe the bug**
Wasn't working in 2024.4 either

**Expected behavior**
Expect it to load

**Screenshots**
Logger: homeassistant.setup
Source: setup.py:273
First occurred: 14:13:40 (1 occurrences)
Last logged: 14:13:40

Setup failed for custom integration 'smartthinq_sensors': Requirements for smartthinq_sensors not found: ['pycountry<23.0.0,>=22.1.10'].

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed:
 - Component version installed:
 - Last know working version:
 - LG device type and model with issue: All
 - LG devices connected (list): None

**Output of HA logs**
Logger: homeassistant.setup
Source: setup.py:273
First occurred: 14:13:40 (1 occurrences)
Last logged: 14:13:40

Setup failed for custom integration 'smartthinq_sensors': Requirements for smartthinq_sensors not found: ['pycountry<23.0.0,>=22.1.10'].

```

```

**Additional context**

**Comment by neclimdul** [comment]
seems the same as #725. just ran into this and saw the updates in the other issue. Clicking on HACS and updating the integration seems to have fixed the problem.

**Comment by Waank1** [comment]
Thanks,   It worked, I will try to remember that for next time!Sent from my iPadOn Apr 5, 2024, at 19:23, James Gilliland ***@***.***> wrote:﻿
seems the same as #725. just ran into this and saw the updates in the other issue. Clicking on HACS and updating the integration seems to have fixed the problem.

**Comment by lorcott** [comment]
YUP...that did it. Open HACS and it will show you the update! THX James
