### ISSUE TITLE
BUG: Air Conditioner Light Control Just Stopped Working

### ISSUE THREAD

**Issue by moebis** [ollo69/ha-smartthinq-sensors#736]
I used to be able to turn on/off the display light on the LG air conditioner unit. Now it throws an error: "Failed to call service switch/turn_on. Not possible to determinate a valid light mode" ...this happened after a power outage and I think the Raspberry Pi didn't shut down gracefully, but it could also just be a bug I didn't catch in the last couple of updates because it had been a long time (over a month) since I last used that switch.

<img width="477" alt="Screenshot 2024-04-16 at 8 16 50 AM" src="https://github.com/ollo69/ha-smartthinq-sensors/assets/3595244/f541ad7e-4561-4d63-ba6f-e70df4cec6aa">
<img width="511" alt="Screenshot 2024-04-16 at 8 16 54 AM" src="https://github.com/ollo69/ha-smartthinq-sensors/assets/3595244/b14ce5ab-e275-4e39-a4bd-aff7b0c408b8">

**Comment by ADKMechETECH** [comment]
I just discovered that the toggle doesn't seem to exist anymore.  I found it very useful.  Hopefully LG didn't break something permanently.

**Comment by andrelr84** [comment]
This problem still persists, in the LG app the option to turn off the display during integration does not work.

**Comment by ADKMechETECH** [comment]
> This problem still persists, in the LG app the option to turn off the display during integration does not work.

Do you still have the toggle? It isn't even showing up for me anymore.

**Comment by ADKMechETECH** [comment]
Bump...

**Comment by dilnuwan-calcey** [comment]
I have the same issue

**Comment by ADKMechETECH** [comment]
This is still an issue....

Bump.

**Comment by moebis** [comment]
Still doesn't work and now the entire LG Thinq integration for Air Conditioners are broken. There is another thread being ignored: https://github.com/home-assistant/core/issues/131252
