### ISSUE TITLE
Power Usage and Ice Maker Controls

### ISSUE THREAD

**Issue by stimpy2318** [ollo69/ha-smartthinq-sensors#74]
I managed to get my refrigerator setup using this integration and it would be nice to also get some of the power usage information into Home Assistant so that I have another point of data for how much energy my home is consuming and can analyze it based on device better.

Also the LG app allows me to control temperatures and ice maker settings (Ice+ mode) these might be nice to be able to do within Home Assistant as well if this integration could be made to include them.

Also being able to check air and water filter statuses within Home Assistant might be nice as well.

**Comment by stimpy2318** [comment]
Looks like filter statuses are already included.

**Comment by ollo69** [comment]
Sensor attributes already provide additional device information.
About power usage, this information is not available.
For the control, is work in progress. Last months I don't have lot of time available, but for sure in the future will be implemented.

**Comment by ollo69** [comment]
Close this issue due to inactivity and because feature requested already implemented or duplicated.
