### ISSUE TITLE
[BUG] Google Auth doesn't work in Poland

### ISSUE THREAD

**Issue by edgard** [ollo69/ha-smartthinq-sensors#75]
**Describe the bug**
When trying to login to LG with a Google linked account it fails because the redirect URL (pl.m.lgaccount...) is not allowed by the application.

**Expected behavior**
Login to work.

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed: 0.114.2
 - Component version installed: 0.5.5
 - Last know working version: N/A
 - LG device type and model with issue: LG Washer
 - LG devices connected (list):

**Comment by ollo69** [comment]
Does not work with social network account, is clearly explained in readme. You must create a dedicated LG account.
I close this issue.

**Comment by KTibow** [comment]
If you create a Poland LG account without Google does it still error?

**Comment by KTibow** [comment]
Also I can do it just fine with a US google account.
