### ISSUE TITLE
Blocking call to open inside the event loop

### ISSUE THREAD

**Issue by desosav** [ollo69/ha-smartthinq-sensors#754]
HA 2024.6.0b0

`Detected blocking call to open inside the event loop by custom integration 'smartthinq_sensors' at custom_components/smartthinq_sensors/wideq/core_async.py, line 1704: with open(data_file, "r", encoding="utf-8") as lang_file: (offender: /config/custom_components/smartthinq_sensors/wideq/core_async.py, line 1704: with open(data_file, "r", encoding="utf-8") as lang_file:), please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues`

**Comment by ollo69** [comment]
Fixed in [v0.39.2](https://github.com/ollo69/ha-smartthinq-sensors/releases/tag/v0.39.2)
