### ISSUE TITLE
[BUG] Refrigerator: No value update on sensor.refrigerator_refrigerator_temp & sensor.sensor.refrigerator_freezer_temp 

### ISSUE THREAD

**Issue by osakalevin** [ollo69/ha-smartthinq-sensors#76]
**Describe the bug**
Values for the following sensors are not updated:
- sensor.refrigerator_refrigerator_temp
- sensor.sensor.refrigerator_freezer_temp

**Expected behavior**
Values should be updated upon change.

**Environment details:**
 - HassOS 4.12 (Pi 4 Model B)
 - Home Assistant version installed: 0.114.3
 - Component version installed: SmartThinQ LGE Sensors 0.5.5
 - Last know working version: Unknown
 - LG device type and model with issue: Refrigerator model 2REB1GLVB1___-BF
 - LG devices connected (list): Only refrigerator

```

```

**Additional context**
If I manually set the state for another temperature, after a couple of seconds it returns to the previous set temperature (5ºC Fridge; -21ºC Freezer). The temperature that is set on LG's ThinQ app is 7ºC and -15ºC.

If I set the temperature using the LG ThinQ app, the refrigerator and freezer temperature are updated on the App and on the Refrigerator itself, but not on HA.

Hope this helps.

Thanks

**Comment by ollo69** [comment]
Fine,

my suspect is that there are some from conversion from measure unit, but I need some log from you to analyze it.
You should add the following line in configuration.yaml:

```
logger:
  default: info
  logs:
    custom_components.smartthinq_sensors: debug
```

tan reboot HA and send me the log file that should contain debug info so that I can analyze the value that the component is receiving.
Please before posting log file remove your personal information, the first line of the log will contain your access token.

**Comment by osakalevin** [comment]
> Fine,
> 
> my suspect is that there are an issue in conversion from measure unit, but I need some log from you to analyze it.
> You should add the following line in configuration.yaml:
> 
> ```
> logger:
>   default: info
>   logs:
>     custom_components.smartthinq_sensors: debug
> ```
> 
> than reboot HA and send me the log file that should contain debug info so that I can analyze the values that the component is receiving.
> Please before posting log file remove your personal information, the first line of the log will contain your access token.

Hey,

Ok, debug info [here](https://pastebin.com/mH9M2tFw)

Let me know if you need anything else.

Thanks for helping.

**Comment by ollo69** [comment]
Loking at the log and JSON info file, the component is showing the correct values:

```
'refState': {'activeSaving': 'OFF', 'atLeastOneDoorOpen': 'CLOSE', 'convertibleTemp': 0.0, 'displayLock': 'UNLOCK', 'dualFridgeMode': 'IGNORE', 'ecoFriendly': 'ON', 'expressFridge': 'OFF', 'expressMode': 'OFF', 'freezerTemp': 6.0, 'freshAirFilter': 'IGNORE', 'fridgeTemp': 3.0, 'monStatus': 'NORMAL', 'sabbathMode': 'OFF', 'smartSavingMode': 'OFF', 'smartSavingRun': 'STOP', 'tempUnit': 'CELSIUS', 'waterFilter': '0_MONTH'}
```

As you can see `fridgeTemp: 3.0` and `freezerTemp: 6.0` that mapped with the JSON file means 5° and -20°. What is also surprising me are the value on the app, because 7° and -15° are the minumum temperature available and the default value. Are you sure that this value are correct? May be you should try to reset the fridge and the remove and re-add in the app.
Component is showing exacltly what is receiving!!!!

**Comment by osakalevin** [comment]
Hey,

Yes, I'm sure the values (7ºC and -15ºC) are correct. Those values are shown on the refrigerator door and on LG's App. If I change the temperature on the refrigerator door, it will also change on LG's App. The only place where the temperature does not change, in any way, is within Home Assistant. Looks like the API is always receiving the same (wrong) values.

Will try a reboot and add the frige back in the app. Will advise.

Thanks

**Comment by ollo69** [comment]
Can you leave the HA log enabled while you change the temperatures on the fridge, to check if something change or not?

**Comment by osakalevin** [comment]
Hey,

So finally, we're on to something :) I believe I've figured out what is happening.

1. If the fridge/freezer temperature is updated manually, either on the refrigerator door or LG's App, it will trigger an API call with the updated temperature values:

> online': True, 'refState': {'activeSaving': 'OFF', 'atLeastOneDoorOpen': 'CLOSE', 'convertibleTemp': 0.0, 'displayLock': 'UNLOCK', 'dualFridgeMode': 'IGNORE', 'ecoFriendly': 'OFF', 'expressFridge': 'OFF', 'expressMode': 'OFF', **'freezerTemp': 3.0**, 'freshAirFilter': 'IGNORE', **'fridgeTemp': 4.0**, 'monStatus': 'NORMAL', 'sabbathMode': 'OFF', 'smartSavingMode': 'OFF', 'smartSavingRun': 'STOP', 'tempUnit': 'CELSIUS', 'waterFilter': '0_MONTH'
![Screenshot_20200825-153710](https://user-images.githubusercontent.com/10699626/91189765-be707c00-e6ea-11ea-8bcf-e88325eee9d7.png)

![Screenshot from 2020-08-25 15-52-22](https://user-images.githubusercontent.com/10699626/91189997-ff689080-e6ea-11ea-9c2c-1af3608d4d0d.png)

2. If I select ECO Friendly mode, which is an economical mode to trigger a default temperature of 7ºC (Fridge) and -15ºC (Freezer) (json **ecoFriendly**), the temperatures on the refrigerator door and LG's App are updated, **however**, they are not updated on the API call. The **mode**, however, is updated as you can see below:

> 'online': True, 'refState': {'activeSaving': 'OFF', 'atLeastOneDoorOpen': 'CLOSE', 'convertibleTemp': 0.0, 'displayLock': 'UNLOCK', 'dualFridgeMode': 'IGNORE', **'ecoFriendly': 'ON'**, 'expressFridge': 'OFF', 'expressMode': 'OFF', **'freezerTemp': 3.0**, 'freshAirFilter': 'IGNORE', **'fridgeTemp': 4.0**, 'monStatus': 'NORMAL', 'sabbathMode': 'OFF', 'smartSavingMode': 'OFF', 'smartSavingRun': 'STOP', 'tempUnit': 'CELSIUS', 'waterFilter': '0_MONTH'
![Screenshot_20200825-152611](https://user-images.githubusercontent.com/10699626/91190033-0bece900-e6eb-11ea-8297-bbdf0ff3dcb9.png)

![Screenshot from 2020-08-25 15-53-06](https://user-images.githubusercontent.com/10699626/91190076-1ad39b80-e6eb-11ea-89e6-dbf847e054a4.png)

So, it looks like an issue with LG's API not sending the correct temperature when a mode is selected, instead of a manual temperature being set.

Let me know if this makes any sense.

Thanks

**Comment by ollo69** [comment]
You are right, I didnt't realize that your fridge was in EcoFrienly mode.
But it is not a LG API issue, they probably implement API in this way to be able to remember the temperature set with eco friendly status OFF.
I have to implement the logic in the component to set the temperature to the default EcoFriendly values (that are reported in JSON file) when this flag is on. 
I will inform you when the change will be released.

**Comment by ollo69** [comment]
> PS: I know this is a separate issue, but it would be cool if we could retrieve the values for the modes within lovelace ('ecoFriendly', 'expressFridge', 'expressMode'). If you'd like, I can open a new thread as a feature request :D

This can be already done in multiple way, for example::

1. Use platform template to expose attribute as sensor
2. Use a front-end extension (you can search in HACS) that allow you to directly shou attribute values in lovelace

**Comment by osakalevin** [comment]
Hey,

Awesome! Thanks!

**Comment by ollo69** [comment]
I close this issue because it should be fixed and I do not receive any feed-back from 1 month

**Comment by KTibow** [comment]
@ollo69 You should install the Stale bot.

**Comment by osakalevin** [comment]
Yep, all good! Thanks!
