### ISSUE TITLE
Add support for "energy consumption" for AC

### ISSUE THREAD

**Issue by dzervas** [ollo69/ha-smartthinq-sensors#762]
**Describe the bug**
I have a `RAC_056905_WW-RAC (AC)` (LG ArtCool Mirror) and the exposed sensors include "energy current" but I can't add it to the energy panel

**Expected behavior**
Be able to add the AC to the energy consumption of the house

**Comment by stewartadam** [comment]
The Energy dashboard supports energy (kWh) now power (watts) sensors - see [Creating an Energy Sensor out of a Power Sensor](https://www.home-assistant.io/docs/energy/faq/#creating-an-energy-sensor-out-of-a-power-sensor).

**Comment by dzervas** [comment]
thanks!
