### ISSUE TITLE
FIXED:  See comments - ERROR: Failed Setup, will retry: ThinQ platform not ready

### ISSUE THREAD

**Issue by robkjr** [ollo69/ha-smartthinq-sensors#766]
**Describe the bug**
SInce the last HACS update I receive the following with my ThinQ integration.   This used to work perfectly but now seems broken.  

**Expected behavior**
HACS inegration worked prior to last update. 

**Screenshots**
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/51068706/5e5b6d61-72f2-4270-82ed-6e9b4afb53b7)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed: Latest version
 - Component version installed: Latest Version
 - Last know working version: Previous version. 
 - LG device type and model with issue: ALL
 - LG devices connected (list): 3 window ACs and a dishwasher

**Output of HA logs**
This seems to be the relevent log information 
2024-06-21 08:11:35.461 WARNING (MainThread) [custom_components.smartthinq_sensors] Connection not available. ThinQ platform not ready
Traceback (most recent call last):
File "/config/custom_components/smartthinq_sensors/__init__.py", line 269, in async_setup_entry
client = await lge_auth.create_client_from_token(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/smartthinq_sensors/__init__.py", line 153, in create_client_from_token
return await ClientAsync.from_token(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1605, in from_token
await client.refresh()
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1513, in refresh
self._auth = await self.auth.refresh(True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 989, in refresh
access_token, token_validity = await self._gateway.core.refresh_auth(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 707, in refresh_auth
out = await self._auth_request(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 653, in _auth_request
oauth_url = await self.get_oauth_url()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 436, in get_oauth_url
async with self._get_session().post(
File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
self._resp = await self._coro
^^^^^^^^^^^^^^^^

```

```

**Additional context**

**Comment by Maxloader2000** [comment]
I'm having the exact same problem.

**Comment by SpudsterZ** [comment]
Ditto. Been this way for quite some time.

**Comment by edterbak** [comment]
I seem to have the same issue as well. 
It is not initializing with the message "Failed setup, will retry: Thinq platform not ready"

**Comment by robkjr** [comment]
Well I'm glad to see I'm not the only one.    Is there anyone still monitoring this project to see if there's a fix?

**Comment by robkjr** [comment]
Seems like LG has changed or broken something because now my Google Home app won't connect.   I've lost all control over my LG devices except for the LG App.

**Comment by robkjr** [comment]
I FIXED THIS!!!!!!   It turns out I had South Korea geo-blocked on my firewall.   Once unblocked, everything worked.

**Comment by Maxloader2000** [comment]
Mine actually started working yesterday after a complete reboot, i had to shut everything down because my utility meter got replaced.

**Comment by edterbak** [comment]
OMG.
Indeed. 1 month ago I also added geo-blocking to my unifi UDM pro. 
I checked if I had South Korea ticked... and it was. Now I unticked it. As a result, this plugin is now again working :D: D  whahaha..

SO. Sorry for falsly confirming this bug.
@robkjr  thank you for sharing your update

**Comment by robkjr** [comment]
@edterbak It's not actually a bad thing to report this kind of thing.  Helps others not chase their tails for weeks trying to figure out why it won't work.  AND its a lesson for anyone using integrations and IoT devices that depend on cloud connectivity.  Lastly it shows just were our daily data goes when we choose to use such devices.  

I'm glad I reported this and I'm glad I was able to find the solution and share it.  Frankly I think a note should be added to the installation instructions warning about geoblocking.

**Comment by edterbak** [comment]
@robkjr Yes yes.. you are right. I did not intend to say you did something wrong here by rerpoting this issue. 😄 
Not at all! And you are also right in your conclusion by putting this in here, it can help others. So indeed, thank you for that.

I was only trying to say it was ME who caused this situation on my setup. As usual... 
And of course for jumping to the conclusion that something outside of my doing/my setup was responsible. ghehe  Sorry for that. 😄
