### ISSUE TITLE
After few minutes, integration is not updating values and doesn't see when machine finished program. 

### ISSUE THREAD

**Issue by BartoszKordylewski** [ollo69/ha-smartthinq-sensors#767]
**Describe the bug**
I just installed this integration and turned on washer machine, it was showing correct values for few minutes and then remaining time frozen. For example, I turned on washer, set program for 14min, HA was updating status for 4min (each 1min it was updating status), it stopped at remaining time 10min and that's it, nothing happened for last 10min. Even HA didn't record that washer finished program and now is off. HA is still showing that washer is on and 10min left.

**Expected behavior**
Update status each 30s or 1min without freeze and then get status that washer finished program and is off. 

**Screenshots**
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/39264859/02184f46-a68b-4fcc-b303-86cfc76a6c6c)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed: Core - 2024.6.4, OS - 12.4, Supervisor - 2024.06.2
 - Component version installed: 0.39.2
 - Last know working version: -
 - LG device type and model with issue: F4WV5N9S2TE 
 - LG devices connected (list): F4WV5N9S2TE 

**Output of HA logs**
Not logs, but image of status update for washer... it's in polish, but you can see that there were no new updates since update about remaining - 10min. 
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/39264859/10fde526-85e8-467d-8139-ff7c72dd5647)

**Additional context**
Turning the washer on again is resetting sensors for this integration.

**Comment by henne155** [comment]
Same Issue here.
Latest SmartThinQ LGE Sensors Version 0.39.2 but also on the last Versions before.
Remaining Time freezes at 09:00 Minutes remaining, sometimes at 10:00 or 14:00 Minutes.

One has to turn washer on and off again, to get sensor resetting.

Best regards and thanks for that nice Integration!
