### ISSUE TITLE
Fan modes in Capitals are rejected by HA  and stop scenes ( and hence automations calling that scene )

### ISSUE THREAD

**Issue by rudgej** [ollo69/ha-smartthinq-sensors#768]
I have this controlling LG ducted Air Conditioning.

The issue is many of the fan modes are in CAPITALS and this is rejected by HA.

      - low
      - medium
      - high
      - auto

Seems to be OK  but when run  I get

Executed: 28 June 2024 at 11:48:48
Error: Fan mode HIGH is not valid. Valid fan modes are: low, medium, high, auto
Result:
params:
  domain: scene
  service: turn_on
  service_data: {}
  target:
    entity_id:
      - scene.global_air_con_on_gnd_floor
running_script: false
child_id:
  domain: automation
  item_id: '1705399156510'
  run_id: 896fe367f31aa202d13a3bd4ca31c75d

I have gone to scenes.yaml and changec all in caps to lower letters, but this does not work and i get the same errors.

Either the system needs to ignore case, or if you can tell me where the case of these modes is set I can edit is so the scenes will work correctly.

**Comment by ollo69** [comment]
I do not understand what is the scene that is not working, but I suppose that issue is in the scene and not in the integration. HA treat fan modes case sensitive so you must provide the required fan mode with the right case. In any case this is not an integration issue and that specific error is raised by HA and not by integration.

**Comment by rudgej** [comment]
I note this has been closed. 

Given there is no way round it and the fan detail is created by the integration I can't see why it will not be fixed. 

If you can tell us a way around it then fine but given the files were populated by the integration and changing case manually does not work it makes the integration no use as the scenes fail.
