### ISSUE TITLE
[QUESTION] Nothing happens after installation; there is no apparent way to configure the integration

### ISSUE THREAD

**Issue by gmusser** [ollo69/ha-smartthinq-sensors#77]
**Describe the bug**
The documentation states: 

> Simply add a new "integration" and look for "SmartThinQ LGE Sensors" among the proposed ones and
> follow setup worflow.
> 
> Important: use your country and language code: SmartThinQ accounts are associated with a specific locale,
> so be sure to use the country and language you originally created your account with.
> Reference for valid code:
> 
> Country code:
> ISO 3166-1 alpha-2 code
> Language code:
> ISO 639-1 code

What does this mean? What "setup worflow [sic]" is it referring to? I searched for and installed the SmartThinQ LGE Sensors integration in HACS. But nothing then happened. The integration appears in the relevant pane of HCAS, but I was not presented with, nor do I see anywhere, a configuration panel where I can enter the country and language code. No LG sensor entities appear, but that is to be expected, since there is no way to configure the integration.

The documentation expressly says not to modify the configuration.yaml. For want of anything else to do, I nonetheless tried editing that file. These two lines appeared in the HA log file:

> Integration configuration using configuration.yaml is not supported. Please configure integration from HA user interface
> 10:37:03 PM – SmartThinQ LGE Sensors (WARNING)
> The 'smartthinq_sensors' option is deprecated, please remove it from your configuration
> 10:37:03 PM – SmartThinQ LGE Sensors (WARNING)

So I removed the lines

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HassOS 4.12
 - Home Assistant version installed: 0.114.3
 - Component version installed: 0.5.5
 - Last know working version: n/a
 - LG device type and model with issue: n/a
 - LG devices connected (list): n/a

**Output of HA logs**
Paste the relavant output of the HA log here.

The only log entry is:

> 2020-08-21 22:17:28 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

**Additional context**

**Comment by hoodwink55** [comment]
Clearing browser cache worked for me.

**Comment by ollo69** [comment]
I close this issue, seems solved and outdated
