### ISSUE TITLE
Add "URL redirect authentication method" information

### ISSUE THREAD

**Issue by GooodFr** [ollo69/ha-smartthinq-sensors#773]
Hello,
After only 1 month, I have "Authentication expired for LGE Devices"
I will have to login every month ?
There's a "URL redirect authentication method" check box.
What about it ? I see nothing about it …

**Comment by MathiasReker** [comment]
Hello @GooodFr,

I've experienced the same issue with having to log in again. Despite this, my integration has been running smoothly for the past six months.

Additionally, I've observed that the app and its policies have changed.

It guess that LG released an update that includes several changes, such as the method for token renewal.

**Comment by jaal2001** [comment]
Currently the integration is not useable, as the login is not possible anymore. The observation of @MathiasReker seems to be valid from my point of view.

**Comment by PvdGulik** [comment]
Same issue here in homeassistant.

No problem in Domoticz with this plugin: https://github.com/majki09/domoticz_lg_thinq_plugin

Or in Homebridge with this plugin:
https://github.com/nVuln/homebridge-lg-thinq#readme

Maybe one of these is the solution?

**Comment by ollo69** [comment]
When LG change TOS is necessary to accept on LG app to be able to connect again with integration.
I understand that request to login again on integration confuse many user, I'll try to understand if there is a way to recognize the specific issue and eventually accept TOS without manual requests.

**Comment by muhlba91** [comment]
same here but the app also doesn‘t ask to accept new TOS.

**Comment by albinsunnanbo** [comment]
Currently even the LG app seems to have trouble signing in, so while the LG backend is broken I guess the plugin will have problems too :-)

**Comment by albinsunnanbo** [comment]
> Currently even the LG app seems to have trouble signing in, so while the LG backend is broken I guess the plugin will have problems too :-)

Back online (for now...)

**Comment by muhlba91** [comment]
working ahain for me as well, and a reload of the integration solved the problem.

**Comment by GooodFr** [comment]
Thank you ;)
I accepted TOS and everything is OK +1
