### ISSUE TITLE
After upgrade HA to 2024.8.0 integration stop

### ISSUE THREAD

**Issue by herosamaral** [ollo69/ha-smartthinq-sensors#782]
After the HA update, the integration stopped working correctly despite there being no failure logs or recognition of devices that previously worked normally.
anything to do to fix this bug before the next update?

**Comment by tbclark3** [comment]
I'm getting the same thing. Entities show as unavailable when running 2024.8.0.  Downgrading was a mess.  I had to reinstall the integration, and that triggered LG to require a new password because I hadn't changed it in 30 months. (I'm glad LG is so on top of security. Sometimes I can't sleep at night because I worry that somebody is trying to break into my washing machine.)  It took an hour or so for LG to accept my new password from HA.

**Comment by tbclark3** [comment]
I tried again this morning and the LG integration loaded normally on the first try, so I don't think the issue is due to 2024.8.0, but more likely due to issue 772 or the LG password drama I had yesterday.

**Comment by herosamaral** [comment]
> I tried again this morning and the LG integration loaded normally on the first try, so I don't think the issue is due to 2024.8.0, but more likely due to issue 772 or the LG password drama I had yesterday.

Your device is also a washing machine as you mentioned above, here I still have no communication with mine, I will wait a little longer to see if any developer says something, for now I took a look at the logs and guess what, everything is fine without any errors.

**Comment by tbclark3** [comment]
I actually have 4 thinq devices--washer, dryer, dishwasher, and refrigerator, but they're all or nothing. 

Have you tried logging out of the LG website on your phone and logging back in? Maybe you're facing the same required password change that others have seen.

**Comment by herosamaral** [comment]
I just did this but without success, I'm going to try again because the LG account I use is not the main LG account but a secondary account, I'll test it here and then submit the result here.

**Comment by herosamaral** [comment]
To conclude the matter, I checked and the problem was indeed in the LG cloud, after deleting and re-registering my device it started working normally again.
