### ISSUE TITLE
Delay Start run state not displayed correctly

### ISSUE THREAD

**Issue by irv075** [ollo69/ha-smartthinq-sensors#785]
**Describe the bug**
When the washer has been programmed to start later, instead of `Delay Start` I see `@CP_UX30_CARD_DELAY_SET` as the run state

**Expected behavior**
The correct translated string of `Delay Start` is displayed

**Screenshots**
![image](https://github.com/user-attachments/assets/141a48cb-c201-4ead-b71c-8c27398ac2ee)

**Environment details:**
 - Environment: HAOS
 - Home Assistant version installed: 2024.7.4
 - Component version installed: 0.39.2
 - Last know working version: n/a
 - LG device type and model with issue: FWY937BCTA1
 - LG devices connected (list):

It looks like the DelayStart feature is missing from WasherDryer

**Comment by irv075** [comment]
PR raised #784

**Comment by chrisrbk86** [comment]
Same issue with model: F4Y709WBTA1.
