### ISSUE TITLE
Dryer hidden entities

### ISSUE THREAD

**Issue by jkrchd** [ollo69/ha-smartthinq-sensors#789]
[smartthinq_sensors-01J67YX0BP20C6JA7WVFC34882-Szárító-2ee5b485ac1c9de136bd8cc131538ec5.json](https://github.com/user-attachments/files/16867314/smartthinq_sensors-01J67YX0BP20C6JA7WVFC34882-Szarito-2ee5b485ac1c9de136bd8cc131538ec5.json)
**Describe the bug**
The integration recognise the dryer as a different model (RH90V9_WW-Dryer, instead of RH80V3AVNBN.BBWQKMR). The integration show the most important entities (like initial time and remaining time) as hidden entities, without any value. The integration does not allow the power control, but i think the ThinQ app also have issues with this.

**Expected behavior**
I hope, that the time entities will visible in the app, so i can use it's values in automations

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Hassio
 - Home Assistant version installed: 2024.08.3
 - Component version installed: 0.39.2
 - Last know working version: -
 - LG device type and model with issue: RH80V3AVNBN.BBWQKMR
 - LG devices connected (list): just the dryer

**Output of HA logs**
Paste the relavant output of the HA log here.

2024. szeptember 4.
Szárító Error message állapota megváltozott: -
11:20:23 - 17 perccel ezelőtt
Szárító Dry level állapota megváltozott: Nincs kiválasztva
11:20:23 - 17 perccel ezelőtt
Szárító Process state állapota megváltozott: -
11:20:23 - 17 perccel ezelőtt
Szárító Run state állapota megváltozott: -
11:20:23 - 17 perccel ezelőtt
Szárító Current course állapota megváltozott: -
11:20:23 - 17 perccel ezelőtt
Szárító kikapcsolva
11:20:23 - 17 perccel ezelőtt
Szárító Error state probléma észlelés befejeződött
11:20:23 - 17 perccel ezelőtt
Szárító Run completed kikapcsolva
11:20:23 - 17 perccel ezelőtt
Szárító Error message elérhetetlen lett
11:20:20 - 17 perccel ezelőtt
Szárító Dry level elérhetetlen lett
11:20:20 - 17 perccel ezelőtt
Szárító Process state elérhetetlen lett
11:20:20 - 17 perccel ezelőtt
Szárító Run state elérhetetlen lett
11:20:20 - 17 perccel ezelőtt
Szárító Current course elérhetetlen lett
11:20:20 - 17 perccel ezelőtt
Szárító elérhetetlen lett
11:20:20 - 17 perccel ezelőtt
Szárító Error state elérhetetlen lett
11:20:20 - 17 perccel ezelőtt
Szárító Run completed elérhetetlen lett
11:20:20 - 17 perccel ezelőtt

**Additional context**

**Comment by ThePaulTanner** [comment]
I had the same issue and was impatient. Un-disable those sensors and be patient. Run the machine even. They did get a reading eventually. Like 5 min when the machine was running. Not sure if the running is what helped.

Hope that helps.

**Comment by ollo69** [comment]
If you need entity that are disabled by default, just enable them. You just need to do it once, why this is an issue?
