### ISSUE TITLE
Invalid redirection URL.

### ISSUE THREAD

**Issue by darkluk13** [ollo69/ha-smartthinq-sensors#79]
Hello,

i start getting error "Invalid redirection URL."
Today my integration stopped working, so i deleted intergration and try to re add it back.
But i keep getting this error.

I have ha-smartthinq-sensors installed from HACS and it was working great until today.

**Comment by ollo69** [comment]
Try login to SmartThinQ web page with your account to see if is asking for update of privacy condition.

**Comment by darkluk13** [comment]
It was before, i accept and continue to log into account, changed password and everything.
But it still give me Invalid URL error.

**Comment by ollo69** [comment]
Provide more detail, report here the log lines with the error

**Comment by darkluk13** [comment]
Log Details (ERROR)
Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:237
Integration: SmartThinQ LGE Sensors (documentation)
First occurred: 2:06:04 PM (1 occurrences)
Last logged: 2:06:04 PM

Error retrieving OAuth info from ThinQ
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 114, in getOAuthInfoFromUrl
    oauth_info = ClientV2.oauthinfo_from_url(callback_url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 737, in oauthinfo_from_url
    access_token, refresh_token = login(oauth_url, auth_code)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 251, in login
    out = auth_request(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 237, in auth_request
    raise exc.TokenError()
custom_components.smartthinq_sensors.wideq.core_exceptions.TokenError

I try reinstall HACS integration, it still give me this error

**Comment by ollo69** [comment]
You have a token error, so token is invalid.
Reinstall is unusefull because just replace the files.
You must go in integration configuration page, remove the component and re-configure it.

**Comment by darkluk13** [comment]
I was able to fix it with uninstalling integration from HACS, reboot, install it back, reboot.
Now its working.
Thank you so much for helping me with this issue.
And big THX for making this integration!!!
