### ISSUE TITLE
'smartthinq_sensors' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 

### ISSUE THREAD

**Issue by ExquisiteMetropolis** [ollo69/ha-smartthinq-sensors#797]
I'm getting this warning in the logs. Looks like there is a depricated fuction being used.
1 year to fix it (please) ;-)

`Detected that custom integration 'smartthinq_sensors' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/smartthinq_sensors/humidifier.py, line 67: platform.async_register_entity_service(, please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues`

**Comment by Teunhen** [comment]
Same here

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 00:13:27 (1 occurrences)
Last logged: 00:13:27

Detected that custom integration 'smartthinq_sensors' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/smartthinq_sensors/humidifier.py, line 67: platform.async_register_entity_service(, please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues

**Comment by matth08080808** [comment]
Same Here

**Comment by tenkaibr** [comment]
Same here:

`Registrador: homeassistant.helpers.frame
Fonte: helpers/frame.py:184
Ocorreu pela primeira vez: 07:35:15 (1 ocorrências)
Último registro: 07:35:15
Detected that custom integration 'smartthinq_sensors' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/smartthinq_sensors/humidifier.py, line 67: platform.async_register_entity_service(, please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues`

**Comment by ollo69** [comment]
Closed with last release [0.40.0](https://github.com/ollo69/ha-smartthinq-sensors/releases/tag/v0.40.0)
