### ISSUE TITLE
"Error: Entity water_heater.<name> does not support this service." When running automation

### ISSUE THREAD

**Issue by samueljsmalmeida** [ollo69/ha-smartthinq-sensors#799]
**Describe the bug**
When running an automation, to change the state of the water_heater it returns the following error.
```
Executed: 24 September 2024 at 14:08:00
Error: Entity water_heater.aquecedor_de_agua does not support this service.
```

**Expected behavior**
Change the status to the water heater

**Screenshots**
![image](https://github.com/user-attachments/assets/f2a63064-0a0a-4ead-a4a4-d049477a7271)
![image](https://github.com/user-attachments/assets/835e241a-79e6-4ce2-bd8b-45b92cce0046)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Raspbian
 - Home Assistant version installed: ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2024.9.3
 - Component version installed: 0.39.2
 - Last know working version: Not sure
 - LG device type and model with issue: WHT_056905_WW-Water Heater, Firmware: clip_hna_v1.9.203
 - LG devices connected (list): Just this one

**Output of HA logs**
Paste the relavant output of the HA log here.

```
Executed: 24 September 2024 at 14:08:00
Error: Entity water_heater.aquecedor_de_agua does not support this service.
```

**Additional context**
Via dashboard, I can change the status of the device.

**Comment by pabsi** [comment]
Same issue on `2024.10.0`
It used to work...today I found out it doesn't anymore.

**Comment by pabsi** [comment]
I found out what my issue was:
instead of using the specific action to turn off the water_heater entity, I used the set operation mode (with off, or heat_pump):
```yaml
action: water_heater.set_operation_mode
target:
  entity_id:
    - water_heater.aerotermia_therma_v_water_heater
data:
  operation_mode: "off"
```

**Comment by pabsi** [comment]
@samueljsmalmeida may I suggest you please close this issue then?
For the sake of the maintainer's work. Just so we don't leave unnecessary issues open.
Thank you :)

**Comment by samueljsmalmeida** [comment]
Closing the issue, since there's a working alternative.
Thanks
