### ISSUE TITLE
off and Off typo fridge sensor

### ISSUE THREAD

**Issue by sagitt** [ollo69/ha-smartthinq-sensors#80]
see image

![Schermata 2020-09-06 alle 02 42 16](https://user-images.githubusercontent.com/169086/92315741-b0740280-efea-11ea-9ce1-014600d34a90.png)

**Comment by KTibow** [comment]
That's different things, door open is only on/off, express freeze can be more options.

**Comment by ollo69** [comment]
Closing this issue because already answered without any additional feed-back
