### ISSUE TITLE
Current temperature is not the current temperature on fridge

### ISSUE THREAD

**Issue by McGiverGim** [ollo69/ha-smartthinq-sensors#801]
**Describe the bug**
In the attributes of the fridge entity, there is a "current_temperature: 3". That's not right, the current temperature is unknown, only the "desired" temperature is known for the fridge (I don't know why LG does not publish this data, but it seems it does not for fridges).

It's better to have this value null "current_temperature: null", in this way, the thermostat card of Home Assistant shows the desired temperature but it hides the current temperature (that is unknown).

**Expected behavior**
Don't have current_temperature attribute when this value is unknown.

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed: 2024.9.2
 - Component version installed: 0.39.2
 - Last know working version: -
 - LG device type and model with issue: 2REB1GLVB1__2-BF (REFRIGERATOR)
 - LG devices connected (list):

**Comment by andorardo** [comment]
I'm having the same problem: https://github.com/ollo69/ha-smartthinq-sensors/issues/800#issuecomment-2394585309

Model number: LRFLS3206S.ASTCNA0

**Comment by ollo69** [comment]
> It's better to have this value null "current_temperature: null", in this way, the thermostat card of Home Assistant shows the desired temperature but it hides the current temperature (that is unknown).

I think is better to replace climate control with a slider in this case, will avoid confusion. I will manage this change with next release

**Comment by McGiverGim** [comment]
> I think is better to replace climate control with a slider in this case, will avoid confusion. I will manage this change with next release

I don't think so. It's in reality a "climate control" or at least a "thermostat". But the thermostat does not give information about current temperature. That's all.

**Comment by ollo69** [comment]
I will try to set `current_temperature` to none and check the result, not sure this work properly.
Looking at the LG app the fridge temperatures are managed by a slider (beautiful, but just a slider)

![Screenshot_20241010_101432_LG ThinQ](https://github.com/user-attachments/assets/01b98cbe-69d6-4e44-924a-1848fb28bf1c)

**Comment by McGiverGim** [comment]
This is how it looks when I put a "null" value in the developers tools for the current_temperature:
![image](https://github.com/user-attachments/assets/2eb86543-6f27-4957-a551-e4211c79dc4d)

As you see the current temperature disappears.

I don't know if none will work, I think I can't emulate it from the developers tools.

Another thing is that maybe the "Express" modes must be a "mode" of the thermostat, like "auto", but this is another thing and a breaking change.

**Comment by ollo69** [comment]
Now I remember that I set the current temperature because in the thermostat interface the target temperature is not shown when the device is set in `eco friendly` mode and the target temperature feature is disabled.
In any case the 2 temperature sensors are still available, so I will set the climate current temperature to `none` in next release to avoid confusion a let see if someone will complain about this...

**Comment by McGiverGim** [comment]
Tested latest update in Home Assistant, and it seems to work. It seems the `none` ends with a `null` value in the attribute, and it works.
Thanks for the change!

> Another thing is that maybe the "Express" modes must be a "mode" of the thermostat, like "auto", but this is another thing and a breaking change.

This "feature" remains, but the current switch works so it's not a problem or a need. More a personal like.

**Comment by ollo69** [comment]
I close this issue as fixed in last releases. About the feature, eventually create a new feature request, but it will be complex to map this because not all devices have this mode and [HVAC mode](https://developers.home-assistant.io/docs/core/entity/climate#hvac-modes) must always match the modes provided by HA
