### ISSUE TITLE
LG dryer "remain time" attribute stays at 0:01:00 when cycle is complete

### ISSUE THREAD

**Issue by crafty35a** [ollo69/ha-smartthinq-sensors#803]
**Describe the bug**
Remain time attribute stays at 1 minute when cycle is complete. Same exact bug described here: https://github.com/ollo69/ha-smartthinq-sensors/issues/544

**Expected behavior**
Remaining time should change to 0:00:00 when cycle is complete

**Screenshots**
![image](https://github.com/user-attachments/assets/75bf9deb-f651-403d-9fe7-a34d9fdd2b63)

**Environment details:**
 - Environment: HASSIO
 - Home Assistant version installed: 2024.9.3
 - Component version installed: latest
 - Last know working version: none, this issue has existed since I bought the dryer nearly a year ago
 - LG device type and model with issue: DLEX6500B

Diagnostic with device in this state: 
[smartthinq_sensors-536817956fbcb75f7bf9282036e8f182-Dryer-3058f0e3651aa008e882e6bfa76557f3.json](https://github.com/user-attachments/files/17214190/smartthinq_sensors-536817956fbcb75f7bf9282036e8f182-Dryer-3058f0e3651aa008e882e6bfa76557f3.json)

**Comment by crazytimmy** [comment]
I've noticed the same behavior with our LG dishwasher recently. I updated the integration from 0.39.0 to 0.39.2 with no change. Maybe LG pushed an update to app/firmware recently?

I also noticed when HA shows a constant 1:00 remaining the dishwasher's status in the LG app is offline and confirmed it's not connected to my wifi. Powering the dishwasher on reconnects to wifi, no change to HA remaining time status. But powering dishwasher off then updates HA remaining remaining status.

Not sure if there's a way to check when updates are pushed to devices but here's the versions I'm running:

HA (container): 2024.9.2
LG ThinQ Integration: 0.39.2

Dishwasher Device Info:
Model#: LDP6810SS.ASSESNA
Device App: 5002.05
Modem: clip_hna_v1.9.198_RT
Firmware1: SAA41263713.0000F8B6
Firmware2: SAA41260907.0000D254

**Comment by crafty35a** [comment]
> I've noticed the same behavior with our LG dishwasher recently

Funny you should say that, I noticed it for my dishwasher this morning as well. This is probably not new behavior, the dishwasher is fairly new and I only recently added a card to track it to HA. Here is the diagnostic for that device: 
[smartthinq_sensors-536817956fbcb75f7bf9282036e8f182-Dishwasher-78d9e9a18b893bbbd17adb967a977d87(1).json](https://github.com/user-attachments/files/17250001/smartthinq_sensors-536817956fbcb75f7bf9282036e8f182-Dishwasher-78d9e9a18b893bbbd17adb967a977d87.1.json)

**Comment by crazytimmy** [comment]
I think this issue should stay open. Dishwasher ran last night and this morning was still showing 1:00 remaining as before.
Just updated from 0.40.0 to 0.40.3 but the only change seems to be the SSID diagnostics so I don't anticipate this will resolve the issue.

I'll try to look into the logs in the next few days. If there's a specific log that'll help narrow down the issue please reply. Otherwise I'll post what I can find.

**Comment by byrnes-patrick** [comment]
Is anyone else still having this issue? Or has anyone found a workaround for it?
