### ISSUE TITLE
Warning: registers an entity service with a non entity service schema

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [ollo69/ha-smartthinq-sensors#809]
**Describe the bug**
On startup, I get the following warning in the logs:

**Output of HA logs**
`WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'smartthinq_sensors' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/smartthinq_sensors/humidifier.py, line 67: platform.async_register_entity_service(, please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues`

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Raspbian
 - Home Assistant version installed: 2024.10.1
 - Component version installed: 0.39.2
 - Last know working version: N/A

**Comment by ollo69** [comment]
This issue is fixed with last release 0.40.0. Please upgrade integration version.
