### ISSUE TITLE
Detected that custom integration 'smartthinq_sensors' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/smartthinq_sensors/humidifier.py, line 67: platform.async_register_entity_service

### ISSUE THREAD

**Issue by DeaneG1967** [ollo69/ha-smartthinq-sensors#815]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Environment details:**
HA green
Core 2024.10.2
Supervisor 2024.10.2
Operating System 13.2
Frontend 20241002.3
 - LG device type and model with issue:
 - LG washing machine WM9000H
 - LG dryer DLEX9000V

**Output of HA logs**
Detected that custom integration 'smartthinq_sensors' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/smartthinq_sensors/humidifier.py, line 67: platform.async_register_entity_service(, please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues

**Comment by DeaneG1967** [comment]
Though the error message has something to do with a humidifier, I have none - only a clothes washer and dryer.

**Comment by ollo69** [comment]
This should be fixed by last release. What is the integration version you are using?

**Comment by DeaneG1967** [comment]
Ah, I'm using 0.39.2, thanks, I'll update to the current release.
Deane

**Comment by DeaneG1967** [comment]
Interestingly my HA instance does not show an available update.
Deane

**Comment by ollo69** [comment]
Last release is v0.40.1. To auto update you must install and configure HACS. I close this.

**Comment by DeaneG1967** [comment]
Thanks. I have been running HACS. For some reason it does not show an
update is available.
Deane
