### ISSUE TITLE
[BUG] No SmartThinQ devices found. Component setup aborted

### ISSUE THREAD

**Issue by David8867** [ollo69/ha-smartthinq-sensors#82]
Hello :-)!

**Describe the bug**
I have added OLED TV to the SmartThinQ application. Unfortunalrey when I try to add it via HA, I get the error "No SmartThinQ devices found. Component setup aborted". I log in using yahoo account.
Please tell me if you need more details.

Thank you,

Kr,

David.

**Comment by ollo69** [comment]
This component do not support LG TV. Should exist a dedicated component in HA for this.

**Comment by KTibow** [comment]
Consider closing?
https://www.home-assistant.io/integrations/webostv/

**Comment by David8867** [comment]
Oh, sorry for that...

Thank you for your fast reply :-). Yes for sure it can be closed.

Cheers.
