### ISSUE TITLE
Express Freeze sensor for fridge

### ISSUE THREAD

**Issue by ronnybugle** [ollo69/ha-smartthinq-sensors#83]
Thanks a lot for this addon!  Any chance you could add the Express Freeze as a sensor for the fridges please?

It would be fantastic to have a readable/writeable binary switch on/off for the Express Freeze within HA, or even to have a read-only sensor for the Express Freeze would be good.

Or is it already a sensor? Because it's not showing up my latest version.. I thought I saw it in changelog notes though.  I'm using latest version, region "AU" and language "en".

**Comment by ollo69** [comment]
You can create already now a sensor from the device attribute using HA [platform_template.](https://www.home-assistant.io/integrations/template/).
About make it writable, obviously is more complex, but it will come when I will have time to add device control features to the integration

**Comment by ronnybugle** [comment]
Great, thank you.  I look forward to the writeable functionality when you have the time.

**Comment by ollo69** [comment]
Can we close this issue?

**Comment by Dilergore** [comment]
I'm really looking forward to have such switch. I would like to automate to turn express freeze off after n hours using an automation.
