### ISSUE TITLE
Unable to connect it reconfigure after 0.115.1 update[BUG]

### ISSUE THREAD

**Issue by nikiyao** [ollo69/ha-smartthinq-sensors#84]
When I restarted after update, there was an error after trying a few restarts I tried to reconfigure and now I get an invalid credentials error after I have successfully logged into lg.

**Comment by KTibow** [comment]
Try remove/reinstall?

**Comment by nikiyao** [comment]
That's what I tried once it wouldn't work after a few restarts. I even
completely removed the hacs integration for lg, restarted and tried to
reconfigure

**Comment by KTibow** [comment]
1. Remove integration from `custom_components` (check with file editor)
2. Restart HA
3. Install integration
4. Restart HA
5. Clear cache
6. Install
7. Report back here with results

**Comment by nikiyao** [comment]
I just did that and same error

**Comment by KTibow** [comment]
Using a plain LG account or Google?

**Comment by nikiyao** [comment]
Lg account

**Comment by KTibow** [comment]
Screenshot? Config steps?

**Comment by ollo69** [comment]
Just updated to 0.115.1, no issue here. So I don't think this is a component related problem. More probably you need to check your LG account, sometimes is reguired to accept new term condition and reboot cause login failing for this
Eventually Post your HA logs with error details...

**Comment by nikiyao** [comment]
Good call, I realized I had never opened the app in my new phone, once I
did that and accepted terms it connected. Thanks.
