### ISSUE TITLE
"SmartThinQ LGE Sensors" Missing from Integrations after Uninstall/Reinstall

### ISSUE THREAD

**Issue by Gazeley** [ollo69/ha-smartthinq-sensors#85]
Was working great for some time, but for some reason my washer became unavailable today. 

In an attempt to resolve the issue I uninstalled this component from HACS and deleted "SmartThinQ LGE Sensors" from integrations, and then tried reinstalling everything again.

But after reinstalling this component and restarting, the "SmartThinQ LGE Sensors" integration won't show up as an option.

Am I missing something obvious or is this some sort of bug?

**Comment by KTibow** [comment]
Clear cache.

**Comment by Gazeley** [comment]
*Facepalm*  Can't believe I didn't think to try that.

Thank you! That did the trick.

**Comment by KTibow** [comment]
Consider closing?
