### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by tayanov** [ollo69/ha-smartthinq-sensors#95]
**Describe the bug**
I see error when restart ha.

**Expected behavior**
i remove integration and re-add it.
When paste url for redirect i see window for change pass for account lg
When im changing pass i try copy redirect url to ha. but see error

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): supervised
 - Home Assistant version installed: last stable
 - Component version installed: last
 - Last know working version: many days ago
 - LG device type and model with issue:
 - LG devices connected (list): worked washer and fridge early

**Output of HA logs**
Invalid SmartThinQ credentials.

```

```

**Additional context**

part with *** of url redirect
https://kr.m.lgaccount.com/login/iabClose?state=29d13f2e06*********3c54cedfb423b2d&code=7uZplcza********QfcPTyuK9HxH&user_number=RU1*******2267&oauth2_backend_url=https%3A%2F%2Fru.lgeapi.com%2F

**Comment by ollo69** [comment]
If you go through password change, repeat the process from the beginning.
Also verify that your ThinQ phone app is properly connected and check if is asking for new "Term Of Service".

**Comment by tayanov** [comment]
thanks, after relogin in mobile app. i can re-add integration. close
