### ISSUE TITLE
[BUG] WT7900 washer does not have all the sensors

### ISSUE THREAD

**Issue by Madj42** [ollo69/ha-smartthinq-sensors#96]
**Describe the bug**
I only get the power state, error state, and wash complete sensors.

**Expected behavior**
From all the reports I've read, there are supposed to be other sensors exposed like wash cycle, etc.  Not sure if I can get these exposed by providing information?

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):. Hassii
 - Home Assistant version installed: 0.116
 - Component version installed:. 0.5.7
 - Last know working version: n/a
 - LG device type and model with issue:. WT7900HBA
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by Madj42** [comment]
Not sure what logs to provide.

**Comment by hmoffatt** [comment]
Did you check the attributes? There's a ton, and there's all sorts of information about current state, remaining time etc.

**Comment by Madj42** [comment]
Yeah, I'm sorry.  I just came here to close it due to finding this out.  Thanks
