### ISSUE TITLE
[BUG] WM4000HWA Time Showing 0:00

### ISSUE THREAD

**Issue by yoshi43** [ollo69/ha-smartthinq-sensors#97]
**Describe the bug**
I just got a new washer (WM400HWA) and dryer (DLGX4001W) installed. Everything appears to be working except the remain, initial, and reserve time on the WM400HWA will only show 0:00. The dryer is working correctly.

**Expected behavior**
The time to update with as the cycle runs.

**Screenshots**
![Washer](https://user-images.githubusercontent.com/35871765/95665451-dfafef00-0b15-11eb-868d-1b2b91d57ca4.jpg)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed: 0.116.2
 - Component version installed: 0.5.7
 - Last know working version: N/A
 - LG device type and model with issue: WM4000HWA (F3P2CYUBE__-FL in HA)
 - LG devices connected (list):
     - WM4000HWA (F3P2CYUBE__-FL in HA)
     - DLGX4001W (RV13D4ASJW_D_US-Dryer in HA)

**Comment by KTibow** [comment]
Can you show a photo of the laundry machine's display and how long on its timer?

**Comment by yoshi43** [comment]
Here is a screenshot of the ThinQ iOS app, machine's display, and the HA app.

![IMG_2047](https://user-images.githubusercontent.com/35871765/95667636-68d32000-0b2e-11eb-89a1-d94ed63fc552.PNG)
![IMG_2048](https://user-images.githubusercontent.com/35871765/95667649-95873780-0b2e-11eb-89c0-bb75c79e650b.jpg)
![IMG_2049](https://user-images.githubusercontent.com/35871765/95667651-99b35500-0b2e-11eb-8cc0-64a3d42f9e8b.jpg)

**Comment by KTibow** [comment]
It should only update every 30 seconds. Can you set the logs to:
```
logger:
  default: critical
  logs:
    custom_components.smartthinq_sensors: debug
```
Reboot, and post the logs to me (@KTibow) or @ollo69 on the forums in a PM.

**Comment by ollo69** [comment]
Seems that your washer do not provide hours information in the payload. Not really clear what happen when minutes >= 60!!
Anyway I just released a new version that should fix this issue, please try it and let us now,

**Comment by yoshi43** [comment]
@ollo69 As you expected. It seems to be working when minutes <60, but things are still a little buggy when minutes >=60. The first screenshot is for when there was an 1hr 43min left on the cycle and the second screenshot is when there was 1hr 39min left on the cycle. 

1hr 43min is appearing as 2 hours minus 17 minutes.
1 hr 39min is appearing as 2 hours minus 21 minutes.

![Screenshot 1](https://user-images.githubusercontent.com/35871765/95679620-ae790280-0b99-11eb-8b06-a87953fec911.jpg)
![Screenshot 2](https://user-images.githubusercontent.com/35871765/95679622-b173f300-0b99-11eb-8538-212b02941b64.jpg)

**Comment by ollo69** [comment]
Can you provide a log as yesterday with time >= 60? I see that is providing negative number, but is not really clear the logic, maybe it use some other payload attribute in this case.

**Comment by ollo69** [comment]
Nevermind, my mistake. Wait for new release, I'm going to fix this

**Comment by ollo69** [comment]
Issue is that I was rounding calculated hours instead truncating. Just released new version that should fix this,

**Comment by yoshi43** [comment]
Seems to be working great!

**Comment by ollo69** [comment]
Please remember to close this issue when you think that everything is fine. Thanks.
