### ISSUE TITLE
[Feature Request]Support for LG Ovens?

### ISSUE THREAD

**Issue by KungFuJoe23** [ollo69/ha-smartthinq-sensors#98]
Any plans for adding oven support to this integration?  I can assist if necessary.  I have a Signature Duel Oven (Gas, Elec).

**Comment by KTibow** [comment]
Does wideq support this?

**Comment by ollo69** [comment]
Potentially it is possible, wideq is the protocol so is just a matter to manage the property that comes from the payload. Real complexity is to implement without having an oven device.
I put this in the todo list, but my priority here is implement controls so to be able to add climate entity and control existing sensors.

**Comment by ollo69** [comment]
Oven now is supported, I close this request
